objects/SFDC_Purchase_Order__c/SFDC_Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>Track the lifestyle of a Purchase Order, as it starts as a purchase request and becomes a fully-approved PO. Associate this with a specific cost center and Invoices.</description>
    <label>Supplier Purchase Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Purchase_Order__c/fields/Supplier1__c.field-meta.xml
<CustomField>
    <fullName>Supplier1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Search and select the relevant Supplier, if you cannot find the one you need, use the Supplier Pending Creation Supplier, and enter the name of the Supplier in the Branch field, then ask Accounts to setup the new Supplier, and assign this P/O to it.</inlineHelpText>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipName>Purchase_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SFDC_Purchase_Order__c/fields/Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>Telephone_Number__c</fullName>
    <label>Tel:</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SFDC_Purchase_Order__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Visit this P/O relates to, if applicable.</inlineHelpText>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Suppliers__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Suppliers__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <defaultValue>&quot;UK&quot;</defaultValue>
    <label>Billing Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Suppliers__c/fields/Billing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Billing_State_Province__c</fullName>
    <label>Billing State/Province</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Suppliers__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Billing Zip/Postal Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Suppliers__c/fields/Sage_Code__c.field-meta.xml
<CustomField>
    <fullName>Sage_Code__c</fullName>
    <label>Sage Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Site_Address__c.field-meta.xml
<CustomField>
    <fullName>Site_Address__c</fullName>
    <formula>Site__r.ShippingStreet&amp;BR() + 
Site__r.ShippingCity&amp;BR ()+  
Site__r.ShippingState&amp;BR ()+ 
Site__r.ShippingPostalCode&amp;BR ()+ 
&quot;Tel : &quot; &amp; if(Site_Contract__r.TELEPHONE_NUMBER__c==NULL,  Site__r.Phone,Site_Contract__r.TELEPHONE_NUMBER__c )  &amp;BR ()+
&quot;Contact : &quot;&amp; Site_Contract__r.ContactName__c
&amp;
IF ( Cancelled__c, BR()&amp;IMAGE(&quot;/servlet/servlet.FileDownload?file=015280000000oBn&quot;,&quot;Cross&quot;)&amp;&quot; VISIT HAS BEEN CANCELLED&quot;&amp;BR()&amp;&quot;PLEASE DO NOT BOOK&quot;,&quot;&quot;)</formula>
    <inlineHelpText>Formula to present all the Site Details onto the Visit Page. Takes it from various fields.</inlineHelpText>
    <label>Site Details</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/Purchase_Order_Controller.cls
/*============================================================================================================
*Class Name     : Purchase_Order_Controller 
*Description    : To handle the Supplier Purchase Order Pdf
*Company        : Puthuvannam Technology Solutions Pvt Ltd.
*Date           : 23rd June, 2014
*Version        : 30.0
*Methods        : public Purchase_Order_Controller(ApexPages.StandardController controller)

*============================================================================================================*/

public class Purchase_Order_Controller {

   
    public Purchase_Order_Controller(ApexPages.StandardController controller) {
    
       Purchaseorder = ApexPages.CurrentPage().getParameters().get('id');
    
    SFDC_Purchase_Order__c PO = [select id,Name,Supplier1__c,Visit__c from SFDC_Purchase_Order__c where id=:Purchaseorder ];
    
    Suppliers__c Sup =[select id,Name,Billing_Street__c ,Billing_City__c,Billing_State_Province__c,Billing_Zip_Postal_Code__c,Billing_Country__c,Telephone_Number__c,Fax_Number__c,Sage_Code__c,Email__c from Suppliers__c where id=:PO.Supplier1__c];
    
    setvalue = [select Billing_Street__c from Suppliers__c where id=:PO.Supplier1__c].Billing_Street__c;
    setvalue1 = [select Billing_City__c from Suppliers__c where id=:PO.Supplier1__c].Billing_City__c;
    setvalue2 = [select Billing_State_Province__c from Suppliers__c where id=:PO.Supplier1__c].Billing_State_Province__c;
    setvalue3 = [select Billing_Zip_Postal_Code__c from Suppliers__c where id=:PO.Supplier1__c].Billing_Zip_Postal_Code__c;
    setvalue4 = [select Billing_Country__c from Suppliers__c where id=:PO.Supplier1__c].Billing_Country__c;
    setvalue5 = [select Telephone_Number__c from Suppliers__c where id=:PO.Supplier1__c].Telephone_Number__c;
    setvalue6 = [select Fax_Number__c from Suppliers__c where id=:PO.Supplier1__c].Fax_Number__c;
    setvalue7 = [select Sage_Code__c from Suppliers__c where id=:PO.Supplier1__c].Sage_Code__c ;
    setvalue8 = [select Email__c from Suppliers__c where id=:PO.Supplier1__c].Email__c ;
    
    if(PO.Visit__c !=Null){
    Visits__c Visit =[select id,Name,Site_Address__c,Site_Contract__c from Visits__c where id=:PO.Visit__c ];
    setvalueVisit = [select Site_Address__c from Visits__c where id=:PO.Visit__c].Site_Address__c ;
    }

    
    
    }

public String Purchaseorder{get; set;}
public String PO{get; set;}
public String Sup{get; set;}
public String setvalue {get; set;}
public String setvalue1 {get; set;}
public String setvalue2 {get; set;}
public String setvalue3 {get; set;}
public String setvalue4 {get; set;}
public String setvalue5 {get; set;}
public String setvalue6 {get; set;}
public String setvalue7 {get; set;}
public String setvalue8 {get; set;}
public String Visit{get; set;}
public String setvalueVisit{get; set;}

}