objects/SFDC_Purchase_Order__c/SFDC_Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>Track the lifestyle of a Purchase Order, as it starts as a purchase request and becomes a fully-approved PO. Associate this with a specific cost center and Invoices.</description>
    <label>Supplier Purchase Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Purchase_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supplier Purchase Orders</relationshipLabel>
    <relationshipName>Supplier_Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SFDC_Purchase_Order__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Visit this P/O relates to, if applicable.</inlineHelpText>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PurchaseOrderTriggerHandler.cls
/*============================================================================================================
*Class Name     : PurchaseOrderTriggerHandler
*Description    : All the implementations related to Purchase Order Triggers should be handled here
*Company        : Puthuvannam Technology Solutions
*Date           : 17th June, 2014
*Version        : 1.0
*Change History : Initial Trigger Handler
*Methods        : public void OnAfterInsert(Map<Id,SFDC_Purchase_Order__c> newPOMap)
                 public void OnAfterUpdate(Map<Id,SFDC_Purchase_Order__c> newPOMap,Map<Id,SFDC_Purchase_Order__c> oldPOMap)
*================================================================================================================*/

 public class PurchaseOrderTriggerHandler{
/*    public void OnAfterInsert(Map<Id,SFDC_Purchase_Order__c> newPOMap) {

      
    }
    public void OnBeforeInsert(List<SFDC_Purchase_Order__c> newPOList) {
      this.UpdateOppName(newPOList);
      
    }
    
    public void OnBeforeUpdate(List<SFDC_Purchase_Order__c> newPOList) {
      this.UpdateOppName(newPOList);
      
    }
  
    public void OnAfterUpdate(Map<Id,SFDC_Purchase_Order__c> newPOMap,Map<Id,SFDC_Purchase_Order__c> oldPOMap){
  
     }
     private void UpdateOppName(List<SFDC_Purchase_Order__c> newPOList){
     // Variable Declaration
        List<id> visitIds = new List<id> ();
        for(SFDC_Purchase_Order__c po:newPOList){
            visitIds.add(po.Visit__c);
            system.debug('======'+po.Visit__c);
        }
      //to get a list of Visits      
      if(visitIds != null && visitIds.size() > 0){ 
        Map<id, Visits__c> visitMap=new Map<id, Visits__c>([select Id,Opportunity__c from Visits__c where ID IN:visitIds And Opportunity__c != null]);
        for(SFDC_Purchase_Order__c po:newPOList){
            if(visitMap.containsKey(po.visit__c)){
                po.Opportunity__c=visitMap.get(po.visit__c).Opportunity__c;    
            }else{
                po.Opportunity__c = null;
            }         
        }
      }
     } */
}