objects/Credit_Note_Line_Item__c/Credit_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line Item</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Note_Line_Item__c/fields/Product_credit__c.field-meta.xml
<CustomField>
    <fullName>Product_credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>Credit_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Credit_Note_Line_Item__c/fields/SalesDescription__c.field-meta.xml
<CustomField>
    <fullName>SalesDescription__c</fullName>
    <label>SalesDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

classes/CreditLineItemHandler.cls
Public class CreditLineItemHandler{

 public void BeforeInsert(List<Credit_Note_Line_Item__c> newList){
   
        
        InsertExtendedSales(newList);
        
    }


 public void InsertExtendedSales(List<Credit_Note_Line_Item__c> newMap){
   
        List<Id> ProductId=new List<Id>();
       
        Map<Id,Product2> PrdsList=new Map<Id,Product2>();
        
       
        for(Credit_Note_Line_Item__c NewId:newMap)
        {
            ProductId.add(NewId.Product_credit__c);
           
         }
        system.debug('ProductId=========='+ProductId);
       
        
       
        for(Product2 prd:[select id,Extended_Sales_Description__c,Sales_Description__c from product2 where id IN:ProductId]){
               PrdsList.put(prd.id,prd);
               
         } 
       
         for(Credit_Note_Line_Item__c NewId:newMap){
           
           if(PrdsList.containskey(NewId.Product_credit__c)){
             if(NewId.Extended_Sales_Description__c==null){        
                NewId.Extended_Sales_Description__c=PrdsList.get(NewId.Product_credit__c).Extended_Sales_Description__c;
              }
              if(NewId.SalesDescription__c==null){
                 NewId.SalesDescription__c=PrdsList.get(NewId.Product_credit__c).Sales_Description__c;
               }
              
               
           }
           
          
       }
    }
  }