objects/Credit_Note_Line_Item__c/Credit_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line Item</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Note_Line_Item__c/fields/Credit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Credit_Notes__c</fullName>
    <label>Credit Notes</label>
    <referenceTo>Credit_Notes__c</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>Credit_Note_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Credit_Note_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>Credit_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Credit_Notes__c/Credit_Notes__c.object-meta.xml
<CustomObject>
    <label>Credit Notes</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Credit_Notes__c/fields/Credit_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Number__c</fullName>
    <label>Credit Note Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Credit_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Number__c</fullName>
    <label>Credit Note Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

classes/CreditHandler.cls
public class CreditHandler{
     
    public void AfterUpdate(Map<id,Credit_Notes__c> newMap,Map<id,Credit_Notes__c> oldMap){
    
        showdesc(newMap,oldMap);
    }
    
    public void AfterInsert(Map<Id,Credit_Notes__c> newMap){
       
        UpdateCreditNo(newMap);
    }
    
     public void showdesc(Map<id,Credit_Notes__c> newMap,Map<id,Credit_Notes__c> oldMap){
        Set<id> crdid=new Set<id>();
        List<Credit_Note_Line_Item__c> cli=new List<Credit_Note_Line_Item__c>();
       
       for(Credit_Notes__c cn:newMap.values()){
          if(cn.Show_Description__c!=oldMap.get(cn.id).Show_Description__c){
              crdid.add(cn.id);
          }
       }
          
         
       if(crdid.size()>0){ 
         for(Credit_Note_Line_Item__c cl:[Select id,Show_Description__c,Credit_Notes__r.Show_Description__c,Credit_Notes__c from Credit_Note_Line_Item__c where Credit_Notes__c IN:crdid]){
           cl.Show_Description__c=cl.Credit_Notes__r.Show_Description__c;
           cli.add(cl);
         } 
       }
       if(cli.size()>0){
           update cli;
       }  

    }
    
/* =======================================

Method Name: UpdateCreditNo
Created Date: 31.10.17
Purpose: To link credit note number in opportunity.This is used in reports and dashboard for credit note number reference
Argument: NewMap

============================================= */    
     
    public void UpdateCreditNo(Map<Id,Credit_Notes__c> newMap){
      List<Id> oppid=new List<Id>();
      Map<Id,String> creno=new Map<Id,string>();
      List<Opportunity> opplist=new List<Opportunity>();
       
       for(Credit_Notes__c cn:newMap.values()){
          if(cn.Opportunity__c!=null){
              oppid.add(cn.Opportunity__c);
              if(!creno.containskey(cn.Opportunity__c)){
                  creno.put(cn.Opportunity__c,cn.Name);
                  system.debug('creno=========='+creno);
               }
          }
       }
       if(oppid.size()>0){
         for(Opportunity opp:[Select id,name,Credit_Note_Number__c from opportunity where id IN:oppid]){
            if(creno.containskey(opp.id)){
                opp.Credit_Note_Number__c=creno.get(opp.id);
                opplist.add(opp);
                system.debug('opplist=========='+opplist);
            }
         }
       }
       if(opplist.size()>0){
          update opplist;
       }
     
     }
     
     
}