objects/Credit_Note_Line_Item__c/Credit_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line Item</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Note_Line_Item__c/fields/Credit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Credit_Notes__c</fullName>
    <label>Credit Notes</label>
    <referenceTo>Credit_Notes__c</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>Credit_Note_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Credit_Note_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>Credit_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Credit_Note_Line_Item__c/fields/Product_credit__c.field-meta.xml
<CustomField>
    <fullName>Product_credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>Credit_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Credit_Notes__c/Credit_Notes__c.object-meta.xml
<CustomObject>
    <label>Credit Notes</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Credit_Notes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>Credit_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

classes/CreditHandlerTest.cls
@isTest(SeeAllData=true)
    public class CreditHandlerTest{
       static TestMethod void method1(){
       
       Product2 prd=new Product2();
       prd.name='test prd';
       prd.IsActive=true;
       insert prd;
       
       Account acc=new Account();
       acc.name='test';
       insert acc;
       
       Opportunity opp=new opportunity();
       opp.Name='test opp';
       opp.AccountId=acc.id;
       opp.CloseDate=system.today();
       opp.StageName='Closed Won';
       insert opp;
       
       Credit_Notes__c cn=new Credit_Notes__c();
       cn.Opportunity__c=opp.id;
       cn.Account__c=acc.id;
       insert cn;
       
       Credit_Note_Line_Item__c cnli=new Credit_Note_Line_Item__c();
       cnli.Opportunity__c=opp.id;
       cnli.Product_credit__c=prd.id;
       cnli.Credit_Notes__c=cn.id;
       insert cnli;
       
       cn.Show_Description__c=true;
       update cn;
       
       
       }
            
    }