objects/Next_Visit_Product__c/Next_Visit_Product__c.object-meta.xml
<CustomObject>
    <label>Requested for Next Visit Product</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Next Visit Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requested for Next Visit Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Next_Visit_Product__c/fields/Maintenance_Reactive_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Reactive_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maintenance &amp; Reactive Sheet</label>
    <referenceTo>Service_Sheet_STD__c</referenceTo>
    <relationshipLabel>Requested for Next Visit Products</relationshipLabel>
    <relationshipName>Requested_for_Next_Visit_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Next_Visit_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Requested for Next Visit Products</relationshipLabel>
    <relationshipName>Requested_for_Next_Visit_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PartsConfig__c/PartsConfig__c.object-meta.xml
<CustomObject>
    <label>PartsConfig</label>
    <nameField>
        <displayFormat>PRT-{00000}</displayFormat>
        <label>Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PartsConfig</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PartsConfig__c/fields/isDefaultProduct__c.field-meta.xml
<CustomField>
    <fullName>isDefaultProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDefaultProduct</label>
    <type>Checkbox</type>
</CustomField>

objects/PartsConfig__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>PartsConfig</relationshipLabel>
    <relationshipName>PartsConfig</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Sheet_STD__c/Service_Sheet_STD__c.object-meta.xml
<CustomObject>
    <label>M&amp;R Sheet</label>
    <nameField>
        <displayFormat>RS{000000}</displayFormat>
        <label>Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>M&amp;R Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Sheet_STD__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Relates to the contract which will cover this service sheet</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipName>Reactive_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Price_Book_IdFormula__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_IdFormula__c</fullName>
    <formula>IF(Price_Book__c &lt;&gt; &apos;&apos;, Price_Book__c, Site__r.Price_Book__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This shows the price book ID that will be used when we create the opportunity.</inlineHelpText>
    <label>Price Book Id (Customer / Site)</label>
    <type>Text</type>
</CustomField>

classes/NextVisitPrdController.cls
public class NextVisitPrdController {

   
    public String searchString {get;set;}
    public Next_Visit_Product__c[] shoppingCart {get;set;}
    public Product2[] AvailableProducts {get;set;}
    public String toSelect {get; set;}
    public String toUnselect {get; set;}
    public Decimal Total {get;set;}
    public List<Id> Prdids;
    public Id CurrentId;
    public Boolean overLimit {get;set;}
    public Boolean multipleCurrencies {get; set;}
    String Soql='';
     public Service_Sheet_STD__c reac;
     public List<String> pbid;
    
    private Boolean forcePricebookSelection = false;
    
    private Next_Visit_Product__c[] forDeletion = new Next_Visit_Product__c[]{};

    public NextVisitPrdController(ApexPages.StandardController controller) {
        
        Schema.SObjectType sObjName = controller.getRecord().Id.getSObjectType();
        CurrentId=controller.getRecord().Id;
        
        Soql='select Id,Product__c,Quantity__c from Next_Visit_Product__c where ';
        Soql+='Maintenance_Reactive_Sheet__c=:CurrentId';
        shoppingCart =database.query(Soql);
        updateAvailableList();
    }
    
     public void updateAvailableList() {
        
        Prdids=new List<Id>();
   pbid=new List<String>();
        for(Next_Visit_Product__c ShopId:shoppingCart)
        Prdids.add(ShopId.Product__c);
        
       // String qString = 'select Id,Product_Name__r.Name, Product_Name__c from PartsConfig__c where isDefaultProduct__c=false and Product_Name__c NOT IN:Prdids';
        
        
                  
        reac=[select id,name,Site_Contract__r.Price_Book_IdFormula__c from Service_Sheet_STD__c where id=:CurrentId];       
        String[] pbook= new String[]{reac.Site_Contract__r.Price_Book_IdFormula__c};        
        system.debug('pbook=='+pbook);      
            
        List<PricebookEntry> pbe = new List<PricebookEntry>();      
        pbe = [select id,name,Pricebook2Id from PricebookEntry where pricebook2Id =:pbook];     
        system.debug('pbe===='+pbe );       
                if(pbe.size()>0){
        for(PricebookEntry pe :pbe){        
                if(pe.name!=null)
                pbid.add(pe.name);    
                  
                    
        }       
           }
         system.debug('pbid==='+pbid);      
       String  qString='select id,name from product2 where name IN:pbid';       
       system.debug('qString==='+qString);      
       
        
        if(searchString!=null){
           qString ='select name from product2 where name IN:pbid and name like \'%' +searchString+ '%\'';
        }
        
        Set<Id> selectedEntries = new Set<Id>();
        for(Next_Visit_Product__c d:shoppingCart){
            selectedEntries.add(d.Product__c);
        }
        
        if(selectedEntries.size()>0){
            String tempFilter = ' and Id not in (';
            for(Id i : selectedEntries){
                tempFilter+= '\'' + (String)i + '\',';
            }
            String extraFilter = tempFilter.substring(0,tempFilter.length()-1);
            extraFilter+= ')';
            
            qString+= extraFilter;
        }
        
        qString+= ' order by Name';
        qString+= ' limit 101';
        
        system.debug('qString:>>>' +qString);        
        AvailableProducts = database.query(qString);
        system.debug('AvailableProducts:>>>>'+AvailableProducts);
        
        if(AvailableProducts.size()==101){
            AvailableProducts.remove(100);
            overLimit = true;
        }
        else{
            overLimit=false;
        }
    }
    
    public void addToShoppingCart(){
    
        for(Product2 d : AvailableProducts){
            if((String)d.Id==toSelect){
                shoppingCart.add(new Next_Visit_Product__c(Product__c=d.id, Quantity__c=1,Maintenance_Reactive_Sheet__c=CurrentId));
                break;
            }
        }
        
        updateAvailableList();  
    }
    

    public PageReference removeFromShoppingCart(){
    
        Integer count = 0;
    
        for(Next_Visit_Product__c d : shoppingCart){
            if((String)d.Product__c==toUnselect){
            
                if(d.Id!=null)
                    forDeletion.add(d);
            
                shoppingCart.remove(count);
                break;
            }
            count++;
        }
        
        updateAvailableList();
        
        return null;
    }
    
    public PageReference onSave(){
    
        if(forDeletion.size()>0)
            delete(forDeletion);
    
        try{
            if(shoppingCart.size()>0)
                upsert(shoppingCart);
        }
        catch(Exception e){
            ApexPages.addMessages(e);
            return null;
        }  
           
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }
    
    public PageReference onCancel(){
 
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }
}