objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/SalesOrderLineItems__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sales_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/LineItemTest.cls
@isTest(SeeAllData=true)
public class LineItemTest{
    
    static testMethod void myTest(){
    
    test.starttest();
    
    Account Acc=new Account();
    Acc.Name='Test';
    insert Acc;
    
    SalesOrder__c sales=new SalesOrder__c();
    sales.Account__c=Acc.id;
    insert sales;
    
    product2 prd=new product2();
    prd.Name='Test Product';
    prd.IsActive=true;
    prd.ProductCode='TES124';
    prd.Cost__c=12;
    insert prd;
    
    List<SalesOrderLineItems__c> SL =new List<SalesOrderLineItems__c>();
    SalesOrderLineItems__c SL1=new SalesOrderLineItems__c();
    SL1.Product__c=prd.id;
    SL1.Quantity__c=1;
    SL1.Sales_Order__c=sales.id;
    SL.add(SL1);
    insert SL;
    
    SalesOrderLineItems__c SL2=new SalesOrderLineItems__c();
    SL2.Product__c=prd.id;
    SL2.Quantity__c=1;
    SL2.Sales_Order__c=sales.id;
    insert SL2;
    
    ApexPages.CurrentPage().getParameters().put('Products',string.valueOf(SL2));
    ApexPages.StandardController sc = new ApexPages.standardController(SL2);
    LineItem LI=new LineItem(sc);
    LI.getProducts();
       
    test.stoptest();
    }
}