objects/Product2/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Extended_Supplier_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Supplier_Description__c</fullName>
    <label>Extended Supplier Description</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>Purchase Order List No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Extended_Supplier_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Supplier_Description__c</fullName>
    <label>Extended Supplier Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/PurchaseLineHandler.cls
Public class PurchaseLineHandler{


    public void AfterInsert(Map<Id,PurchaseOrderLineItem__c > newMap){
   
    UpddateExtendedSales(newMap);
   }
    
  /* =======================================
  Method Name: UpddateExtendedSales
  Description: Update currency type and extended sales description
  ========================================== */
  

  public void UpddateExtendedSales(Map<Id,PurchaseOrderLineItem__c> newMap){
        List<Id> ProductId=new List<Id>();
        List<PurchaseOrderLineItem__c> olist=new List<PurchaseOrderLineItem__c>();
        Map<Id,Product2> PrdMap=new Map<Id,Product2>();
        
       for(PurchaseOrderLineItem__c  NewId:newMap.values())
            ProductId.add(NewId.Product__c);
       
       for(Product2 prd:[select id,Extended_Sales_Description__c,Extended_Supplier_Description__c ,Sales_Description__c from product2 where id IN:ProductId]){
               PrdMap.put(prd.id,prd);
       }  
       
       
       for(PurchaseOrderLineItem__c   NewId:[SELECT Id,CurrencyIsoCode,Purchase_Order__r.CurrencyIsoCode, Extended_Sales_Description__c,Sales_Description__c,Extended_Supplier_Description__c,Product__c FROM PurchaseOrderLineItem__c  WHERE Id IN: Trigger.newMap.keySet()]){
           
           NewId.CurrencyIsoCode=NewId.Purchase_Order__r.CurrencyIsoCode;
           
          if(PrdMap.ContainsKey(NewId.Product__c )){
             
                  NewId.Extended_Sales_Description__c=PrdMap.get(NewId.Product__c ).Extended_Sales_Description__c;
                  NewId.Sales_Description__c=PrdMap.get(NewId.Product__c ).Sales_Description__c;
                  NewId.Extended_Supplier_Description__c=PrdMap.get(NewId.Product__c ).Extended_Supplier_Description__c;
               
               
               
             }
             olist.add(NewId);
           
       }
       
       if(olist.size()>0){
       update olist;
       }
    }
    
  
 }