objects/Product2/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Product_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_URL__c</fullName>
    <label>Product URL</label>
    <type>Url</type>
</CustomField>

objects/Product2/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Stock_Unit__c.field-meta.xml
<CustomField>
    <fullName>Stock_Unit__c</fullName>
    <label>Stock Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Metre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Quote/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/QuoteLineItem/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/QuoteController.cls
Public class QuoteController{
    Public Id QliId;
     public List<QuoteLineitem> Qli{get;set;}  
    public QuoteController()
    {
       
    }
     public ID getQliId()
    {
    
    system.debug('getQliId========'+QliId);
    return QliId;
    
    }
    
    public void setQliId(ID QliIds){
        if(QliIds != null){
            QliId= QliIds ;
            system.debug('setQliId========'+QliId);
            ChangeOrder();
         }
    }
    
    public void ChangeOrder()
    {
       
    //added << Product2.Product_URL__c >> Field For Quote Line Item.
    Qli=[Select id,QuoteId,Product2.Name,Product2.Product_URL__c,Sales_Description__c,Show_Description__c,Extended_Sales_Description__c,Product2.Description,
         Quantity,Product2.Stock_Unit__c,UnitPrice,TotalPrice from QuoteLineitem where QuoteId =:QliId order by SortOrder,Pricebookentry.product2.Name];
    system.debug('Qli========'+Qli);
    }
    }