objects/Product2/fields/Maximum_stock_level__c.field-meta.xml
<CustomField>
    <fullName>Maximum_stock_level__c</fullName>
    <label>Maximum stock level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product2/fields/Min_Stock__c.field-meta.xml
<CustomField>
    <fullName>Min_Stock__c</fullName>
    <label>Re-order stock level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product2/fields/Supplier_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product_Code__c</fullName>
    <label>Supplier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/FormQRCodeController.cls
/*============================================================================================================
*Class Name     : FormQRCodeController 
*Description    : All the implementations related Generate Label For Product.
*Company        : Merfantz Technologies Pvt Ltd
*Date           : 25th Jun, 2020
*Version        : 1.0
*Change History : Initial class
*Methods        : No Methods
*============================================================================================================*/
public with sharing class FormQRCodeController {

Public id ProdId;
public Product2 prod{get;set;}
Public String URLString{get;set;}


Public FormQRCodeController (){
ProdId=ApexPages.currentPage().getparameters().get('id');
prod=new Product2();
System.debug('id=='+ProdId);

prod=[Select id,Name,ProductCode,Supplier_Product_Code__c,Min_Stock__c,Maximum_stock_level__c from Product2 where id=:ProdId];

if(prod.Supplier_Product_Code__c!=null)

URLString ='https://chart.googleapis.com/chart?chs=250x250&cht=qr&chl='+prod.Supplier_Product_Code__c;

else
URLString='No Supplier Code';


}

}