objects/Product2/fields/Supplier_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product_Code__c</fullName>
    <label>Supplier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>Purchase Order List No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Supplier_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product_Code__c</fullName>
    <label>Supplier Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Purchase_Order__r.Shipping_Warehouse__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InsertPOLineItemController.cls
/*============================================================================================================
*Class Name     : InsertPOLineItemController
*Description    : All the implementations related to scan and Add the PO LineItem.
*Company        : Merfantz Technologies Pvt Ltd
*Date           : 25th Jun, 2020
*Version        : 1.0
*Change History : Initial class
*Methods        : public static PurchaseOrderLineItem__c insertPart(string productCode,string qty,string purchaseId)
                  public pagereference pageRedirector(){         
*============================================================================================================*/
public class InsertPOLineItemController{
public List<SelectOption> options{get;set;}
public id currentSheet{get;set;}
   public InsertPOLineItemController(ApexPages.StandardController controller){
         currentSheet=ApexPages.currentPage().getParameters().get('id');
         options=new List<SelectOption>();
         List<Warehouse__C> whlist=new List<Warehouse__c>();
         whlist=[Select id,name from Warehouse__c];
         for(Warehouse__c wh:whlist){
           options.add(new Selectoption(wh.id,wh.name));
         }
  }
/*====================================================
*Method Name     : insertPart
*Description     : This method gets input from page and search products based on supplier code.
*Arguments       : string productCode,string qty,string purchaseId
*Ticket No       : 40744
====================================================*/
   @RemoteAction
     public static PurchaseOrderLineItem__c insertPart(string productCode,string qty,string purchaseId){
          id reportid=purchaseId;
          Schema.SObjectType sobjectName=reportid.getSObjectType();
          system.debug(sobjectName);

          Product2 prod=[Select id,name,Supplier_Product_Code__c from Product2 where product2.Supplier_Product_Code__c=:productCode limit 1];
          PurchaseOrderLineItem__c  parts;
          if(prod!=null){
           parts=new PurchaseOrderLineItem__c();
           
          parts.Purchase_Order__c=purchaseId;
          
          parts.Product__c=prod.id;
          parts.Quantity__c=Decimal.valueof(qty);          
          system.debug(parts);
          try{                            
              insert parts;                            
          }
          catch(Exception e){
            system.debug(e);
            return null;
          }
         
               
          }
          return parts;

  
  }//insertPart
/*====================================================
*Method Name     : pageRedirector
*Description     : This method redirects to the record page.
*Arguments       : No arguments
*Ticket No       : 40744
====================================================*/ 
  public pagereference pageRedirector(){    
    ApexPages.Pagereference  pg=new ApexPages.Pagereference('/'+currentSheet);
    pg.setRedirect(true);
    return pg;
  }
  
}