objects/Technician_Compliance__c/Technician_Compliance__c.object-meta.xml
<CustomObject>
    <label>Customer Gift</label>
    <nameField>
        <displayFormat>CG{000000}</displayFormat>
        <label>Technician Compliance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Technician_Compliance__c/fields/Customer_Site__c.field-meta.xml
<CustomField>
    <fullName>Customer_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Technician Compliance</relationshipLabel>
    <relationshipName>Technician_Compliance</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Technician_Compliance__c/fields/Firstname__c.field-meta.xml
<CustomField>
    <fullName>Firstname__c</fullName>
    <label>Firstname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Technician_Compliance__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <label>Gift</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Biscuits</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Flowers</fullName>
            </value>
            <value>
                <fullName>Fudge</fullName>
            </value>
            <value>
                <fullName>Graze Box</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Technician_Compliance__c/fields/Lastname__c.field-meta.xml
<CustomField>
    <fullName>Lastname__c</fullName>
    <label>Lastname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/CustomerdeliveryNoteControllerTests.cls
@isTest(SeeAllData=True)

    public class CustomerdeliveryNoteControllerTests {

      @isTest Static void CustomerdeliveryNoteControllerTests() {
      Technician_Compliance__c comp=new Technician_Compliance__c();
      comp.Customer_Site__c=[SELECT id from Account LIMIT 1].id;
      comp.Firstname__c='First Name';
      comp.Lastname__c='Last Name';
      comp.Gift__c ='Gift';
      insert comp;
      Technician_Compliance__c Cid=[select id,Customer_Site__r.name,Firstname__c,Lastname__c,Gift__c from Technician_Compliance__c LIMIT 1];
      
      apexPages.CurrentPage().getParameters().Put('id',String.valueOf(Cid.id));
      ApexPages.StandardController sc = new ApexPages.StandardController(Cid);
      CustomerdeliveryNoteController CNc = New CustomerdeliveryNoteController(sc);
      
      Account listAccount=[select ShippingStreet,ShippingCity,ShippingState,ShippingPostalCode,ShippingCountry from Account where id=:Cid.Customer_Site__c LIMIT 1];
    }
}