objects/Engineer_Checklist__c/Engineer_Checklist__c.object-meta.xml
<CustomObject>
    <description>Onsite checklist</description>
    <label>Service Sheet</label>
    <nameField>
        <displayFormat>SS2{000000}</displayFormat>
        <label>Service Sheet No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inreview</fullName>
                <label>In review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Opportunity/fields/Service_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Service_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Sheet</label>
    <referenceTo>Engineer_Checklist__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Service_Sheet</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/Approval.cls
public class Approval{
    List<Engineer_Checklist__c > eng;
    List<Opportunity > opp;
    public String Sid;
        public Approval(ApexPages.StandardController controller) {
        Sid=  ApexPages.CurrentPage().getParameters().get('id');
        system.debug('sidd====='+Sid);
       for(Engineer_Checklist__c eng: [select Name,id,(select name,Approval_status__c from Service_Sheet__r) from Engineer_Checklist__c where id=:Sid])
        {
        for(Opportunity opp:eng.Service_Sheet__r){
        if(opp.Approval_status__c!=null && opp.Approval_status__c=='Approved')
        {
        system.debug('status===='+opp.Approval_status__c );
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,opp.Name+' - Invoice is Approved'));
        }
        
         if(opp.Approval_status__c!=null && opp.Approval_status__c=='Rejected')
        {
        system.debug('status===='+opp.Approval_status__c );
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,opp.Name+' - Invoice is Rejected'));
        }
            }
         }
        }
    
    }