objects/Engineer_Checklist__c/Engineer_Checklist__c.object-meta.xml
<CustomObject>
    <description>Onsite checklist</description>
    <label>Service Sheet</label>
    <nameField>
        <displayFormat>SS2{000000}</displayFormat>
        <label>Service Sheet No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Engineer_Checklist__c/fields/Fire_Extinguisher_Service_complete__c.field-meta.xml
<CustomField>
    <fullName>Fire_Extinguisher_Service_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Completed sheet creates invoice and sends confirmation to customer. If you select a Next Service Date (NSD) it will alert the Service Team to schedule the next service.</inlineHelpText>
    <label>Submit This Service</label>
    <type>Checkbox</type>
</CustomField>

objects/Engineer_Checklist__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <inlineHelpText>This is the visit record that generated this service sheet. when the service sheet is created from the visit, this is automatically filled in. When it is created from the offline excel sheet, this is not automated and needs to be manually connected.</inlineHelpText>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VisitDuplicateSheetHandler.cls
/*============================================================================================================
*Class Name     : VisitDuplicateSheetHandler
*Description    : Identify the Duplicate sheet
*Company        : Merfantz Technology Solutions
*Date           : 25th Oct, 2014
*Version        : 31.0
*Change History : Initial Version
*============================================================================================================*/
public class VisitDuplicateSheetHandler {

     // Variable Declaration
     public Boolean Allvisitsubmitedsheet{get;set;}
     public String ObjType{get; set;}
     public String VisitId{get; set;}
     
     public List<Engineer_Checklist__c> listEngineerCheckList;
    
     public  map<string, id> allrecordtypeMap {get;set;}
     
     // Constractor
     public VisitDuplicateSheetHandler(ApexPages.StandardController objStandardController){
     
        map<String, Schema.RecordTypeInfo> recordTypeInfos;
       
        // get the Service sheet Recordtype Name and ids in that map:
            recordTypeInfos=Schema.SObjectType.Engineer_Checklist__c.RecordTypeInfosByName;
            
            allrecordtypeMap  = new map<string, id>();
            // get the Service sheet recordtype ids 
            
            allrecordtypeMap.put('Air Compressor Service and Test Report',recordTypeInfos.get('Air Compressor Service and Test Report').RecordTypeId);
            allrecordtypeMap.put('Getinge Autoclave',recordTypeInfos.get('Getinge Autoclave').RecordTypeId);
            allrecordtypeMap.put('Getinge Washer Disinfector',recordTypeInfos.get('Getinge Washer Disinfector').RecordTypeId);
            allrecordtypeMap.put('Mechanical X-Ray Report',recordTypeInfos.get('Mechanical X-Ray Report').RecordTypeId);
            allrecordtypeMap.put('Medisafe Washer disinfector service',recordTypeInfos.get('Medisafe Washer disinfector service').RecordTypeId);
            allrecordtypeMap.put('Report of Examination',recordTypeInfos.get('Report of Examination').RecordTypeId);
            allrecordtypeMap.put('Suction Pump Service',recordTypeInfos.get('Suction Pump Service').RecordTypeId);
            allrecordtypeMap.put('Treatment Centre Certificate Of Service',recordTypeInfos.get('Treatment Centre Certificate Of Service').RecordTypeId);
            
            system.debug('****************allrecordtypeMap*************'+allrecordtypeMap);
   
         ObjType = Apexpages.CurrentPage().getparameters().get('ObjType');
         
         VisitId = Apexpages.CurrentPage().getparameters().get('id');
       
         if (VisitId != null) {

                listEngineerCheckList = new List<Engineer_Checklist__c>([SELECT Id,Visit__c 
                                                                         FROM Engineer_Checklist__c
                                                                         
                                                                         WHERE Visit__r.Id =: VisitId AND Fire_Extinguisher_Service_complete__c = True]);


                if (listEngineerCheckList.size() > 0 )  {

                     Allvisitsubmitedsheet = true;
                 } else {
                     Allvisitsubmitedsheet = false;
                 }

          }
    }
 
}