objects/Engineer_Checklist__c/Engineer_Checklist__c.object-meta.xml
<CustomObject>
    <description>Onsite checklist</description>
    <label>Service Sheet</label>
    <nameField>
        <displayFormat>SS2{000000}</displayFormat>
        <label>Service Sheet No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Engineer_Checklist__c/fields/Engineer__c.field-meta.xml
<CustomField>
    <fullName>Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Service Sheets Completed by this Engineer</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Engineer_Checklist__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the relationship to the Site and Contract - this also relates to Alarm Master Historic Data</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/Mechanical_Service_Sheet__c.object-meta.xml
<CustomObject>
    <description>This object contains two Inspection Certificates:-

Suppression System Mechanical Inspection Certificate
Riser &amp; Hydrant Inspection Certificate</description>
    <label>Mechanical Service Sheet</label>
    <nameField>
        <displayFormat>SSM{00000}</displayFormat>
        <label>Mechanical Service Sheets</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mechanical Service Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mechanical_Service_Sheet__c/fields/Engineer__c.field-meta.xml
<CustomField>
    <fullName>Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Mechanical Service Sheets (Technician)</relationshipLabel>
    <relationshipName>Mechanical_Service_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Relates to the contract which will cover this service sheet</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipName>Inspection_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Project_Sheet__c/Project_Sheet__c.object-meta.xml
<CustomObject>
    <label>Project Sheet</label>
    <nameField>
        <displayFormat>PS{000000}</displayFormat>
        <label>Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Sheet__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Project Sheets</relationshipLabel>
    <relationshipName>Project_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Sheet_STD__c/Service_Sheet_STD__c.object-meta.xml
<CustomObject>
    <label>M&amp;R Sheet</label>
    <nameField>
        <displayFormat>RS{000000}</displayFormat>
        <label>Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>M&amp;R Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Sheet_STD__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Relates to the contract which will cover this service sheet</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipName>Reactive_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts (Customer)</relationshipLabel>
    <relationshipName>Site_Contract</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SiteContracts__c/fields/Job_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_Time__c</fullName>
    <description>Assign the job time</description>
    <inlineHelpText>Job Time</inlineHelpText>
    <label>Job Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Type_of_Panel_DVR__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Panel_DVR__c</fullName>
    <label>Type of Panel / DVR</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Small_Works__c/Small_Works__c.object-meta.xml
<CustomObject>
    <description>28/03/14~removed HSW- from SmallWorksID Name~WB.</description>
    <label>Small Works</label>
    <nameField>
        <displayFormat>SW{000000}</displayFormat>
        <label>Small Works Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Small Works</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Small_Works__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Small Works</relationshipLabel>
    <relationshipName>Small_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Booked_with_Customers__c.field-meta.xml
<CustomField>
    <fullName>Booked_with_Customers__c</fullName>
    <inlineHelpText>1. Yes first time, sends Booking confirmation email
2. Yes to any other, sends Rescheduling notification email
3. Yes again, sends Rescheduled confirmation email.</inlineHelpText>
    <label>Booked with Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Waiting P/O</fullName>
            </value>
            <value>
                <fullName>Waiting Permit</fullName>
            </value>
            <value>
                <fullName>Waiting Confirmation</fullName>
            </value>
            <value>
                <fullName>Booked Via Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/FE_Total_Formula__c.field-meta.xml
<CustomField>
    <fullName>FE_Total_Formula__c</fullName>
    <formula>&apos;&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FE Total</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Requested_Attendance_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Attendance_Time__c</fullName>
    <inlineHelpText>Enter the time the technician should attend this Visit in the format - HH:MM</inlineHelpText>
    <label>Required On Site</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00:00</fullName>
            </value>
            <value>
                <fullName>00:30</fullName>
            </value>
            <value>
                <fullName>01:00</fullName>
            </value>
            <value>
                <fullName>01:30</fullName>
            </value>
            <value>
                <fullName>02:00</fullName>
            </value>
            <value>
                <fullName>02:30</fullName>
            </value>
            <value>
                <fullName>03:00</fullName>
            </value>
            <value>
                <fullName>03:30</fullName>
            </value>
            <value>
                <fullName>04:00</fullName>
            </value>
            <value>
                <fullName>04:30</fullName>
            </value>
            <value>
                <fullName>05:00</fullName>
            </value>
            <value>
                <fullName>05:30</fullName>
            </value>
            <value>
                <fullName>06:00</fullName>
            </value>
            <value>
                <fullName>06:30</fullName>
            </value>
            <value>
                <fullName>07:00</fullName>
            </value>
            <value>
                <fullName>07:30</fullName>
            </value>
            <value>
                <fullName>08:00</fullName>
            </value>
            <value>
                <fullName>08:30</fullName>
            </value>
            <value>
                <fullName>09:00</fullName>
            </value>
            <value>
                <fullName>09:30</fullName>
            </value>
            <value>
                <fullName>10:00</fullName>
            </value>
            <value>
                <fullName>10:30</fullName>
            </value>
            <value>
                <fullName>11:00</fullName>
            </value>
            <value>
                <fullName>11:30</fullName>
            </value>
            <value>
                <fullName>12:00</fullName>
            </value>
            <value>
                <fullName>12:30</fullName>
            </value>
            <value>
                <fullName>13:00</fullName>
            </value>
            <value>
                <fullName>13:30</fullName>
            </value>
            <value>
                <fullName>14:00</fullName>
            </value>
            <value>
                <fullName>14:30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/TechnicianCaladerEndDateTime__c.field-meta.xml
<CustomField>
    <fullName>TechnicianCaladerEndDateTime__c</fullName>
    <formula>if(AND(TEXT(End_Date__c) != null,Time_Allowed_for_Visit__c!=null),TEXT(End_Date__c)+&quot; &quot;+TEXT((VALUE( MID(TEXT(Requested_Attendance_Time__c), 1, 2))+VALUE( TEXT(if(isnull(Time_Allowed_for_Visit__c),0,value(MID(Time_Allowed_for_Visit__c,1,2)))) )+VALUE(MID(TechnicianCalendarMins__c,0,1))))+&apos;:&apos;+MID(TechnicianCalendarMins__c,3,4), 
IF(AND(TEXT(End_Date__c) != null,Time_Allowed_for_Visit__c=null),TEXT(End_Date__c)+&quot; 17:30&quot;,TEXT(Actual_Service_Date__c)+&quot; 17:30&quot;))</formula>
    <label>TechnicianCaladerEndDateTime</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/TechnicianCaladerStartDateTime__c.field-meta.xml
<CustomField>
    <fullName>TechnicianCaladerStartDateTime__c</fullName>
    <formula>if(TEXT(Requested_Attendance_Time__c) != null, 
TEXT(Actual_Service_Date__c)+&quot; &quot;+TEXT(Requested_Attendance_Time__c),TEXT(Actual_Service_Date__c)+&quot; 8:30&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TechnicianCaladerStartDateTime</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Type_of_Panel_DVR__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Panel_DVR__c</fullName>
    <description>This field pull through the Site Contract Type of Panel / DVR field.</description>
    <label>Type of Panel / DVR</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Visit_Complete__c.field-meta.xml
<CustomField>
    <fullName>Visit_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Complete</label>
    <type>Checkbox</type>
</CustomField>

objects/Visits__c/fields/Visit_Postcode__c.field-meta.xml
<CustomField>
    <fullName>Visit_Postcode__c</fullName>
    <formula>Site__r.ShippingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Postcode</label>
    <type>Text</type>
</CustomField>

classes/TechnicianCalendarHandler.cls
/*============================================================================================================
*Class Name     : TechnicianCalendarHandler 
*Description    : All the Technician Visit Details handled here.
*Company        : Puthuvannam Technology Solutions Pvt Ltd.
*Date           : 17th Sep, 2014
*Version        : 1.0
*Change History : Initial Trigger Handler
*============================================================================================================*/


global  class TechnicianCalendarHandler {
    
    public transient list<calEvent> BookingLists {get;set;}
    transient Engineer__c technicianId;
    //The calendar plugin is expecting dates is a certain format. We can use this string to get it formated correctly
    String dtFormat = 'EEE, d MMM yyyy HH:mm:ss z';
    
    transient Map<id,Visits__c > visitMap;
    Map<id,Holiday> HolidayMap; 
    
    transient  List<Service_Sheet_STD__c> RSRecord;
    transient List<Engineer_Checklist__c> SSRecord ;
    transient List<Mechanical_Service_Sheet__c> MSSRecord ;
    transient List<Small_Works__c> SWRecord ;
    transient List<Project_Sheet__c> PSRecord;
    
    transient Map<string,siteContractValues> rsMap =  new Map<string,siteContractValues>();
    transient Map<string,siteContractValues> ssMap =  new Map<string,siteContractValues>();
    transient Map<string,siteContractValues> mssMap =  new Map<string,siteContractValues>();
    transient Map<string,siteContractValues> swMap =  new Map<string,siteContractValues>();
    transient Map<string,siteContractValues> psMap =  new Map<string,siteContractValues>();

    public TechnicianCalendarHandler(ApexPages.StandardController controller) {
        this.technicianId = (Engineer__c)controller.getRecord();
        visitMap = new Map<id,Visits__c >([Select id,Engineer2__c,TechnicianCaladerStartDateTime__c,TechnicianCaladerEndDateTime__c,Requested_Attendance_Time__c,Visit_Postcode__c,FE_Total_Formula__c,Visit_Complete__c,Booked_with_Customers__c,Site_Contract__r.Type_of_Panel_DVR__c,Site_Contract__r.Job_Time__c,Site_Contract__r.Spend_Limit__c,Site_Contract__r.Service_Charge__c,X2nd_Technician__c,Actual_Service_Date__c,End_Date__c, Name, Visit_Type__c,Call_Out_Types__c,Site__r.name,Service_Type__c,Mechanical_Service_Sheet_Numbers__c,Reactive_Sheet_Number__c,Small_Works_Sheet_Number__c,Service_Sheet_Number__c,Project_Sheet_Number__c 
                                           From Visits__c  
                                           Where (X2nd_Technician__c=:technicianId.id or Engineer2__c=:technicianId.id) and Actual_Service_Date__c!=null ORDER BY createddate desc LIMIT 900]);  
        
        
        HolidayMap  = new Map<id,Holiday>([Select Name, Id, ActivityDate From Holiday limit 1000]);  
        
  
        siteContractValues scValues;
        try{
            RSRecord  = [SELECT id,name,Visit__c, createddate,Site_Contract__r.Job_Time__c,Site_Contract__r.Job_time_value__c  
                         FROM Service_Sheet_STD__c 
                         WHERE Visit__c 
                         IN :visitMap.keyset() and (Site_Contract__r.Job_Time__c != null) ORDER BY createddate desc LIMIT 700];
            if(RSRecord != null)
            {
            for(Service_Sheet_STD__c rs:RSRecord){
             scValues = new siteContractValues();
              scValues.scpaneldvr =rs.Site_Contract__r.Type_of_Panel_DVR__c;
              scValues.scjobtime = rs.Site_Contract__r.Job_Time__c;
              rsMap.put(rs.name,scValues);
             }
            }             
        }
        catch(exception e){
            
        }  

         
        try{                                
            SSRecord  = [SELECT id,name,Visit__c, createddate,Site_Contract__r.Type_of_Panel_DVR__c,Site_Contract__r.Job_Time__c,Site_Contract__r.Job_time_value__c  
                         FROM Engineer_Checklist__c 
                         WHERE Visit__c 
                         IN :visitMap.keyset() and (Site_Contract__r.Job_Time__c != null) ORDER BY createddate desc LIMIT 700];
        
         if(SSRecord != null)
            {
            for(Engineer_Checklist__c ss: SSRecord){
            scValues = new siteContractValues();
              scValues.scpaneldvr = ss.Site_Contract__r.Type_of_Panel_DVR__c;
              scValues.scjobtime = ss.Site_Contract__r.Job_Time__c;
              ssMap.put(ss.name,scValues);
             }
            }    
        
        }
        catch(exception e){
            
        } 
        
       
        try{                                 
            MSSRecord  = [SELECT id,name,Visit__c, createddate,Site_Contract__r.Type_of_Panel_DVR__c,Site_Contract__r.Job_Time__c,Site_Contract__r.Job_time_value__c  
                          FROM Mechanical_Service_Sheet__c
                          WHERE Visit__c 
                          IN :visitMap.keyset() and (Site_Contract__r.Job_Time__c != null) ORDER BY createddate desc LIMIT 700];
         if(MSSRecord != null)
            {
            for(Mechanical_Service_Sheet__c mss: MSSRecord){
            scValues = new siteContractValues();
              scValues.scpaneldvr = mss.Site_Contract__r.Type_of_Panel_DVR__c;
              scValues.scjobtime = mss.Site_Contract__r.Job_Time__c;
              mssMap.put(mss.name,scValues);
             }
            }
        
        
        }
        catch(exception e){
            
        }                                  
        
      
        try{                                
            SWRecord  = [SELECT id,name,Visit__c, createddate,Site_Contract__r.Type_of_Panel_DVR__c,Site_Contract__r.Job_Time__c,Site_Contract__r.Job_time_value__c  
                         FROM Small_Works__c 
                         WHERE Visit__c 
                         IN :visitMap.keyset() and (Site_Contract__r.Job_Time__c != null) ORDER BY createddate desc LIMIT 700];
        
         if(SWRecord  != null)
            {
            for(Small_Works__c sw: SWRecord  ){
            scValues = new siteContractValues();
              scValues.scpaneldvr = sw.Site_Contract__r.Type_of_Panel_DVR__c;
              scValues.scjobtime = sw.Site_Contract__r.Job_Time__c;
              swMap.put(sw.name,scValues);
             }
            }
         
        }
        catch(exception e){
            
        }
        
        try{                                 
            PSRecord  = [SELECT id,name,Visit__c, createddate,Site_Contract__r.Type_of_Panel_DVR__c,Site_Contract__r.Job_Time__c,Site_Contract__r.Job_time_value__c  
                         FROM Project_Sheet__c 
                         WHERE Visit__c 
                         IN :visitMap.keyset() and (Site_Contract__r.Job_Time__c != null) ORDER BY createddate desc LIMIT 700];                                                                                                                                          
        
        
         if(PSRecord  != null)
            {
            for(Project_Sheet__c ps: PSRecord  ){
            scValues = new siteContractValues();
              scValues.scpaneldvr = ps.Site_Contract__r.Type_of_Panel_DVR__c;
              scValues.scjobtime = ps.Site_Contract__r.Job_Time__c;
              psMap.put(ps.name,scValues);
             }
            }
            
        
        }
        catch(exception e){
            
        }
        
     
    }
    
    
    public PageReference pageLoad() {
        BookingLists = new list<calEvent>();
        
        
         transient String LeastSSName = 'NA';
         transient String SSName = 'NA';
        //Get my BookingLists if we have selected the correct option
        for(Visits__c v : visitMap.values()){
           
            DateTime startDT = v.Actual_Service_Date__c;
            string startdate = v.TechnicianCaladerStartDateTime__c;
            string enddate = v.TechnicianCaladerEndDateTime__c;
            DateTime endDT = v.End_Date__c;
            calEvent myEvent = new calEvent();
            myEvent.title ='Visit : '+ v.name;
           
            if(v.Service_Sheet_Number__c != Null){LeastSSName = v.Service_Sheet_Number__c; SSName = 'SS';
           
            }else if(v.Mechanical_Service_Sheet_Numbers__c != Null){LeastSSName = v.Mechanical_Service_Sheet_Numbers__c;SSName = 'MSS';
            
            }else if(v.Reactive_Sheet_Number__c!= Null){LeastSSName = v.Reactive_Sheet_Number__c;SSName = 'RS';
            
            }else if(v.Small_Works_Sheet_Number__c!= Null){LeastSSName = v.Small_Works_Sheet_Number__c;SSName = 'SW';

            }else if(v.Project_Sheet_Number__c!= Null){LeastSSName = v.Project_Sheet_Number__c;SSName = 'PS';
            
            }else{
             LeastSSName  = 'NA';
            }
            
           
            myEvent.serviceType =(v.Service_Type__c != null ? 'Service Type: '+ v.Service_Type__c :'Service Type: ') ;   
            myEvent.visitType =(v.Visit_Type__c != null ? 'Visit Type: '+ v.Visit_Type__c :'Visit Type: ') ;   
                      
            myEvent.siteName =(v.Site__r.name != null ? 'Site Name: '+ v.Site__r.name :'Site Name: ') ;
            myEvent.servicecharge =(v.Site_Contract__r.Service_Charge__c != null ? 'Service Charge: '+ v.Site_Contract__r.Service_Charge__c :'Service Charge: 0.0') ;
            myEvent.postCode =(v.Visit_Postcode__c != null ? 'PostCode: '+ v.Visit_Postcode__c :'PostCode: ') ;
            myEvent.feTotal=(v.FE_Total_Formula__c!= null ? 'FE Total: '+ v.FE_Total_Formula__c:'FE Total: ') ;
            myEvent.attendanceTime=(v.Requested_Attendance_Time__c!= null ? 'Requested Attendance Time: '+ v.Requested_Attendance_Time__c:'Requested Attendance Time:') ;
            
            myEvent.spendLimit=(v.Site_Contract__r.Spend_Limit__c != null ? 'Spend Limit: '+ v.Site_Contract__r.Spend_Limit__c:'Spend Limit: ') ;
            
            myEvent.spend  = (v.Site_Contract__r.Spend_Limit__c != null ? v.Site_Contract__r.Spend_Limit__c  :'0.0') ;
            myEvent.scharge  = (v.Site_Contract__r.Service_Charge__c != null ? v.Site_Contract__r.Service_Charge__c :0.0) ;
            
            //myEvent.scpaneldvr = (v.Site_Contract__r.Type_of_Panel_DVR__c!= null ? 'Type of Panel DVR: '+ v.Site_Contract__r.Type_of_Panel_DVR__c:'Type of Panel DVR: ') ;
            //myEvent.scjobtime = (v.Site_Contract__r.Job_Time__c != null ? 'Job Time: '+ v.Site_Contract__r.Job_Time__c:'Job Time: ') ;
             
             
            if(LeastSSName != 'NA'  && rsMap.get(LeastSSName) != null && SSName == 'RS'){
            myEvent.scpaneldvr = (rsMap.get(LeastSSName).scpaneldvr != null ? 'Type of Panel DVR: '+rsMap.get(LeastSSName).scpaneldvr:'Type of Panel DVR: ');
            myEvent.scjobtime = (string.valueOf(rsMap.get(LeastSSName).scjobtime) != null ? 'Job Time: '+ string.valueOf(rsMap.get(LeastSSName).scjobtime) :'Job Time: '); 
            }
            else{
            myEvent.scpaneldvr = 'Type of Panel DVR: ';
            myEvent.scjobtime = 'Job Time: ';
            }
            
            if(LeastSSName != 'NA'  && ssMap.get(LeastSSName) != null  && SSName == 'SS'){
            myEvent.scpaneldvr = (ssMap.get(LeastSSName).scpaneldvr != null ? 'Type of Panel DVR: '+ssMap.get(LeastSSName).scpaneldvr:'Type of Panel DVR: ');
            myEvent.scjobtime = (string.valueOf(ssMap.get(LeastSSName).scjobtime) != null ? 'Job Time: '+ string.valueOf(ssMap.get(LeastSSName).scjobtime) :'Job Time: '); 
            }
            else{
            myEvent.scpaneldvr = 'Type of Panel DVR: ';
            myEvent.scjobtime = 'Job Time: ';
            }
            
            if(LeastSSName != 'NA'  &&  mssMap.get(LeastSSName) != null  && SSName == 'MSS'){
            myEvent.scpaneldvr = (mssMap.get(LeastSSName).scpaneldvr != null ? 'Type of Panel DVR: '+mssMap.get(LeastSSName).scpaneldvr:'Type of Panel DVR: ');
            myEvent.scjobtime = (string.valueOf(mssMap.get(LeastSSName).scjobtime) != null ? 'Job Time: '+ string.valueOf(mssMap.get(LeastSSName).scjobtime) :'Job Time: '); 
            }
            else{
            myEvent.scpaneldvr = 'Type of Panel DVR: ';
            myEvent.scjobtime = 'Job Time: ';
            }
            
            if(LeastSSName != 'NA'  && swMap.get(LeastSSName) != null && SSName == 'SW'){
            myEvent.scpaneldvr = (swMap.get(LeastSSName).scpaneldvr != null ? 'Type of Panel DVR: '+swMap.get(LeastSSName).scpaneldvr:'Type of Panel DVR: ');
            myEvent.scjobtime = (string.valueOf(swMap.get(LeastSSName).scjobtime) != null ? 'Job Time: '+ string.valueOf(swMap.get(LeastSSName).scjobtime) :'Job Time: '); 
            }
            else{
            myEvent.scpaneldvr = 'Type of Panel DVR: ';
            myEvent.scjobtime = 'Job Time: ';
            }
            
            if(LeastSSName != 'NA'  && psMap.get(LeastSSName) != null && SSName == 'PS'){
            myEvent.scpaneldvr = (psMap.get(LeastSSName).scpaneldvr != null ? 'Type of Panel DVR: '+psMap.get(LeastSSName).scpaneldvr:'Type of Panel DVR: ');
            myEvent.scjobtime = (string.valueOf(psMap.get(LeastSSName).scjobtime) != null ? 'Job Time: '+ string.valueOf(psMap.get(LeastSSName).scjobtime) :'Job Time: '); 
            }
            else{
            myEvent.scpaneldvr = 'Type of Panel DVR: ';
            myEvent.scjobtime = 'Job Time: ';
            }
            
            myEvent.url = '/' + v.Id ;
            
             if(v.End_Date__c != null){
             myEvent.startString =startdate ;
             myEvent.endString = enddate;
            }
            if(v.End_Date__c == null){
             myEvent.startString =startdate ;
             myEvent.endString = startdate ;
            }
           
            if(v.Visit_Complete__c == true){
                myEvent.className = 'complete';
                BookingLists.add(myEvent);
            }
            else if(v.Booked_with_Customers__c=='Yes' && v.Actual_Service_Date__c == date.today()){
                myEvent.className = 'bookedtoday';
                BookingLists.add(myEvent);
            }
            else if(v.Booked_with_Customers__c=='Yes'){
                myEvent.className = 'bookedwithcustomers';
                BookingLists.add(myEvent);
            }
            else if(v.Booked_with_Customers__c=='Waiting P/O' || v.Booked_with_Customers__c=='Waiting Permit' || v.Booked_with_Customers__c=='Waiting Confirmation'){
                myEvent.className = 'bookedwithcustomersothers';
                BookingLists.add(myEvent);
            }
            else if(v.Booked_with_Customers__c=='Booked Via Schedule'){
                myEvent.className = 'scheduled-work';
                BookingLists.add(myEvent);
            }
            else if(v.Visit_Type__c =='Holiday'){
                myEvent.className = 'holiday';
                BookingLists.add(myEvent);
            }
            else if(v.Visit_Type__c =='Projects'){
                myEvent.className = 'projects';
                BookingLists.add(myEvent);
            }
            else if(v.Call_Out_Types__c =='Call Out'){
                myEvent.className = 'call-out-day';
                BookingLists.add(myEvent);
            }
            else if(v.Call_Out_Types__c =='Small Works'){
                myEvent.className = 'small-works';
                BookingLists.add(myEvent);
            }
            
            else{
                myEvent.className = 'no-work';
                BookingLists.add(myEvent);
            }
            
        }
        
        for(Holiday h:HolidayMap.values()){
            DateTime startDT = h.ActivityDate;
            DateTime endDT = h.ActivityDate;
            calEvent myEvent = new calEvent();
            
            myEvent.title = h.name;
            myEvent.startString = startDT.format(dtFormat,'America/Los_Angeles');
            myEvent.endString = startDT.format(dtFormat,'America/Los_Angeles');
            myEvent.className = 'holiday';
            BookingLists.add(myEvent);
        }
        return null;
    }
     public class siteContractValues{
         public transient String scpaneldvr{get;set;}
         public transient decimal  scjobtime{get;set;}
     }
    //Class to hold calendar event data
    public class calEvent{
        public transient String title {get;set;}
        public transient String serviceType {get;set;}
        public transient String visitType {get;set;}
        public transient String siteName {get;set;}
        
        public transient String spend {get;set;}
        Public transient decimal scharge{get;set;}
        
        Public transient String startString {get;set;}
        Public transient String endString {get;set;}
        Public transient String url {get;set;}
        Public transient String className {get;set;}
        Public transient String servicecharge {get;set;}
        Public transient String postCode {get;set;}
        Public transient String feTotal{get;set;}
        Public transient String attendanceTime{get;set;}
        Public transient String holidayName{get;set;}
        Public transient String spendLimit{get;set;}
        
        
        
        Public transient String scpaneldvr{get;set;}
        Public transient String scjobtime{get;set;}
        

        
    }
    
    @RemoteAction
    global static Visits__c UpdateVisit(string actualServiceDate, string endDate, string visitURL) {
        Visits__c updateVisit = new Visits__c();
        Map<id,Holiday> HolidayMap = new Map<id,Holiday>([Select Name, Id, ActivityDate From Holiday limit 50000]);  
        DateTime dragStartDate ;
        DateTime dragEndDate ;
        String dtFormat = 'EEE, d MMM yyyy HH:mm:ss z';
        
        
        
        List <String> stringParts1 = actualServiceDate.split('T');
        List <String> stringParts = stringParts1[0].split('-');
        List <String> timeParts = stringParts1[1].split(':');
        dragStartDate = DateTime.newInstanceGmt(Integer.valueOf(stringParts[0]), Integer.valueOf(stringParts[1]), Integer.valueOf(stringParts[2]), Integer.valueOf(timeParts[0]), Integer.valueOf(timeParts[1]), Integer.valueOf(timeParts[2]));
        
        if(endDate!=null){
            List <String> stringEndParts1 = endDate.split('T');
            List <String> stringEndParts = stringEndParts1[0].split('-');
            List <String> timeEndParts = stringEndParts1[1].split(':');
            dragEndDate = DateTime.newInstanceGmt(Integer.valueOf(stringEndParts[0]), Integer.valueOf(stringEndParts[1]), Integer.valueOf(stringEndParts[2]), Integer.valueOf(timeEndParts[0]), Integer.valueOf(timeEndParts[1]), Integer.valueOf(timeEndParts[2]));
            
            list<string> IdList=visitURL.split('/');
            updateVisit =[Select id,Engineer2__c,X2nd_Technician__c,Actual_Service_Date__c,End_Date__c, Name, Visit_Type__c,Call_Out_Types__c 
                          From Visits__c  where id =:IdList[1]];
            
            
            for(Holiday h:HolidayMap.values()){
                if(h.ActivityDate ==dragStartDate.date() || h.ActivityDate == dragEndDate.date() || (h.ActivityDate >= dragStartDate.date() && h.ActivityDate <= dragEndDate.date() )  ){
                    throw new RecordNotFoundException('Visit date is Holiday');
                }
            }
            
            updateVisit.Actual_Service_Date__c=dragStartDate.date();
            updateVisit.End_Date__c = dragEndDate.date();
            
            
            
        }else{    dragEndDate  = dragStartDate;  }    
        if(!Test.isRunningTest()){
            if(updateVisit != null) {  update updateVisit; }
        }
        return updateVisit;
    }
    
    
    public class RecordNotFoundException extends Exception { }
    
}