objects/Engineer_Checklist__c/Engineer_Checklist__c.object-meta.xml
<CustomObject>
    <description>Onsite checklist</description>
    <label>Service Sheet</label>
    <nameField>
        <displayFormat>SS2{000000}</displayFormat>
        <label>Service Sheet No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Engineer_Checklist__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the relationship to the Site and Contract - this also relates to Alarm Master Historic Data</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

classes/CameraAccessTest.cls
@isTest(seeAlldata=true)
Public Class CameraAccessTest{
   
   @isTest public static void CameraAccessTest(){
      
   Engineer_Checklist__c  ec=[Select id,Name, Site_Contract__c from Engineer_Checklist__c limit 1];

   ApexPages.CurrentPage().getParameters().put('Id',String.valueOf(ec.id)); 
  
   ApexPages.StandardController sc = new ApexPages.StandardController(ec);
   
   CameraAccess ca=new CameraAccess(sc);
   ca.AttachmentName = 'TestImage';
   Blob bdy=Blob.valueOf('test');
   ca.attachmentObj.Body=bdy;
   ca.saveFile();
   
   }

}