objects/Engineer_Checklist__c/Engineer_Checklist__c.object-meta.xml
<CustomObject>
    <description>Onsite checklist</description>
    <label>Service Sheet</label>
    <nameField>
        <displayFormat>SS2{000000}</displayFormat>
        <label>Service Sheet No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Engineer_Checklist__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the relationship to the Site and Contract - this also relates to Alarm Master Historic Data</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Organization</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Order/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PartsConfig__c/PartsConfig__c.object-meta.xml
<CustomObject>
    <label>PartsConfig</label>
    <nameField>
        <displayFormat>PRT-{00000}</displayFormat>
        <label>Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PartsConfig</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PartsConfig__c/fields/isDefaultProduct__c.field-meta.xml
<CustomField>
    <fullName>isDefaultProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDefaultProduct</label>
    <type>Checkbox</type>
</CustomField>

objects/PartsConfig__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>PartsConfig</relationshipLabel>
    <relationshipName>PartsConfig</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product2/fields/Supplier_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product_Code__c</fullName>
    <label>Supplier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Required_Parts__c/Required_Parts__c.object-meta.xml
<CustomObject>
    <label>Required Parts</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Required Parts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Required Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Required_Parts__c/fields/Include_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Include_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Include Invoice</label>
    <type>Checkbox</type>
</CustomField>

objects/Required_Parts__c/fields/Maintenance_Reactive_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Reactive_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maintenance &amp; Reactive Sheet</label>
    <referenceTo>Service_Sheet_STD__c</referenceTo>
    <relationshipLabel>Required Parts</relationshipLabel>
    <relationshipName>Required_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Required_Parts__c/fields/Parts_Used_Description__c.field-meta.xml
<CustomField>
    <fullName>Parts_Used_Description__c</fullName>
    <label>Parts Used / Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Required_Parts__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Required Parts</relationshipLabel>
    <relationshipName>Required_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Required_Parts__c/fields/Service_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Service_Sheet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Sheet</label>
    <referenceTo>Engineer_Checklist__c</referenceTo>
    <relationshipLabel>Required Parts</relationshipLabel>
    <relationshipName>Required_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Required_Parts__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Required Parts</relationshipLabel>
    <relationshipName>Required_Parts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Service_Sheet_STD__c/Service_Sheet_STD__c.object-meta.xml
<CustomObject>
    <label>M&amp;R Sheet</label>
    <nameField>
        <displayFormat>RS{000000}</displayFormat>
        <label>Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>M&amp;R Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Sheet_STD__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Relates to the contract which will cover this service sheet</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipName>Reactive_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Price_Book_IdFormula__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_IdFormula__c</fullName>
    <formula>IF(Price_Book__c &lt;&gt; &apos;&apos;, Price_Book__c, Site__r.Price_Book__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This shows the price book ID that will be used when we create the opportunity.</inlineHelpText>
    <label>Price Book Id (Customer / Site)</label>
    <type>Text</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateSheetsParts.cls
public class UpdateSheetsParts {

   
    public String searchString {get;set;}
    public Required_Parts__c[] shoppingCart {get;set;}
    public Product2[] AvailableProducts {get;set;}
    public List<product2> prd;   
    public String toSelect {get; set;}
    public String toUnselect {get; set;}
    public Decimal Total {get;set;}
    public List<String> Prdids;
    public List<String> pbid;
    public Engineer_Checklist__c  Eng;
    public Service_Sheet_STD__c reac;
    public Id CurrentId;
    public Boolean overLimit {get;set;}
    public Boolean multipleCurrencies {get; set;}
    String Soql='';
    Schema.SObjectType sObjName;
   // String pbook;
    private Boolean forcePricebookSelection = false;
    
    private Required_Parts__c[] forDeletion = new Required_Parts__c[]{};

    public UpdateSheetsParts(ApexPages.StandardController controller) {
        
        sObjName = controller.getRecord().Id.getSObjectType();
        system.debug('sObjName ='+sObjName );
        CurrentId=controller.getRecord().Id;
        system.debug('CurrentId='+CurrentId);
        Soql='select Id,Product_Name__c,Include_Invoice__c,Quantity__c,Parts_Used_Description__c,Location__c,Warehouse__c from Required_Parts__c where ';
        Soql+=String.valueof(sObjName)=='Engineer_Checklist__c'?'Service_Sheet__c=:CurrentId':'Maintenance_Reactive_Sheet__c=:CurrentId';
        system.debug('Soql===='+Soql);
        shoppingCart =database.query(Soql);
        system.debug('shoppingCart ='+shoppingCart );
        
        updateAvailableList();
    }
    
     public void updateAvailableList() {
        
        Prdids=new List<String>();
        pbid = new List<String>();
        system.debug('shoppingCart updateAvailableList='+ shoppingCart );
        for(Required_Parts__c ShopId:shoppingCart)
        Prdids.add(ShopId.Product_Name__c);
        system.debug('Prdids===='+Prdids);
        
       // String qString = 'select Id, Product_Name__r.Name,namefrom PartsConfig__c where isDefaultProduct__c=false and nameNOT IN:Prdids';
        //system.debug('qString ='+qString );
        if(String.valueof(sObjName) =='Engineer_Checklist__c'){
        Eng=[select id,name,Site_Contract__r.Price_Book_IdFormula__c from Engineer_Checklist__c where id=:CurrentId];
        String[] pbook= new String[]{Eng.Site_Contract__r.Price_Book_IdFormula__c};
        system.debug('pbook=='+pbook);
     
        List<PricebookEntry> pbe = new List<PricebookEntry>();
        pbe = [select id,name,Pricebook2Id from PricebookEntry where pricebook2Id =:pbook];
        system.debug('pbe===='+pbe );
         
        for(PricebookEntry pe :pbe){
          
                pbid.add(pe.name);
            
        }
          }
          
         else if(String.valueof(sObjName) =='Service_Sheet_STD__c'){
        reac=[select id,name,Site_Contract__r.Price_Book_IdFormula__c from Service_Sheet_STD__c where id=:CurrentId];
        String[] pbook= new String[]{reac.Site_Contract__r.Price_Book_IdFormula__c};
        system.debug('pbook=='+pbook);
     
        List<PricebookEntry> pbe = new List<PricebookEntry>();
        pbe = [select id,name,Pricebook2Id from PricebookEntry where pricebook2Id =:pbook];
        system.debug('pbe===='+pbe );
         
        for(PricebookEntry pe :pbe){
          
                pbid.add(pe.name);
            
        }
          }
         system.debug('pbid==='+pbid);
       String  qString='select id,name from product2 where name IN:pbid';
       system.debug('qString==='+qString);
       
        
        //system.debug('Eng====='+Eng.Site_Contract__r.Price_Book_IdFormula__c);
        
       /* for(Engineer_Checklist__c Eng:[select id,Site_Contract__r.Price_Book_IdFormula__c from Engineer_Checklist__c where id=:CurrentId]){
       if(Eng.Site_Contract__r.Price_Book_IdFormula__c!=null){
        site.add(Eng.Site_Contract__r.Price_Book_IdFormula__c);
        }
        } */
       // system.debug('Eng====='+Eng);
      // system.debug('site===='+site);
        if(searchString!=null){
        
            qString ='select name from product2 where name IN:pbid and (name like \'%' +searchString+ '%\' or Description like \'%' + searchString + '%\'  or ProductCode like \'%' + searchString + '%\' or Supplier_Product_Code__c  like \'%' + searchString + '%\')';
           // qString+= ' and (Product_Name__r.Name like \'%' + searchString + '%\')';
       // prd=[select name from product2 where name IN:pbid and name like '% searchString %' ];
        //system.debug('prd======='+prd);
            system.debug('qString inside='+qString);
        }
        
        Set<String> selectedEntries = new Set<String>();
        for(Required_Parts__c d:shoppingCart){
            selectedEntries.add(d.Product_Name__c);
        }
        
        if(selectedEntries.size()>0){
            String tempFilter = ' and Id not in (';
            for(Id i : selectedEntries){
                tempFilter+= '\'' + (String)i + '\',';
            }
            String extraFilter = tempFilter.substring(0,tempFilter.length()-1);
            extraFilter+= ')';
            
            qString+= extraFilter;
        }
        
        qString+= ' order by Name';
        qString+= ' limit 101';
        
        system.debug('qString:>>>' +qString);        
        AvailableProducts = database.query(qString);
        system.debug('AvailableProducts:>>>>'+AvailableProducts);
        
        if(AvailableProducts.size()==101){
            AvailableProducts.remove(100);
            overLimit = true;
        }
        else{
            overLimit=false;
        }
    }
    
    public void addToShoppingCart(){
    
        for(Product2 d : AvailableProducts){
            if((String)d.Id==toSelect){
                if(string.valueof(sObjName)=='Service_Sheet_STD__c')
                shoppingCart.add(new Required_Parts__c(Product_Name__c=d.id, Quantity__c=1,Location__c ='',Maintenance_Reactive_Sheet__c=CurrentId,Include_Invoice__c=true,Parts_Used_Description__c=''));
                else
                shoppingCart.add(new Required_Parts__c(Product_Name__c=d.id, Quantity__c=1,Location__c ='',Service_Sheet__c=CurrentId,Include_Invoice__c=true,Parts_Used_Description__c=''));
                break;
            }
        }
        
        updateAvailableList();  
    }
    

    public PageReference removeFromShoppingCart(){
    
        Integer count = 0;
    
        for(Required_Parts__c d : shoppingCart){
            if((String)d.Product_Name__c==toUnselect){
            
                if(d.Id!=null)
                    forDeletion.add(d);
            
                shoppingCart.remove(count);
                break;
            }
            count++;
        }
        
        updateAvailableList();
        
        return null;
    }
    
    public PageReference onSave(){
    
        if(forDeletion.size()>0)
            delete(forDeletion);
    
        try{
            if(shoppingCart.size()>0)
                upsert(shoppingCart);
        }
        catch(Exception e){
            ApexPages.addMessages(e);
            return null;
        }  
           
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }
    
    public PageReference onCancel(){
 
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }
}