objects/Complaints__c/Complaints__c.object-meta.xml
<CustomObject>
    <description>Used to record customer complaints.</description>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Compliant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Complaints__c/fields/Passed_To__c.field-meta.xml
<CustomField>
    <fullName>Passed_To__c</fullName>
    <inlineHelpText>Enter the name of the person you passed this onto to complete.</inlineHelpText>
    <label>Passed To</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adrian Warne</fullName>
            </value>
            <value>
                <fullName>Alison Read</fullName>
            </value>
            <value>
                <fullName>Anne Bassinder</fullName>
            </value>
            <value>
                <fullName>Beverley Harris</fullName>
            </value>
            <value>
                <fullName>Chester Bidmead</fullName>
            </value>
            <value>
                <fullName>Darren Crompton</fullName>
            </value>
            <value>
                <fullName>Diana Pascoe</fullName>
            </value>
            <value>
                <fullName>Gwen Bradby</fullName>
            </value>
            <value>
                <fullName>Harvey Melvin</fullName>
            </value>
            <value>
                <fullName>Joanna Fyffe</fullName>
            </value>
            <value>
                <fullName>Joel Bidmead</fullName>
            </value>
            <value>
                <fullName>Laura Borthwick</fullName>
            </value>
            <value>
                <fullName>Michelle Bassinder</fullName>
            </value>
            <value>
                <fullName>Natasha Blake</fullName>
            </value>
            <value>
                <fullName>Nicki Pratten</fullName>
            </value>
            <value>
                <fullName>Nigel Welch</fullName>
            </value>
            <value>
                <fullName>Paul Faraway</fullName>
            </value>
            <value>
                <fullName>Phil Bassinder</fullName>
            </value>
            <value>
                <fullName>Rachel Dowrick</fullName>
            </value>
            <value>
                <fullName>Rachel Yelland</fullName>
            </value>
            <value>
                <fullName>Samantha Cavinder</fullName>
            </value>
            <value>
                <fullName>Samantha Spencer</fullName>
            </value>
            <value>
                <fullName>Sarah Bayley</fullName>
            </value>
            <value>
                <fullName>Sharon Standen</fullName>
            </value>
            <value>
                <fullName>Tracey Coles</fullName>
            </value>
            <value>
                <fullName>Viv Stuchberry</fullName>
            </value>
            <value>
                <fullName>Warren Bidmead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Complaints__c/fields/Passed_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Passed_To_Email__c</fullName>
    <label>Passed To Email</label>
    <type>Email</type>
</CustomField>

classes/ComplaintTriggerHandler.cls
/*============================================================================================================
*Class Name     : ComplaintTriggerHandler
*Description    : To send a mail to the Passed To field Value
*Company        : Puthuvannam Technology Solutions
*Date           : 25th Jul, 2014
*Version        : 1.0
*Change History : Initial Trigger Handler
*Methods        : public void OnAfterUpdate(Map<id,Complaint> complaintNewMap)
                  
                 
*============================================================================================================*/
public class ComplaintTriggerHandler{

public list<Complaints__c> newList;
/*====================================================

*Method Name     : OnBeforeInsert
*Description     : Handle the Before Insert operation
*Arguments       : new map list
====================================================*/

    public void onBeforeInsert(List<Complaints__c > complaintNewList){
    
        passComplaints(complaintNewList);
    
    }
/*====================================================

*Method Name     : OnBeforeUpdate
*Description     : Handle the Before Update operation
*Arguments       : new map list
====================================================*/    
    public void onBeforeUpdate(List<Complaints__c > complaintNewList){
        if(RecursiveHandler.runCTH_UPCOnce()){
        	this.passComplaints(complaintNewList);
        }    
    
    }
/*====================================================

*Method Name     : passComplaints
*Description     : Insert or Update Passed To Complaints Email Field
*Arguments       : new map list
====================================================*/
    private void passComplaints(List<Complaints__c > complaintNewList){
        String Name;
        for(Complaints__c c:complaintNewList){
            //Name= complaintNewMap.get(c.id).Passed_To__c;
            if(c.Passed_To__c!=NULL){
            
            
            Name=c.Passed_To__c;
            Name = Name.replaceAll( '\\s+', '.');
            Name=Name+'@hentland.com';
            System.Debug('======Name'+Name);
            c.Passed_To_Email__c=Name;
            System.Debug('======'+c.Passed_To_Email__c);
            //Insert c;
            }
        }
         
    }
}