objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The technician is either on holiday, sick, or training.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Setting__mdt/fields/DB_End_Time__c.field-meta.xml
<CustomField>
    <fullName>DB_End_Time__c</fullName>
    <label>DB End Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:00:00</fullName>
                <default>true</default>
                <label>1:00:00</label>
            </value>
            <value>
                <fullName>2:00:00</fullName>
            </value>
            <value>
                <fullName>3:00:00</fullName>
            </value>
            <value>
                <fullName>4:00:00</fullName>
            </value>
            <value>
                <fullName>5:00:00</fullName>
            </value>
            <value>
                <fullName>6:00:00</fullName>
            </value>
            <value>
                <fullName>7:00:00</fullName>
            </value>
            <value>
                <fullName>8:00:00</fullName>
            </value>
            <value>
                <fullName>9:00:00</fullName>
            </value>
            <value>
                <fullName>10:00:00</fullName>
            </value>
            <value>
                <fullName>11:00:00</fullName>
            </value>
            <value>
                <fullName>12:00:00</fullName>
            </value>
            <value>
                <fullName>13:00:00</fullName>
            </value>
            <value>
                <fullName>14:00:00</fullName>
            </value>
            <value>
                <fullName>15:00:00</fullName>
            </value>
            <value>
                <fullName>16:00:00</fullName>
            </value>
            <value>
                <fullName>17:00:00</fullName>
            </value>
            <value>
                <fullName>18:00:00</fullName>
            </value>
            <value>
                <fullName>19:00:00</fullName>
            </value>
            <value>
                <fullName>20:00:00</fullName>
            </value>
            <value>
                <fullName>21:00:00</fullName>
            </value>
            <value>
                <fullName>22:00:00</fullName>
            </value>
            <value>
                <fullName>23:00:00</fullName>
            </value>
            <value>
                <fullName>00:00:00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Setting__mdt/fields/DB_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>DB_Start_Time__c</fullName>
    <label>DB Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:00:00</fullName>
                <default>true</default>
                <label>1:00:00</label>
            </value>
            <value>
                <fullName>2:00:00</fullName>
            </value>
            <value>
                <fullName>3:00:00</fullName>
            </value>
            <value>
                <fullName>4:00:00</fullName>
            </value>
            <value>
                <fullName>5:00:00</fullName>
            </value>
            <value>
                <fullName>6:00:00</fullName>
            </value>
            <value>
                <fullName>7:00:00</fullName>
            </value>
            <value>
                <fullName>8:00:00</fullName>
            </value>
            <value>
                <fullName>9:00:00</fullName>
            </value>
            <value>
                <fullName>10:00:00</fullName>
            </value>
            <value>
                <fullName>11:00:00</fullName>
            </value>
            <value>
                <fullName>12:00:00</fullName>
            </value>
            <value>
                <fullName>13:00:00</fullName>
            </value>
            <value>
                <fullName>14:00:00</fullName>
            </value>
            <value>
                <fullName>15:00:00</fullName>
            </value>
            <value>
                <fullName>16:00:00</fullName>
            </value>
            <value>
                <fullName>17:00:00</fullName>
            </value>
            <value>
                <fullName>18:00:00</fullName>
            </value>
            <value>
                <fullName>19:00:00</fullName>
            </value>
            <value>
                <fullName>20:00:00</fullName>
            </value>
            <value>
                <fullName>21:00:00</fullName>
            </value>
            <value>
                <fullName>22:00:00</fullName>
            </value>
            <value>
                <fullName>23:00:00</fullName>
            </value>
            <value>
                <fullName>00:00:00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <formula>IF ( Is_in_a_shopping_centre__c &lt;&gt; &quot;&quot;, IF ( Is_in_a_shopping_centre__c &lt;&gt; &quot;No&quot;, IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;red&quot;,20,20)&amp; &quot;This is in a shopping centre : &quot;&amp;Is_in_a_shopping_centre__c&amp;BR(),&quot;&quot;),&quot;&quot;)&amp;

IF (  Site_Contract__r.Specific_Day__c  &lt;&gt; &quot;&quot;, IF ( Site_Contract__r.Specific_Day__c  &lt;&gt; &quot;No&quot;, IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;red&quot;,20,20)&amp; &quot;Specific Date/Time: &quot;&amp;Site_Contract__r.Specific_Day__c &amp;BR(),&quot;&quot;),&quot;&quot;)&amp;

IF (  Site__r.Site_Induction__c  &lt;&gt; &quot;&quot;, IF ( Site__r.Site_Induction__c  &lt;&gt; &quot;No&quot;, IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;red&quot;,20,20)&amp; &quot;Permit Required : &quot;&amp;Site__r.Site_Induction__c &amp;BR(),&quot;&quot;),&quot;&quot;)&amp;
  
IF(  TEXT(Site_Contract__r.Site__r.UK_Related__c) = &quot;Yes&quot;,IMAGE( &quot;/img/samples/color_red.gif&quot;, &quot;red&quot;, 15, 15) &amp;&quot; OFFSHORE SITE &quot;&amp;IMAGE( &quot;/img/samples/color_red.gif&quot;, &quot;red&quot;, 15, 15), &quot;&quot;)&amp;

IF(   AND(TEXT(Original_Actual_Service_Date__c) &lt;&gt; &quot;&quot;,  TEXT(Actual_Service_Date__c) &lt;&gt; &quot;&quot;, Actual_Service_Date__c - Original_Actual_Service_Date__c &gt; 60), IMAGE( &quot;/img/samples/color_red.gif&quot;, &quot;red&quot;, 15, 15)&amp;&quot; NOTE Original Service Date is &quot;&amp;TEXT(Actual_Service_Date__c - Original_Actual_Service_Date__c)&amp;&quot; days in the past&quot; , &quot;&quot;)&amp;

IF (  OR ( 
        TEXT(Site_Contract__r.AM_Status__c) = &quot;Dormant&quot;,
        TEXT(Site_Contract__r.AM_Status__c) = &quot;Hold&quot; ),
&quot;***** WARNING THIS ACCOUNT IS &quot;&amp;TEXT(Site_Contract__r.AM_Status__c)&amp;&quot; ******   &quot; &amp;IMAGE( &quot;/img/samples/color_red.gif&quot;, &quot;red&quot;, 15, 200), &quot;&quot; 
   )

&amp;

IF(
AND (TEXT (Accepted__c) = &quot;Yes&quot;,  IF( ISPICKVAL(Booked_with_Customers__c, &apos;Yes&apos;),1,0) = 1), IMAGE( &quot;/img/samples/color_green.gif&quot;, &quot;green&quot;, 15, 200),


IF(AND( Actual_Service_Date__c &lt; TODAY() + 2,   IF(ISPICKVAL(Booked_with_Customers__c, &apos;Yes&apos;),1,0) = 0),IMAGE( &quot;/img/samples/color_red.gif&quot;, &quot;red&quot;, 15, 200),

IF(AND( Actual_Service_Date__c &lt; TODAY() + 3,  IF(ISPICKVAL(Booked_with_Customers__c, &apos;Yes&apos;),1,0) = 0),IMAGE( &quot;/img/samples/color_red.gif&quot;, &quot;red&quot;, 15, 150),

IF(AND( Actual_Service_Date__c &lt; TODAY() + 4,  IF(ISPICKVAL(Booked_with_Customers__c, &apos;Yes&apos;),1,0) = 0),IMAGE( &quot;/img/samples/color_yellow.gif&quot;, &quot;yellow&quot;, 15, 200),

IF
(AND (Actual_Service_Date__c &lt; TODAY()+ 5,   IF(ISPICKVAL(Booked_with_Customers__c, &apos;Yes&apos;),1,0)= 0),IMAGE( &quot;/img/samples/color_yellow.gif&quot;, &quot;yellow&quot;, 15, 150),




 &quot;&quot;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Accepted is Yes and Booked with Customer is true- Green
Actual Service Date is a day away and BWC is false - Long Red  
Actual Service Date is 2 days  away and BWC is false - Short Red
Actual Service Date is 3 days away and BWC is false - Long Yellow</inlineHelpText>
    <label>Booking Status</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>If this is a multi-day service, please enter the end date here..</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date / Time</label>
    <type>DateTime</type>
</CustomField>

objects/Visits__c/fields/End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>End_DateTime__c</fullName>
    <formula>if(ISBLANK(End_Date__c ),DATETIMEVALUE(Text( Year(Actual_Service_Date__c))+&apos;-&apos;+Text( month(Actual_Service_Date__c))+&apos;-&apos;+Text( day(Actual_Service_Date__c))+&apos; &apos;+&apos;10:00:00&apos;),
DATETIMEVALUE(Text( Year(End_Date__c))+&apos;-&apos;+Text( month(End_Date__c))+&apos;-&apos;+Text( day(End_Date__c))+&apos; &apos;+&apos;10:00:00&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End DateTime</label>
    <type>DateTime</type>
</CustomField>

objects/Visits__c/fields/Gantt_color__c.field-meta.xml
<CustomField>
    <fullName>Gantt_color__c</fullName>
    <formula>if(Visit_Complete__c,&apos;#2ECC71&apos;,&apos;#0a67ad&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gantt_color</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Job_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_Time__c</fullName>
    <description>It pull through the site contract Job Time field.</description>
    <label>Job Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Visits__c/fields/Original_Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Actual_Service_Date__c</fullName>
    <inlineHelpText>This captures the value of the actual service date when it is first set. After that this will not change. Booking status warns if this is more than 60 days before the actual service date. ( NOTE the original capture was on 21/10/2013 )</inlineHelpText>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Start_date_time__c.field-meta.xml
<CustomField>
    <fullName>Start_date_time__c</fullName>
    <label>Start Date / Time</label>
    <type>DateTime</type>
</CustomField>

objects/Visits__c/fields/start_datetime__c.field-meta.xml
<CustomField>
    <fullName>start_datetime__c</fullName>
    <formula>DATETIMEVALUE(Text( Year(Actual_Service_Date__c))+&apos;-&apos;+Text( month(Actual_Service_Date__c))+&apos;-&apos;+Text( day(Actual_Service_Date__c))+&apos; &apos;+&apos;09:00:00&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>start datetime</label>
    <type>DateTime</type>
</CustomField>

objects/Visits__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Workshop Repair</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/DispatchBoardCls.cls
public class DispatchBoardCls {
    public static string YESORNO ='Yes';
    
    //Get the dispatch board settings to allign the dispatch board
    @AuraEnabled
    public static Map<String,Setting__mdt> getDispatchBoardSettings(){
        list<Setting__mdt> settingList = new list<Setting__mdt>();
        
              settingList =[Select id,DeveloperName, DB_Start_Time__c, DB_End_Time__c  from Setting__mdt] ;     

        Map<String, Setting__mdt> settings = new Map<String, Setting__mdt>();
        system.debug('settings:'+settings);
        for(Setting__mdt setting : settingList){
            settings.put(setting.DeveloperName, setting);
        }
        return settings;
    }

      @AuraEnabled
    public static list<visits__c> getAssignmentsByUser(string userId){  
        
        visits__c eng  =new  visits__c();
        list<visits__c> assignments = new list<visits__c>();
        Date startDate=System.TODAY()-90;
        Date endDate=System.TODAY()+90;

         //assignments =[Select id, Name,End_DateTime__c,Start_datetime__c,Job_Number__c,Site__c,Job_Status__c,Job_Time__c,Start_date_time__c,End_Date_Time__c,Visit_Type__c,Booking_Status__c,Original_Actual_Service_Date__c, Actual_Service_Date__c, End_Date__c,Gantt_color__c,Engineer2__c from visits__c where Engineer2__r.Salesforce_User__c=:userId and ((Start_date_time__c>=:startDate and Start_date_time__c<=:endDate) OR (End_Date_Time__c>=:startDate and End_Date_Time__c<=:endDate) OR (Start_date_time__c<:startDate and End_Date_Time__c>:endDate)) LIMIT 5000];
        assignments =[Select id, Name,End_DateTime__c,Message_to_Technician__c,Site_Name__c,Start_datetime__c,Job_Number__c,Site__c,Job_Status__c,Job_Time__c,Start_date_time__c,End_Date_Time__c,Visit_Type__c,Booking_Status__c,Original_Actual_Service_Date__c, Actual_Service_Date__c, End_Date__c,Gantt_color__c,Engineer2__c from visits__c where Engineer2__r.Salesforce_User__c=:userId and ((Start_datetime__c>=:startDate and Start_datetime__c<=:endDate) OR (End_DateTime__c>=:startDate and End_DateTime__c<=:endDate) OR (Start_datetime__c<:startDate and End_DateTime__c>:endDate)) LIMIT 5000];   
              
          system.debug('Engineers:'+assignments);
        return assignments;
        
    }
  



}