objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/Active_User__c.field-meta.xml
<CustomField>
    <fullName>Active_User__c</fullName>
    <inlineHelpText>If this is Yes, the technician is still employed. If No, the technician has left.</inlineHelpText>
    <label>Active User</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The technician is either on holiday, sick, or training.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Engineer__c/fields/Engineer_ID__c.field-meta.xml
<CustomField>
    <fullName>Engineer_ID__c</fullName>
    <label>Technician ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Job_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_Time__c</fullName>
    <description>Assign the job time</description>
    <inlineHelpText>Job Time</inlineHelpText>
    <label>Job Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Number_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Services__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Number of Visits per year, the Visits auto reschedule, based on this field.</inlineHelpText>
    <label>Number of Services</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Visit_Rescheduling__c.field-meta.xml
<CustomField>
    <fullName>Visit_Rescheduling__c</fullName>
    <inlineHelpText>On Schedule = When visit completes, new visit is planned based on Month Due field.
On Visit = When visit completes, new visit is planned based on visit date.
Pre-Scheduled = User has scheduled all visits so no revisit is booked. Service Maintains these.</inlineHelpText>
    <label>Visit Rescheduling</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Schedule</fullName>
            </value>
            <value>
                <fullName>On Visit</fullName>
            </value>
            <value>
                <fullName>Pre-Scheduled</fullName>
                <default>true</default>
                <label>Pre-Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Booked_with_Customers__c.field-meta.xml
<CustomField>
    <fullName>Booked_with_Customers__c</fullName>
    <inlineHelpText>1. Yes first time, sends Booking confirmation email
2. Yes to any other, sends Rescheduling notification email
3. Yes again, sends Rescheduled confirmation email.</inlineHelpText>
    <label>Booked with Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Waiting P/O</fullName>
            </value>
            <value>
                <fullName>Waiting Permit</fullName>
            </value>
            <value>
                <fullName>Waiting Confirmation</fullName>
            </value>
            <value>
                <fullName>Booked Via Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>If this is a multi-day service, please enter the end date here..</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Job_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_Time__c</fullName>
    <description>It pull through the site contract Job Time field.</description>
    <label>Job Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Visits__c/fields/Service_Sheet_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Sheet_Number__c</fullName>
    <inlineHelpText>This field is populated by an automatic trigger to help with reporting. If a hard copy sheet is used, please ensure that the sheet number is entered into this box.</inlineHelpText>
    <label>Service Sheet Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Part</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Visit_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>General Equipment</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
                <label>Autoclave</label>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>X-Ray</fullName>
            </value>
            <value>
                <fullName>Annual Mechanical Service &amp; Certificate to Pan Oral X-ray</fullName>
            </value>
            <value>
                <fullName>OPG</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Image Plate Scanner</fullName>
            </value>
            <value>
                <fullName>Sewer pump</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/Visit_Complete__c.field-meta.xml
<CustomField>
    <fullName>Visit_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Complete</label>
    <type>Checkbox</type>
</CustomField>

objects/Visits__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Workshop Repair</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/TechnicianCalendarHandler_Test.cls
@isTest(seealldata=true)
private class TechnicianCalendarHandler_Test {
    
    
    public static Account newAccount;
    public static Account newAccount1;
    public static Engineer__c tmp_technician;
    public static SiteContracts__c t_siteContract;
    public static Visits__c t_visit;
    
    public static testMethod void inserTestRecord(){
         /*Holiday hol = new Holiday();
         hol.Name='Test holiday';
         hol.activitydate = System.Today();
         insert hol;*/
         
         newAccount =new Account();
         newAccount.Name='Test Account';
         insert newAccount;
         
         newAccount1 =new Account();
         newAccount1.Name='Holidays';
         insert newAccount1;
         
         tmp_technician = new Engineer__c();
         tmp_technician.Name='Test Engineer';
         tmp_technician.Mobile_Phone__c='99999 999999';
         tmp_technician.Active_User__c='Yes';
         //tmp_technician.Start_Date_Long__c= '20/09/2015;2/09/2015';
         //tmp_technician.End_Date_Long__c   = '21/09/2015;12/09/2015';
         //tmp_technician.Cost_per_Hour__c = 1;
         tmp_technician.Target__c = 1;
         tmp_technician.Engineer_ID__c = 'test'; 
         //tmp_technician.Discipline_Group__c = 'Electrical';
         insert tmp_technician;
         
         t_siteContract= new SiteContracts__c();
         t_siteContract.site__c=newAccount.id;
         t_siteContract.Job_Time__c =10;
         t_siteContract.Number_of_Services__c =1;
         t_siteContract.Visit_Rescheduling__c = 'On Visit';
         insert t_siteContract;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Actual_Service_Date__c = date.today();
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.Visit_Type__c='Small Works';
         t_visit.Order_Value__c=10;
         insert t_visit;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Actual_Service_Date__c = date.today();
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.End_Date__c=null;
         t_visit.Visit_Type__c='Small Works';
         t_visit.Order_Value__c=10;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Booked_with_Customers__c='Yes';
         t_visit.Actual_Service_Date__c = date.today();
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.Visit_Type__c='Small Works';
         t_visit.Order_Value__c=10;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Actual_Service_Date__c = date.today();
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.End_Date__c=date.today();
         t_visit.Visit_Type__c='Small Works';
         t_visit.Order_Value__c=10;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Actual_Service_Date__c = date.today();
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.Service_Sheet_Number__c='1000';
         t_visit.Visit_Complete__c=true;
         t_visit.Visit_Type__c='Small Works';
         t_visit.Order_Value__c=10;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Booked_with_Customers__c='Yes';
         t_visit.Actual_Service_Date__c = date.today()+1;
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.Visit_Complete__c=false;
         t_visit.Visit_Type__c='Small Works';
         t_visit.Order_Value__c=10;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Booked_with_Customers__c='Waiting P/O';
         t_visit.Actual_Service_Date__c = date.today()+1;
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.Visit_Complete__c=false;
         t_visit.Visit_Type__c='Small Works';
         t_visit.Order_Value__c=10;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Booked_with_Customers__c='Booked Via Schedule';
         t_visit.Actual_Service_Date__c = date.today()+1;
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.Visit_Complete__c=false;
         t_visit.Visit_Type__c='Small Works';
         t_visit.Order_Value__c=10;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount1.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Visit_Type__c='Holiday';
         t_visit.Actual_Service_Date__c = date.today()+1;
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.Visit_Complete__c=false; 
         t_visit.Visit_Type__c='Small Works';
         t_visit.Order_Value__c=10;
         
         t_visit=new Visits__c(); 
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Visit_Type__c='Projects';
         t_visit.Actual_Service_Date__c = date.today()+1;
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Service_Type__c='Testing';
         t_visit.Visit_Complete__c=false;
         t_visit.Order_Value__c=10;
         insert t_visit; 
        
        BusinessHours defaultBH = [Select Id From BusinessHours Where IsDefault = True];
         
          ApexPages.currentPage().getParameters().put('id', tmp_technician.Id); 
          
                  
          t_visit.Booked_with_Customers__c = 'Yes';
          update t_visit; 
          ApexPages.currentPage().getParameters().put('id', tmp_technician.Id); 
          
           t_visit.Booked_with_Customers__c = 'Booked Via Schedule';
          update t_visit; 
          ApexPages.currentPage().getParameters().put('id', tmp_technician.Id); 
         
          t_visit.Actual_Service_Date__c = system.today();
          update t_visit; 
          ApexPages.currentPage().getParameters().put('id', tmp_technician.Id); 
         
          
         
          ApexPages.StandardController stdController = new ApexPages.StandardController(tmp_technician);
          TechnicianCalendarHandler con= new TechnicianCalendarHandler(stdController);
          con.pageLoad();
          TechnicianCalendarHandler.UpdateVisit('2014-10-08T01:02:03', '2014-10-08T01:03:03','/'+t_visit.id);  
   }
}