objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer_Checklist__c/Engineer_Checklist__c.object-meta.xml
<CustomObject>
    <description>Onsite checklist</description>
    <label>Service Sheet</label>
    <nameField>
        <displayFormat>SS2{000000}</displayFormat>
        <label>Service Sheet No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Engineer_Checklist__c/fields/Engineer__c.field-meta.xml
<CustomField>
    <fullName>Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Service Sheets Completed by this Engineer</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Sheet_STD__c/Service_Sheet_STD__c.object-meta.xml
<CustomObject>
    <label>M&amp;R Sheet</label>
    <nameField>
        <displayFormat>RS{000000}</displayFormat>
        <label>Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>M&amp;R Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ServiceController.cls
public class ServiceController{
      public String TechSign{get;set;} 
      public ID sheetid;
      public Engineer_Checklist__c ss{get;set;}
      public Service_Sheet_STD__c rs{get;set;}
      public Boolean sign{get;set;}
      public ID getsheetid(){ return sheetid; }
      public String Sheettype{get;set;}
      public void setsheetid(ID s){
        sheetid = s;
        ServiceController();
    } 
    
     Public void ServiceController(){
       
            
     try{
          Sheettype=ApexPages.currentPage().getParameters().get('Type');
          system.debug('Sheettype==========='+Sheettype);
          system.debug('sheetid ====='+sheetid );
                     sheetid = ApexPages.currentPage().getParameters().get('id');
          system.debug('sheetid ====='+sheetid );

             ss=[Select id,name,Engineer__r.Signature__c from Engineer_Checklist__c  where id=:sheetid ];
             system.debug('ss======='+ss.Engineer__r.Signature__c);
             if(ss.Engineer__r.Signature__c!=null || !test.isRunningTest()){
                TechSign=ss.Engineer__r.Signature__c.subStringBetween(ss.Engineer__r.Signature__c.contains('src') ? 'src="' : 'href="','"').replaceAll('&amp;','&');
                sign=true;
                system.debug('TechSign======'+TechSign+'>>>>sign====='+sign);
              }
               else{ 
                 sign=false;
                 system.debug('sign====='+sign);
                }
           
                  
         }
         Catch(Exception e){
          system.debug('Problem in gettin image'+ e);
         }  
   }     	

    }