objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Config__c/fields/Background_Colour__c.field-meta.xml
<CustomField>
    <fullName>Background_Colour__c</fullName>
    <label>Background Colour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <label>Created By</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tim Boyt</fullName>
            </value>
            <value>
                <fullName>Merfantz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PurchaseOrder__c/fields/Document_Creator__c.field-meta.xml
<CustomField>
    <fullName>Document_Creator__c</fullName>
    <label>Document Creator</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

classes/Purchase_Order_Preview_CtrlTest.cls
@isTest
/*============================================================================================================
*Class Name     : Purchase_Order_Preview_CtrlTest
*Description    : All implementation to test the class Purchase_Order_Preview_Controller.
*Company        : Merfantz Technologies Pvt Ltd
*Date           : 29th Jan, 2017
*Version        : 2.0
*Change History : Initial Class
*Methods        : static testMethod void myTest()
*============================================================================================================*/
public class Purchase_Order_Preview_CtrlTest{

/*====================================================

*Method Name     : myTest
*Description     : This method test the Purchase_Order_Preview_Controller class
*Arguments       : No Arguments
*Ticket No       : 32042
====================================================*/
    
    static testMethod void myTest(){
    
    test.starttest();
    
    /*Config__c cnf=new Config__c();
    cnf.Background_Colour__c='#0FF123';
    cnf.Name='Test';
    insert cnf;
    
    ApexPages.StandardController sc = new ApexPages.standardController(cnf);
    Purchase_Order_Preview_Controller PP=new Purchase_Order_Preview_Controller(sc);
    */
    PurchaseOrder__c po=new PurchaseOrder__c();
    po.Created_By__c='Tim Loyn';
    po.Document_Creator__c='test@gmail.com';
    insert po;
    
    
    ApexPages.StandardController sc = new ApexPages.standardController(po);
    Purchase_Order_Preview_Controller PP=new Purchase_Order_Preview_Controller(sc);
    
    test.stoptest();
    }
}