objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Config__c/fields/Background_Colour__c.field-meta.xml
<CustomField>
    <fullName>Background_Colour__c</fullName>
    <label>Background Colour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Config__c/fields/Footer_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Footer_Line_1__c</fullName>
    <label>Footer Line 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Config__c/fields/Footer_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Footer_Line_2__c</fullName>
    <label>Footer Line 2</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Config__c/fields/Header_Title__c.field-meta.xml
<CustomField>
    <fullName>Header_Title__c</fullName>
    <label>Header Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Config__c/fields/Invoice_Background__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Background__c</fullName>
    <label>Invoice Background</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Config__c/fields/Product_Table_Colour__c.field-meta.xml
<CustomField>
    <fullName>Product_Table_Colour__c</fullName>
    <label>Product Table Colour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/Purchase_Order_Preview_Controller.cls
/*============================================================================================================
*Class Name     : Purchase_Order_Preview_Controller 
*Description    : Naming the Purchase Order as 'Eclipse Dental Purchase Order.pdf' when it will be download
*Company        : Merfantz Technologies Pvt Ltd
*Date           : 29th Jan, 2017
*Version        : 2.0
*Change History : Initial Class
*Methods        : No methods
*============================================================================================================*/

public class Purchase_Order_Preview_Controller {
//public Config__c configvalue{get;set;}


    public Purchase_Order_Preview_Controller(ApexPages.StandardController controller) {
    //configvalue = [select Background_Colour__c,Header__c,Footer_Line_1__c,Footer_Line_2__c,Product_Table_Colour__c,Header_Title__c,Invoice_Background__c from Config__c Limit 1];
     Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=Eclipse Dental Purchase Order.pdf');
    }

}