objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Config__c/fields/Background_Colour__c.field-meta.xml
<CustomField>
    <fullName>Background_Colour__c</fullName>
    <label>Background Colour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Config__c/fields/Footer_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Footer_Line_1__c</fullName>
    <label>Footer Line 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Config__c/fields/Footer_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Footer_Line_2__c</fullName>
    <label>Footer Line 2</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Config__c/fields/Header_Title__c.field-meta.xml
<CustomField>
    <fullName>Header_Title__c</fullName>
    <label>Header Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Config__c/fields/Invoice_Background__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Background__c</fullName>
    <label>Invoice Background</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Config__c/fields/Product_Table_Colour__c.field-meta.xml
<CustomField>
    <fullName>Product_Table_Colour__c</fullName>
    <label>Product Table Colour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/customConfigTest.cls
@isTest
public class customConfigTest{
    
    static testMethod void myTest(){
    
    test.starttest();
    
    Config__c cus=new Config__c();
    cus.Header__c='Test';
    cus.Background_Colour__c='#0FF123';
    cus.Product_Table_Colour__c='#0FF123';
    cus.Footer_Line_1__c='Test';
    cus.Footer_Line_2__c='Test';
    cus.Header_Title__c='Test';
    cus.Invoice_Background__c='#0FF123';
    
    insert cus;
    
    customConfig cusIng=new customConfig();
    cusIng.SAVE();
    cusIng.cust=cus;
    
    test.stoptest();
    }
}