objects/Mechanical_Service_Sheet__c/Mechanical_Service_Sheet__c.object-meta.xml
<CustomObject>
    <description>This object contains two Inspection Certificates:-

Suppression System Mechanical Inspection Certificate
Riser &amp; Hydrant Inspection Certificate</description>
    <label>Mechanical Service Sheet</label>
    <nameField>
        <displayFormat>SSM{00000}</displayFormat>
        <label>Mechanical Service Sheets</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mechanical Service Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mechanical_Service_Sheet__c/fields/Change_Over_Done__c.field-meta.xml
<CustomField>
    <fullName>Change_Over_Done__c</fullName>
    <label>Change Over Done</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dry</fullName>
            </value>
            <value>
                <fullName>Wet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Close_Visit__c.field-meta.xml
<CustomField>
    <fullName>Close_Visit__c</fullName>
    <inlineHelpText>The visit related to this service sheet will be closed &amp; a new visit will be created if you choose &quot;Yes&quot;. On some service visits, there may be more than one service sheet, which is why this is now an option. The visit will remain open if you select &quot;No&quot;</inlineHelpText>
    <label>Close Visit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Comments_to_service__c.field-meta.xml
<CustomField>
    <fullName>Comments_to_service__c</fullName>
    <inlineHelpText>These comments are intended for Service and will not appear on any customer communication.</inlineHelpText>
    <label>Technician Comments to Office</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <label>Order No:</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Inspection</fullName>
            </value>
            <value>
                <fullName>Visual Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Relates to the contract which will cover this service sheet</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipName>Inspection_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/System_Type__c.field-meta.xml
<CustomField>
    <fullName>System_Type__c</fullName>
    <label>System Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dry Riser</fullName>
            </value>
            <value>
                <fullName>Fire Suppression</fullName>
            </value>
            <value>
                <fullName>Hydrant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Sprinkler</fullName>
            </value>
            <value>
                <fullName>Wet Riser</fullName>
            </value>
            <value>
                <fullName>Dry Riser, Wet Riser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipName>Inspection_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Opportunity/fields/Actual_GP_Margin__c.field-meta.xml
<CustomField>
    <fullName>Actual_GP_Margin__c</fullName>
    <label>Actual GP Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

objects/Opportunity/fields/Actual_Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Actual_Total_Cost__c</fullName>
    <label>Actual Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Opportunity/fields/Mechanical_Service_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Service_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mechanical Service Sheet</label>
    <referenceTo>Mechanical_Service_Sheet__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <label>Project Manager</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Purchase_order_number2__c.field-meta.xml
<CustomField>
    <fullName>Purchase_order_number2__c</fullName>
    <label>Purchase Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <formula>IF(Service_Sheet__c &lt;&gt; &quot;&quot;, Service_Sheet__r.Service_Sheet_Type__c, Reactive_Sheet__r.Sheets_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Type</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site Contract Number</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <formula>IF(Service_Sheet__c  &lt;&gt; &apos;&apos;, TEXT(Service_Sheet__r.Visit__r.Visit_Type__c)  , IF( Reactive_Sheet__c  &lt;&gt; &apos;&apos;, TEXT(Reactive_Sheet__r.Visit__r.Visit_Type__c), &apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visit Type</label>
    <type>Text</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Change_Over_Done__c.field-meta.xml
<CustomField>
    <fullName>Change_Over_Done__c</fullName>
    <label>Change Over Done</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Cost__c.field-meta.xml
<CustomField>
    <fullName>Actual_Cost__c</fullName>
    <inlineHelpText>Auto calculates providing the Order Value, Parts Cost and Labour Costs fields are filled in.</inlineHelpText>
    <label>Actual Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/Actual_GP_Margin__c.field-meta.xml
<CustomField>
    <fullName>Actual_GP_Margin__c</fullName>
    <inlineHelpText>Auto calculates providing the Order Value and Cost fields are filled in.</inlineHelpText>
    <label>Actual GP Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Mechanical_Service_Sheet_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Service_Sheet_Numbers__c</fullName>
    <label>Mechanical Service Sheet Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Notes_from_Previous_Service__c.field-meta.xml
<CustomField>
    <fullName>Notes_from_Previous_Service__c</fullName>
    <inlineHelpText>If the technician entered any notes on the previous service sheet in the &quot;Notes for next service&quot; box they will appear here.</inlineHelpText>
    <label>Notes from Previous Service</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Visits__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <label>Project Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Joel Bidmead</fullName>
            </value>
            <value>
                <fullName>Natasha Blake</fullName>
            </value>
            <value>
                <fullName>Nigel Welch</fullName>
            </value>
            <value>
                <fullName>Paul Faraway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Service_Sheet_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Sheet_Number__c</fullName>
    <inlineHelpText>This field is populated by an automatic trigger to help with reporting. If a hard copy sheet is used, please ensure that the sheet number is entered into this box.</inlineHelpText>
    <label>Service Sheet Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Part</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Visit_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>General Equipment</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
                <label>Autoclave</label>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>X-Ray</fullName>
            </value>
            <value>
                <fullName>Annual Mechanical Service &amp; Certificate to Pan Oral X-ray</fullName>
            </value>
            <value>
                <fullName>OPG</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Image Plate Scanner</fullName>
            </value>
            <value>
                <fullName>Sewer pump</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/Visit_Complete__c.field-meta.xml
<CustomField>
    <fullName>Visit_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Complete</label>
    <type>Checkbox</type>
</CustomField>

objects/Visits__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Workshop Repair</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/MSS_ServSheetTriggerHandler.cls
/*============================================================================================================
*Class Name     : MSS_ServSheetTriggerHandler
*Description    : All the implementations related to MSS_ServSheet Triggers should be handled here
*Company        : Puthuvannam Technology Solutions
*Date           : 19th May, 2014
*Version        : 1.0
*Change History : Initial Trigger Handler
*Methods        : public void OnAfterUpdate(Map<Id,Mechanical_Service_Sheet__c> newMssMap,Map<Id,Mechanical_Service_Sheet__c> oldMssMap)
                  public void OnAfterInsert(Map<Id,Mechanical_Service_Sheet__c> newMssMap)
                  Private void UpdateVisitComplete(Map<Id,Mechanical_Service_Sheet__c> newMssMap)
                  Private void UpdateVisitMSSNumber(Map<Id,Mechanical_Service_Sheet__c> newMssMap)            
*============================================================================================================*/
public class MSS_ServSheetTriggerHandler{
    
   public void OnAfterUpdate(Map<Id,Mechanical_Service_Sheet__c> newMssMap,Map<Id,Mechanical_Service_Sheet__c> oldMssMap){
         if(RecursiveHandler.runMSSSSTH_UVCOnce()){ 
             this.UpdateVisitComplete(newMssMap);    //Updating the Visit Complete on the Visit.
             //this.UpdateVisitMSSNumber(newMssMap);    //Updating the Visit mechanical Service Number Filed on the Visit.
              
        }
        if(RecursiveHandler.runMSSTH_ULMSSDOnce() || (test.isRunningTest() && limits.getqueries()<90)){UpdateLastServiceSheetDetails(newMssMap);}
        if(RecursiveHandler.runMSSSSTH_UPONOnce()){ 
             this.UpdatePurchaseOrderNumber(newMssMap,oldMssMap);     // Update the Purchase Order Number Field on the Opportunity
        }
        if(RecursiveHandler.runMSSSSTH_UVOLTOnce()){ 
             this.UpdateVisitOppLayout(newMssMap,oldMssMap);     // Update the Actual GP Margin, Actual Total Cost, Project Manager Fields on the Opportunity
        }
    }
    public void OnAfterInsert(Map<Id,Mechanical_Service_Sheet__c> newMssMap){
        //if(RecursiveHandler.RunOnce()){
            this.UpdateVisitMSSNumber(newMssMap);    //Updating the Visit mechanical Service Number Filed on the Visit.
            this.UpdatePreviousServiceField(newMssMap);
       // }
    }
    
    public void OnBeforeUpdate(List<Mechanical_Service_Sheet__c> newMssList,List<Mechanical_Service_Sheet__c> oldMssList){
        if(RecursiveHandler.runMSSSSTH_USTOnce()){
            UpdateSystemType(newMssList);
        }
    }
    public void OnBeforeInsert(List<Mechanical_Service_Sheet__c> newMssList){
        UpdateSystemType(newMssList);
    }
    
/*====================================================
*Method Name     : UpdateSystemType
*Description     : Update the System Type Field.
*Arguments       : new Mechanical Service Sheet list
====================================================*/     
    
    Private void UpdateSystemType(List<Mechanical_Service_Sheet__c> newMssList){       
        list<id> visitIds=new List<id>();        
        for(Mechanical_Service_Sheet__c ms:newMssList){
           if(ms.Visit__c!= NULL)
                visitIds.add(ms.Visit__c);
        }
        Map<id, Visits__c> visitMap=new Map<Id, Visits__c>([SELECT id, Service_Type__c
                                                                FROM Visits__c
                                                                WHERE id IN: visitIds]);  
        for(Mechanical_Service_Sheet__c ms:newMssList){
                ms.System_type__c=visitMap.get(ms.Visit__c).Service_Type__c;
        }        
    }

/*====================================================
*Method Name     : UpdateVisitComplete
*Description     : Update the Visit Complete Field.
*Arguments       : new Mechanical Service Sheet list
====================================================*/   
    Private void UpdateVisitComplete(Map<Id,Mechanical_Service_Sheet__c> newMssMap){
        //Variable Declaration
        List<id> visitIds=new List<id>();

        //to get the List Of visit IDS
        for(Mechanical_Service_Sheet__c ms:newMssMap.values()){
            visitIds.add(ms.visit__c);
        }

        //to get a list of Visits 
        List<Visits__c> visitList=[select id,Visit_Complete__c from Visits__c where ID IN:visitIds ];
        for(Mechanical_Service_Sheet__c ms:newMssMap.values()){
            for(Visits__c  vt :visitList){
                if(ms.Visit__c == vt.Id && ms.Close_Visit__c=='Yes' && ms.Fire_Extinguisher_Service_complete__c ){
                    //assign  Visit Complete Field
                     vt.Visit_Complete__c =true;
                     vt.Actual_Service_Date__c=system.today();
               }
           }
        }
        update visitList;    //update the Visits
    
    }
/*====================================================
*Method Name     : UpdateVisitMSSNumber
*Description     : Update the Visit Service Sheet Number Field.
*Arguments       : new Mechanical Service Sheet list
====================================================*/      
    
    Private void UpdateVisitMSSNumber(Map<Id,Mechanical_Service_Sheet__c> newMssMap){
        //Variable Declaration
        List<id> visitIds=new List<id>();

        //to get the List Of visit IDS
        for(Mechanical_Service_Sheet__c ms:newMssMap.values()){
            visitIds.add(ms.visit__c);
        }

        //to get a list of Visits 
        
        List<Visits__c> visitList=[select id,Mechanical_Service_Sheet_Numbers__c,Service_Type__c from Visits__c where ID IN:visitIds ];
        List<Mechanical_Service_Sheet__c> mechList=new List<Mechanical_Service_Sheet__c>();
        
        system.debug('======='+visitList);
        for(Mechanical_Service_Sheet__c ms:newMssMap.values()){
            for(Visits__c  vt :visitList){
                if(ms.Visit__c == vt.Id  ){
                    //assign  Service Sheet Number Field
                     vt.Mechanical_Service_Sheet_Numbers__c=ms.Name;
                     //vt.Service_Type__c=ms.System_Type__c;
                     System.debug('======='+vt.Service_Sheet_Number__c);
               }
           }
        }
        
        update visitList;    //update the Visits
        System.debug('======='+visitList);
    
    }

/*====================================================
*Method Name     : UpdatePreviousServiceField
*Description     : Update the Notes From Previous Service Field.
*Arguments       : new Service Sheet list
====================================================*/    
    PRIVATE VOID UpdatePreviousServiceField(map<id,Mechanical_Service_Sheet__c> NewMSSMap){
        //Variable Declaration
        List<id> visitIds=new List<id>();
        for(Mechanical_Service_Sheet__c ms:NewMSSMap.values()){
            visitIds.add(ms.visit__c);
        }
        System.debug('--------'+visitIds);
        //to get a list of Visits 
        List<Visits__c> visitList=[select id,Notes_from_Previous_Service__c from Visits__c where ID IN:visitIds ];
        
        System.debug('--------'+visitList);
        for(Mechanical_Service_Sheet__c ms:NewMSSMap.values()){
            for(Visits__c  vt :visitList){
                if(ms.Visit__c == vt.Id){
                    //assign  Previous Service Field
                     vt.Notes_from_Previous_Service__c=ms.Comments_to_service__c;
               }
           }
        }
        update visitList;    //update the Visits
    }
    
//Name           : UpdateLastMechanicalServiceSheetDetails
//Description    : Whenever the 'Dry Riser' Service sheet gets submitted, reset the Last Service Sheet Details-Mechanical in the Site Contract record.
//Arguments      :
//Date           : 23rd May, 2014
 

  PRIVATE VOID UpdateLastServiceSheetDetails(Map<id,Mechanical_Service_Sheet__c> NewMSSMap){        
        List<id> visitIds=new List<id>();
        for(Mechanical_Service_Sheet__c ms:NewMSSMap.values()){
            visitIds.add(ms.visit__c);
        }
   String recordRiserId =[select id,name from RecordType
                 where SObjectType='Mechanical_Service_Sheet__c' 
                 AND name='Riser Service Sheet'].id;
   String recordSprinklerId =[select id,name from RecordType
                 where SObjectType='Mechanical_Service_Sheet__c' 
                 AND name='Sprinkler Service Sheet'].id;
    Map<id, Visits__c> visitMap=new Map<id, Visits__c>([SELECT id, Visit_Type__c from Visits__c where id IN:visitIds]);
        system.debug('Coming To visit print==='+visitMap);
        List<id> MRsiteContractIds=new List<Id>();
        List<id> MSsiteContractIds=new List<Id>();
        Map<id, Mechanical_Service_Sheet__c> MRMSSMap=new Map<Id, Mechanical_Service_Sheet__c>();
        Map<id, Mechanical_Service_Sheet__c> MSMSSMap=new Map<Id, Mechanical_Service_Sheet__c>(); 

    for(Mechanical_Service_Sheet__c ms:NewMSSMap.values()){

            if(visitMap.get(ms.Visit__c).Visit_Type__c=='Service' && ms.RecordTypeId==recordRiserId && ms.Fire_Extinguisher_Service_complete__c){                
                MRsiteContractIds.add(ms.Site_Contract__c);
                MRMSSMap.put(ms.id, ms);
 
            }else if(visitMap.get(ms.Visit__c).Visit_Type__c=='Service' && ms.RecordTypeID==recordSprinklerId  && ms.Fire_Extinguisher_Service_complete__c){
                MSsiteContractIds.add(ms.Site_Contract__c);
                MSMSSMap.put(ms.id, ms);
            }
        }
     Map<id,SiteContracts__c> MRSCMap=new Map<id, SiteContracts__c>([SELECT id,Service_Type__c FROM SiteContracts__c
                          WHERE Id IN: MRsiteContractIds]);
    Map<id,SiteContracts__c> MSSCMap=new Map<id, SiteContracts__c>([SELECT id, Change_Over_Done__c FROM SiteContracts__c
                          WHERE Id IN: MSsiteContractIds]);
    system.debug('Coming after the signal point 1===');
                  
        if(!MRSCMap.isEmpty()){            
            system.debug('Coming after the signal Point 2===');
            UPDATE UpdateMRSheetDetails(MRSCMap,MRMSSMap);    
        }

        if(!MSSCMap.isEmpty()){            
            UPDATE UpdateMSSheetDetails(MSSCMap,MSMSSMap);    
        }
    }
    
    //Name           : UpdateFESheetDetails
    //Description    : Set default value from the custom setting for the Site Contract's Last Service Sheet Details
    //Arguments      :
    //Date           : 23rd May, 2014
    Private SiteContracts__c[] UpdateMRSheetDetails(Map<id,SiteContracts__c> siteContractsMap,Map<id,Mechanical_Service_Sheet__c> NewMSSMap){ 
        Map<id,SiteContracts__c> scsNeedUpdate=new Map<id,SiteContracts__c>();
        SiteContracts__c siteContract;
        for(Mechanical_Service_Sheet__c mss:NewMSSMap.values()){
            siteContract=siteContractsMap.get(mss.Site_Contract__c);
            siteContract.Service_Type__c =mss.Service_Type__c ;
            if(!scsNeedUpdate.containsKey(siteContract.id)){    //Avoiding Duplicates
                scsNeedUpdate.put(siteContract.id, siteContract);                                  
            }
        }   
        system.debug('Coming after the signal Point 3===');     
        return scsNeedUpdate.values();
    }
    
    //Name           : UpdateFAESheetDetails
    //Description    : Set default value from the custom setting for the Site Contract's Last Service Sheet Details
    //Arguments      :
    //Date           : 23rd May, 2014
    Private SiteContracts__c[] UpdateMSSheetDetails(Map<id,SiteContracts__c> siteContractsMap,Map<id,Mechanical_Service_Sheet__c> NewMSSMap){ 
        Map<id,SiteContracts__c> scsNeedUpdate=new Map<id,SiteContracts__c>();
        SiteContracts__c siteContract;
        for(Mechanical_Service_Sheet__c mss:NewMSSMap.values()){
            siteContract=siteContractsMap.get(mss.Site_Contract__c);
            siteContract.Change_Over_Done__c =mss.Change_Over_Done__c ;
            if(!scsNeedUpdate.containsKey(siteContract.id)){    //Avoiding Duplicates
                scsNeedUpdate.put(siteContract.id, siteContract);                                  
            }
        }        
        return scsNeedUpdate.values();
             
    }
    
/*====================================================
*Method Name     : UpdatePurchaseOrderNumber
*Description     : Update the Purchase Order Number Field.
*Arguments       : new Mechanical Service Sheet list
====================================================*/        
    Private void UpdatePurchaseOrderNumber(Map<id,Mechanical_Service_Sheet__c> NewMSSMap,Map<id,Mechanical_Service_Sheet__c> oldMSSMap){
        //Variable Declaration
        List<id> mssIds=new List<id>();
        for(Mechanical_Service_Sheet__c ms:NewMSSMap.values()){
            if(oldMSSMap.get(ms.id).Order_No__c!=ms.Order_No__c)
                mssIds.add(ms.Id);
        }
        //to get a list of Opportunity
        List<Opportunity> oppList=[select id,Purchase_order_number2__c,Mechanical_Service_Sheet__c from Opportunity
                                            where Mechanical_Service_Sheet__c IN:mssIds ];
        for(Opportunity opp :oppList){
            //assign Purchase Order Number Field
            if(opp.Mechanical_Service_Sheet__c!=NULL){
                opp.Purchase_order_number2__c =NewMSSMap.get(opp.Mechanical_Service_Sheet__c).Order_No__c;
            }
        }
        update oppList;    //update the Opportunity
    }  
    
    /*====================================================
*Method Name     : UpdateVisitOppLayout
*Description     : Update the Actual GP Margin, Actual Total Cost, Project Manager Fields.
*Arguments       : new Mechanical Service Sheet list
====================================================*/        
    Private void UpdateVisitOppLayout(Map<id,Mechanical_Service_Sheet__c> NewMSSMap,Map<id,Mechanical_Service_Sheet__c> oldMSSMap){
        //Variable Declaration
        List<id> mssIds=new List<id>();
        Map<id,Mechanical_Service_Sheet__c> NewMSMap = new Map<id,Mechanical_Service_Sheet__c>([select id,Visit__r.Actual_GP_Margin__c,
                                                                                       Visit__r.Actual_Cost__c, Visit__r.Project_Manager__c
                                                                                        from Mechanical_Service_Sheet__c
                                                                                        where id=:NewMSSMap.keyset()]);
        for(Mechanical_Service_Sheet__c ms:NewMSMap.values()){
            
                mssIds.add(ms.Id);
        }
        //to get a list of Opportunity
        List<Opportunity> oppList=[select id,Actual_GP_Margin__c,Actual_Total_Cost__c,Project_Manager__c,Mechanical_Service_Sheet__c from Opportunity
                                            where Mechanical_Service_Sheet__c IN:mssIds ];
        for(Opportunity opp :oppList){
            //assign Purchase Order Number Field
            if(opp.Mechanical_Service_Sheet__c!=NULL){
                opp.Actual_GP_Margin__c =NewMSMap.get(opp.Mechanical_Service_Sheet__c).Visit__r.Actual_GP_Margin__c;
                opp.Actual_Total_Cost__c =NewMSMap.get(opp.Mechanical_Service_Sheet__c).Visit__r.Actual_Cost__c;
                opp.Project_Manager__c =NewMSMap.get(opp.Mechanical_Service_Sheet__c).Visit__r.Project_Manager__c;
            }
        }
        update oppList;    //update the Opportunity
    }  

    
}