objects/Mechanical_Service_Sheet__c/Mechanical_Service_Sheet__c.object-meta.xml
<CustomObject>
    <description>This object contains two Inspection Certificates:-

Suppression System Mechanical Inspection Certificate
Riser &amp; Hydrant Inspection Certificate</description>
    <label>Mechanical Service Sheet</label>
    <nameField>
        <displayFormat>SSM{00000}</displayFormat>
        <label>Mechanical Service Sheets</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mechanical Service Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mechanical_Service_Sheet__c/fields/Agent_Fill__c.field-meta.xml
<CustomField>
    <fullName>Agent_Fill__c</fullName>
    <label>Agent Fill</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/No_of_Cycles__c.field-meta.xml
<CustomField>
    <fullName>No_of_Cycles__c</fullName>
    <label>No. of Cycles</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/System_Location__c.field-meta.xml
<CustomField>
    <fullName>System_Location__c</fullName>
    <label>System Location</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Test_Date__c.field-meta.xml
<CustomField>
    <fullName>Test_Date__c</fullName>
    <label>Test Date</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/mechSFCertificateControllerTest.cls
@isTest(SeeAllData=True)

    public class mechSFCertificateControllerTest {

      @isTest Static void mechSFCertificateControllertest() {
      Mechanical_Service_Sheet__c mech;
      try{
      mech = [select Id,System_Location__c,No_of_Cycles__c,Capacity__c,Agent_Fill__c,Test_Date__c  from Mechanical_Service_Sheet__c Limit 1];
      apexPages.CurrentPage().getParameters().Put('id',String.valueOf(mech.id));
      ApexPages.StandardController sc = new ApexPages.StandardController(mech);
      mechSFCertificateController qc = New mechSFCertificateController(sc);
      qc.getSystemLocation();
      qc.mSSId=mech.id;
      }catch(exception e){
      
      }
      
    }
}