objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c/fields/Long_Project_Order__c.field-meta.xml
<CustomField>
    <fullName>Long_Project_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Long Project Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Long_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Project__c/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <displayFormat>P-{00000}</displayFormat>
    <label>Project Number</label>
    <type>AutoNumber</type>
</CustomField>

classes/Projno.cls
Public class Projno{

    public Projno(ApexPages.StandardController controller) {

    }


    public ID Projid;
    public Project__c pro{get;set;}
    String prono{get;set;}
    


    public ID getProjid()
    {
    
    return Projid;
    
    }
    
    public void setProjid(ID Projids){
        if(Projids!= null){
            Projid= Projids;
            print();
            
         }
    }
    
    public void print(){
    
       try{
            if(Projid!= Null){
                pro=[select id,Project_Number__c from Project__c  where Long_Project_Order__c =:Projid order by createddate desc limit 1];   
                system.debug(pro.Project_Number__c );
                if(pro.Project_Number__c!=null){
                prono=pro.Project_Number__c;
                
                }
            }
        }catch(Exception e){}
        
    }
    
    }