objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Delivery Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Delivery_Note_Line_Item__c/Delivery_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Line Item</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Delivery_Note_Line_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <label>Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/DeliveryNoteHandler.cls
public class DeliveryNoteHandler{
        
         public void AfterUpdate(Map<id,Delivery_Note__c > newMap,Map<id,Delivery_Note__c > oldMap){
            ShowDescUpdate(newMap,oldMap);
         }
         
             
/*==============================================================================
Method Name: ShowDescUpdate
Description: Update Show Description based on Parent Show Descripton Field
Created date: 14-07-2017
================================================================================*/


public void ShowDescUpdate(Map<id,Delivery_Note__c > newMap,Map<id,Delivery_Note__c > oldMap){
List<Id> DnIds=new List<Id>();
List<Delivery_Note_Line_Item__c> UpdateDli=new List<Delivery_Note_Line_Item__c>();
       
    for(Delivery_Note__c Dn:newMap.values()){
          if(Dn.Show_Description__c!=oldMap.get(Dn.id).Show_Description__c){
              DnIds.add(Dn.id);
          }
    }
    
    if(DnIds.size()>0){
        for(Delivery_Note_Line_Item__c Dli:[Select id,Show_Description__c,Delivery_Note__r.Show_Description__c,Delivery_Note__c from Delivery_Note_Line_Item__c  where Delivery_Note__c IN:DnIds]){
            Dli.Show_Description__c=Dli.Delivery_Note__r.Show_Description__c;
            UpdateDli.add(Dli);
        }
    }      
    
    if(UpdateDli.size()>0){
       update UpdateDli;
    }  
}
    }