objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Delivery Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Delivery_Note__c/fields/Delivery_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Number__c</fullName>
    <label>Delivery Note Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Delivery_Note__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Engineer_Checklist__c/Engineer_Checklist__c.object-meta.xml
<CustomObject>
    <description>Onsite checklist</description>
    <label>Service Sheet</label>
    <nameField>
        <displayFormat>SS2{000000}</displayFormat>
        <label>Service Sheet No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Engineer_Checklist__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <inlineHelpText>This is the visit record that generated this service sheet. when the service sheet is created from the visit, this is automatically filled in. When it is created from the offline excel sheet, this is not automated and needs to be manually connected.</inlineHelpText>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Opportunity/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Delivery_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Number__c</fullName>
    <label>Delivery Note Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/ModxInvoice__c.field-meta.xml
<CustomField>
    <fullName>ModxInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ModxInvoice</label>
    <type>Checkbox</type>
</CustomField>

objects/Opportunity/fields/Reactive_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Reactive_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reactive Sheet</label>
    <referenceTo>Service_Sheet_STD__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Service_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Service_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Sheet</label>
    <referenceTo>Engineer_Checklist__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Service_Sheet</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/Opportunity/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <defaultValue>0.20</defaultValue>
    <inlineHelpText>This field is no longer useful for those opportunity created after 29th May 2020.</inlineHelpText>
    <label>VAT Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/OpportunityLineItem/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/OpportunityLineItem/fields/Line_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Description__c</fullName>
    <label>Line Item Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OpportunityLineItem/fields/Maintenance_Reactive_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Reactive_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maintenance &amp; Reactive Sheet</label>
    <referenceTo>Service_Sheet_STD__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/OpportunityLineItem/fields/SalesDescription__c.field-meta.xml
<CustomField>
    <fullName>SalesDescription__c</fullName>
    <label>SalesDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/OpportunityLineItem/fields/Service_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Service_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Sheet</label>
    <referenceTo>Engineer_Checklist__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/OpportunityLineItem/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/OpportunityLineItem/fields/Vat_Rate__c.field-meta.xml
<CustomField>
    <fullName>Vat_Rate__c</fullName>
    <defaultValue>0.2</defaultValue>
    <label>Vat Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Product2/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Stock_Unit__c.field-meta.xml
<CustomField>
    <fullName>Stock_Unit__c</fullName>
    <label>Stock Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Metre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Quote/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <defaultValue>0.20</defaultValue>
    <label>VAT Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/SalesOrder__c/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <defaultValue>0.20</defaultValue>
    <label>VAT Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Service_Sheet_STD__c/Service_Sheet_STD__c.object-meta.xml
<CustomObject>
    <label>M&amp;R Sheet</label>
    <nameField>
        <displayFormat>RS{000000}</displayFormat>
        <label>Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>M&amp;R Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Sheet_STD__c/fields/Actual_Service_date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_date__c</fullName>
    <formula>Visit__r.Actual_Service_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Service date</label>
    <type>Date</type>
</CustomField>

objects/Service_Sheet_STD__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipName>Service_Sheets_STD</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>Asset.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Maintenance_Reactive_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Reactive_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last submitt Reactive Sheet</label>
    <referenceTo>Service_Sheet_STD__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/UpdateDeliveryNoteNumber.cls
public class UpdateDeliveryNoteNumber{

    public ID Delnoteid;
    public Delivery_Note__c note{get;set;}
    public SalesOrder__c salesorder{get;set;}
    public String delnumber{get;set;}
    public String delname{get;set;}
    public String QuoteNo{get;set;}
    public Opportunity opp;
    public List<OpportunityLineitem> Oli{get;set;}  
    public List<OpportunityLineitem> Olii{get;set;}  
    public String[] SheetNo{get;set;}
    public List<Wrapp> Wlist{get;set;}
    public Boolean sheeton{get;set;}
    public Boolean Nosheet{get;set;}
    public String PriSheet{get;set;}
    public String Asset{get;set;}
    public Date Service{get;set;}
    public set<String>Prijoin{get;set;}
    public Boolean Primatch{get;set;}
    


    public ID getDelnoteid()
    {
    system.debug('getDelnoteid==========='+Delnoteid);
    return Delnoteid;
    
    }
    
    public void setDelnoteid(ID Delnoteids){
        if(Delnoteids != null){
            Delnoteid = Delnoteids;
            system.debug('setDelnoteid==========='+Delnoteid);
            UpdateOppDelNoteNumber();
            load();
         }
    }

    public void UpdateOppDelNoteNumber(){
        try{
            note = [select id,name,Delivery_Note_Number__c,createddate,Opportunity__c from Delivery_Note__c where Opportunity__c =:Delnoteid order by createddate desc limit 1];
            if(note.Opportunity__c != Null){
                delname = note.name;
                delnumber = note.Delivery_Note_Number__c;
            }
        }catch(Exception e){}
        
        
        
        try{
            if(Delnoteid!= Null){
                QuoteNo=[select QuoteNumber from Quote where OpportunityId=:Delnoteid order by createddate desc limit 1].QuoteNumber;   
            }
        }catch(Exception e){}
        
    }
    
    public void load() {
    sheeton=false;
    Nosheet=false;
    Primatch=false;   
    
    OpportunityLineItem temp=null;
    Oli=new List<OpportunityLineitem>();
    Olii=new List<OpportunityLineitem>();
    for(OpportunityLineItem opl: [Select id,OpportunityId,vat_rate__c,Description,SalesDescription__c,Extended_Sales_Description__c,Opportunity.Reactive_Sheet__r.name,Opportunity.Service_Sheet__r.name,Opportunity.Reactive_Sheet__c,
														 Opportunity.Service_Sheet__c,Service_Sheet__r.name,Maintenance_Reactive_Sheet__r.name,Quantity,Product2.name,Maintenance_Reactive_Sheet__c,Service_Sheet__c ,Product2.Stock_Unit__c,UnitPrice,TotalPrice,Opportunity.VAT_Rate__c,Service_Sheet__r.Visit__r.Asset__r.Name,Opportunity.ModxInvoice__c,
                                                         Opportunity.Reactive_Sheet__r.Visit__r.Asset__r.Name,Opportunity.Service_Sheet__r.Visit__r.Asset__r.Name,Show_Description__c,Line_Item_Description__c,Product2Id,Product2.Extended_Sales_Description__c,Product2.Sales_Description__c,Opportunity.Service_Sheet__r.Visit__r.Actual_Service_Date__c,Opportunity.Reactive_Sheet__r.Visit__r.Actual_Service_Date__c 
                                                         From OpportunityLineitem 
                                                         Where OpportunityId =:Delnoteid order by SortOrder,Pricebookentry.product2.Name]){
        
            if(opl.Product2Id!=System.Label.Carriage){
               Oli.add(opl);
            }
            else{
              temp=opl;
            }
         
         
         system.debug('Oli=========='+Oli);      
     }  
     
     if(temp!=null){
       Oli.add(temp);
     }                                        
                                                         
   for(OpportunityLineItem opl :[Select id,OpportunityId,vat_rate__c,Description,SalesDescription__c,Extended_Sales_Description__c,Opportunity.Reactive_Sheet__r.name,Opportunity.Service_Sheet__r.name,Opportunity.Reactive_Sheet__c,
														 Opportunity.Service_Sheet__c,Service_Sheet__r.name,Maintenance_Reactive_Sheet__r.name,Quantity,Product2.name,Maintenance_Reactive_Sheet__c,Service_Sheet__c ,Product2.Stock_Unit__c,UnitPrice,TotalPrice,Opportunity.VAT_Rate__c,Service_Sheet__r.Visit__r.Asset__r.Name,Opportunity.ModxInvoice__c,
                                                         Opportunity.Reactive_Sheet__r.Visit__r.Asset__r.Name,Opportunity.Service_Sheet__r.Visit__r.Asset__r.Name,Show_Description__c,Line_Item_Description__c,Product2Id,Product2.Extended_Sales_Description__c,Product2.Sales_Description__c,Opportunity.Service_Sheet__r.Visit__r.Actual_Service_Date__c,Opportunity.Reactive_Sheet__r.Visit__r.Actual_Service_Date__c 
                                                         From OpportunityLineitem 
                                                         Where OpportunityId=:Delnoteid AND Service_Sheet__r.name=null
                                                         AND Maintenance_Reactive_Sheet__r.name=null order by SortOrder,Pricebookentry.product2.Name]){
            
         
            if(opl.Product2Id!=System.Label.Carriage){
               Olii.add(opl);
            }
            else{
              temp=opl;
            }
         
         
         system.debug('Olii=========='+Olii);                                             
                                                         
    }                                                       
          
     if(temp!=null){
       Olii.add(temp);
     } 
             
     
     if(Olii.size()>0){
     Nosheet=true;
     for(OpportunityLineitem ol:Olii)
     {
     

     if(ol.Opportunity.Reactive_Sheet__r.name!=null)
     {
     PriSheet=ol.Opportunity.Reactive_Sheet__r.name;
     
     Asset=ol.Opportunity.Reactive_Sheet__r.Visit__r.Asset__r.Name;
     Service=ol.Opportunity.Reactive_Sheet__r.Visit__r.Actual_Service_Date__c;
     
     }
      else if(ol.Opportunity.Service_Sheet__r.name!=null)
      {
      PriSheet=ol.Opportunity.Service_Sheet__r.name;
      Asset=ol.Opportunity.Service_Sheet__r.Visit__r.Asset__r.Name;
      Service=ol.Opportunity.Service_Sheet__r.Visit__r.Actual_Service_Date__c;
      
      }
     }   
     
     }
     system.debug('PriSheet=========='+PriSheet);
     system.debug('Asset========'+Asset);
     system.debug('Nosheet=========='+Nosheet);                                            
    // dynamically create set of unique Sheet no from query
    Set<String> Sheetset= new Set<String>();
    for (OpportunityLineitem o : Oli){
   
   
       if(o.Service_Sheet__c !=null){     
      Sheetset.add(o.Service_Sheet__r.name);
       }
        else if(o.Maintenance_Reactive_Sheet__c!=null){
        Sheetset.add(o.Maintenance_Reactive_Sheet__r.name);
        }
     }
       system.debug('Sheetset=========='+Sheetset);
    // convert the set into a string array  
    SheetNo= new String[Sheetset.size()];
    Integer i = 0;
    for (String sheet: Sheetset) { 
      SheetNo[i] = sheet;
      i++;
    }

    Wlist=new List<Wrapp>();
  for(Engineer_Checklist__c eng:[Select id,name,Visit__r.Actual_Service_Date__c,Visit__r.Asset__r.Name from Engineer_Checklist__c where name IN:Sheetset]){
  Wlist.add(new Wrapp(eng.name,eng.Visit__r.Asset__r.Name,eng.Visit__r.Actual_Service_Date__c));
   system.debug('Wlistserv======='+Wlist);
   sheeton=true;
   
  } 
    
    
    for(Service_Sheet_STD__c rea:[Select id,name,Visit__r.Actual_Service_Date__c,Visit__r.Asset__r.Name from Service_Sheet_STD__c  where name IN:Sheetset]){
    Wlist.add(new Wrapp(rea.name,rea.Visit__r.Asset__r.Name,rea.Visit__r.Actual_Service_Date__c));
    system.debug('Wlistreact======='+Wlist);
    sheeton=true;
    }
    system.debug('Wlist======='+Wlist);
    system.debug('sheeton=========='+sheeton);
    
    for(Wrapp wp:Wlist){
    if(wp.SNo==PriSheet){
    Primatch=true;
    }
    
    }
    system.debug('primatch======='+primatch);
  }
  public class Wrapp{
  public String SNo {get;set;}
  public String Asset{get;set;}
  public Date Servi{get;set;}
  
  public Wrapp(String SNo,String Asset,Date Servi){
  
  this.SNo=SNo ;
  this.Asset=Asset;
  this.Servi=Servi;
  
  }
  }
  
}