objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Price_Book_IdFormula__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_IdFormula__c</fullName>
    <formula>IF(Price_Book__c &lt;&gt; &apos;&apos;, Price_Book__c, Site__r.Price_Book__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This shows the price book ID that will be used when we create the opportunity.</inlineHelpText>
    <label>Price Book Id (Customer / Site)</label>
    <type>Text</type>
</CustomField>

objects/Small_Works__c/Small_Works__c.object-meta.xml
<CustomObject>
    <description>28/03/14~removed HSW- from SmallWorksID Name~WB.</description>
    <label>Small Works</label>
    <nameField>
        <displayFormat>SW{000000}</displayFormat>
        <label>Small Works Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Small Works</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Small_Works__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Small Works</relationshipLabel>
    <relationshipName>Small_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Small_Works__c/fields/Submit_this_Small_Works_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Submit_this_Small_Works_Sheet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit this Small Works Sheet</label>
    <type>Checkbox</type>
</CustomField>

classes/SWOppTest.cls
public class SWOppTest {
public static testMethod void Tester() {
Small_Works__c ss2;
try{
    ss2= [select Id, Submit_this_Small_Works_Sheet__c,close_visit__c
                                     from Small_Works__c 
                                     where Site_Contract__r.Price_Book_IdFormula__c!=null                                 
                                     limit 1];
    Small_Works__c ss = ss2.clone(false,true,true,true);
    ss.Submit_this_Small_Works_Sheet__c=false;                                 
    insert ss;
    ss.Submit_this_Small_Works_Sheet__c=true; 
    ss.close_visit__c='Yes';
    ss.Depart__c=system.now();                                
    update ss;
}catch(exception e){

}
}
}