objects/ControlFetch__c/ControlFetch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ControlFetch</label>
</CustomObject>

objects/ControlFetch__c/fields/Serial_Number_Check__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Serial Number Check</label>
    <type>Checkbox</type>
</CustomField>

objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <description>Inventory Transaction</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory_Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Inventory__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Inventory__r.Warehouse__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/InventoryTransactionHandler.cls
public class InventoryTransactionHandler{

    public void OnAfterInsert(Map<id,Inventory_Transaction__c> newInvMap){
        AvoidDulipcateSN(newInvMap);
    }
    
    public void OnBeforeUpdate(Map<id,Inventory_Transaction__c> newInvMap){
        AvoidDulipcateSN(newInvMap);
    }
    
    public void AvoidDulipcateSN(Map<id,Inventory_Transaction__c> newInvMap){
       Map<String,String> FindDuplicate=new Map<String,String>();
       List<String> InvId=new List<String>();
       Boolean Flag=false;
       
       for(Inventory_Transaction__c InvenTrans:newInvMap.values()){
          InvId.add(InvenTrans.Product__c);
       }
      
      if(InvId.size()>0){
          for(Inventory_Transaction__c InvTrans:[select id,Name,Product__c,Inventory__c,Warehouse__c from Inventory_Transaction__c where Product__c IN:InvId]){
          //system.debug(InvTrans.Name+'>>>>>>>'+InvTrans.Product__c);
          if(FindDuplicate.containskey(InvTrans.Name) && FindDuplicate.get(InvTrans.Name)==InvTrans.Product__c)
          Flag=true;
          else
          FindDuplicate.put(InvTrans.Name,InvTrans.Product__c);
          }
       }
       
       for(Inventory_Transaction__c InvenTrans:newInvMap.values()){
           IF(Test.isRunningTest())
           if(Flag && ControlFetch__c.getInstance('Avoid Duplicate').Serial_Number_Check__c)
           InvenTrans.addError(ControlFetch__c.getInstance('Avoid Duplicate').Error_Message__c!=null?ControlFetch__c.getInstance('Avoid Duplicate').Error_Message__c:'Duplicate Serial Number found');
       }
    }
    
}