objects/ControlFetch__c/ControlFetch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ControlFetch</label>
</CustomObject>

objects/ControlFetch__c/fields/Allow_Duplicate__c.field-meta.xml
<CustomField>
    <fullName>Allow_Duplicate__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick to allow duplicate products in Inventory</inlineHelpText>
    <label>Allow Duplicate</label>
    <type>Checkbox</type>
</CustomField>

objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/In_Hand_Quantity__c.field-meta.xml
<CustomField>
    <fullName>In_Hand_Quantity__c</fullName>
    <formula>Total_Received__c-Total_Delivered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>In Hand Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Inventories (Location)</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Total_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Total_Delivered__c</fullName>
    <label>Total Delivered</label>
    <summarizedField>Inventory_Transaction__c.Qty__c</summarizedField>
    <summaryFilterItems>
        <field>Inventory_Transaction__c.Transaction_Type__c</field>
        <operation>equals</operation>
        <value>Delivered</value>
    </summaryFilterItems>
    <summaryForeignKey>Inventory_Transaction__c.Inventory__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Inventory__c/fields/Total_in_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Total_in_Vehicle__c</fullName>
    <label>Total in Vehicle</label>
    <summaryFilterItems>
        <field>Inventory_Transaction__c.Transaction_Type__c</field>
        <operation>equals</operation>
        <value>In Vehicle</value>
    </summaryFilterItems>
    <summaryForeignKey>Inventory_Transaction__c.Inventory__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Organization</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c/fields/Occupied__c.field-meta.xml
<CustomField>
    <fullName>Occupied__c</fullName>
    <label>Occupied</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Location__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Product2/fields/Total_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Total_Delivered__c</fullName>
    <label>Total Delivered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product2/fields/Total_In_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Total_In_Vehicle__c</fullName>
    <label>Total In Vehicle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product2/fields/Total_Stock_In_Hand__c.field-meta.xml
<CustomField>
    <fullName>Total_Stock_In_Hand__c</fullName>
    <label>Total Stock In Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Warehouse__c/fields/Occupied__c.field-meta.xml
<CustomField>
    <fullName>Occupied__c</fullName>
    <label>Occupied</label>
    <summarizedField>Inventory__c.In_Hand_Quantity__c</summarizedField>
    <summaryForeignKey>Inventory__c.Warehouse__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

classes/InventoryTriggerHandler.cls
/*============================================================================================================
*Class Name     : InventoryTriggerHandler
*Description    : All the implementations related to Inventory Triggers should be handled here
*Company        : Merfantz Technology Solutions
*Date           : 18th Augest, 2014
*Version        : 1.0
*Change History : Initial Trigger Handler
*Methods        : public void OnAfterInsert(Map<id,Inventory__c> newInvMap,Map<id,Inventory__c> oldInvMap)

*============================================================================================================*/

public class InventoryTriggerHandler{
    
    
/*====================================================
    *Method Name     : OnAfterInsert
    *Description     : Handle the after Insert operation
    *Arguments       : new map list
====================================================*/

    public void OnBeforeInsert(List<Inventory__c> newInv){
     //DuplicInv(newInvMap);
    system.debug('before insert====='+newInv);
     if(ControlFetch__c.getInstance('Inventory check').Allow_Duplicate__c==false){
     DuplicInv(newInv);
     }
    }
    
    public void OnAfterInsert(Map<id,Inventory__c> newInvMap,Map<id,Inventory__c> oldInvMap){
        
         UpdateCapacity(newInvMap);
        if(!Test.isRunningTest())
         RollupSumOnInv(newInvMap);
       
        
    }
    public void OnAfterUpdate(Map<id,Inventory__c> newInvMap,Map<id,Inventory__c> oldInvMap){
        UpdateCapacity(newInvMap);
        RollupSumOnInv(newInvMap);
    }
    
    public void OnAfterDelete(Map<id,Inventory__c> oldMap){
        UpdateCapacity(oldMap);
        RollupSumOnInv(oldMap);
    }
    
    public void OnAfterUnDelete(Map<id,Inventory__c> newInvMap){
        UpdateCapacity(newInvMap);
        RollupSumOnInv(newInvMap);
    }
    
    public void RollupSumOnInv(Map<id,Inventory__c> newInvMap){
        system.debug('newInvMap RollupSumOnInv============'+newInvMap);
        List<Id> PrdIds=new List<Id>();
        Map<id,Product2> Products;
        for(Inventory__c Inv:newInvMap.values()){
            PrdIds.add(Inv.Product__c);
            System.debug('Product Id === '+PrdIds);
        }
        
        if(PrdIds.size()>0){
            Products=new Map<Id,Product2>([select id,Total_Inventory__c,Total_In_Vehicle__c,Total_Delivered__c from product2 where id In:PrdIds]);
            AggregateResult[] Result=[select Product__c,Count(Id)cnt,SUM(In_Hand_Quantity__c)tot,SUM(Total_in_Vehicle__c)veh,SUM(Total_Delivered__c)disp from Inventory__c where Product__c IN:PrdIds GROUP BY Product__c];
            system.debug('Result========'+Result.size());
            for(AggregateResult agg:Result){
                if(Products.containskey((Id)agg.get('Product__c'))){
                Products.get((Id)agg.get('Product__c')).Total_Inventory__c=(Decimal)agg.get('cnt');
                Products.get((Id)agg.get('Product__c')).Total_Stock_In_Hand__c=(Decimal)agg.get('tot');
                Products.get((Id)agg.get('Product__c')).Total_In_Vehicle__c=(Decimal)agg.get('veh');
                Products.get((Id)agg.get('Product__c')).Total_Delivered__c=(Decimal)agg.get('disp');
                }
            }
        }
        if(Products.size()>0){
            update Products.values();
        }
    }
    
    public void UpdateCapacity(Map<id,Inventory__c> newInvMap){
        List<String> loc=new List<String>();
        Map<Id,Integer> LocHand=new Map<Id,Integer>();
         List<Location__c> locList=new List<Location__c>();
        system.debug('newInvMap UpdateCapacity============'+newInvMap);
        for(Inventory__c inv:newInvMap.values()){
            if(inv.Location__c!=null){
                loc.add(inv.Location__c);
            }
        }
        
        if(loc.size()!=0){
            AggregateResult[] Results= [select Location__c,sum(In_Hand_Quantity__c)inHand from Inventory__c group by Location__c having Location__c IN:loc ];
           for(AggregateResult agr :Results){ 
               LocHand.put((Id)agr.get('Location__c'),integer.valueOf(agr.get('inHand')));
           } 
        }
        
        list<Location__c> loca =new list<Location__c>([select id,Occupied__c from Location__c where id IN:loc]);
        
        for(Location__c Locloop:loca){
            if(LocHand.containskey(Locloop.id)){
                Locloop.Occupied__c=LocHand.get(Locloop.id);
                locList.add(Locloop);
            }
        }
        
        if(locList.size()>0){
            update locList;
        }
       // System.debug('111111111111'+locList);
    }
    
  public void DuplicInv(List<Inventory__c> newInvMap){
  
  List<Id> Whid=new List<Id>();
  Map<Id,Inventory__c> dupinv=new Map<Id,Inventory__c>();  
  
   for(Inventory__c I:newInvMap){
     Whid.add(I.Warehouse__c);
     } 
     system.debug('whid========'+Whid);
    system.debug('newInvMap=============='+newInvMap);
    list<Inventory__c> inv = new list<Inventory__c>([Select id,Product__c,Warehouse__c from Inventory__c where Warehouse__c=:Whid]);
    for(Inventory__c Inve:inv){
    dupinv.put(Inve.Product__c,Inve);
    }
    system.debug('dupinv==========='+dupinv);
    
    for(Inventory__c dup:newInvMap){
    if(dupinv.ContainsKey(dup.Product__c))
    {
     dup.addError('Product you choose is already exist for this warehouse. Duplicate products are not allowed in Inventory');
    }
    } 
    
    }  
}