objects/Date__c/Date__c.object-meta.xml
<CustomObject>
    <label>Date</label>
    <nameField>
        <label>Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Delivery Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Delivery_Note_Line_Item__c/Delivery_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Line Item</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Delivery_Note_Line_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <label>Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Delivery_Note_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/DeliveryNoteHandlerTest.cls
@isTest(SeeAllData=true)
    public class DeliveryNoteHandlerTest{
    
    public static testMethod void method1(){
    
    Delivery_Note__c Dn=new Delivery_Note__c (Date__c=system.today());
    insert Dn;
    
    Product2 prd=new Product2(name='test',IsActive=true);
    insert prd;
    
    Delivery_Note_Line_Item__c Dnoli=new Delivery_Note_Line_Item__c(Delivery_Note__c=Dn.id,Product__c=prd.id);
    insert Dnoli;
    
    Dn.Show_Description__c=true;
    update Dn;
    
    }
    
    }