objects/Date__c/Date__c.object-meta.xml
<CustomObject>
    <label>Date</label>
    <nameField>
        <label>Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Delivery Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Delivery_Note__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Delivery_Note_Line_Item__c/Delivery_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Line Item</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Delivery_Note_Line_Item__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <label>Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Delivery_Note_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/DeliverydetailsTest.cls
@isTest(seeAlldata=true)
Public Class DeliverydetailsTest{
     @isTest Public static void Method1(){ 

     List <Delivery_Note__c> lstDelivery = new List<Delivery_Note__c>();
     
     Account Acc=new Account();
     Acc.Name='Test Account';
     insert Acc;
     
     Delivery_Note__c testDel = new Delivery_Note__c();
     testDel.Date__c=system.today();
     testDel.Site__c=Acc.id;
     lstDelivery.add(testDel);
     
     Delivery_Note__c testDel1 = new Delivery_Note__c();
     testDel1.Date__c=system.today();
     testDel.Site__c=Acc.id;
     lstDelivery.add(testDel1);
     
     insert lstDelivery;
     
     product2 p=new Product2(Name='Test',isActive=true);
     insert p;
     
     Delivery_Note_Line_Item__c Deloli=new Delivery_Note_Line_Item__c();
     Deloli.Product__c=p.id;
     Deloli.Delivery_Note__c=lstDelivery[0].id;
     insert Deloli;
     
    Test.startTest();
      Test.setCurrentPage(Page.Export_Contact);
      ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(lstDelivery);
      stdSetController.setSelected(lstDelivery);
      Deliverydetails DelDetails = new Deliverydetails(stdSetController);
     Test.stopTest();
   }
}