objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/In_Hand_Quantity__c.field-meta.xml
<CustomField>
    <fullName>In_Hand_Quantity__c</fullName>
    <formula>Total_Received__c-Total_Delivered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>In Hand Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Inventories (Location)</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Maximum_Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Stock_Level__c</fullName>
    <label>Maximum Stock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Minimum_Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Stock_Level__c</fullName>
    <label>Minimum Stock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Out_Of_Stocks__c.field-meta.xml
<CustomField>
    <fullName>Out_Of_Stocks__c</fullName>
    <formula>In_Hand_Quantity__c  &lt;=  Minimum_Stock_Level__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Out Of Stock</label>
    <type>Checkbox</type>
</CustomField>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Total_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Total_Delivered__c</fullName>
    <label>Total Delivered</label>
    <summarizedField>Inventory_Transaction__c.Qty__c</summarizedField>
    <summaryFilterItems>
        <field>Inventory_Transaction__c.Transaction_Type__c</field>
        <operation>equals</operation>
        <value>Delivered</value>
    </summaryFilterItems>
    <summaryForeignKey>Inventory_Transaction__c.Inventory__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Inventory__c/fields/Total_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoiced__c</fullName>
    <label>Total Invoiced</label>
    <summaryFilterItems>
        <field>Inventory_Transaction__c.Transaction_Type__c</field>
        <operation>equals</operation>
        <value>Invoiced</value>
    </summaryFilterItems>
    <summaryForeignKey>Inventory_Transaction__c.Inventory__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Inventory__c/fields/Total_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Received__c</fullName>
    <label>Total Received</label>
    <summarizedField>Inventory_Transaction__c.Qty__c</summarizedField>
    <summaryFilterItems>
        <field>Inventory_Transaction__c.Transaction_Type__c</field>
        <operation>equals</operation>
        <value>Received</value>
    </summaryFilterItems>
    <summaryForeignKey>Inventory_Transaction__c.Inventory__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Organization</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Product2/fields/Maximum_stock_level__c.field-meta.xml
<CustomField>
    <fullName>Maximum_stock_level__c</fullName>
    <label>Maximum stock level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product2/fields/Total_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Total_Delivered__c</fullName>
    <label>Total Delivered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/StockVerification.cls
public class StockVerification {
    
    public String selectedLoc{get;set;}
    public Inventory__c invT{get;set;}
    public List<Inventory__c> invList{get;set;}
    public List<SelectOption> locList{get;set;}
    public Location__c loc{get;set;}
    public StockVerification(){
        invT=new Inventory__c(); 
        loc=new Location__c();
        locList=new List<SelectOption>(); 
        locList.add(new SelectOption('None','None')); 
        if(Test.isRunningTest())loc=[select id,name,Warehouse__c from Location__c limit 1];        
    }
    
    public void locLists(){
        if(loc.Warehouse__c !=null){
            for(Location__c lo:[select id,name from Location__c where Warehouse__c=:loc.Warehouse__c]){
                locList.add(new SelectOption(lo.id,lo.Name));
            }
        }
    }
    
    public void changePrd(){
        if(invT != null){
        
        }
    }
    
    public void invLists(){        
        invList=new List<Inventory__c>();  
        if(invT.Product__c != null && loc.Warehouse__c != null && selectedLoc !='None'){
            for(Inventory__c inv : [select id,Total_Delivered__c,Total_Invoiced__c,Total_Received__c,Warehouse_Location__c,Product__c,Out_Of_Stocks__c,Product__r.name,name,Warehouse__c,Warehouse__r.name,In_Hand_Quantity__c,Maximum_Stock_Level__c,Minimum_Stock_Level__c from Inventory__c where (Product__c=:invT.Product__c AND Warehouse__c=:loc.Warehouse__c) AND Warehouse_Location__c=:selectedLoc]){
                invList.add(inv);
            }
        }
        else if(invT.Product__c == null && loc.Warehouse__c != null && selectedLoc !='None'){
            for(Inventory__c inv : [select id,Total_Delivered__c,Total_Invoiced__c,Total_Received__c,Warehouse_Location__c,Product__c,Out_Of_Stocks__c,Product__r.name,name,Warehouse__c,Warehouse__r.name,In_Hand_Quantity__c,Maximum_Stock_Level__c,Minimum_Stock_Level__c from Inventory__c where Warehouse__c=:loc.Warehouse__c AND Warehouse_Location__c=:selectedLoc]){
                invList.add(inv);
            }
        }
        else if(invT.Product__c != null && loc.Warehouse__c != null && selectedLoc =='None'){
            for(Inventory__c inv : [select id,Total_Delivered__c,Total_Invoiced__c,Total_Received__c,Warehouse_Location__c,Product__c,Out_Of_Stocks__c,Product__r.name,name,Warehouse__c,Warehouse__r.name,In_Hand_Quantity__c,Maximum_Stock_Level__c,Minimum_Stock_Level__c from Inventory__c where (Product__c=:invT.Product__c AND Warehouse__c=:loc.Warehouse__c) OR Warehouse_Location__c=:selectedLoc]){
                invList.add(inv);
            }
        } 
        else if(invT.Product__c != null && selectedLoc =='None'){
            for(Inventory__c inv : [select id,Total_Delivered__c,Total_Invoiced__c,Total_Received__c,Warehouse_Location__c,Product__c,Out_Of_Stocks__c,Product__r.name,name,Warehouse__c,Warehouse__r.name,In_Hand_Quantity__c,Maximum_Stock_Level__c,Minimum_Stock_Level__c from Inventory__c where Product__c=:invT.Product__c OR Warehouse__c=:loc.Warehouse__c OR Warehouse_Location__c=:selectedLoc]){
                invList.add(inv);
            }
            //invT=new Inventory__c();
        }
        else if(loc.Warehouse__c != null && selectedLoc =='None'){
            for(Inventory__c inv : [select id,Total_Delivered__c,Total_Invoiced__c,Total_Received__c,Warehouse_Location__c,Product__c,Out_Of_Stocks__c,Product__r.name,name,Warehouse__c,Warehouse__r.name,In_Hand_Quantity__c,Maximum_Stock_Level__c,Minimum_Stock_Level__c from Inventory__c where Warehouse__c=:loc.Warehouse__c OR Warehouse_Location__c=:selectedLoc]){
                invList.add(inv);
            }
        }            
    }
}