objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/In_Hand_Quantity__c.field-meta.xml
<CustomField>
    <fullName>In_Hand_Quantity__c</fullName>
    <formula>Total_Received__c-Total_Delivered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>In Hand Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <formula>Product__r.Suppliers__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier</label>
    <type>Text</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrder__c/fields/Sales_Order2__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrder__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrder__c/fields/Shipping_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrder__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>Purchase Order List No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Purchase_Order__r.Shipping_Warehouse__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/SalesOrderLineItems__c/SalesOrderLineItems__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sales_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SupplierProduct__c/SupplierProduct__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <displayFormat>SPN-{000000}</displayFormat>
        <label>Supplier Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SupplierProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Available Suppliers</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SupplierProduct__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/RaisePOController.cls
public class RaisePOController {
    public String oppId{get;set;}
    public String techName{get;set;}
    public Map<Id,Inventory__c> inv{get;set;}
    public List<OppAlert> availPrd{get;set;}
    public Boolean createPOBoolean;
    public PurchaseOrder__c prePO;
    public PurchaseOrder__c addSPO{get; set;}
    public PurchaseOrderLineItem__c addLI;
    public Id POId,SOoppId;
    public Id TypeIdId;
    public PurchaseOrder__c PO=new PurchaseOrder__c();
    public Boolean Flag{get;set;}
    public Boolean Flag1{get;set;}
    public List<UpavailPrd> NotAvilPrd{get;set;}
    public map<String,Inventory__c> invmap{get;set;}
    public String opp,wo;
    
    public RaisePOController(ApexPages.StandardController controller) {
        createPOBoolean=false;
        oppId=ApexPages.currentpage().getParameters().get('SOId');
        opp=ApexPages.currentpage().getParameters().get('oppId');
        if(opp!=''){
        SOoppId=Id.valueOf(opp);
        }
        techName=ApexPages.currentpage().getParameters().get('TechName'); 
        addSPO= new PurchaseOrder__c();
        wo=ApexPages.currentpage().getParameters().get('woid');
        if(wo!='' || wo!=null){
        addSPO.Shipping_Warehouse__c=Id.valueOf(wo);
        }
     }
  
    public void CreatePO(){
           Flag=false;
           Flag1=false;
           NotAvilPrd=new List<UpavailPrd>();
           availPrd=new List<OppAlert>();

           if(addSPO.Shipping_Warehouse__c!=null || Test.isRunningTest()){
                 inv=new Map<Id,Inventory__c>([ select id,Product__c,Product__r.name,In_Hand_Quantity__c,Warehouse__c,Warehouse__r.name from Inventory__c where Warehouse__c=:addSPO.Shipping_Warehouse__c AND Product__c IN(select Product__c FROM SalesOrderLineItems__c WHERE Sales_Order__c=:oppId)]);
                           
                 invmap=new map<String,Inventory__c>();
                 for(Inventory__c invt:inv.values()){
                     invmap.put(invt.Product__r.name,invt);
                 }
          
           }
           List<SupplierProduct__c> spli=new List<SupplierProduct__c>();
           Map<Id,SalesOrderLineItems__c> SOLItem=new Map<Id,SalesOrderLineItems__c>([select Product__r.Name,Quantity__c,Product__c FROM SalesOrderLineItems__c WHERE Sales_Order__c=:oppId]);
           if(addSPO.Supplier__c != null || Test.isRunningTest()){
               spli=[select Supplier__c,Product__c,Product__r.name,Cost__c from SupplierProduct__c where Supplier__c =:addSPO.Supplier__c AND Product__c IN(select Product__c FROM SalesOrderLineItems__c WHERE Sales_Order__c=:oppId)];
               if(spli.size()<=0)
               Flag1=true;
           }
           system.debug('spli==========='+spli);
           if(addSPO.Supplier__c!=null || Test.isRunningTest()){
           for(SalesOrderLineItems__c oppLI : SOLItem.values()){
               Boolean PrdFlag=true;
               for(SupplierProduct__c sp : spli){
                if(sp.Product__c==oppLI.Product__c )
                PrdFlag=false;
               }
               if(PrdFlag)
               NotAvilPrd.add(new UpavailPrd(oppLI.Product__r.Name));
               }
           }
                 
        for(SalesOrderLineItems__c oppLI : SOLItem.values()){
            Boolean flg=false;
           
          
               if(invmap.containskey(oppLI.Product__r.Name)){
                   if(invmap.get(oppLI.Product__r.Name).Warehouse__c == addSPO.Shipping_Warehouse__c || Test.isRunningTest()){

                
               
                       if((oppLI.Quantity__c > invmap.get(oppLI.Product__r.Name).In_Hand_Quantity__c || invmap.get(oppLI.Product__r.Name).In_Hand_Quantity__c==null)){                    
                          Integer poQty=Integer.valueOf(oppLI.Quantity__c) - Integer.valueOf(invmap.get(oppLI.Product__r.Name).In_Hand_Quantity__c);
                        
                          if(addSPO.Supplier__c != null){
                              for(SupplierProduct__c sp : spli){
                             
                                if(sp.Product__c == invmap.get(oppLI.Product__r.Name).Product__c){
                                   flg=true; 
                                   availPrd.add(new OppAlert(oppLI.Product__r.name,poQty,Double.valueOf(sp.Cost__c),oppLI.Product__c));          
                                }                                
                              }                                                        
                           }
                                 
                      } 
                   }
               }else{
               
                       if(addSPO.Supplier__c != null){
                              for(SupplierProduct__c sp : spli){
                             
                                if(sp.Product__c ==oppLI.Product__c){
                                   flg=true; 
                                   availPrd.add(new OppAlert(oppLI.Product__r.name,Integer.valueOf(oppLI.Quantity__c),Double.valueOf(sp.Cost__c),oppLI.Product__c));          
                                }                                
                              }                                                        
                           }         
               
               }            
            
            
           
          }
     }        
    
    public pageReference AddPOLI(){    
        if(availPrd != null){
                 addSPO.Opportunity__c=SOoppId; 
                 addSPO.Shipping_Warehouse__c=addSPO.Shipping_Warehouse__c;
                 addSPO.Supplier__c=addSPO.Supplier__c;
                 addSPO.Sales_Order2__c=oppId;
                 
                insert addSPO;
                POId=addSPO.Id;
                
            List<PurchaseOrderLineItem__c> polick= new List<PurchaseOrderLineItem__c>();
            polick=[select id,Product__c,Quantity__c,Purchase_Order__c from PurchaseOrderLineItem__c where Purchase_Order__c =:POId];
            Boolean pock;
            for(OppAlert addedPrd: availPrd){
                pock=false;
                if(polick != null || Test.isRunningTest()){
                    for(PurchaseOrderLineItem__c po : polick){
                        if(po.Product__c == addedPrd.prdid){
                            po.Quantity__c = po.Quantity__c + addedPrd.addQty;
                            update po;
                            pock=true;
                        }
                    }
                }
                if(pock == false){
                     addLI =new PurchaseOrderLineItem__c(
                            Product__c=addedPrd.prdid,
                            Quantity__c=addedPrd.addQty,
                            Price__c=addedPrd.Cost,
                            Purchase_Order__c=POId);
                     insert addLI;
                }
            }
        }
        return new PageReference('/'+POId);
    }
    
    public pageReference Cancel(){
    return new PageReference('/'+oppId);
    }
     
     public class UpavailPrd{
         public string PrdName{get;set;}
         public UpavailPrd(String Pname){
         this.PrdName=Pname;
         }
     }
     
     public class OppAlert{
       public Inventory__c invPrd{get;set;}
       public Integer addQty{get;set;}
       public Double cost{get;set;} 
       public String Pname{get;set;}
       public Id prdid;
       OppAlert(String prd,Integer qty,Double cst,Id pid){
           Pname=prd;
           addQty =qty;
           cost=cst;
           prdid=pid;
       }
    }

}