objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <description>Inventory Transaction</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory_Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Inventory__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers_del</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Inventory__r.Warehouse__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Non_Stock__c.field-meta.xml
<CustomField>
    <fullName>Non_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non Stock</label>
    <type>Checkbox</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Create_Date__c</fullName>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

objects/PurchaseOrder__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <label>Created By</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tim Boyt</fullName>
            </value>
            <value>
                <fullName>Merfantz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PurchaseOrder__c/fields/Document_Creator__c.field-meta.xml
<CustomField>
    <fullName>Document_Creator__c</fullName>
    <label>Document Creator</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

objects/PurchaseOrder__c/fields/Shipping_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>Purchase Order List No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Last_Received_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Last_Received_Quantity__c</fullName>
    <label>Last Received Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Non_Stock__c.field-meta.xml
<CustomField>
    <fullName>Non_Stock__c</fullName>
    <formula>Product__r.Non_Stock__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Non Stock</label>
    <type>Checkbox</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Remaining_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Quantity__c</fullName>
    <formula>Quantity__c- Total_Received_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Total_Received_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Received_Quantity__c</fullName>
    <label>Total Received Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Purchase_Order__r.Shipping_Warehouse__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/UpdateInventoryControllerTest.cls
@isTest(SeeAllData=true)
public class UpdateInventoryControllerTest{
    
    static testMethod void myTest(){
    
    test.starttest();
    
    Warehouse__c WH=new Warehouse__c();
    WH.Name='Test';
    insert WH;
    
    PurchaseOrder__c PO=new PurchaseOrder__c();
    PO.Shipping_Warehouse__c=WH.id;
    PO.Create_Date__c=system.today();
    PO.Created_By__c='Tim Boyt';
    PO.Document_Creator__c='test@gmail.com';
    insert PO;
    
    List<Product2> PrdList=new List<Product2>();
    Product2 prd;
    
    prd=new product2();
    prd.Name='Test Product';
    prd.IsActive=true;
    prd.ProductCode='TES124';
    prd.Cost__c=12;
    PrdList.add(prd);
    
    prd=new product2();
    prd.Name='Test Serial';
    prd.IsActive=true;
    prd.ProductCode='TESer';
    prd.Cost__c=12;
    prd.Serialized__c=true;
    PrdList.add(prd);
    
    insert PrdList;
  
    List<PurchaseOrderLineItem__c> POLis=new List<PurchaseOrderLineItem__c>();
    PurchaseOrderLineItem__c POLine;
    
    for(Product2 Prds:PrdList){
        POLine=new PurchaseOrderLineItem__c();
        POLine.Purchase_Order__c=PO.id;
        POLine.Product__c=Prds.id;
        POLine.Quantity__c=3;
        POLine.Price__c=10;
        POLis.add(POLine);
    }
    
    insert POLis;
    
    Inventory__c Inv=new Inventory__c();
        Inv.Warehouse__c=WH.id;
        Inv.Product__c=PrdList[0].id;
    insert Inv;
        
    apexpages.standardcontroller sc=new apexpages.standardcontroller(PO);
    apexpages.currentpage().getparameters().put('id',String.valueof(PO.id));
    
    UpdateInventoryController InvCtrl=new UpdateInventoryController(sc);
    
    for(PurchaseOrderLineItem__c POli:[select id,Name,Product__r.Name,Product__c,Quantity__c,Last_Received_Quantity__c,Remaining_Quantity__c,Total_Received_Quantity__c from PurchaseOrderLineItem__c where Purchase_Order__c=:PO.id and Serialized__c=false and Non_Stock__c=false and Remaining_Quantity__c>0]){
        UpdateInventoryController.NonSerialWrap wrap=new UpdateInventoryController.NonSerialWrap(POli.id,POli.Product__r.Name,POli.Product__c,POli.Quantity__c,POli.Remaining_Quantity__c,1,POli.Total_Received_Quantity__c!=null?POli.Total_Received_Quantity__c:0,null);
        InvCtrl.NonSerial.add(wrap);
    }
    
    for(PurchaseOrderLineItem__c POli:[select id,Name,Product__r.Name,Product__c,Quantity__c,Last_Received_Quantity__c,Remaining_Quantity__c,Total_Received_Quantity__c from PurchaseOrderLineItem__c where Purchase_Order__c=:PO.id and Serialized__c=true and Remaining_Quantity__c>0]){
        List<Inventory_Transaction__c> NewInvTrns=new List<Inventory_Transaction__c>();
        UpdateInventoryController.SerialWrap wrap1=new UpdateInventoryController.SerialWrap(POli.id,POli.Product__r.Name,POli.Product__c,POli.Quantity__c,POli.Remaining_Quantity__c,1,POli.Total_Received_Quantity__c!=null?POli.Total_Received_Quantity__c:0,NewInvTrns,null);
        InvCtrl.Serial.add(wrap1);
    }
    
    InvCtrl.CheckValidQty();
    InvCtrl.SerialCount();
    InvCtrl.Cancel();
    InvCtrl.SaveAction();
    
    test.stoptest();
    }
}