objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/StockAdjustmentsCtrlTest.cls
@isTest(SeeAllData=true)
public class StockAdjustmentsCtrlTest{
    
    static testMethod void myTest(){
    
    test.starttest();
    
    Warehouse__c WH=new Warehouse__c();
    WH.Name='Test';
    insert WH;
    
    product2 prd=new product2();
    prd.Name='Test Product';
    prd.IsActive=true;
    prd.Serialized__c=true;
    prd.ProductCode='TES124';
    prd.Cost__c=12;
    insert prd;
    
    Inventory__c Inv=new Inventory__c();
    Inv.Warehouse__c=WH.id;
    Inv.Product__c=prd.id;
    insert Inv;
    
    ApexPages.StandardController sc = new ApexPages.standardController(WH);
    ApexPages.currentPage().getParameters().put('Id', WH.id);
    StockAdjustmentsController SCA=new StockAdjustmentsController(sc); 
    
    Apexpages.currentpage().getparameters().put('selInv',String.Valueof(prd.id));
    
    SCA.ProductId=prd.id;
    SCA.ProductName=prd.Name;
    SCA.Quantity='3';
    
    SCA.AddStock();
    SCA.RemoveStock();
    SCA.PrdRemCancel();
    SCA.PrdCancel();
    SCA.Cancel();
    SCA.selctedInvs();
    SCA.StockSearch();
    SCA.StockAdjust();
    SCA.saveclick();
    SCA.UpdateInvTrans();
    SCA.RemovePrdSelect();
    test.stoptest();
    }
    
    static testMethod void myTest1(){
        test.starttest();
    
        Warehouse__c WH1=new Warehouse__c();
        WH1.Name='Test';
        insert WH1;
    
        product2 prd1=new product2();
        prd1.Name='Test Product';
        prd1.IsActive=true;
        prd1.Serialized__c=true;
        prd1.ProductCode='TES124';
        prd1.Cost__c=12;
        insert prd1;
        
        ApexPages.StandardController sc1 = new ApexPages.standardController(WH1);
        ApexPages.currentPage().getParameters().put('Id', WH1.id);
        StockAdjustmentsController SCA1=new StockAdjustmentsController(sc1); 
        
        SCA1.ProductId=prd1.id;
        
        SCA1.saveclick();
        
        test.stoptest();
    }
}