objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/In_Hand_Quantity__c.field-meta.xml
<CustomField>
    <fullName>In_Hand_Quantity__c</fullName>
    <formula>Total_Received__c-Total_Delivered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>In Hand Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/OpportunityLineItem/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/OppStockAlertController.cls
public class OppStockAlertController{
    public String soId{get;set;}
    public List<Inventory__c> InvList;
    public List<OpportunityLineItem> soLIs{get;set;}
     //public List<OppAlert> availPrd{get;set;}
    //public List<AvailPrd> PrdList{get;set;}
    public List<OppAlert> PrdList{get;set;}
    public OppStockAlertController(ApexPages.StandardController controller) {
        soId=ApexPages.currentPage().getParameters().get('id');
        soLIs=[select Id,Product2Id,Product2.Name,Quantity,OpportunityId from OpportunityLineItem where OpportunityId=:soId];
        InvList=[select Id,Product__c,Product__r.Name,In_Hand_Quantity__c,Warehouse__c,Warehouse__r.Name from Inventory__c where Product__c IN(select Product2Id from OpportunityLineItem where OpportunityId=:soId)];
    }
    
    public List<OppAlert> getPrdList(){
        PrdList=new List<OppAlert>();
        Boolean isAvailable;
        for(OpportunityLineItem soLI : soLIs){ 
            isAvailable=false;
            for(Inventory__c invPrd : InvList){                       
                if((soLI.Quantity>= invPrd.In_Hand_Quantity__c) && soLI.Product2Id== invPrd.Product__c ){                    
                    PrdList.add(new OppAlert(soLI.Product2.Name,Double.valueOf(soLI.Quantity ),invPrd.In_Hand_Quantity__c,invPrd.Warehouse__r.Name));
                }else if(soLI.Product2Id== invPrd.Product__c){
                    isAvailable=true;
                }
            }
            /*if(!isAvailable)
                PrdList.add(new OppAlert(soLI.Product__r.Name,Double.valueOf(soLI.Quantity__c),0,''));*/
                
                system.debug('Inventory List==='+InvList);
        }
        return PrdList;
    }
        
    public void OppStockAlertOpp(){
        PrdList=getPrdList();
    }
    public class OppAlert{        
        public Double addedQty{get;set;}
        public String prodName{get; set;}
        Public Decimal available{get; set;}
        Public String whName{get; set;}
        
        public OppAlert(String name,Double qty, Decimal avail,String wh){
            prodName=name;
            addedQty=qty;
            available=avail;
            whName=wh;
        }        
    }
}