objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory__c/fields/Warehouse_id__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_id__c</fullName>
    <formula>Warehouse__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse id</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <description>Inventory Transaction</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory_Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Inventory__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>In Vehicle</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Inventory_Transaction__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Vehicle__c.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Inventory__r.Warehouse__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Warehouse_id__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_id__c</fullName>
    <formula>Inventory__r.Warehouse__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse id</label>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Available?</label>
    <type>Checkbox</type>
</CustomField>

objects/Vehicle__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Warehouse__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/TrasferPartsControllerTest.cls
@isTest(SeeAllData=true)
public class TrasferPartsControllerTest{
    
    
    
    static testMethod void myTest1(){
    
    Map<Id,List<Inventory__c>> CheckStatus=new Map<Id,List<Inventory__c>>();
    Map<String,Inventory_Transaction__c> UpdateVehMap;
    UpdateVehMap=new Map<String,Inventory_Transaction__c>();
    test.starttest();
    
    product2 prd=new product2();
    prd.Name='Test Product';
    prd.IsActive=true;
    prd.ProductCode='TES124';
    prd.Cost__c=12;
    insert prd;
    
    Warehouse__c WH=new Warehouse__c();
    WH.Name='Test';
    insert WH;
    
    Vehicle__c ve=new Vehicle__c(Name='vehicle',Warehouse__c=WH.id,Available__c=true);
    insert ve;
       
    Inventory__c Inv=new Inventory__c();
     Inv.Warehouse__c=WH.id;
    Inv.Product__c=prd.id;
    insert Inv;
    
     
   Inventory_Transaction__c IT=new Inventory_Transaction__c();
    It.Name='Test';
    IT.Transaction_Type__c='In Vehicle';
    IT.Inventory__c=Inv.id;
    IT.Vehicle__c=ve.id;
   // IT.Inventory__r.Product__r.Name;
    insert IT;
    system.debug('invT============='+Inv.id);
   
  
    ApexPages.currentPage().getParameters().put('Id',WH.id);
    ApexPages.currentPage().getParameters().put('selInv',String.valueOf(Inv.id));
    
     List<TrasferPartsController.SerialWrapper> SerialWrap=new List<TrasferPartsController.SerialWrapper>();
     list<TrasferPartsController.WrapInv> wrapInvList = new list<TrasferPartsController.WrapInv>();
     list<TrasferPartsController.wrapTran> wrapTranList = new list<TrasferPartsController.wrapTran>();
     TrasferPartsController.WrapInv wrapI = new TrasferPartsController.WrapInv('Test Product',wrapTranList ,2,4,prd.id,SerialWrap,Inv.id,Inv.Warehouse__c);
     wrapInvList.add(wrapI);
     
    
     PageReference pageRef = Page.TransferParts;
     Test.setCurrentPage(pageRef);

     pageRef.getParameters().put('Id', String.valueOf(WH.Id));
     ApexPages.StandardController sc = new ApexPages.StandardController(WH);
     TrasferPartsController TP=new TrasferPartsController(sc);
    TP.searchString ='';
    TP.wrapInvList=wrapInvList;
    apexpages.currentpage().getparameters().put('qtyPrd',prd.Name);
   // TrasferPartsController.wrapTran tr=new TrasferPartsController.wrapTran(prd.name, 'test',IT.id);
   // TrasferPartsController.WrapInv wrp=new TrasferPartsController.WrapInv(prd.Name,'',2,1);
   // TrasferPartsController.Vehctransfer vt=new TrasferPartsController.Vehctransfer (prd.name,IT.Name,true,IT.Vehicle__c,IT.id,null);
    // system.debug('prd name= '+prd.name+' S.no= '+IT.Name+' false= '+false+'vehicle = '+IT.Vehicle__c+'id=== '+IT.id);
   // TP.ChngReason='Test';
   // TP.transTypeWH=true;
   // TP.Invslists();
   // TP.cancel();
   // TP.selctedInvs();
   
    TP.selectedPicValue='Warehouse to Vehicle';
    TP.transTypeWH = false;
    TP.transTypeVH = true;
    TP.transTypeHV = false;
    TP.TransferTypeChange();
    
    
   TP.selectedPicValue='Vehicle to Warehouse';
   TP.transTypeWH = false;
    TP.transTypeVH = false;
    TP.transTypeHV = true;
    TP.TransferTypeChange();
    TP.InvQtyChange();
    
    list<TrasferPartsController.Vehctransfer> VehicleParts= new list<TrasferPartsController.Vehctransfer>();
    TrasferPartsController.Vehctransfer trans = new TrasferPartsController.Vehctransfer('Test Product','Test',true,'vehicle',IT.id,null,IT.Warehouse_id__c);
    VehicleParts.add(trans);
     TP.getVehicleParts();
      
    
    
    TP.SaveInv();
    }
    
    static testMethod void myTest2(){
    List<TrasferPartsController.SerialWrapper> SerialWrap=new List<TrasferPartsController.SerialWrapper>();
     Map<Id,List<Inventory__c>> CheckStatus=new Map<Id,List<Inventory__c>>();
    test.starttest();
    
    product2 prd=new product2();
    prd.Name='Test Product';
    prd.IsActive=true;
    prd.ProductCode='TES124';
    prd.Cost__c=12;
    insert prd;
    
    Warehouse__c WH=new Warehouse__c();
    WH.Name='Test';
    insert WH;
    
    Vehicle__c ve=new Vehicle__c(Name='vehicle',Warehouse__c=WH.id,Available__c=true);
    insert ve;
    
    Inventory__c Inv=new Inventory__c();
     Inv.Warehouse__c=WH.id;
    Inv.Product__c=prd.id;
    insert Inv;
    
   Inventory_Transaction__c IT=new Inventory_Transaction__c();
    It.Name='Test';
    IT.Transaction_Type__c='Received';
    IT.Inventory__c=Inv.id;
    
    insert IT;
    
    system.debug('invT============='+Inv.id);
    ApexPages.currentPage().getParameters().put('Id',WH.id);
    ApexPages.currentPage().getParameters().put('selInv',String.valueOf(Inv.id));
    apexpages.currentpage().getparameters().put('qtyPrd',prd.Name);
    PageReference pageRef = Page.TransferParts;
     Test.setCurrentPage(pageRef);

     pageRef.getParameters().put('Id', String.valueOf(WH.Id));
     ApexPages.StandardController sc = new ApexPages.StandardController(WH);
     TrasferPartsController TP=new TrasferPartsController(sc);
    TP.searchString ='';
    
    
   //TrasferPartsController.WrapInv wrp=new TrasferPartsController.WrapInv(prd.Name,inv,0,1);
    // TrasferPartsController.Vehctransfer vt=new TrasferPartsController.Vehctransfer (prd.name,IT.Name,false,IT.Vehicle__c,IT.id,null);
    // system.debug('prd name= '+prd.name+' S.no= '+IT.Name+' false= '+false+'vehicle = '+IT.Vehicle__c+'id=== '+IT.id);
    TP.ChngReason='Test';
    TP.transTypeWH=true;
    TP.Invslists();
    TP.cancel();
    TP.selctedInvs();
    //TP.InvQtyChange();
     TP.getVehicleParts();
    
   
   // TP.updateinvs();
   TP.selectedPicValue='Warehouse to Warehouse';
    TP.transTypeWH = true;
    TP.transTypeVH = false;
    TP.transTypeHV = false;
    TP.TransferTypeChange();
    
    TrasferPartsController.wrapTran tr=new TrasferPartsController.wrapTran(prd.name,'Test',IT.id);
    list<TrasferPartsController.wrapTran> wraptranList =new list<TrasferPartsController.wrapTran>();
    wraptranList.add(tr);
    system.debug('wraptranList<<<<<<<<====='+wraptranList);
    list<TrasferPartsController.WrapInv> wrapInvList = new list<TrasferPartsController.WrapInv>();
    TrasferPartsController.WrapInv wrapI = new TrasferPartsController.WrapInv('Test Product',wraptranList ,2,4,prd.id,SerialWrap,Inv.id,Inv.Warehouse__c);
    wrapInvList.add(wrapI );
     system.debug('wrapInvList<<<<<<<<====='+wrapInvList);
   
     TP.SaveInv();
    //TP.Transaction_Type__c='In Vehicle';
   
    test.stoptest();
    }
    
}