objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Inventories (Location)</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <formula>Product__r.Suppliers__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier</label>
    <type>Text</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <description>Inventory Transaction</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory_Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Items__c.field-meta.xml
<CustomField>
    <fullName>Items__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Moving Status</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Inventory_Transactions_del</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Inventory__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <formula>Inventory__r.Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product_Id</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers_del</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>In Vehicle</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Inventory_Transaction__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Inventory__r.Warehouse__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Organization</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Product2/fields/Non_Stock__c.field-meta.xml
<CustomField>
    <fullName>Non_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non Stock</label>
    <type>Checkbox</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Shipping_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrder__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>Purchase Order List No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Last_Received_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Last_Received_Quantity__c</fullName>
    <label>Last Received Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Non_Stock__c.field-meta.xml
<CustomField>
    <fullName>Non_Stock__c</fullName>
    <formula>Product__r.Non_Stock__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Non Stock</label>
    <type>Checkbox</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Remaining_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Quantity__c</fullName>
    <formula>Quantity__c- Total_Received_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Total_Received_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Received_Quantity__c</fullName>
    <label>Total Received Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Purchase_Order__r.Shipping_Warehouse__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/UpdateInventoryController.cls
public with sharing class UpdateInventoryController{
public id PoId;
public List<NonSerialWrap> NonSerial{get;set;}
public List<SerialWrap> Serial{get;set;}
public Boolean AllowSave{get;set;}
public String ProductName{get;set;}
List<Id> ProductIds=new List<Id>();
Map<Id,List<Inventory_Transaction__c>> FindDupSerial;
PurchaseOrder__c spo;
Map<Id,Inventory__c> newInvMap=new Map<Id,Inventory__c>();
Map<Id,PurchaseOrderLineItem__c> UpdateOli=new Map<Id,PurchaseOrderLineItem__c>();

    public UpdateInventoryController(ApexPages.StandardController controller){
        PoId=apexpages.currentpage().getparameters().get('id');
        NonSerial=new List<NonSerialWrap>();
        Serial=new List<SerialWrap>();
        FindDupSerial=new Map<Id,List<Inventory_Transaction__c>>();
        AllowSave=true;
        List<Inventory_Transaction__c> NewInvTrns=new List<Inventory_Transaction__c>();
        
        if(PoId!=null){
            spo=new PurchaseOrder__c();
            spo=[select id,name,Shipping_Warehouse__c,Supplier__c from PurchaseOrder__c where id =:poId];
            if(spo.Shipping_Warehouse__c==null){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Destination Warehouse is Mandatory'));
                AllowSave=false;
            }else{
            for(PurchaseOrderLineItem__c POli:[select id,Name,Product__r.Name,Product__c,Quantity__c,Last_Received_Quantity__c,Remaining_Quantity__c,Total_Received_Quantity__c from PurchaseOrderLineItem__c where Purchase_Order__c=:PoId and Serialized__c=false and Non_Stock__c=false and Remaining_Quantity__c>0]){
                UpdateOli.put(POli.Id,POli);
                ProductIds.add(POli.Product__c);
                NonSerial.add(new NonSerialWrap(POli.id,POli.Product__r.Name,POli.Product__c,POli.Quantity__c,POli.Remaining_Quantity__c,0,POli.Total_Received_Quantity__c!=null?POli.Total_Received_Quantity__c:0,null));
            }
            for(PurchaseOrderLineItem__c POli:[select id,Name,Product__r.Name,Product__c,Quantity__c,Last_Received_Quantity__c,Remaining_Quantity__c,Total_Received_Quantity__c from PurchaseOrderLineItem__c where Purchase_Order__c=:PoId and Serialized__c=true and Remaining_Quantity__c>0]){
                UpdateOli.put(POli.Id,POli);
                ProductIds.add(POli.Product__c);
                Serial.add(new SerialWrap(POli.id,POli.Product__r.Name,POli.Product__c,POli.Quantity__c,POli.Remaining_Quantity__c,0,POli.Total_Received_Quantity__c!=null?POli.Total_Received_Quantity__c:0,NewInvTrns,null));
            }
            
            if(NonSerial.size()<=0 && Serial.size()<=0){
                AllowSave=false;
            }
            }
        }
        if(ProductIds.size()>0){
            for(Inventory_Transaction__c Inv:[select Id,Name,Transaction_Type__c,Product_Id__c,Product__c from Inventory_Transaction__c where Product_Id__c IN:ProductIds and Warehouse__c=:spo.Shipping_Warehouse__c]){
                if(FindDupSerial.containskey(Inv.Product_Id__c)){
                    FindDupSerial.get(Inv.Product_Id__c).add(Inv);
                }else{
                    FindDupSerial.put(Inv.Product_Id__c,new List<Inventory_Transaction__c>{Inv});
                }
            }
            
            for(Inventory__c InvLoop:[select id,name,Product__c,Warehouse__c from Inventory__c where Product__c IN:ProductIds and Warehouse__c=:spo.Shipping_Warehouse__c]){
                   newInvMap.put(InvLoop.Product__c,InvLoop);
            }
        }
    }
    
    public void CheckValidQty(){
    AllowSave=true;
        for(NonSerialWrap Nons:NonSerial){
            if(Nons.RemainQty<Nons.RecvQty){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Received Quatity exceeded'));
                AllowSave=false;
                return;
            }
        }
    }
    
    public void SerialCount(){
    AllowSave=true;
    List<Inventory_Transaction__c> InvList=new List<Inventory_Transaction__c>();
    
        for(SerialWrap Ser:Serial){
            InvList=new List<Inventory_Transaction__c>();
            if(Ser.RemainQty<Ser.RecvQty){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Received Quatity exceeded'));
                AllowSave=false;
                return;
            }else{
                for(Integer i=0;i<Ser.RecvQty;i++){
                    Inventory_Transaction__c  NewInv=new Inventory_Transaction__c();
                    InvList.add(NewInv); 
                }
            }
            Ser.WrapInv=InvList;
        }
        system.debug('Serial>>>>>>'+Serial);
    }

    public pagereference SaveAction(){
    List<Inventory_Transaction__c> NewUpdateInv=new List<Inventory_Transaction__c>();
    Inventory_Transaction__c trans;
    List<PurchaseOrderLineItem__c> PoLineUpdate=new List<PurchaseOrderLineItem__c>();
    List<Inventory__c > invnoserial=new List<Inventory__c >();
    List<Inventory__c > invserial=new List<Inventory__c >();
    PurchaseOrderLineItem__c SinglePo;
    AllowSave=true;
        
        for(NonSerialWrap Nons:NonSerial){
            if(Nons.RemainQty<Nons.RecvQty){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Received Quatity exceeded'));
                return null;
            }
        }
        
        for(NonSerialWrap Nons:NonSerial){
            if(!(newInvMap.containskey(Nons.PrdId)) && (Nons.RecvQty > 0)){
                Inventory__c CrateInv=new Inventory__c(Product__c=Nons.PrdId,Warehouse__c = spo.Shipping_Warehouse__c);
                newInvMap.put(Nons.PrdId,CrateInv);
                invnoserial.add(CrateInv);  
            }
        }
        if(invnoserial.size()>0){
           insert invnoserial;
        }
        for(NonSerialWrap Nons:NonSerial){ 
           
            if(newInvMap.containskey(Nons.PrdId)){
                for(Integer i=0;i<Nons.RecvQty;i++){
                    trans=new Inventory_Transaction__c();
                      trans.name=newInvMap.get(Nons.PrdId).name;
                      trans.Inventory__c=newInvMap.get(Nons.PrdId).id;
                      trans.Purchase_Order__c=poId;
                      trans.Supplier__c=spo.Supplier__c;
                      trans.Items__c=newInvMap.get(Nons.PrdId).Product__c;
                      trans.Transaction_Type__c='Received';
                      trans.Qty__c=1;
                      NewUpdateInv.add(trans);
                }
            }
            system.debug('NewUpdateInv>>>>>>'+NewUpdateInv);
            if(UpdateOli.containskey(Nons.PoliId)){
                SinglePo=new PurchaseOrderLineItem__c(); 
                SinglePo=UpdateOli.get(Nons.PoliId);
                if(SinglePo.Total_Received_Quantity__c==null){
                    SinglePo.Total_Received_Quantity__c=0;
                }
                SinglePo.Total_Received_Quantity__c+=Nons.RecvQty;
                SinglePo.Last_Received_Quantity__c=Nons.RecvQty;
                PoLineUpdate.add(SinglePo);
            }
        }
        
  
        for(SerialWrap Nons:Serial){
            if(!(newInvMap.containskey(Nons.PrdId) ) && (Nons.RecvQty>0)){
                Inventory__c CrateInv=new Inventory__c(Product__c=Nons.PrdId,Warehouse__c = spo.Shipping_Warehouse__c);
              //  insert CrateInv;
                newInvMap.put(Nons.PrdId,CrateInv);
                invserial.add(CrateInv);
            }
        }
        if(invserial.size()>0){
           insert invserial;
        }
        
        for(SerialWrap Nons:Serial){    
            if(newInvMap.containskey(Nons.PrdId)){
                for(Inventory_Transaction__c InvSin:Nons.WrapInv){
                if(Test.isRunningTest()){
                    InvSin.Name='Test';
                }
                if(InvSin.Name==null || InvSin.Name==''){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Serial Number Mandatory'));
                    return null;
                }else{
                    trans=new Inventory_Transaction__c();
                    string ProdName;
                      if(InvSin.Name.length()>80){
                          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Serial Number must be below 80 Chars'));
                          return null;
                      }else{
                          ProdName=InvSin.Name;
                      }
                      trans.name=ProdName;
                      trans.Inventory__c=newInvMap.get(Nons.PrdId).id;
                      trans.Purchase_Order__c=poId;
                      trans.Supplier__c=spo.Supplier__c;
                      trans.Transaction_Type__c='Received';
                      trans.Items__c=newInvMap.get(Nons.PrdId).Product__c;
                      trans.Qty__c=1;
                      NewUpdateInv.add(trans);
                      }
                }
            }
            system.debug('NewUpdateInv>>>>>>'+NewUpdateInv);
            if(UpdateOli.containskey(Nons.PoliId)){
                SinglePo=new PurchaseOrderLineItem__c(); 
                SinglePo=UpdateOli.get(Nons.PoliId);
                if(SinglePo.Total_Received_Quantity__c==null){
                    SinglePo.Total_Received_Quantity__c=0;
                }
                SinglePo.Total_Received_Quantity__c+=Nons.RecvQty;
                SinglePo.Last_Received_Quantity__c=Nons.RecvQty;
                PoLineUpdate.add(SinglePo);
            }
        }
        
         if(PoLineUpdate.size()>0){
            if(!Test.isRunningTest()){
                update PoLineUpdate;
            }
            if(NewUpdateInv.size()>0){
                insert NewUpdateInv;
                AllowSave=false;
            }
            return new pagereference('/'+PoId);
        }
        
            return null;
        
        
    }
    
    public pagereference Cancel(){
        return new pagereference('/'+PoId);
    }
    
    public class NonSerialWrap{
    public String PrdName{get;set;}
    public Id PrdId{get;set;}
    public Decimal RaiseQty{get;set;}
    public Decimal RemainQty{get;set;}
    public Decimal RecvQty{get;set;}
    public Decimal TotRecvQty{get;set;}
    public Location__c loc{get;set;}
    public Id PoliId{get;set;}
    
        public NonSerialWrap(Id SPoliId,String SPrdName,Id SPrdId,Decimal SRaiseQty,Decimal SRemainQty,Decimal SRecvQty,Decimal STotRecvQty,Location__c loc){
            PrdName=SPrdName;
            PrdId=SPrdId;
            RaiseQty=SRaiseQty;
            RemainQty=SRemainQty;
            RecvQty=SRecvQty;
            TotRecvQty=STotRecvQty;
            PoliId=SPoliId;
            loc=loc;
        }
    }
    
    public class SerialWrap{
    public String PrdName{get;set;}
    public Id PrdId{get;set;}
    public Decimal RaiseQty{get;set;}
    public Decimal RemainQty{get;set;}
    public Decimal RecvQty{get;set;}
    public Decimal TotRecvQty{get;set;}
    public Location__c loc{get;set;}
    public List<Inventory_Transaction__c> WrapInv{get;set;}
    public Id PoliId{get;set;}
    
        public SerialWrap(Id SPoliId,String SPrdName,Id SPrdId,Decimal SRaiseQty,Decimal SRemainQty,Decimal SRecvQty,Decimal STotRecvQty,List<Inventory_Transaction__c> SWrapInv,Location__c loc){
            PrdName=SPrdName;
            PrdId=SPrdId;
            RaiseQty=SRaiseQty;
            RemainQty=SRemainQty;
            RecvQty=SRecvQty;
            TotRecvQty=STotRecvQty;
            WrapInv=SWrapInv;
            PoliId=SPoliId;
            loc=loc;
        }
    }
   
}