objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/In_Hand_Quantity__c.field-meta.xml
<CustomField>
    <fullName>In_Hand_Quantity__c</fullName>
    <formula>Total_Received__c-Total_Delivered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>In Hand Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/SalesOrderStockAlert.cls
public class SalesOrderStockAlert {

    public SalesOrderStockAlert(ApexPages.StandardController controller) {
        OrdId=ApexPages.currentPage().getParameters().get('id');
        prds=new List<String>();
        if(OrdId !=null){
            OrdLI=[select Id,PricebookEntry.Product2Id,Quantity, OrderId from OrderItem where OrderId=:OrdId];        
            for(OrderItem oli:OrdLI){
                prds.add(oli.PricebookEntry.Product2Id);
            }
            if(prds.size()>0){
            InvList=[select Id,Product__c,Product__r.Name,In_Hand_Quantity__c,Warehouse__c,Warehouse__r.Name from Inventory__c where Product__c IN:prds];
            }
        }
    }
    
    public List<String> prds;
    public String OrdId{get;set;}
    public List<Inventory__c> InvList;
    public List<OrderItem> OrdLI{get;set;}
    public List<AvailPrd> PrdList{get;set;}    
    
    public List<AvailPrd> getPrdList(){
        PrdList=new List<AvailPrd>();
        for(OrderItem OrdLIprd : OrdLI){
            for(Inventory__c invPrd : InvList){
                if((OrdLIprd.Quantity > invPrd.In_Hand_Quantity__c ||  invPrd.In_Hand_Quantity__c == null) && OrdLIprd.PricebookEntry.Product2Id == invPrd.Product__c ){
                    PrdList.add(new AvailPrd(invPrd,Double.valueOf(OrdLIprd.Quantity)));
                }
            }
        }
        return PrdList;
    }
        
    public void StockAlertOrd(){
        PrdList=getPrdList();
    }
    public class AvailPrd{
        public Inventory__c inv{get;set;}
        public Double addedQty{get;set;}
        public AvailPrd(Inventory__c invPrd,Double qty){
            inv=invPrd;
            addedQty=qty;
        }        
    }

}