objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/In_Hand_Quantity__c.field-meta.xml
<CustomField>
    <fullName>In_Hand_Quantity__c</fullName>
    <formula>Total_Received__c-Total_Delivered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>In Hand Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/SalesOrderLineItems__c/SalesOrderLineItems__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sales_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/StockAlertController.cls
public class StockAlertController{
    public String soId{get;set;}
    public List<Inventory__c> InvList;
    public List<SalesOrderLineItems__c> soLIs{get;set;}
    public List<AvailPrd> PrdList{get;set;}
    public StockAlertController(ApexPages.StandardController controller) {
        soId=ApexPages.currentPage().getParameters().get('id');
        soLIs=[select Id,Product__c,Product__r.Name,Quantity__c, Sales_Order__c from SalesOrderLineItems__c where Sales_Order__c=:soId];
        system.debug('line item========'+soLIs);
        InvList=[select Id,Product__c,Product__r.Name,In_Hand_Quantity__c,Warehouse__c,Warehouse__r.Name from Inventory__c where Product__c IN(select product__c from SalesOrderLineItems__c where Sales_Order__c=:soId)];
        system.debug('Inventory======='+InvList);
    }
    
    public List<AvailPrd> getPrdList(){
        PrdList=new List<AvailPrd>();
        Boolean isAvailable;
        for(SalesOrderLineItems__c soLI : soLIs){ 
            isAvailable=false;
            for(Inventory__c invPrd : InvList){                       
                if((soLI.Quantity__c >= invPrd.In_Hand_Quantity__c) && soLI.Product__c == invPrd.Product__c ){                    
                    PrdList.add(new AvailPrd(soLI.Product__r.Name,Double.valueOf(soLI.Quantity__c),invPrd.In_Hand_Quantity__c,invPrd.Warehouse__r.Name));
                    system.debug('PrdList======'+PrdList);
                }/* else if(soLI.Product__c == invPrd.Product__c){
                    isAvailable=true;
                } */
            }
            /*if(!isAvailable)
                PrdList.add(new AvailPrd(soLI.Product__r.Name,Double.valueOf(soLI.Quantity__c),0,''));*/
                
                system.debug('Inventory List==='+InvList);
        }
        return PrdList;
    }
        
    public void StockAlertOpp(){
        PrdList=getPrdList();
    }
    public class AvailPrd{        
        public Double addedQty{get;set;}
        public String prodName{get; set;}
        Public Decimal available{get; set;}
        Public String whName{get; set;}
        
        public AvailPrd(String name,Double qty, Decimal avail,String wh){
            prodName=name;
            addedQty=qty;
            available=avail;
            whName=wh;
        }        
    }
}