objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <description>Inventory Transaction</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory_Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Inventory__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers_del</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>In Vehicle</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Inventory_Transaction__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Inventory__r.Warehouse__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Shipping_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>Purchase Order List No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Purchase_Order__r.Shipping_Warehouse__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/SerialNumberEachProductController.cls
public class SerialNumberEachProductController {
    
    public List<PurchaseOrderLineItem__c > PoliList;
    public String poId{get;set;}
    public String Jstring{get;set;}
    public string prd{get;set;}
    public Boolean viewState{get;set;}
    public string selectedId{get;set;}
    public string serialNO{get;set;}
    public SerialNumberEachProductController (){
        poId=ApexPages.currentPage().getParameters().get('id');
    }
   
   //POILList = [Select id, Name, Product__c, Quantity__c, Price__c, Description__c From Purchase_Order_Line_Item__c Where Supplier_Purchase_Order__c = : POId];
   
   public void getJstring(){
       Jstring=createJson();
   }
   
   public String createJson(){
           
           system.debug('-------Current----'+poId);
            JSONGenerator Jgen = JSON.createGenerator(true);  
              
              
               Jgen.writeStartArray(); 
               Integer j=1;   
             Map<Id,Product2> prdName=new  Map<id,Product2>([select id,Name from Product2]);
      for(PurchaseOrderLineItem__c poliPrd : [Select id, Name, Product__c, Quantity__c, Price__c,Description__c From PurchaseOrderLineItem__c Where Purchase_Order__c = : poId]){
            //PurchaseOrderLineItem__c poliPrd = [Select id, Name, Product__c, Quantity__c, Price__c, Description__c From PurchaseOrderLineItem__c Where Purchase_Order__c = : poId Limit 1];
           
                       
            Jgen.writeStartObject();  
           
            Jgen.writeStringField('product',prdName.get(poliPrd.Product__c).Name);
            Jgen.writeStringField('parentid', '-1');
            Jgen.writeStringField('serial','');
            Jgen.writeStringField('id',String.valueOf(j));
             Jgen.writeEndObject();           
            
            
            SerialNumberWrapper serialNoRow=new SerialNumberWrapper(poliPrd,'');
            

                  // Jgen.writeFieldName('children'); 
                  // Jgen.writeStartArray();
                                                       
                for(Integer i=1;i<=Integer.valueOf(poliPrd.Quantity__c);i++){   
                 
                    
                    Jgen .writeStartObject();   
                    Jgen.writeStringField('parentid',String.valueOf(j));
                    Jgen.writeStringField('id',String.valueOf(j+'-'+i));                
                    Jgen.writeStringField('product',prdName.get(serialNoRow.LineItem.Product__c).Name);
                    Jgen.writeStringField('serial',serialNoRow.SNumber);
                    Jgen.writeBooleanField('isFolder',true); 
                    
                     Jgen.writeEndObject();
                                   
                  
                }  
                j+=1;              
                 // Jgen.writeEndArray();    
                  //   Jgen.writeEndObject();
                
               
                
                          
      }
      Jgen.writeEndArray();
      String str = Jgen.getAsString();
      system.debug('-------JSON----'+str);
      return str;
   }
   
   public void viewselectedItem(){
       viewState=true;
   }
   
   public void InsertInventory(){
       /*Inventory_Transaction__c insertinvT;
       Inventory_Transaction__c getinvT;
       if(prd != null){
           getinvT=[select id,SerialId__c,SerialNumber__c from Inventory_Transaction__c where SerialId__c =:prd];
           if(getinvT.SerialId__c == null){
               PurchaseOrder__c po=[select id, Shipping_Warehouse__c from PurchaseOrder__c where id=:poId];
               if(po.Shipping_Warehouse__c !=null){
                   Inventory__c inv=[select id, Warehouse__c,product__c from Inventory__c where Warehouse__c =:po.Shipping_Warehouse__c];
                   if(inv.product__c !=null && inv.product__c !=prd && serialNO != null){
                       insertinvT=new Inventory_Transaction__c(Inventory__c=inv.id, SerialId__c=selectedId, SerialNumber__c=serialNO, Transaction_Type__c='Added');
                       insert insertinvT;
                   }
                   else if(inv.product__c == null && serialNO != null){
                       Inventory__c insertInv=new Inventory__c(Warehouse__c=po.Shipping_Warehouse__c);
                       insert insertInv;
                       insertinvT=new Inventory_Transaction__c(Inventory__c=insertInv.id, SerialId__c=selectedId, SerialNumber__c=serialNO, Transaction_Type__c='Added');
                       insert insertinvT;
                   }
               }
               //Inventory_Transaction__c insertInvT=new Inventory_Transaction__c();
           }
       }*/
   }
   
   public class SerialNumberWrapper{
       public PurchaseOrderLineItem__c LineItem{get;set;}
       public String SNumber{get;set;}
       
       public SerialNumberWrapper(PurchaseOrderLineItem__c LI,String sn){
           LineItem=LI;
           SNumber=sn;
       }
   }
}