objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <description>Inventory Transaction</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory_Transaction__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <label>Product2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers_del</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/AcknowledgementComponentController.cls
global class AcknowledgementComponentController {
//global String poNo{get; set;}
global String poId{get; set;}
global Map<String, String> prodCounts{get; set;}
global List<String> prods{get; set;}


public String poNo;
public String getpoNo(){return poNo; }
public void setpoNo(String po) {
    poNo = po;
    System.debug('pooo==='+poNo);
    AcknowledgementComponentController();
}
 
    global void AcknowledgementComponentController() {
        poId=ApexPages.currentPage().getParameters().get('id');
        System.debug('pooo==='+poId);
        prodCounts=new Map<String, String>();
        prods=new List<String>();
        for(AggregateResult ag:[select Product2__c prod, count(Id) cnt from Inventory_transaction__c where Purchase_Order__c=:poNo group by Product2__c]){
            prodCounts.put(String.ValueOf(ag.get('prod')),String.ValueOf(ag.get('cnt')));
            prods.add(String.ValueOf(ag.get('prod')));   
                  
        }
        System.debug('poNopc==='+prodCounts);
        System.debug('poNoprdsa==='+prods);
    }        
}