objects/Location_List__c/Location_List__c.object-meta.xml
<CustomObject>
    <label>Location List</label>
    <nameField>
        <label>Location List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Location_List__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Location_List__c/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Asset Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Location_List__c/fields/Location_Description__c.field-meta.xml
<CustomField>
    <fullName>Location_Description__c</fullName>
    <label>Location Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Location_List__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/LocationlistControllerTest.cls
@isTest(SeeAllData=true)
private class LocationlistControllerTest 
{
   
    static Location_List__c testLocationList;
    @isTest public static void init()
    {
        testLocationList = new Location_List__c ();
       
        testLocationList .Location_Description__c= 'location;';
        testLocationList .Area__c= 'chennai;';
        testLocationList .Zone__c='5;';
        testLocationList .Asset_Type__c= 'XYZ;';
      
       
        
        database.insert(testLocationList );
        
    }
    static testMethod void Locationtest()
    {
        init();
        PageReference pg = new PageReference('/apex/Locationlist?id='+testLocationList.id);
        Test.setCurrentPageReference(pg);
        ApexPages.StandardController sc = new ApexPages.standardController(testLocationList);
        LocationlistController controller = new LocationlistController (sc);
        //controller.getSystemDetails();
        controller.getItems();
        controller.getValue();
        
        controller.setZone(controller.getZone());
        controller.setassettyp (controller.getassettyp());
        controller.getSystemLocation();
        controller.addSystemLocations();
        //controller.saveSystemDetails();
        controller.editSystemLocations();
        controller.saveSystemLocations();
        controller.remove();
    }
}