objects/Opportunity/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inreview</fullName>
                <label>In review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Opportunity/fields/Cloned_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Cloned_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Reactive_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Reactive_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reactive Sheet</label>
    <referenceTo>Service_Sheet_STD__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Sheet_STD__c/Service_Sheet_STD__c.object-meta.xml
<CustomObject>
    <label>M&amp;R Sheet</label>
    <nameField>
        <displayFormat>RS{000000}</displayFormat>
        <label>Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>M&amp;R Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApprovalMaintain.cls
public class ApprovalMaintain{
   
    public String Mid;
        public ApprovalMaintain(ApexPages.StandardController controller) {
        Mid=  ApexPages.CurrentPage().getParameters().get('id');
        system.debug('Mid====='+Mid);
       for(Service_Sheet_STD__c eng: [select Name,id,(select name,Approval_status__c from Opportunities__r) from Service_Sheet_STD__c where id=:Mid])
        {
        for(Opportunity opp:eng.Opportunities__r){
        if(opp.Approval_status__c!=null && opp.Approval_status__c=='Approved')
        {
        system.debug('status===='+opp.Approval_status__c );
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,opp.Name+' - Invoice is Approved'));
        }
        
         if(opp.Approval_status__c!=null && opp.Approval_status__c=='Rejected')
        {
        system.debug('status===='+opp.Approval_status__c );
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,opp.Name+' - Invoice is Rejected'));
        }
           }
         }
        }
    
    }