objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

objects/Opportunity/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <formula>IF(OR(Billing_Street__c &lt;&gt; &apos;&apos;,Billing_City__c &lt;&gt; &apos;&apos;,Billing_State__c &lt;&gt; &apos;&apos;,Billing_Country__c &lt;&gt; &apos;&apos;,Billing_Postal_Code__c &lt;&gt; &apos;&apos;, Alternative_Invoice_Company_Name__c &lt;&gt; &apos;&apos;), 
IF(Alternative_Invoice_Company_Name__c &lt;&gt; &apos;&apos;, Alternative_Invoice_Company_Name__c &amp;BR(), &apos;&apos;) &amp; 
IF(Billing_Street__c &lt;&gt; &apos;&apos;, Billing_Street__c &amp;BR() , &apos;&apos;) &amp; 
IF(Billing_City__c&lt;&gt; &apos;&apos;, Billing_City__c&amp;BR(), &apos;&apos;) &amp; 
IF(Billing_State__c &lt;&gt; &apos;&apos;, Billing_State__c&amp;BR(), &apos;&apos;) &amp; 
IF(Billing_Postal_Code__c &lt;&gt; &apos;&apos;, Billing_Postal_Code__c&amp;BR(), &apos;&apos;) &amp; 
IF( Billing_Country__c &lt;&gt; &apos;&apos;, Billing_Country__c, &apos;&apos;),&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Address</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Invoice_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Address__c</fullName>
    <formula>Account.Site_Invoice_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Address</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Schedule_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Schedule_of_Work__c</fullName>
    <label>Schedule of Work</label>
    <type>TextArea</type>
</CustomField>

objects/Opportunity/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/Product2/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Stock_Unit__c.field-meta.xml
<CustomField>
    <fullName>Stock_Unit__c</fullName>
    <label>Stock Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Metre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <formula>Opportunity__r.Billing_City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing City</label>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <formula>Opportunity__r.Billing_Country__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Country</label>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <formula>Opportunity__r.Billing_Postal_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Postal Code</label>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <formula>Opportunity__r.Billing_State__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing State</label>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <formula>Opportunity__r.Billing_Street__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Street</label>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <formula>Opportunity__r.Site_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Address</label>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <label>Fax</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/fields/Invoice_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Address__c</fullName>
    <formula>Opportunity__r.Invoice_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Address</label>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <formula>Total_Price__c  +  Vat_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/SalesOrder__c/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/SalesOrder__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>SalesOrderLineItems__c.Total_Price__c</summarizedField>
    <summaryForeignKey>SalesOrderLineItems__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/SalesOrder__c/fields/Vat_Total__c.field-meta.xml
<CustomField>
    <fullName>Vat_Total__c</fullName>
    <formula>( Total_Price__c  *   VAT_Rate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vat Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/SalesOrderLineItems__c/SalesOrderLineItems__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sales_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

classes/LongProjectOrderController.cls
public with sharing class LongProjectOrderController {
public String MasterRecordId;
 
    public opportunity[] ChildRecords{get; set;}
    public List<SalesOrderLineItems__c> salesoli  {get; set;}
    public SalesOrder__c MasterRecord{get; set;}
     public opportunity pro{get;set;}
    public String prono{get;set;}
    public Boolean checked{get;set;}
    
    public LongProjectOrderController()
    {
    system.debug('constructor>>>>>>>>');
      
}

 public String getMasterRecordId (){        
        return MasterRecordId ;
    }
    public void setMasterRecordId (String msid){
        this.MasterRecordId =msid;
        system.debug('MasterRecordId ========'+MasterRecordId );
        if(!String.isBlank(MasterRecordId)){
          Proj();
       }
        
    }

public void Proj(){
MasterRecord =
                [
                    SELECT 
                        Invoice_Address__c,
                        Delivery_Address__c,
                        Due_Date__c,Account__r.Site_Contact__r.Name,Name,CreatedBy.Name,CreatedDate,Account__r.Parent_SAGE_ID__c,Fax__c,Email__c,Phone__c,
                        Account__r.Name,Account__r.Site_Invoice_Name__c,Total_Price__c,Vat_Total__c,Order_Total__c  
                    FROM
                        SalesOrder__c
                    WHERE
                        Id = :MasterRecordId
                ];
                system.debug('<<<<<<>>>>>>>>>');
                /** ChildRecords =
                 [
                    SELECT 
                          Delivery_Address__c,Billing_Street__c,Billing_City__c,Billing_State__c,Billing_Country__c,Billing_Postal_Code__c,Schedule_of_Work__c
                    FROM
                        opportunity
                    WHERE 
                        Long_Project_Order__c = :MasterRecordId order by createddate desc limit 1
                ];**/
            /*     system.debug('###########################');
               system.debug(''+ChildRecords);
                    checked=true;
                    For(opportunity po:ChildRecords){
                    if(((po.Room1_Dispensors_Include_In_Print__c)==checked) &&(po.Room1_Dispensors__c==null))
                    {
                        po.Room1_Dispensors__c='None';
                        system.debug(''+po.Room1_Dispensors__c);
                    }
                        
                        
                        if(((po.Room1_Splashbacks_Include_In_Print__c)==checked) &&(po.Room1_Splashbacks__c==null)) {
                            po.Room1_Splashbacks__c='None';
                            system.debug(''+po.Room1_Splashbacks__c); */
                        
                        
        
                

              salesoli=
                [
                    SELECT 
                        Price__c,
                        Product__c,
                        Quantity__c,
                        Product__r.Stock_Unit__c,
                        Extended_Sales_Description__c,
                        Show_Description__c ,
                        Sales_Description__c,
                        Total_Price__c,Product__r.Name
                    FROM
                        SalesOrderLineItems__c
                    WHERE 
                        Sales_Order__c= :MasterRecordId
                ];
                
    
}
}