objects/Opportunity/fields/Project_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Project_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Sheet</label>
    <referenceTo>Project_Sheet__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site Contract Number</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Site_Visit_Time__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Time__c</fullName>
    <label>Site Visit Times</label>
    <type>TextArea</type>
</CustomField>

objects/Project_Sheet__c/Project_Sheet__c.object-meta.xml
<CustomObject>
    <label>Project Sheet</label>
    <nameField>
        <displayFormat>PS{000000}</displayFormat>
        <label>Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Sheet__c/fields/Document_Attached__c.field-meta.xml
<CustomField>
    <fullName>Document_Attached__c</fullName>
    <inlineHelpText>Please Enter the Work Completion Note number to confirm that you have taken a photo of the Priory Work Completion Note that you have completed for this Visit, and attached to this Service Sheet.</inlineHelpText>
    <label>Document Attached</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Project_Sheet__c/fields/Fire_Extinguisher_Service_complete__c.field-meta.xml
<CustomField>
    <fullName>Fire_Extinguisher_Service_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit this Service</label>
    <type>Checkbox</type>
</CustomField>

objects/Project_Sheet__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Project Sheets</relationshipLabel>
    <relationshipName>Project_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Project_Sheet__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipLabel>Project Sheets</relationshipLabel>
    <relationshipName>Project_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/Visit_Complete__c.field-meta.xml
<CustomField>
    <fullName>Visit_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Complete</label>
    <type>Checkbox</type>
</CustomField>

classes/ProjectSheetTriggerHandlerTest.cls
/*============================================================================================================
*Class Name     : ProjectSheetTriggerHandlerTest
*Description    : Test Class for ProjectSheetTriggerHandler
*Company        : Puthuvannam Technology Solutions
*Date           : 9th July, 2014
*Version        : 1.0
*Change History : 
*============================================================================================================*/


@isTest(seeAlldata=true)
Public Class ProjectSheetTriggerHandlerTest{

     @isTest Public static void UpdateSiteVisitTimeTest() { 
        Test.StartTest(); 
            Project_Sheet__c exProsheet;
            try{
            exprosheet=[Select id,Arrive__c,Depart__c 
                                            FROM Project_Sheet__c
                                            WHERE Fire_Extinguisher_Service_complete__c!=TRUE AND Site_Contract__c!=NULL AND Visit__c!=NULL LIMIT 1];
            
            Project_Sheet__c newProSheet=exProsheet.clone();
            insert newProSheet;        
            exProsheet.Arrive__c=system.now();
            exProsheet.Depart__c=system.now()+2;        
            update exProsheet; 
            Opportunity exOpp=[SELECT id, Site_Visit_Time__c 
                           FROM Opportunity
                           WHERE Project_Sheet__c =:exProsheet.id LIMIT 1];                                   
            //Check the testing Resuls
            if(exOpp!=NULL){
                system.assertNotEquals(exOpp.Site_Visit_Time__c,'','Site Visit Time not updated');               
            }
        }catch(exception e){
      
      }
        
        
        Test.StopTest();       
        
     }     
     
     //Test Auto Visit complete checkbox testing
     @isTest Public static void AutoVisitCompleteTest(){
        
         Project_Sheet__c exProsheet;
         try{
             exprosheet=[Select id,Fire_Extinguisher_Service_complete__c,Visit__c,Depart__c,Close_Visit__c 
                                            FROM Project_Sheet__c
                                            WHERE Fire_Extinguisher_Service_complete__c!=TRUE AND Site_Contract__c!=NULL AND Visit__c!=NULL LIMIT 1];
             exProsheet.Fire_Extinguisher_Service_complete__c=True;
             exProsheet.Close_Visit__c='Yes';
             exProsheet.Depart__c=system.today();
             exProsheet.Document_Attached__c='Testing';
             //Submit the service sheet
             Update exProsheet;
             System.assertEquals([SELECT Visit_Complete__c from Visits__c WHERE id=:exProsheet.Visit__c].Visit_Complete__c,TRUE,'Visit not completed');
         }catch(exception e){
      
          }         
      
     }   

}