objects/Opportunity/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

classes/QuoteHandler.cls
public class QuoteHandler{
     
     public void OnBeforeInsert(List<Quote> NewList){
         UpdateQouteId(NewList);
     }
     
     public void OnBeforeUpdate(List<Quote> NewList){
         UpdateQouteId(NewList);
     }
     
       public void AfterUpdate(Map<id,Quote> newMap,Map<id,Quote> oldMap){
    
        showdesc(newMap,oldMap);
        
    }
    
    
     public void showdesc(Map<id,Quote> newMap,Map<id,Quote> oldMap){
        Set<id> quoid=new Set<id>();
        List<QuoteLineItem> qliList=new List<QuoteLineItem>();
        List<QuoteLineItem> qli=new List<QuoteLineItem>();
       for(Quote quo:newMap.values()){
          if(quo.Show_Description__c!=oldMap.get(quo.id).Show_Description__c){
              quoid.add(quo.id);
          }
          }
          
         
       if(quoid.size()>0){ 
         for(QuoteLineItem ql:[Select id,Show_Description__c,Quote.Show_Description__c,QuoteId from QuoteLineItem where QuoteId  IN:quoid]){
           ql.Show_Description__c=ql.Quote.Show_Description__c;
           qli.add(ql);
         } 
       }
       if(qli.size()>0){
           update qli;
       }  

    }
    
     public void UpdateQouteId(List<Quote> NewList){
         List<Id> QuoteIds=new List<Id>();
         Map<Id,Id> ContactIds=new Map<Id,Id>();
         
         for(Quote Qo:NewList){
             if(Qo.OpportunityId!=null){
                 QuoteIds.add(Qo.OpportunityId);
             }
         }
         
         if(QuoteIds.size()>0){
             for(Opportunity opp:[select id,Name,Shipping_Contact__c from Opportunity where id IN:QuoteIds]){
                 ContactIds.put(opp.Id,opp.Shipping_Contact__c );
             }
         }
         
         for(Quote Qo:NewList){
             if(Qo.OpportunityId !=null){
                 if(ContactIds.containskey(Qo.OpportunityId)){
                     Qo.ContactId=ContactIds.get(Qo.OpportunityId);
                     system.debug('ContactId======='+Qo.ContactId);
                 }
             }
         }
     }
     
}