objects/OpportunityLineItem/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/OpportunityLineItem/fields/SalesDescription__c.field-meta.xml
<CustomField>
    <fullName>SalesDescription__c</fullName>
    <label>SalesDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/SalesOrderLineItems__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sales_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/SalesLineHandler.cls
public class SalesLineHandler{

    
   
    public void AfterInsert(Map<Id,SalesOrderLineItems__c> newMap){
    system.debug('after insert==========='+newMap);
    UpddateExtendedSales(newMap);
   
    }
    
     
    
    public void UpddateExtendedSales(Map<Id,SalesOrderLineItems__c> newMap){
    system.debug('update newMap=========='+newMap.values());
        List<Id> ProductId=new List<Id>();
        Map<Id,OpportunityLineItem > PrdsList=new Map<Id,OpportunityLineItem >();
        Set<Id> soid=new Set<Id>();
        Set<Id> oppid=new Set<Id>();
        List<SalesOrderLineItems__c> olist=new List<SalesOrderLineItems__c>();
        Map<Id,Product2> PrdMap=new Map<Id,Product2>();
        List<SalesOrderLineItems__c> olistnew=new List<SalesOrderLineItems__c>();
        
        
        
        for(SalesOrderLineItems__c NewId:newMap.values()){
            soid.add(NewId.Sales_Order__c);
            ProductId.add(NewId.Product__c);
           
        }
        
        for(Product2 prd:[select id,Extended_Sales_Description__c,Sales_Description__c from product2 where id IN:ProductId])
            PrdMap.put(prd.id,prd);
       
        for(SalesOrder__c qu:[select id,name,Opportunity__c from SalesOrder__c where id IN:soid])
            oppid.add(qu.Opportunity__c );
        
        for(OpportunityLineItem ol:[select id,name,OpportunityId,Extended_Sales_Description__c,SalesDescription__c,Product2Id from OpportunityLineItem where OpportunityId IN:oppid])
             PrdsList.put(ol.Product2Id,ol);
        
        
       for(SalesOrderLineItems__c  NewId:[SELECT Id,Sales_Description__c,Extended_Sales_Description__c,Product__c FROM SalesOrderLineItems__c  WHERE Id IN: Trigger.newMap.keySet()] ){
           
           if(PrdsList.containskey(NewId.Product__c )){
               if(NewId.Extended_Sales_Description__c==null){
                   NewId.Extended_Sales_Description__c=PrdsList.get(NewId.Product__c ).Extended_Sales_Description__c;
               }
               if(NewId.Sales_Description__c==null){
                   NewId.Sales_Description__c=PrdsList.get(NewId.Product__c ).SalesDescription__c;
               }
               olist.add(NewId);
           }else{
           
                 if(NewId.Extended_Sales_Description__c==null){
                       NewId.Extended_Sales_Description__c=PrdMap.get(NewId.Product__c).Extended_Sales_Description__c;
                 }
                 if(NewId.Sales_Description__c==null){
                       NewId.Sales_Description__c=PrdMap.get(NewId.Product__c).Sales_Description__c;
                 }
               
               olist.add(NewId);
              }
       }
       
     
       
       if(olist.size()>0){
   
       update olist;
       }
    }
    
     
}