objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Price_List_Correct__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Correct__c</fullName>
    <inlineHelpText>This is the date on which the pricing level for this customer was last checked.</inlineHelpText>
    <label>Price List Correct</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BN Zone D</fullName>
            </value>
            <value>
                <fullName>BR Zone B</fullName>
            </value>
            <value>
                <fullName>Central London (E,EC,WC,W)</fullName>
            </value>
            <value>
                <fullName>CM Zone C</fullName>
            </value>
            <value>
                <fullName>CR Zone C</fullName>
            </value>
            <value>
                <fullName>CT Zone C</fullName>
            </value>
            <value>
                <fullName>CN Zone D</fullName>
            </value>
            <value>
                <fullName>DA Zone A</fullName>
            </value>
            <value>
                <fullName>E Zone C</fullName>
            </value>
            <value>
                <fullName>GU Zone D</fullName>
            </value>
            <value>
                <fullName>HA Zone D</fullName>
            </value>
            <value>
                <fullName>HP Zone D</fullName>
            </value>
            <value>
                <fullName>IG Zone C</fullName>
            </value>
            <value>
                <fullName>KT Zone C</fullName>
            </value>
            <value>
                <fullName>ME Zone B</fullName>
            </value>
            <value>
                <fullName>MK Zone D</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PO Zone E</fullName>
            </value>
            <value>
                <fullName>RG Zone D</fullName>
            </value>
            <value>
                <fullName>RH Zone C</fullName>
            </value>
            <value>
                <fullName>RM Zone B</fullName>
            </value>
            <value>
                <fullName>SE Zone C</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>SL Zone D</fullName>
            </value>
            <value>
                <fullName>SM Zone C</fullName>
            </value>
            <value>
                <fullName>SO Zone D</fullName>
            </value>
            <value>
                <fullName>S- Scotland</fullName>
            </value>
            <value>
                <fullName>SS Zone C</fullName>
            </value>
            <value>
                <fullName>SW Zone C&amp;D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Opportunity/fields/InvoiceEmailTo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceEmailTo__c</fullName>
    <label>Invoice Email To</label>
    <type>Email</type>
</CustomField>

objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT(Account.Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Sales_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Type__c</fullName>
    <label>Sales Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Small Equipment</fullName>
            </value>
            <value>
                <fullName>Spares</fullName>
                <label>Spares &amp; Supplies</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PriceBook__c/PriceBook__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Price Book</label>
</CustomObject>

objects/Quote/fields/Increase_Version__c.field-meta.xml
<CustomField>
    <fullName>Increase_Version__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Increase Version</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>Opportunity.Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

objects/Quote/fields/Sales_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Type__c</fullName>
    <label>Sales Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Small Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Quote/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Version Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SendEmailDocTest.cls
@isTest
/*============================================================================================================
*Class Name     : SendEmailDocTest
*Description    : All the implementations related to test SendEmailDoc class.
*Company        : Merfantz Technologies Pvt Ltd
*Date           : 2nd Mar, 2020
*Version        : 2.0
*Change History : 
*Methods        : static testMethod void myTest()
                  static testMethod void myTest1()
                  static testMethod void myTest2()
                  static testMethod void myTest3()
                 
*============================================================================================================*/
public class SendEmailDocTest{
 
 static Id BasicPropsalId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Equipment Proposal').getRecordTypeId();
 Static Id LongPrjId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Project Proposal').getRecordTypeId(); 
 Static Id ServicePrjId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Service Proposal').getRecordTypeId(); 
 Static Id ShortPrjId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Short Project Proposal').getRecordTypeId(); 

/*====================================================

*Method Name     : myTest
*Description     : All the implementations related to test SendEmailDoc class.
*Arguments       : No arguments
====================================================*/   
    static testMethod void myTest(){
        PriceBook__c pre =new PriceBook__c();
        pre.Region__c='BN Zone D';
        pre.Name ='BN Zone D';
        insert pre;
        
        Pricebook2 price =new Pricebook2();
        price.name='test';
        insert price;	
        
        Account ac=new Account();
        ac.name='Test Account';
        ac.Account_Status__c='live';
        ac.Price_List_Correct__c=system.today();
        ac.Customer_type__c='Prison';
        ac.Price_Book__c=price.Id;
        ac.Region__c='BN Zone D';
        insert ac;
       
       
        
        Contact cont=new Contact();
        cont.lastname='Test Contact';
        cont.AccountId=ac.id;
        insert cont;
        
        Campaign cmp=new Campaign();
        cmp.Name='Test Cmp';
        insert cmp;
        
        Warehouse__c ware3 =new Warehouse__c();
        ware3.Name='test';	
        ware3.CurrencyIsoCode ='EUR';
        ware3.Default__c =true;
        insert ware3;
 
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.StageName = 'Prospecting';
        opp.CloseDate = system.today();
        opp.AccountId=ac.id;
        opp.Sales_Type__c='Service';
        opp.InvoiceEmailTo__c='test@gmail.com';
        opp.Campaign=cmp;
        opp.CurrencyIsoCode ='EUR';
        insert opp;
       
        Quote quo = new Quote();
        quo.Name = 'Test Quote';
        quo.RecordTypeId=BasicPropsalId;
        quo.OpportunityId = opp.Id; 
        quo.Increase_Version__c=true; 
        quo.Version_Number__c=2;      
       
        Test.startTest();
        insert quo;
        
        Test.setCurrentPage(page.EquipmentProposal);
        Blob content = Blob.valueOf('UNIT.TEST');
        
        SendEmailDoc.saveAndSend(quo.id,'save');
        SendEmailDoc.saveAndSend(quo.id,'saveandsend');
        SendEmailDoc.saveAndSend(quo.id,'cancelQuote');
        Test.stopTest();
    }
/*====================================================

*Method Name     : myTest1
*Description     : All the implementations related to test SendEmailDoc class.
*Arguments       : No arguments
====================================================*/      
    static testMethod void myTest1(){
         PriceBook__c pre =new PriceBook__c();
        pre.Region__c='BN Zone D';
        pre.Name ='BN Zone D';
        insert pre;
        
         Pricebook2 price =new Pricebook2();
        price.name='test';
        insert price;
    
        Account ac=new Account();
        ac.name='Test Account';
        ac.Account_Status__c='live';
        ac.Customer_type__c='others';
        ac.Price_Book__c=price.Id;
          ac.Region__c='BN Zone D';
        insert ac;
        
        Contact cont=new Contact();
        cont.lastname='Test Contact';
        cont.AccountId=ac.id;
        insert cont;
        
        Campaign cmp=new Campaign();
        cmp.Name='Test Cmp';
        insert cmp;
        
        Warehouse__c ware2 =new Warehouse__c();
        ware2.Name='test';	
        ware2.CurrencyIsoCode ='EUR';
        ware2.Default__c =true;
        insert ware2;
 
 
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'Test Opportunity';
        opp1.StageName = 'Prospecting';
        opp1.CloseDate = system.today();
        opp1.AccountId=ac.id;
        opp1.Sales_Type__c='Service';
        opp1.InvoiceEmailTo__c='test@gmail.com';
        opp1.Campaign=cmp;
        opp1.CurrencyIsoCode ='EUR';
        insert opp1;
       
        Quote quo1 = new Quote();
        quo1.Name = 'Test Quote';
        quo1.RecordTypeId=LongPrjId;
        quo1.OpportunityId = opp1.Id; 
        quo1.Increase_Version__c=true; 
        quo1.Version_Number__c=2;        
       
        Test.startTest();
        insert quo1;
        
        Test.setCurrentPage(page.ProjectProposal);
        Blob content = Blob.valueOf('UNIT.TEST');
        
        SendEmailDoc.saveAndSend(quo1.id,'save');
        SendEmailDoc.saveAndSend(quo1.id,'saveandsend');
        SendEmailDoc.saveAndSend(quo1.id,'cancelQuote');
        Test.stopTest();
    }
/*====================================================

*Method Name     : myTest2
*Description     : All the implementations related to test SendEmailDoc class.
*Arguments       : No arguments
====================================================*/      
    static testMethod void myTest2(){
         PriceBook__c pre =new PriceBook__c();
        pre.Region__c='BN Zone D';
        pre.Name ='BN Zone D';
        insert pre;
        
       Pricebook2 price =new Pricebook2();
        price.name='test';
        insert price;
    
        Account ac=new Account();
        ac.name='Test Account';
        ac.Account_Status__c='live';
        ac.Customer_type__c='others';
        ac.Price_Book__c=price.Id;
        ac.Region__c='BN Zone D';
        insert ac;
        
        Contact cont=new Contact();
        cont.lastname='Test Contact';
        cont.AccountId=ac.id;
        insert cont;
        
        Campaign cmp=new Campaign();
        cmp.Name='Test Cmp';
        insert cmp;
        
        Warehouse__c ware1 =new Warehouse__c();
        ware1.Name='test';	
        ware1.CurrencyIsoCode ='EUR';
        ware1.Default__c =true;
        insert ware1;
 
 
        Opportunity opp2 = new Opportunity();
        opp2.Name = 'Test Opportunity';
        opp2.StageName = 'Prospecting';
        opp2.CloseDate = system.today();
        opp2.AccountId=ac.id;
        opp2.Sales_Type__c='Service';
        opp2.InvoiceEmailTo__c='test@gmail.com';
        opp2.Campaign=cmp;
        opp2.CurrencyIsoCode ='EUR';
        insert opp2;
       
        Quote quo2 = new Quote();
        quo2.Name = 'Test Quote';
        quo2.RecordTypeId=ServicePrjId;
        quo2.OpportunityId = opp2.Id;  
        quo2.Increase_Version__c=true; 
        quo2.Version_Number__c=2;       
       
        Test.startTest();
        insert quo2;
        
        
        Test.setCurrentPage(page.ServiceProposal);
        Blob content = Blob.valueOf('UNIT.TEST');
        
        SendEmailDoc.saveAndSend(quo2.id,'save');
        SendEmailDoc.saveAndSend(quo2.id,'saveandsend');
        SendEmailDoc.saveAndSend(quo2.id,'cancelQuote');
        Test.stopTest();
    }
/*====================================================

*Method Name     : myTest3
*Description     : All the implementations related to test SendEmailDoc class.
*Arguments       : No arguments
====================================================*/      
    static testMethod void myTest3(){
         PriceBook__c pre =new PriceBook__c();
        pre.Region__c='BN Zone D';
        pre.Name ='BN Zone D';
        insert pre;
        
         Pricebook2 price =new Pricebook2();
        price.name='test';
        insert price;
    
        Account ac=new Account();
        ac.name='Test Account';
        ac.Account_Status__c='live';
        ac.Customer_type__c='others';
        ac.Price_Book__c=price.Id;
          ac.Region__c='BN Zone D';
        insert ac;
        
        Contact cont=new Contact();
        cont.lastname='Test Contact';
        cont.AccountId=ac.id;
        insert cont;
        
        Campaign cmp=new Campaign();
        cmp.Name='Test Cmp';
        insert cmp;
      
        Warehouse__c ware =new Warehouse__c();
        ware.Name='test';	
        ware.CurrencyIsoCode ='EUR';
        ware.Default__c =true;
        insert ware;
 
        Opportunity opp3 = new Opportunity();
        opp3.Name = 'Test Opportunity';
        opp3.StageName = 'Prospecting';
        opp3.CloseDate = system.today();
        opp3.AccountId=ac.id;
        opp3.Sales_Type__c='Service';
        opp3.InvoiceEmailTo__c='test@gmail.com';
        opp3.Campaign=cmp;
        opp3.CurrencyIsoCode ='EUR';
        insert opp3;
       
        Quote quo3 = new Quote();
        quo3.Name = 'Test Quote';
        quo3.RecordTypeId=ShortPrjId;
        quo3.OpportunityId = opp3.Id; 
        quo3.Increase_Version__c=true;  
        quo3.Version_Number__c=2;       
       
        Test.startTest();
        insert quo3;
        
        Test.setCurrentPage(page.ShortProjectProposal);
        Blob content = Blob.valueOf('UNIT.TEST');
        
        SendEmailDoc.saveAndSend(quo3.id,'save');
        SendEmailDoc.saveAndSend(quo3.id,'saveandsend');
        SendEmailDoc.saveAndSend(quo3.id,'cancelQuote');
        Test.stopTest();
    }
}