objects/Account/fields/Account_Notes__c.field-meta.xml
<CustomField>
    <fullName>Account_Notes__c</fullName>
    <inlineHelpText>This fields holds notes for accounts to consider on this parent and all sites.</inlineHelpText>
    <label>Account Notes</label>
    <type>TextArea</type>
</CustomField>

objects/Account/fields/All_Site_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>All_Site_Total_Amount__c</fullName>
    <label>Total customer spend last 12 months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Account/fields/Check_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_Status__c</fullName>
    <description>Check Status</description>
    <label>Check Status</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Supplier Contact)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Invoice_Layout__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Layout__c</fullName>
    <label>Invoice Layout</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Invoiced_in_last_12_months__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_in_last_12_months__c</fullName>
    <description>(StageEQUALSClosed Won, Sent) AND (Invoice DateGREATER OR EQUAL01/01/2018) AND (Invoice DateLESS OR EQUAL31/12/2018)</description>
    <label>Invoiced in last 12 months</label>
    <summarizedField>Opportunity.Total_Sales_Price__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won, Sent</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Invoice_Date__c</field>
        <operation>greaterOrEqual</operation>
        <value>12/1/2021</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Invoice_Date__c</field>
        <operation>lessOrEqual</operation>
        <value>11/30/2022</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Price_List_Correct__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Correct__c</fullName>
    <inlineHelpText>This is the date on which the pricing level for this customer was last checked.</inlineHelpText>
    <label>Price List Correct</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BN Zone D</fullName>
            </value>
            <value>
                <fullName>BR Zone B</fullName>
            </value>
            <value>
                <fullName>Central London (E,EC,WC,W)</fullName>
            </value>
            <value>
                <fullName>CM Zone C</fullName>
            </value>
            <value>
                <fullName>CR Zone C</fullName>
            </value>
            <value>
                <fullName>CT Zone C</fullName>
            </value>
            <value>
                <fullName>CN Zone D</fullName>
            </value>
            <value>
                <fullName>DA Zone A</fullName>
            </value>
            <value>
                <fullName>E Zone C</fullName>
            </value>
            <value>
                <fullName>GU Zone D</fullName>
            </value>
            <value>
                <fullName>HA Zone D</fullName>
            </value>
            <value>
                <fullName>HP Zone D</fullName>
            </value>
            <value>
                <fullName>IG Zone C</fullName>
            </value>
            <value>
                <fullName>KT Zone C</fullName>
            </value>
            <value>
                <fullName>ME Zone B</fullName>
            </value>
            <value>
                <fullName>MK Zone D</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PO Zone E</fullName>
            </value>
            <value>
                <fullName>RG Zone D</fullName>
            </value>
            <value>
                <fullName>RH Zone C</fullName>
            </value>
            <value>
                <fullName>RM Zone B</fullName>
            </value>
            <value>
                <fullName>SE Zone C</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>SL Zone D</fullName>
            </value>
            <value>
                <fullName>SM Zone C</fullName>
            </value>
            <value>
                <fullName>SO Zone D</fullName>
            </value>
            <value>
                <fullName>S- Scotland</fullName>
            </value>
            <value>
                <fullName>SS Zone C</fullName>
            </value>
            <value>
                <fullName>SW Zone C&amp;D</fullName>
            </value>
            <value>
                <fullName>TW Zone D</fullName>
            </value>
            <value>
                <fullName>UB Zone D</fullName>
            </value>
            <value>
                <fullName>WF (NHS)</fullName>
            </value>
            <value>
                <fullName>AL Zone D</fullName>
            </value>
            <value>
                <fullName>CO Zone D</fullName>
            </value>
            <value>
                <fullName>IP Zone D</fullName>
            </value>
            <value>
                <fullName>LU Zone D</fullName>
            </value>
            <value>
                <fullName>NW and N Zone D</fullName>
            </value>
            <value>
                <fullName>WD Zone D</fullName>
            </value>
            <value>
                <fullName>EN Zone C</fullName>
            </value>
            <value>
                <fullName>OX Zone D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/TEST_Service_Contact__c.field-meta.xml
<CustomField>
    <fullName>TEST_Service_Contact__c</fullName>
    <label>Service Contact</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

objects/Opportunity/fields/Check_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_Status__c</fullName>
    <formula>&quot;PriceList: &quot;&amp;IF(TEXT(Account.Price_List_Correct__c) &lt;&gt; &quot;&quot; , &quot;Yes&quot;, &quot;No &quot; ) &amp;&quot; SageCode: &quot;&amp;IF ( Account.Accounts_Checked_Sage_Code__c  , &quot;Yes&quot; , &quot;No &quot; )&amp;
 &quot;  AccAddOK : &quot; &amp;IF(Account.Accounts_Checked_Address__c , &quot;Yes&quot;, &quot;No &quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check Status</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT(Account.Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

objects/PriceBook__c/PriceBook__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Price Book</label>
</CustomObject>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Service Contact</label>
    <length>199</length>
    <type>Text</type>
</CustomField>

objects/SiteContracts__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SupplierProduct__c/SupplierProduct__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <displayFormat>SPN-{000000}</displayFormat>
        <label>Supplier Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SupplierProduct__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/AccountTriggerHandler.cls
/*============================================================================================================
*Class Name     : AccountTriggerHandler
*Description    : All the implementations related to Opportunity Triggers should be handled here
*Company        : Puthuvannam Technology Solutions
*Date           : 23th May, 2014
*Version        : 1.0
*Change History : Initial Trigger Handler
*Methods        : public void OnAfterUpdate(Map<id,Account> accountNewMap)
                  Private void UpdateServiceContactField(map<id,Account> accMap)
                  Private void updateAccountCheckStatusField(List<Account> newList)
                 
*============================================================================================================*/

public class AccountTriggerHandler{


/*====================================================

*Method Name     : OnAfterUpdate
*Description     : Handle the after update operation
*Arguments       : new map list
====================================================*/

    public void OnAfterUpdate(Map<id,Account> accountNewMap,Map<id,Account> accountOldMap){
    system.debug('<<<accountNewMap123>>'+accountNewMap); 
        if(RecursiveHandler.runOnce()){
                //Call UpdatePriceListdate Class
                UpdatePriceListDate(accountNewMap.values(),accountOldMap);
                
            }
        if(RecursiveHandler.runACC_USCTOnce()){
             UpdateServiceContactField(accountNewMap,accountOldMap);
         }
         if(RecursiveHandler.runOnce1()){
                //Call AccountCheckStatusFile Method   
                updateAccountCheckStatusField(accountNewMap,accountOldMap);
                CurrencyType(accountNewMap,accountOldMap); 
           }  
 
    }
    public void OnBeforeInsert(List<Account> NewList){
     UpdatePriceBookBefore(NewList);
    
    }
 
    
    public void OnBeforeUpdate(Map<id,Account> NewMap,Map<id,Account> OldMap){
     UpdatePriceBook(NewMap);
    }
    

/*====================================================
*Method Name     : CurrencyType
*Description     : Update Currency type for supplier product
*Arguments       : new Map list
====================================================*/   

    Public void CurrencyType(Map<id,Account> Newmap,Map<id,Account> Oldmap){
      List<Id> accid=new List<Id>();
      List<SupplierProduct__c > sprd=new List<SupplierProduct__c >();
      for(Account acc:Newmap.values()){
        if(acc.CurrencyIsoCode!=Oldmap.get(acc.id).CurrencyIsoCode){
           accid.add(acc.id);
        }
      }
      if(accid.size()>0){
           List<SupplierProduct__c > supplier=new List<SupplierProduct__c >([Select id,CurrencyIsoCode,Supplier__c,Supplier__r.CurrencyIsoCode from SupplierProduct__c where Supplier__c IN:accid]);
          
           for(SupplierProduct__c sp:supplier){
              sp.CurrencyIsoCode=sp.Supplier__r.CurrencyIsoCode;
              sprd.add(sp);
           }
      }
      if(sprd.size()>0){
         update sprd;
      }
    }

 
/*====================================================
*Method Name     : UpdatePriceBook
*Description     : Update pricebook of Account
*Arguments       : new Map list
====================================================*/    
 
    Private void UpdatePriceBook(Map<id,Account> NewMap){
 
    for(Account ac:NewMap.values()){
    
      if(PriceBook__c.getInstance('BN Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('BN Zone D').Id__c;
       }

       else if(PriceBook__c.getInstance('AL Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('AL Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('BR Zone B').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('BR Zone B').Id__c;
       }
       
       else if(PriceBook__c.getInstance('Central London (E,EC,WC,W)').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('Central London (E,EC,WC,W)').Id__c;
       }
       
       else if(PriceBook__c.getInstance('CM Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('CM Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('CR Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('CR Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('CT Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('CT Zone C').Id__c;
       }
       
       else if (PriceBook__c.getInstance('CN Zone D').Region__c == ac.Region__c) { 
       ac.Price_Book__c = PriceBook__c.getInstance('CN Zone D').Id__c; 
        } 
       
       else if(PriceBook__c.getInstance('CO Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('CO Zone D').Id__c;
       }

       else if(PriceBook__c.getInstance('DA Zone A').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('DA Zone A').Id__c;
       }
       
       else if(PriceBook__c.getInstance('EN Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('EN Zone C').Id__c;
       }

       else if(PriceBook__c.getInstance('GU Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('GU Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('HA Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('HA Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('HP Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('HP Zone D').Id__c;
       }
       
       
       else if(PriceBook__c.getInstance('IG Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('IG Zone C').Id__c;
       }

       else if(PriceBook__c.getInstance('IP Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('IP Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('KT Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('KT Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('LU Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('LU Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('ME Zone B').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('ME Zone B').Id__c;
       }
       
       else if(PriceBook__c.getInstance('MK Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('MK Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('NL').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('NL').Id__c;
       }
       
       
       else if(PriceBook__c.getInstance('North London (NW,N,EN)').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('North London (NW,N,EN)').Id__c;
       }
       
       else if(PriceBook__c.getInstance('NW and N Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('NW and N Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('OX Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('OX Zone D').Id__c;
       }

       else if(PriceBook__c.getInstance('Other').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('Other').Id__c;
       }
       
       else if(PriceBook__c.getInstance('PO Zone E').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('PO Zone E').Id__c;
       }
       
       else if(PriceBook__c.getInstance('RG Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('RG Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('RH Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('RH Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('RM Zone B').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('RM Zone B').Id__c;
       }
       
       else if(PriceBook__c.getInstance('S- Scotland').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('S- Scotland').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SE Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SE Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SG').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SG').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SL Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SL Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SM Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SM Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SO Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SO Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SS Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SS Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SW Zone C&D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SW Zone C&D').Id__c;
       }
       
       
       else if(PriceBook__c.getInstance('TN Zone B & C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('TN Zone B & C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('TW Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('TW Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('UB Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('UB Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('WF (NHS)').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('WF (NHS)').Id__c;
       }

       else if(PriceBook__c.getInstance('WD Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('WD Zone D').Id__c;
       }

       else if(PriceBook__c.getInstance('E Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('E Zone C').Id__c;
       }

       else{
       ac.Price_Book__c=PriceBook__c.getInstance('Standard').Id__c;
       }
      
       system.debug('<<<updated region>>>>>>>>>'+ac.Region__c+ 'updated  pricebook ============='+ac.Price_Book__c); 
    }
     
  }  


/*====================================================
*Method Name     : UpdatePriceBookBefore
*Description     : Update pricebook of Account
*Arguments       : new Account list
====================================================*/    
     Private void UpdatePriceBookBefore(List<Account> NewMap){
    
    for(Account ac:NewMap){
       
       if(!Test.isRunningTest() == false){ 
      if(PriceBook__c.getInstance('BN Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('BN Zone D').Id__c;
       }

       else if(PriceBook__c.getInstance('AL Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('AL Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('BR Zone B').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('BR Zone B').Id__c;
       }
       
       else if(PriceBook__c.getInstance('Central London (E,EC,WC,W)').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('Central London (E,EC,WC,W)').Id__c;
       }
       
       else if(PriceBook__c.getInstance('CM Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('CM Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('CR Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('CR Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('CT Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('CT Zone C').Id__c;
       }
       

       else if (PriceBook__c.getInstance('CN Zone D').Region__c == ac.Region__c) { 
       ac.Price_Book__c = PriceBook__c.getInstance('CN Zone D').Id__c; 
       } 
  
       else if(PriceBook__c.getInstance('CO Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('CO Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('DA Zone A').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('DA Zone A').Id__c;
       }
       
       else if(PriceBook__c.getInstance('EN Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('EN Zone C').Id__c;
       }

       else if(PriceBook__c.getInstance('GU Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('GU Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('HA Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('HA Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('HP Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('HP Zone D').Id__c;
       }
       
       
       else if(PriceBook__c.getInstance('IG Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('IG Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('IP Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('IP Zone D').Id__c;
       }       

       else if(PriceBook__c.getInstance('KT Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('KT Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('LU Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('LU Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('ME Zone B').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('ME Zone B').Id__c;
       }
       
       else if(PriceBook__c.getInstance('MK Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('MK Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('NL').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('NL').Id__c;
       }
       
       
       else if(PriceBook__c.getInstance('North London (NW,N,EN)').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('North London (NW,N,EN)').Id__c;
       }
       
       else if(PriceBook__c.getInstance('NW and N Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('NW and N Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('OX Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('OX Zone D').Id__c;
       }

       else if(PriceBook__c.getInstance('Other').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('Other').Id__c;
       }
       
       else if(PriceBook__c.getInstance('PO Zone E').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('PO Zone E').Id__c;
       }
       
       else if(PriceBook__c.getInstance('RG Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('RG Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('RH Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('RH Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('RM Zone B').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('RM Zone B').Id__c;
       }
       
       else if(PriceBook__c.getInstance('S- Scotland').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('S- Scotland').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SE Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SE Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SG').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SG').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SL Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SL Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SM Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SM Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SO Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SO Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SS Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SS Zone C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('SW Zone C&D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('SW Zone C&D').Id__c;
       }
       
        else if(PriceBook__c.getInstance('TN Zone B & C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('TN Zone B & C').Id__c;
       }
       
       else if(PriceBook__c.getInstance('TW Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('TW Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('UB Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('UB Zone D').Id__c;
       }
       
       else if(PriceBook__c.getInstance('WF (NHS)').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('WF (NHS)').Id__c;
       }

       else if(PriceBook__c.getInstance('WD Zone D').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('WD Zone D').Id__c;
       }
		
	   else if(PriceBook__c.getInstance('E Zone C').Region__c==ac.Region__c){
       ac.Price_Book__c=PriceBook__c.getInstance('E Zone C').Id__c;
       }
    
     
       else{
       ac.Price_Book__c=PriceBook__c.getInstance('Standard').Id__c;
       }
        }else{
           ac.Price_Book__c=null;
       } 
      
       system.debug('<<<updated region>>>>>>>>>'+ac.Region__c+ 'updated  pricebook ============='+ac.Price_Book__c); 
    }
     
  } 


/*====================================================
*Method Name     : UpdateAmsecLogo
*Description     : Update the Logo to Invoice.
*Arguments       : new Account list
====================================================*/    
/*
    Private void UpdateAmsecLogo(map<id,Account> accMap){
    system.debug('<<<beforeaccMap>>'+accMap); 
    List<string> accIds = new List<string>();
    List<opportunity> OpportunityLists = new List<opportunity>();
    List<opportunity> UpdateOppLists = new List<opportunity>();
    
    
    for(Account acc:accMap.values()){
      if(acc.Invoice_Layout__c == 'Amsec'){
        accIds.add(acc.id);
      }
    }
    system.debug('<<<beforaccIds>>'+accIds); 
    
    OpportunityLists= [Select id,AmsecAvailable__c,AccountId
                                      FROM opportunity 
                                      where Accountid IN :accIds];
                                      
    system.debug('<<<beforopportunityLists>>'+opportunityLists.size());                                
    for(opportunity opp:opportunityLists){
           opp.AmsecAvailable__c = true;
           system.debug('<<<opp:opportunityLists>>'+opp.name);
           UpdateOppLists.add(opp);
    }
    
    If(UpdateOppLists != null){
     system.debug('<<<UpdateOppLists >>'+UpdateOppLists.size());   
       update UpdateOppLists;
    }
    
    } 
*/
   
/*====================================================
*Method Name     : UpdateServiceContactField
*Description     : Update the Service Contact Filed.
*Arguments       : new Account list
====================================================*/    

    Private void UpdateServiceContactField(map<id,Account> accMap,Map<id,Account> accountOldMap){
        //Variable Declaration
        List<id> accountIds=new List<id>();
        for(Account acc:accMap.values()){
            accountIds.add(acc.Id);
        }
        //to get a list of SiteContracts 
        List<SiteContracts__c> siteContractList=[select id,site__c,Contact__c from SiteContracts__c where Site__c IN:accountIds];
        for(SiteContracts__c  site :siteContractList){
            //assign Account service contact Field to Site contract Service Contact Field
            site.Contact__c =accMap.get(site.site__c).TEST_Service_Contact__c;
        }
        update siteContractList;    //update the SiteContracts
    }
    
/*====================================================
*Method Name     : updateAccountCheckStatusField
*Description     : Update the Check Filed.
*Arguments       : new Account list
====================================================*/    
    Private void updateAccountCheckStatusField(map<id,Account> newList,Map<id,Account> accountOldMap){
        //Variable Declaration
        List<string> accountids = new List<string>();
        List<AggregateResult> aggList = New List<AggregateResult> ();
        List<opportunity> reqOpplists = new List<opportunity>();
        List<string> OppIds = new List<String>();        
        
        Map<DateTime,id> AccMap=new Map<DateTime,id>(); 
         
        aggList = [SELECT AccountId,max(CreatedDate ) 
                   FROM opportunity 
                   WHERE  AccountId IN :newList.keyset() 
                   group by AccountId];
        for (AggregateResult ar : aggList)  {
            AccMap.put((DateTime)ar.get('expr0'),(id)ar.get('AccountId'));
        }
        List<opportunity> opplists = [Select id,Check_Status__c,CreatedDate,AccountId
                                      FROM opportunity 
                                      where Accountid IN :newList.Keyset()];
        system.debug('==aggList=='+aggList+'===='+AccMap+'===='+AccMap.values());
        
        for(opportunity opp:opplists){
            id maxOppDate  = AccMap.get(opp.createdDate);
            system.debug('==maxOppDate=='+maxOppDate);
            if(maxOppDate != Null){
                system.debug('==opp=='+opp.id+'===check'+opp.Check_Status__c);
                OppIds.add(opp.id);
            }
        }
        reqOpplists = [Select id,Check_Status__c,CreatedDate,AccountId
                       FROM opportunity where id IN :OppIds];
        List<account> AccountList = [Select id,Check_Status__c 
                                     from account 
                                     where id in : newList.Keyset()];
        FOR(Account acc:AccountList){
            FOR(Opportunity opp:reqOpplists){
                if(acc.id == opp.accountid){
                    acc.Check_Status__c = opp.Check_Status__c; 
                }
            }
        }
        //Update the account
        update AccountList;
    }
    
    Private void UpdatePriceListDate(List<Account> newAccounts,Map<id,Account> accountOldMap){
        //Create the instance for the Account
        List<Account> ChildRecords = new List<Account>();
        //Variable Declaration
        string CurrentAccountNotes;
        string CurrentParentId; 
        date PrilistCorrectdate;
         for (Account currentrecord : newAccounts) {
             //Getting the parentid, PriceListDate and Account notes
             CurrentParentId = currentrecord.id;
             PrilistCorrectdate = currentrecord.Price_List_Correct__c;
             CurrentAccountNotes =currentrecord.Account_Notes__c; 
         }
        
        ChildRecords = [Select id,Parentid,Price_List_Correct__c,Account_Notes__c from account where parentid = :CurrentParentId];
       
         for (Account childrecord : ChildRecords) {
             //Update the PriceList Date to Childrecord
             childrecord.Price_List_Correct__c = PrilistCorrectdate;
             //Update the Account Notes to Childrecord
             childrecord.Account_Notes__c = CurrentAccountNotes ;
            } 
        //Updata the Child Records
        update ChildRecords;
    }
/*====================================================
*Method Name     : 
*Description     : Update the amount from all site to customer.
*Arguments       : new Account list
====================================================*/  
Public void Updatetotalamount(map<id,Account> AcctNewMap,Map<id,Account> AcctOldMap){
       List<AggregateResult> aggList = New List<AggregateResult>();
       Set<Id> setParentAccId = new Set<Id>();
  //  Map<id,Account> AcctNewMap = [select Id,name,ParentId from Account];
     If(AcctNewMap != Null){
         
        for(Account acc: AcctNewMap.values()) {
            if(acc.ParentId!=null)
              setParentAccId.add(acc.ParentId); 
    
             system.debug('setParentAccId==[562]==>' + setParentAccId);  
            }
          }
            else{
                   for(Account acc: AcctOldMap.values()) {
            if(acc.ParentId!=null)
              setParentAccId.add(acc.ParentId);
                   }
                 }
     
      List<Account> accList = new  List<Account>();{
      system.debug('accList==[570]==>' + accList);  
  aggList=[Select ParentId, Sum(Invoiced_in_last_12_months__c)Total 
                                 from Account 
                                 where ParentId IN : setParentAccId
                                 group by ParentId];
          
      for(AggregateResult aRes: aggList){
                                   
      accList.add(new Account(Id = (Id)aRes.get('ParentId'), All_Site_Total_Amount__c = (Decimal)aRes.get('Total')));
     //  accList.add(new Account(Id = (Id)aRes.get('ParentId'), All_Site_Total_Amount__c = (Decimal)aRes.get('Total')));                              
      system.debug('aRes==[577]==>'+ aRes);  
                                
        } 
    
  try{	
      if(accList.size() > 0)
      {
       Update accList;
      } 
     }catch(DmlException de){
         System.debug(de);
        }
     } 
      
 }
}