objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <label>AM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DORMANT</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>LIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Supplier Contact)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/Active_User__c.field-meta.xml
<CustomField>
    <fullName>Active_User__c</fullName>
    <inlineHelpText>If this is Yes, the technician is still employed. If No, the technician has left.</inlineHelpText>
    <label>Active User</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/fields/Engineer_ID__c.field-meta.xml
<CustomField>
    <fullName>Engineer_ID__c</fullName>
    <label>Technician ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Engineer__c/fields/Technician_Group__c.field-meta.xml
<CustomField>
    <fullName>Technician_Group__c</fullName>
    <inlineHelpText>Please enter the name of the scheduler for this Technician.</inlineHelpText>
    <label>Technician Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angie Davey</fullName>
            </value>
            <value>
                <fullName>Joel Bidmead</fullName>
            </value>
            <value>
                <fullName>Jo Fyffe</fullName>
            </value>
            <value>
                <fullName>Mel Jones</fullName>
            </value>
            <value>
                <fullName>Nigel Welch</fullName>
            </value>
            <value>
                <fullName>Samantha Cavinder</fullName>
            </value>
            <value>
                <fullName>Sharon Standen</fullName>
            </value>
            <value>
                <fullName>Tim Mann</fullName>
            </value>
            <value>
                <fullName>Tracey Coles</fullName>
            </value>
            <value>
                <fullName>Viv Stuchbery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <inlineHelpText>If changing to Dormant, please setup a view to mass cancel the open visits. Use this field to stop Visits if on hold - a red warning appears on the visit booking status.</inlineHelpText>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Service Contact</label>
    <length>199</length>
    <type>Text</type>
</CustomField>

objects/SiteContracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts (Customer)</relationshipLabel>
    <relationshipName>Site_Contract</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SiteContracts__c/fields/Due__c.field-meta.xml
<CustomField>
    <fullName>Due__c</fullName>
    <inlineHelpText>This is the first month on which a visit/service was/is due on this site. This is used by the salesforce trigger to populate a visit onto the site contract, when the Visit Reschedule is set to On Schedule. On Schedule takes its schedule from this field.</inlineHelpText>
    <label>Month Due</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JAN</fullName>
            </value>
            <value>
                <fullName>FEB</fullName>
            </value>
            <value>
                <fullName>MAR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>MAY</fullName>
            </value>
            <value>
                <fullName>JUN</fullName>
            </value>
            <value>
                <fullName>JUL</fullName>
            </value>
            <value>
                <fullName>AUG</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
            <value>
                <fullName>OCT</fullName>
            </value>
            <value>
                <fullName>NOV</fullName>
            </value>
            <value>
                <fullName>DEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Number_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Services__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Number of Visits per year, the Visits auto reschedule, based on this field.</inlineHelpText>
    <label>Number of Services</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Visit_Rescheduling__c.field-meta.xml
<CustomField>
    <fullName>Visit_Rescheduling__c</fullName>
    <inlineHelpText>On Schedule = When visit completes, new visit is planned based on Month Due field.
On Visit = When visit completes, new visit is planned based on visit date.
Pre-Scheduled = User has scheduled all visits so no revisit is booked. Service Maintains these.</inlineHelpText>
    <label>Visit Rescheduling</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Schedule</fullName>
            </value>
            <value>
                <fullName>On Visit</fullName>
            </value>
            <value>
                <fullName>Pre-Scheduled</fullName>
                <default>true</default>
                <label>Pre-Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Populated by the Site Contract.</inlineHelpText>
    <label>Shipping Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/Technician_Group__c.field-meta.xml
<CustomField>
    <fullName>Technician_Group__c</fullName>
    <formula>TEXT ( Engineer2__r.Technician_Group__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Technician Group</label>
    <type>Text</type>
</CustomField>

classes/MultipleTechnicianCalendarHandler_Test.cls
@isTest(SeeAllData=true)
private class MultipleTechnicianCalendarHandler_Test {
    static testMethod void CallCalendar() {
        
         Contact cc = new Contact();
         cc.LastName='Test';
         //cc.CurrencyIsoCode='';
         cc.Description='Description';
         insert cc;
        
        
         Account newAccount =new Account();
         newAccount.Name='Test Account';
         newAccount.Account_Status__c='Live';
         newAccount.Customer_type__c='OPG';
         newAccount.Contact__c=cc.Id;
         insert newAccount;
         
         
         Account newAccountH =new Account();
         newAccountH.Name='Holidays';
         newAccountH.Account_Status__c='Live';
         newAccountH.Customer_type__c='OPG';	
         newAccountH.Contact__c=cc.Id;
         insert newAccountH;
         
     
         Engineer__c tmp_technician=new Engineer__c();
         tmp_technician.Name='Test Engineer';
         tmp_technician.Active_User__c='Yes';
         tmp_technician.Technician_Group__c = 'Mel Jones';
         tmp_technician.Mobile_Phone__c='99999 999999';
         tmp_technician.Target__c  =1;
         tmp_technician.Engineer_ID__c = 'test';
         insert tmp_technician;        
         
         
         SiteContracts__c t_siteContract= new SiteContracts__c();
         t_siteContract.site__c=newAccount.id;
         t_siteContract.Number_of_Services__c = 1;
         t_siteContract.Number_of_Services__c=1;
         t_siteContract.Visit_Rescheduling__c='On Schedule';
         t_siteContract.Due__c='Test';
         t_siteContract.AM_Status__c='Live';
         t_siteContract.Customer__c=newAccount.id;
         insert t_siteContract;
         
         SiteContracts__c t_siteContractH= new SiteContracts__c();
         t_siteContractH.site__c=newAccountH.id;
         t_siteContractH.Number_of_Services__c = 1;
         t_siteContractH.Number_of_Services__c=1;
         t_siteContractH.Visit_Rescheduling__c='On Schedule';
         t_siteContractH.Due__c='Test';
         t_siteContractH.AM_Status__c='Live';
         t_siteContractH.Customer__c=newAccountH.id;
         insert t_siteContractH;
         
         Visits__c t_visit= new Visits__c();
         t_visit.site__c=newAccount.id;
         t_visit.site_Contract__c=t_siteContract.id;
         t_visit.Actual_Service_Date__c = date.today();
         t_visit.Engineer2__c=tmp_technician.id;
         t_visit.Visit_Type__c='Small Works';
         t_visit.Booked_with_Customers__c='Booked Via Schedule';
         t_visit.Order_Value__c=10;
         insert t_visit;
         
         Visits__c t_visit1= new Visits__c();
         t_visit1.site__c=newAccount.id;
         t_visit1.site_Contract__c=t_siteContract.id;
         t_visit1.Actual_Service_Date__c = date.today();
         t_visit1.Engineer2__c=tmp_technician.id;
         t_visit1.Visit_Type__c ='Projects';
         t_visit1.Booked_with_Customers__c='Yes';
         t_visit1.Actual_Service_Date__c = date.today();
         t_visit1.Order_Value__c=10;
        
         
         Visits__c t_visit2= new Visits__c();
         t_visit2.site__c=newAccountH.id;
         t_visit2.site_Contract__c=t_siteContractH.id;
         t_visit2.Actual_Service_Date__c = date.today();
         t_visit2.Engineer2__c=tmp_technician.id;
         t_visit2.Visit_Type__c ='Holiday';
         t_visit2.Booked_with_Customers__c='Waiting P/O';
         
         Visits__c t_visit3= new Visits__c();
         t_visit3.site__c=newAccountH.id;
         t_visit3.site_Contract__c=t_siteContractH.id;
         t_visit3.Actual_Service_Date__c = date.today();
         t_visit3.Engineer2__c=tmp_technician.id;
         t_visit3.X2nd_Technician__c=tmp_technician.id;
         t_visit3.Visit_Type__c ='Holiday';
         
         Visits__c t_visit4= new Visits__c();
         t_visit4.site__c=newAccountH.id;
         t_visit4.site_Contract__c=t_siteContractH.id;
         t_visit4.Actual_Service_Date__c = date.today();
         t_visit4.Engineer2__c=tmp_technician.id;
         t_visit4.Visit_Type__c ='Holiday';
         t_visit4.Booked_with_Customers__c='Yes';
         t_visit4.Actual_Service_Date__c = Date.valueof('2015-09-01');
         insert t_visit4;    
         
         Visits__c t_visit5= new Visits__c();
         t_visit5.site__c=newAccountH.id;
         t_visit5.site_Contract__c=t_siteContractH.id;
         t_visit5.Actual_Service_Date__c = date.today();
         t_visit5.Engineer2__c=tmp_technician.id;
         t_visit5.Visit_Type__c ='Holiday';
         
         Visits__c t_visit6= new Visits__c();
         t_visit6.site__c=newAccount.id;
         t_visit6.site_Contract__c=t_siteContract.id;
         t_visit6.Actual_Service_Date__c = date.today();
         t_visit6.Engineer2__c=tmp_technician.id;
         t_visit6.Visit_Type__c ='Projects';
         t_visit6.Order_Value__c=10;
         
         Visits__c t_visit7= new Visits__c();
         t_visit7.site__c=newAccount.id;
         t_visit7.site_Contract__c=t_siteContract.id;
         t_visit7.Actual_Service_Date__c = date.today();
         t_visit7.Engineer2__c=tmp_technician.id;
         t_visit7.Visit_Type__c ='Small Works';
         t_visit7.Order_Value__c=10;
         
         Visits__c t_visit8= new Visits__c();
         t_visit8.site__c=newAccount.id;
         t_visit8.site_Contract__c=t_siteContract.id;
         t_visit8.Actual_Service_Date__c = date.today();
         t_visit8.Engineer2__c=tmp_technician.id;
         t_visit8.Visit_Complete__c=true;
         t_visit8.Service_Sheet_Number__c='1000';
         t_visit8.Order_Value__c=10;
       
         
         
          Visits__c t_visit9= new Visits__c();
         t_visit9.site__c=newAccount.id;
         t_visit9.site_Contract__c=t_siteContract.id;
         t_visit9.Actual_Service_Date__c = date.today();
         t_visit9.Engineer2__c=tmp_technician.id;
         t_visit9.Visit_Type__c ='no-work';
          
      /*  Technician_On_Call_Period__c TechOnCalPeriod= new Technician_On_Call_Period__c();
         TechOnCalPeriod.Call_Out_Start_Date__c=Date.valueof('2015-09-01');
         TechOnCalPeriod.Call_Out_End_Date__c=Date.valueof('2015-09-06');
         TechOnCalPeriod.Technician_name__c=tmp_technician.id;
         insert TechOnCalPeriod;*/
     List<Visits__c> Vis=new List<Visits__c>([select id from Visits__c limit 2]);
     String visitURL='/'+Vis[0].id+'/'+Vis[1].id;
     String oldtechId='['+tmp_technician.id+']';
     
      MultipleTechnicianCalendarHandler con= new MultipleTechnicianCalendarHandler();  
      Date tday=con.setStringToDateFormat('07/14/2015');
      con.SelectedTechId= tmp_technician.id;       
      con.LoadVisit();
      MultipleTechnicianCalendarHandler.UpdateTimeAllowed(string.valueof(system.today()),string.valueof(system.today()+1),visitURL,'12','12:30');
      MultipleTechnicianCalendarHandler.UpdateVisit(string.valueOf( t_visit2.Actual_Service_Date__c+' 12:00'),string.valueOf( t_visit2.Actual_Service_Date__c),visitURL,string.valueOf(t_visit2.id),+oldtechId);           
      
    }
}