objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <label>AM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DORMANT</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>LIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Survey_Required__c.field-meta.xml
<CustomField>
    <fullName>Survey_Required__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Check this if you need survey from this site.</inlineHelpText>
    <label>Survey Required</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Contact/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Average</fullName>
                <default>true</default>
                <label>Average</label>
            </value>
            <value>
                <fullName>Distant</fullName>
            </value>
            <value>
                <fullName>Strong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/Active_User__c.field-meta.xml
<CustomField>
    <fullName>Active_User__c</fullName>
    <inlineHelpText>If this is Yes, the technician is still employed. If No, the technician has left.</inlineHelpText>
    <label>Active User</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;Australia&quot;</defaultValue>
    <label>Country</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

objects/Engineer__c/fields/Engineer_ID__c.field-meta.xml
<CustomField>
    <fullName>Engineer_ID__c</fullName>
    <label>Technician ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <inlineHelpText>If changing to Dormant, please setup a view to mass cancel the open visits. Use this field to stop Visits if on hold - a red warning appears on the visit booking status.</inlineHelpText>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts (Customer)</relationshipLabel>
    <relationshipName>Site_Contract</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Booked_with_Customers__c.field-meta.xml
<CustomField>
    <fullName>Booked_with_Customers__c</fullName>
    <inlineHelpText>1. Yes first time, sends Booking confirmation email
2. Yes to any other, sends Rescheduling notification email
3. Yes again, sends Rescheduled confirmation email.</inlineHelpText>
    <label>Booked with Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Waiting P/O</fullName>
            </value>
            <value>
                <fullName>Waiting Permit</fullName>
            </value>
            <value>
                <fullName>Waiting Confirmation</fullName>
            </value>
            <value>
                <fullName>Booked Via Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notContain</operation>
            <value>Left the company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visits (Customer Contact)</relationshipLabel>
    <relationshipName>Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date / Time</label>
    <type>DateTime</type>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Part</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Visit_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>General Equipment</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
                <label>Autoclave</label>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>X-Ray</fullName>
            </value>
            <value>
                <fullName>Annual Mechanical Service &amp; Certificate to Pan Oral X-ray</fullName>
            </value>
            <value>
                <fullName>OPG</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Image Plate Scanner</fullName>
            </value>
            <value>
                <fullName>Sewer pump</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Workshop Repair</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/SurveySubmitControllerTest.cls
@isTest(SeeAllData=True)
public class SurveySubmitControllerTest {
    
    static testmethod void SurveySubmit()
    {
        Account a = new Account();
        a.Name='Test Customer';
        a.Customer_type__c='others';
        a.Survey_required__c=false;
        a.account_status__c='Live';
        insert a;
        
        Account a2 = new Account();
        a2.Name='Test site';
        a2.Customer_type__c='others';
        a2.parentid=a.id;
        a2.recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        a2.Survey_required__c=false;
        a2.Account_Status__c='Live';
        insert a2;
        
        SiteContracts__c b = new SiteContracts__c();
        b.Site__c=a2.id;
        b.AM_Status__c='Live';
        b.Customer__c=a.id;
        insert b;
        
        
        
        Engineer__c c = new Engineer__c();
        c.Name='Andrew';
        c.Engineer_ID__c='3a443d2f-f632-4d30-a60b-7eda067b958b';
        c.Active_User__c='Yes';
        
        c.Country__c= 'Australia';
        insert c;
        
        Engineer__c c1 = new Engineer__c();
        c1.Name='Test';
        c1.Engineer_ID__c='3a443d2f-f632-4d30-a60b-7eda067b958b';
        c1.Active_User__c='Yes';
        
        c1.Country__c= 'Australia';
        insert c1;
        
        Contact cont = new Contact();
        cont.AccountId = a2.id;
        cont.Email = 'test@email.com';
        cont.Relationship__c = 'Average';          
        cont.Description = 'Test comment';
        cont.Lastname = 'Test ';
        insert cont;
        
        
        
        Visits__c vist = new Visits__c();
        
        vist.Site__c=a2.id;
        vist.Site_Contract__c=b.id;
        vist.Engineer2__c=c.id;
        vist.Service_Type__c ='Storm Water Pump';
        vist.End_Date_Time__c=system.today();
        vist.Order_Value__c=2000;
        vist.Customer_Contact__c=cont.id;
        vist.Booked_with_Customers__c='Yes';
        vist.Actual_Service_Date__c=system.today();
        vist.Visit_Type__c='Service';
        vist.Visit_Complete__c=true;
        insert vist;
        
        apexPages.CurrentPage().getParameters().Put('id',String.valueOf(vist.id));
        ApexPages.StandardController sc = new ApexPages.StandardController(vist);
        SurveySubmitController SSc = New SurveySubmitController(sc);
        SSc.sendSurvey();
        vist.Visit_Complete__c=false;
        update vist;
        SSc.sendSurvey();
        SSc.doRedirect();
    }
    
    
    
    
}