objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <label>AM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DORMANT</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>LIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Date_Account_Status_Changed__c.field-meta.xml
<CustomField>
    <fullName>Date_Account_Status_Changed__c</fullName>
    <inlineHelpText>This is the date the account status changes. It is tracked at the bottom of the account. This is set by Workflow, so you cannot change it.</inlineHelpText>
    <label>Date Account Status Changed</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Reason_Dormant_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Reason_Dormant_On_Hold__c</fullName>
    <label>Account Status Reason</label>
    <type>TextArea</type>
</CustomField>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/Active_User__c.field-meta.xml
<CustomField>
    <fullName>Active_User__c</fullName>
    <inlineHelpText>If this is Yes, the technician is still employed. If No, the technician has left.</inlineHelpText>
    <label>Active User</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;Australia&quot;</defaultValue>
    <label>Country</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

objects/Engineer__c/fields/Engineer_ID__c.field-meta.xml
<CustomField>
    <fullName>Engineer_ID__c</fullName>
    <label>Technician ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Engineer__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State / Province</label>
    <type>TextArea</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <inlineHelpText>If changing to Dormant, please setup a view to mass cancel the open visits. Use this field to stop Visits if on hold - a red warning appears on the visit booking status.</inlineHelpText>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Contract_Status_Change_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status_Change_Date_Time__c</fullName>
    <label>Contract Status Change Date/Time</label>
    <type>DateTime</type>
</CustomField>

objects/SiteContracts__c/fields/Due__c.field-meta.xml
<CustomField>
    <fullName>Due__c</fullName>
    <inlineHelpText>This is the first month on which a visit/service was/is due on this site. This is used by the salesforce trigger to populate a visit onto the site contract, when the Visit Reschedule is set to On Schedule. On Schedule takes its schedule from this field.</inlineHelpText>
    <label>Month Due</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JAN</fullName>
            </value>
            <value>
                <fullName>FEB</fullName>
            </value>
            <value>
                <fullName>MAR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>MAY</fullName>
            </value>
            <value>
                <fullName>JUN</fullName>
            </value>
            <value>
                <fullName>JUL</fullName>
            </value>
            <value>
                <fullName>AUG</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
            <value>
                <fullName>OCT</fullName>
            </value>
            <value>
                <fullName>NOV</fullName>
            </value>
            <value>
                <fullName>DEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Number_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Services__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Number of Visits per year, the Visits auto reschedule, based on this field.</inlineHelpText>
    <label>Number of Services</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Reason_Dormant_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Reason_Dormant_On_Hold__c</fullName>
    <inlineHelpText>Please enter the reason for the change.</inlineHelpText>
    <label>Reason Dormant / On Hold</label>
    <type>TextArea</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Visit_Rescheduling__c.field-meta.xml
<CustomField>
    <fullName>Visit_Rescheduling__c</fullName>
    <inlineHelpText>On Schedule = When visit completes, new visit is planned based on Month Due field.
On Visit = When visit completes, new visit is planned based on visit date.
Pre-Scheduled = User has scheduled all visits so no revisit is booked. Service Maintains these.</inlineHelpText>
    <label>Visit Rescheduling</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Schedule</fullName>
            </value>
            <value>
                <fullName>On Visit</fullName>
            </value>
            <value>
                <fullName>Pre-Scheduled</fullName>
                <default>true</default>
                <label>Pre-Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/Visit_Complete__c.field-meta.xml
<CustomField>
    <fullName>Visit_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Complete</label>
    <type>Checkbox</type>
</CustomField>

objects/Visits__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Workshop Repair</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/SiteContractDormantTest.cls
@IsTest(SeeAllData=true)
public class SiteContractDormantTest {
public static testMethod void Tester() {
    
   Account a=new Account();
   a.Name='Test';
   a.Account_Status__c  = 'Dormant';
    a.Date_Account_Status_Changed__c=system.today();    
    a.Reason_Dormant_On_Hold__c = 'Testing';
    insert a;   
    
    List<SiteContracts__c> sc=new List<SiteContracts__c>{new SiteContracts__c( AM_Status__c='Live',
     Visit_Rescheduling__c='On Schedule',
     Number_of_Services__c=2,
     Site__c=a.id,
     Due__c='MAR')};
    
     insert sc;           
     
     set<id> scid=new set<id>();
     List<SiteContracts__c> scc=new List <SiteContracts__c>{[select id from SiteContracts__c where id =:sc]};
     for(SiteContracts__c n:scc){
     n.AM_Status__c='Dormant';
     n.Contract_Status_Change_Date_Time__c=system.today();   
     scid.add(n.Id);
     }
     update scc;      
     
     Engineer__c tech=new Engineer__c();
     tech.Name='technician';
     tech.Engineer_ID__c='123';
     tech.Active_User__c='Yes';
     tech.Street__c='street';
     tech.Postal_Code__c='60039';
     tech.City__c='city';tech.Country__c='country';tech.State_Province__c='state';
     insert tech;
     
       List<Visits__c> lv=new List<Visits__c>{new Visits__c(Engineer2__c=tech.id,Site__c=a.id,Site_Contract__c=sc[0].id,Visit_Type__c='Callout',Actual_Service_Date__c=system.today(),Visit_Complete__c=false)};      
       insert lv;
       system.debug('lv======'+lv);
       
 
       
   /*    List<Visits__c > v=new List<Visits__c >();
       for(Visits__c lvd:lv){
       v.add(lvd);      
     if(v.size()>0)
     v.clear();
       } */
       

                     
}
}