objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Nominal_Code__c.field-meta.xml
<CustomField>
    <fullName>Nominal_Code__c</fullName>
    <label>Nominal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Xero_Account__c.field-meta.xml
<CustomField>
    <fullName>Xero_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is no longer useful for those opportunity created after 29th May 2020.</inlineHelpText>
    <label>Xero Tax Code</label>
    <referenceTo>Xero_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product2/fields/Nominal_Code__c.field-meta.xml
<CustomField>
    <fullName>Nominal_Code__c</fullName>
    <label>Nominal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Xero_Account__c/Xero_Account__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <label>Tax Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Xero_Account__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Tax Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Xero_Account__c/fields/Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Type__c</fullName>
    <label>Tax Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/XeroControllerTest.cls
@isTest(seeAllData=true)
/*============================================================================================================
*Class Name     : XeroController
*Description    : All the implementations are related to test XeroController.
*Company        : Merfantz Technologies Pvt Ltd
*Date           : 29th Apr, 2020
*Version        : 2.0
*Change History : Xero Migration to 2.0
*Methods        : @isTest Public static void XeroControllerMethod()
                  @isTest Public static void XeroControllerMethod2()
                  @isTest Public static void XeroControllerMethod3()
                  @isTest Public static void XeroControllerMethod4()
                  @isTest Public static void XeroControllerMethod5()
                  @isTest Public static void XeroControllerMethod6()
*============================================================================================================*/
Public Class XeroControllerTest{
/*====================================================
*Method Name     : XeroControllerMethod
*Description     : If Invoice Date null test Xero Controller.
*Arguments       : No Arguments
*Ticket No       : 36814
====================================================*/
     @isTest Public static void XeroControllerMethod() {  
       
        PricebookEntry priceBookEntryNew = new PricebookEntry();
        Product2 product = new Product2(); 
        
        Id pb2= Test.getStandardPricebookId();
        
        product.name = 'Test';
        product.ProductCode='Test';
        product.Nominal_Code__c='Test';
        product.IsActive=true;
        insert product;
        
        priceBookEntryNew.Product2Id = product.Id;
        priceBookEntryNew.PriceBook2Id = pb2;
        priceBookEntryNew.UnitPrice = 20.00;
        priceBookEntryNew.isactive = true;
        insert priceBookEntryNew;
        
        Contact newContact=new Contact(LastName='Test Contact');
        insert newContact;
             
        Account a = new Account(Name = 'Test Account',Customer_type__c='Dental Practice', Account_Status__c ='Live');
        PricebookEntry pbID = [select Id, name from PricebookEntry where isActive = True limit 1];
        Opportunity o = new Opportunity();
        OpportunityLineItem ol = new OpportunityLineItem();
            
        insert a;
    
        o.AccountId = a.Id;
        o.Name = 'Test';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
        o.Pricebook2Id=pb2;
        o.Type = 'New Business';
        
        
        insert o;
                 
        OpportunityLineItem oli = new OpportunityLineItem
            (
                OpportunityId = o.Id,
                PricebookEntryId = priceBookEntryNew.Id,
                Quantity = 1,
                UnitPrice = priceBookEntryNew.UnitPrice, 
                ServiceDate = System.today()
            );
         oli.Product2Id=product.id;
         oli.Discount=34;
         insert oli;
         string taxid;
          Xero_Account__c xa=new Xero_Account__c();
          xa.Tax_Type__c='OUTPUT2';
          xa.name='7033';
          insert xa;
          taxid=xa.Tax_Type__c;
      
        test.starttest();
            Test.setMock(HttpCalloutMock.class, new MockAuthHttpResponseGenerator());   
            apexpages.currentpage().getparameters().put('AccIds',String.valueof(a.id));
            apexpages.currentpage().getparameters().put('id',String.valueof(o.id));
            
             XeroController XeroCtrl=new XeroController();
             XeroOAuthUtility auth=new XeroOAuthUtility();
             auth.connectToXero();
            XeroCtrl.ThemesId.add('');
            
             XeroCtrl.CheckConnection();
            XeroCtrl.XeroBrandingTheme();
            XeroCtrl.InsertXero();
             XeroCtrl.PostOpportunity();
             
            XeroCtrl.contacts('Test',true);
            XeroCtrl.PostContact(a.id);
            XeroCtrl.converttoXml(o);
            XeroCtrl.cancel();
        Test.stopTest();
    }
/*====================================================
*Method Name     : XeroControllerMethod2
*Description     : If Invoice due Date null test Xero Controller.
*Arguments       : No Arguments
*Ticket No       : 36814
====================================================*/    
     @isTest Public static void XeroControllerMethod2() {  
       
             
        Account a = new Account(Name = 'Test Account',Customer_type__c='Dental Practice', Account_Status__c ='Live');
        PricebookEntry pbID = [select Id, name from PricebookEntry where isActive = True limit 1];
        Opportunity o = new Opportunity();
        OpportunityLineItem ol = new OpportunityLineItem();
            
        insert a;
    
        o.AccountId = a.Id;
        o.Name = 'Test';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
        
        o.Type = 'New Business';
        o.Invoice_Date__c=system.today();
        
        insert o;
                 
        
        string taxid;
          Xero_Account__c xa=new Xero_Account__c();
          xa.Tax_Type__c='OUTPUT2';
          xa.name='7033';
          insert xa;
          taxid=xa.Tax_Type__c;
      
        test.starttest();
            Test.setMock(HttpCalloutMock.class, new MockAuthHttpResponseGenerator());   
            apexpages.currentpage().getparameters().put('AccIds',String.valueof(a.id));
            apexpages.currentpage().getparameters().put('id',String.valueof(o.id));
            XeroController XeroCtrl=new XeroController();
            XeroOAuthUtility auth=new XeroOAuthUtility();
             auth.connectToXero();
             XeroCtrl.ThemesId.add('');
             XeroCtrl.CheckConnection();
             XeroCtrl.XeroBrandingTheme();
             XeroCtrl.InsertXero();
             XeroCtrl.PostOpportunity();
             
        Test.stopTest();
    }
/*====================================================
*Method Name     : XeroControllerMethod3
*Description     : If Invoice date greater than invoice due Date test Xero Controller.
*Arguments       : No Arguments
*Ticket No       : 36814
====================================================*/      
    @isTest Public static void XeroControllerMethod3() {  
        Xero_Account__c xc=new Xero_Account__c();
         xc.Default__c=true;
         xc.Percentage__c=20.00;
         xc.Name__c='200';
         xc.Tax_Type__c='OUTPUT2';
         insert xc;
        
        Account a = new Account(Name = 'Test Account',Customer_type__c='Dental Practice', Account_Status__c ='Live');
        PricebookEntry pbID = [select Id, name from PricebookEntry where isActive = True limit 1];
        Opportunity o = new Opportunity();
        OpportunityLineItem ol = new OpportunityLineItem();
            
        insert a;
    
        o.AccountId = a.Id;
        o.Name = 'Test';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
       
        o.Type = 'New Business';
        o.Invoice_Date__c=system.today()+1;
        o.Due_Date__c=system.today();
        insert o;
                 
        
        string taxid;
          Xero_Account__c xa=new Xero_Account__c();
          xa.Tax_Type__c='OUTPUT2';
          xa.name='7033';
          insert xa;
          taxid=xa.Tax_Type__c;
      
        test.starttest();
            Test.setMock(HttpCalloutMock.class, new MockAuthHttpResponseGenerator());   
            apexpages.currentpage().getparameters().put('AccIds',String.valueof(a.id));
            apexpages.currentpage().getparameters().put('id',String.valueof(o.id));
            XeroController XeroCtrl=new XeroController();
            XeroOAuthUtility auth=new XeroOAuthUtility();
            auth.connectToXero();
            XeroCtrl.ThemesId.add('');
            XeroCtrl.CheckConnection();
            XeroCtrl.XeroBrandingTheme();
            XeroCtrl.InsertXero();
            XeroCtrl.PostOpportunity();
         
        Test.stopTest();
    }
/*====================================================
*Method Name     : XeroControllerMethod4
*Description     : If Invoice due Date less than today test Xero Controller.
*Arguments       : No Arguments
*Ticket No       : 36814
====================================================*/     
    @isTest Public static void XeroControllerMethod4() {  
       
        
        Account a = new Account(Name = 'Test Account',Customer_type__c='Dental Practice', Account_Status__c ='Live');
        PricebookEntry pbID = [select Id, name from PricebookEntry where isActive = True limit 1];
        Opportunity o = new Opportunity();
        OpportunityLineItem ol = new OpportunityLineItem();
            
        insert a;
    
        o.AccountId = a.Id;
        o.Name = 'Test';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
       
        o.Type = 'New Business';
        o.Invoice_Date__c=system.today();
        o.Due_Date__c=system.today();
        insert o;
                 
        
          string taxid;
          Xero_Account__c xa=new Xero_Account__c();
          xa.Tax_Type__c='OUTPUT2';
          xa.name='7033';
          insert xa;
          taxid=xa.Tax_Type__c;
      
        test.starttest();
            Test.setMock(HttpCalloutMock.class, new MockAuthHttpResponseGenerator());   
            apexpages.currentpage().getparameters().put('AccIds',String.valueof(a.id));
            apexpages.currentpage().getparameters().put('id',String.valueof(o.id));
            XeroController XeroCtrl=new XeroController();
            XeroOAuthUtility auth=new XeroOAuthUtility();
            auth.connectToXero();
            XeroCtrl.ThemesId.add('');
            XeroCtrl.CheckConnection();
            XeroCtrl.XeroBrandingTheme();
            XeroCtrl.InsertXero();
            XeroCtrl.PostOpportunity();
        Test.stopTest();
    }
/*====================================================
*Method Name     : XeroControllerMethod5
*Description     : This method executes when above method not executes, test Xero Controller.
*Arguments       : No Arguments
*Ticket No       : 36814
====================================================*/     
    @isTest Public static void XeroControllerMethod5() {  
       
        
        Account a = new Account(Name = 'Test Account',Customer_type__c='Dental Practice', Account_Status__c ='Live');
        PricebookEntry pbID = [select Id, name from PricebookEntry where isActive = True limit 1];
        Opportunity o = new Opportunity();
        OpportunityLineItem ol = new OpportunityLineItem();
            
        insert a;
    
        o.AccountId = a.Id;
        o.Name = 'Test';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
       
        o.Type = 'New Business';
        o.Invoice_Date__c=system.today()-6;
        o.Due_Date__c=system.today()-1;
        insert o;
                 
        
        string taxid;
          Xero_Account__c xa=new Xero_Account__c();
          xa.Tax_Type__c='OUTPUT2';
          xa.name='7033';
          insert xa;
          taxid=xa.Tax_Type__c;
      
        test.starttest();
            Test.setMock(HttpCalloutMock.class, new MockAuthHttpResponseGenerator());   
            apexpages.currentpage().getparameters().put('AccIds',String.valueof(a.id));
            apexpages.currentpage().getparameters().put('id',String.valueof(o.id));
            XeroController XeroCtrl=new XeroController();
            XeroOAuthUtility auth=new XeroOAuthUtility();
            auth.connectToXero();
            XeroCtrl.ThemesId.add('');
            XeroCtrl.CheckConnection();
            XeroCtrl.XeroBrandingTheme();
            XeroCtrl.InsertXero();
            XeroCtrl.PostOpportunity();
        Test.stopTest();
    }
/*====================================================
*Method Name     : XeroControllerMethod6
*Description     : This method mainly for testing converttoXml method in XeroController.
*Arguments       : No Arguments
*Ticket No       : 36814
====================================================*/ 
    @isTest Public static void XeroControllerMethod6() {  
       
        
        Account a = new Account(Name = 'Test Account',Customer_type__c='Dental Practice', Account_Status__c ='Live');
        PricebookEntry pbID = [select Id, name from PricebookEntry where isActive = True limit 1];
        Opportunity o = new Opportunity();
        OpportunityLineItem ol = new OpportunityLineItem();
            
        insert a;
        Xero_Account__c xa=new Xero_Account__c();
        xa.Tax_Type__c='OUTPUT2';
        xa.name='7033';
        insert xa;

        o.AccountId = a.Id;
        o.Name = 'Test';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
        o.Xero_Account__c=xa.id;
        o.Type = 'New Business';
        o.Invoice_Date__c=system.today()-6;
        o.Due_Date__c=system.today()-1;
        insert o;
                 
        
        string taxid;
          
        taxid=xa.Tax_Type__c;
      
        test.starttest();
            Test.setMock(HttpCalloutMock.class, new MockAuthHttpResponseGenerator());   
            apexpages.currentpage().getparameters().put('AccIds',String.valueof(a.id));
            apexpages.currentpage().getparameters().put('id',String.valueof(o.id));
            XeroController XeroCtrl=new XeroController();
            XeroOAuthUtility auth=new XeroOAuthUtility();
            auth.connectToXero();
            XeroCtrl.ThemesId.add('');
            XeroCtrl.converttoXml(o);
        Test.stopTest();
    }
    

}