objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Customers</fullName>
            </value>
            <value>
                <fullName>Existing Customers</fullName>
            </value>
            <value>
                <fullName>Lapsed Customers</fullName>
            </value>
            <value>
                <fullName>Not Customers</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Price_List_Correct__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Correct__c</fullName>
    <inlineHelpText>This is the date on which the pricing level for this customer was last checked.</inlineHelpText>
    <label>Price List Correct</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BN Zone D</fullName>
            </value>
            <value>
                <fullName>BR Zone B</fullName>
            </value>
            <value>
                <fullName>Central London (E,EC,WC,W)</fullName>
            </value>
            <value>
                <fullName>CM Zone C</fullName>
            </value>
            <value>
                <fullName>CR Zone C</fullName>
            </value>
            <value>
                <fullName>CT Zone C</fullName>
            </value>
            <value>
                <fullName>CN Zone D</fullName>
            </value>
            <value>
                <fullName>DA Zone A</fullName>
            </value>
            <value>
                <fullName>E Zone C</fullName>
            </value>
            <value>
                <fullName>GU Zone D</fullName>
            </value>
            <value>
                <fullName>HA Zone D</fullName>
            </value>
            <value>
                <fullName>HP Zone D</fullName>
            </value>
            <value>
                <fullName>IG Zone C</fullName>
            </value>
            <value>
                <fullName>KT Zone C</fullName>
            </value>
            <value>
                <fullName>ME Zone B</fullName>
            </value>
            <value>
                <fullName>MK Zone D</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PO Zone E</fullName>
            </value>
            <value>
                <fullName>RG Zone D</fullName>
            </value>
            <value>
                <fullName>RH Zone C</fullName>
            </value>
            <value>
                <fullName>RM Zone B</fullName>
            </value>
            <value>
                <fullName>SE Zone C</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>SL Zone D</fullName>
            </value>
            <value>
                <fullName>SM Zone C</fullName>
            </value>
            <value>
                <fullName>SO Zone D</fullName>
            </value>
            <value>
                <fullName>S- Scotland</fullName>
            </value>
            <value>
                <fullName>SS Zone C</fullName>
            </value>
            <value>
                <fullName>SW Zone C&amp;D</fullName>
            </value>
            <value>
                <fullName>TW Zone D</fullName>
            </value>
            <value>
                <fullName>UB Zone D</fullName>
            </value>
            <value>
                <fullName>WF (NHS)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Survey_Required__c.field-meta.xml
<CustomField>
    <fullName>Survey_Required__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Check this if you need survey from this site.</inlineHelpText>
    <label>Survey Required</label>
    <type>Checkbox</type>
</CustomField>

objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT(Account.Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

classes/UpdateCustomerGroupsBatchTest.cls
@isTest(seeAlldata=true)
public class UpdateCustomerGroupsBatchTest 
{
    Public static testmethod void batchtest()     
    {
        List<Account> testAccounts = new List<Account>();
        Account acc = new Account();
        acc.name='Testing';
        acc.Customer_Group__c='New Customers';
        acc.Region__c='BN Zone D';
        acc.Customer_type__c='others';
        acc.Survey_required__c=false;
        acc.account_status__c='Live';
        insert acc;
        
               
        acc.Region__c='BR Zone B';
        update acc;
        
        acc.Region__c='Central London (E,EC,WC,W)';
        update acc;
        
        acc.Region__c='BN Zone D';
        update acc;
        
        acc.Region__c='CM Zone C';
        update acc;
        
        acc.Region__c='HA Zone D';
        update acc;
        
        acc.Region__c='HP Zone D';
        update acc;
        
        acc.Region__c='CR Zone C';
        update acc;
        
        acc.Region__c='CT Zone C';
        update acc;
        
        acc.Region__c='GU Zone D';
        update acc;
        
        acc.Region__c='DA Zone A';
        update acc;
        
        acc.Region__c='IG Zone C';
        update acc;
        
        acc.Region__c='KT Zone C';
        update acc;
        
        acc.Region__c='MK Zone D';
        update acc;
        
        acc.Region__c='ME Zone B';
        update acc;
        
        acc.Region__c='NL';
        update acc;
        
        acc.Region__c='North London (NW,N,EN) Zone D';
        update acc;
        
        
        acc.Region__c='Other';
        update acc;
        
        
        acc.Region__c='PO Zone E';
        update acc;
        
        
        acc.Region__c='RG Zone D';
        update acc;
        
        
        acc.Region__c='RM Zone B';
        update acc;
        
        
        acc.Region__c='RH Zone C';
        update acc;
        
        
        acc.Region__c='SE Zone C';
        update acc;
        
        
        acc.Region__c='SL Zone D';
        update acc;
        
        
        acc.Region__c='SG';
        update acc;
        
        
        acc.Region__c='SM Zone C';
        update acc;
        
        
        acc.Region__c='SO Zone D';
        update acc;
        
        acc.Region__c='S- Scotland';
        update acc;
        
        acc.Region__c='SS Zone C';
        update acc;
        
        acc.Region__c='SW Zone C&D';
        update acc;
        
        acc.Region__c='TW Zone D';
        update acc;
        
        acc.Region__c='UB Zone D';
        update acc;
        
        acc.Region__c='WF (NHS)';
        update acc;
        
        acc.Region__c='TN Zone B & C';
        update acc;

        Account exAccount=[Select id,Price_List_Correct__c from Account LIMIT 1];
        exAccount.Price_List_Correct__c=system.today();
        update exAccount;
        
        list<Account> ChildRecords = [Select id,Parentid,Price_List_Correct__c from account where parentid = :exAccount.id];
        
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPricebook;
        
        Pricebook2 testPriceBook = new Pricebook2();
        testPriceBook.Name = 'TestPricebook2';
        testPriceBook.IsActive = true;
        insert testPriceBook;
        

        Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile', IsActive = true);
        Insert pro;
        
    
       
        
        Account acc1 = new Account();
        acc1.name='Testing1';
        acc1.Customer_Group__c='New Customers';
        acc1.Region__c='BR Zone B';
        acc1.Customer_type__c='others';
        acc1.Survey_required__c=false;
        acc1.account_status__c='Live';
        testAccounts.add(acc1);
        
        insert testAccounts;
               
        List<Opportunity> testOpportunities = new List<Opportunity>();
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Closed Won',
            CloseDate = Date.today(),
            Invoice_Date__c = Date.today().addMonths(-12),
            AccountId = acc.Id
        );
        testOpportunities.add(opp);
        Opportunity opp1 = new Opportunity(
            Name = 'Test Opportunity1',
            StageName = 'Closed Won',
            CloseDate = Date.today(),
            Invoice_Date__c = Date.today().addMonths(-40),
            AccountId = acc1.Id
        );
        testOpportunities.add(opp1);
        Opportunity opp2 = new Opportunity(
            Name = 'Test Opportunity1',
            StageName = 'Closed Won',
            CloseDate = Date.today(),
            Invoice_Date__c = Date.today().addMonths(-70),
            AccountId = acc1.Id
        );
        testOpportunities.add(opp2);
        
        insert testOpportunities;
        
        Test.startTest();
        UpdateCustomerGroupsBatch batch = new UpdateCustomerGroupsBatch(); 
        Database.executeBatch(batch);
        Test.stopTest();
        
    }
    
}