objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <formula>IF(Service_Sheet__c &lt;&gt; &quot;&quot;, Service_Sheet__r.Service_Sheet_Type__c, Reactive_Sheet__r.Sheets_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Type</label>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Product_Name_Check__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Check__c</fullName>
    <inlineHelpText>Enter the product name again in here, and it will check to see if there is another product already created with this name, when you save. This is to avoid duplicates.</inlineHelpText>
    <label>Product Name Check</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Product2/fields/Product_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_URL__c</fullName>
    <label>Product URL</label>
    <type>Url</type>
</CustomField>

objects/Product2/fields/UniqueSageCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueSageCode__c</fullName>
    <inlineHelpText>This is the unique Sage Code, being a combination of the Sage Code and the Nominal Code. It is a required field on the product, and also is the unique external link to Sage.</inlineHelpText>
    <label>Eclipse Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Quote/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer disinfector</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/QuoteControllerTest.cls
@isTest(SeeAllData=true)
    Public class QuoteControllerTest{
    
   static testMethod void ChangeOrder(){
   
    test.StartTest();
    Account acc=new Account();
    acc.name='test acc';
    acc.Customer_type__c='Podiatry';
    acc.Account_Status__c='Live';
    insert acc;
    
    Product2 p = new Product2(Name='test',IsActive=true,Product_URL__c='www.merfantz.com',UniqueSageCode__c='test1',Product_Name_Check__c='10 Person First Aid Kit Product 1_test1');
    insert p;
    
     PriceBook2  objPricebook2= new PriceBook2();
     objPricebook2.Name='Standard Price Book1';
     objPricebook2.IsActive=true;
     
     insert objPricebook2;
            
    Pricebook2 standardPB = [select id,Name from Pricebook2 where isStandard =true];
     Id stdPriceBookRecId = Test.getStandardPricebookId();
      system.debug('Pricebook2 =========='+standardPB );  
      system.debug('stdPriceBookRecId ======'+stdPriceBookRecId ); 
         
  PricebookEntry objpricebookentry =new PricebookEntry();
     objpricebookentry.Product2ID = p.id;
     objpricebookentry.Pricebook2ID = stdPriceBookRecId;
     objpricebookentry.UnitPrice=50;
     objpricebookentry.IsActive=true;
     insert objpricebookentry;
     system.debug('PricebookEntry ==========='+objpricebookentry);
    
    Opportunity opp=new Opportunity();
    opp.Name='test opp';
    opp.AccountId=acc.id;
    opp.CloseDate=system.today();
    opp.StageName='Closed won';
    opp.Pricebook2ID=stdPriceBookRecId;
    insert opp;
    
  /*  OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, PricebookEntryId=pbe.Id, TotalPrice=50);
    insert oli; */

    Quote qu=new Quote();
    qu.Name='Test quote';
    qu.Service_Type__c='Air Compressor';
    qu.OpportunityId=opp.Id;
    qu.Pricebook2ID=stdPriceBookRecId;
    insert qu;
    
    
    
    QuoteLineItem Qli=new QuoteLineItem(QuoteId=qu.Id,Quantity=1, PricebookEntryId=objpricebookentry.Id, UnitPrice=50);
    insert Qli; 
    system.debug('Qli========'+Qli);
    QuoteLineItem Qlii=new QuoteLineItem(QuoteId=qu.Id,Quantity=2, PricebookEntryId=objpricebookentry.Id, UnitPrice=50,id=Qli.id);
    update Qlii;
    
    QuoteController qc= new QuoteController();
    qc.getQliId();
    qc.setQliId(qu.id);
    Test.StopTest();        
    
   
   }     
    }