objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Opportunity/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Opportunity/fields/AmountCredited__c.field-meta.xml
<CustomField>
    <fullName>AmountCredited__c</fullName>
    <label>AmountCredited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Opportunity/fields/ExpectedPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedPaymentDate__c</fullName>
    <label>ExpectedPaymentDate</label>
    <type>Date</type>
</CustomField>

objects/Opportunity/fields/FullyPaidOnDate__c.field-meta.xml
<CustomField>
    <fullName>FullyPaidOnDate__c</fullName>
    <label>FullyPaidOnDate</label>
    <type>Date</type>
</CustomField>

objects/Opportunity/fields/PlannedPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>PlannedPaymentDate__c</fullName>
    <label>PlannedPaymentDate</label>
    <type>Date</type>
</CustomField>

objects/Opportunity/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Xero Invoice No.</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/XeroOppId__c.field-meta.xml
<CustomField>
    <fullName>XeroOppId__c</fullName>
    <label>Xero Invoice Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/XeroInvoiceBatchTest.cls
@isTest
/*============================================================================================================
*Class Name     : XeroInvoiceBatchTest
*Description    : All the implementations are related test XeroInvoiceBatch.
*Company        : Merfantz Technologies Pvt Ltd
*Date           : 29th Apr, 2020
*Version        : 3.0
*Change History : Warehouse object insertion.
*Methods        : @isTest Public static void XeroInvoiceBatchMethod()
                  @isTest Public static void XeroInvoiceBatchMethod2()
                  
*============================================================================================================*/
Public Class XeroInvoiceBatchTest{
/*====================================================
*Method Name     : XeroInvoiceBatchMethod
*Description     : This method test XeroInvoiceBatch class for success response.
*Arguments       : No Arguments
*Ticket No       : 36814
====================================================*/
     @isTest Public static void XeroInvoiceBatchMethod() { 
         Test.setMock(HttpCalloutMock.class, new MockAuthHttpResponseGenerator()); 
         
        
            Account a = new Account(Name = 'Test Account',Customer_type__c='Dental Practice',Account_Status__c='Live');
            insert a;
            
            Warehouse__c wh=new Warehouse__c();
            wh.name='Test';
            wh.default__c=true;
            insert wh;
        
        
            Opportunity o = new Opportunity();
            o.AccountId = a.Id;
            o.Name = 'Test';
            o.StageName = 'Prospecting';
            o.CloseDate = date.today();   
            o.Type = 'New Business';
            o.Invoice_Date__c=system.today()-6;
            o.Due_Date__c=system.today()-1;
            o.XeroOppId__c='123456INV';
            o.Reference__c=null;
            o.ExpectedPaymentDate__c=null;
            o.PlannedPaymentDate__c=null;
            o.FullyPaidOnDate__c=null;
            o.Amount_Paid__c=0;
            o.AmountCredited__c=0;
            o.Amount_Due__c=0;
            insert o;
        test.starttest();
            XeroInvoiceBatch xero=new XeroInvoiceBatch();
             Database.executeBatch(xero);
         test.stopTest();
      }
/*====================================================
*Method Name     : XeroInvoiceBatchMethod2
*Description     : This method test XeroInvoiceBatch class for failure response.
*Arguments       : No Arguments
*Ticket No       : 36814
====================================================*/   
    @isTest Public static void XeroInvoiceBatchMethod2() {  
        Test.setMock(HttpCalloutMock.class, new MockHttpErrResponseGenerator());
        Account a = new Account(Name = 'Test Account',Customer_type__c='Dental Practice',Account_Status__c='Live');
        insert a;
        Opportunity o = new Opportunity();
            
        o.AccountId = a.Id;
        o.Name = 'Test';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
        
        Warehouse__c wh=new Warehouse__c();
        wh.name='Test';
        wh.default__c=true;
        insert wh;
       
        o.Type = 'New Business';
        o.Invoice_Date__c=system.today()-6;
        o.Due_Date__c=system.today()-1;
        o.XeroOppId__c='123456INV';
        insert o;
         
        test.starttest();        
             XeroInvoiceBatch xero=new XeroInvoiceBatch();
             Database.executeBatch(xero);

         test.stopTest();
        }
    
    
}