objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <label>AM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DORMANT</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>LIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/Active_User__c.field-meta.xml
<CustomField>
    <fullName>Active_User__c</fullName>
    <inlineHelpText>If this is Yes, the technician is still employed. If No, the technician has left.</inlineHelpText>
    <label>Active User</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;Australia&quot;</defaultValue>
    <label>Country</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

objects/Engineer__c/fields/Engineer_ID__c.field-meta.xml
<CustomField>
    <fullName>Engineer_ID__c</fullName>
    <label>Technician ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Engineer__c/fields/Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Technicians</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Engineer__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State / Province</label>
    <type>TextArea</type>
</CustomField>

objects/Engineer_Checklist__c/Engineer_Checklist__c.object-meta.xml
<CustomObject>
    <description>Onsite checklist</description>
    <label>Service Sheet</label>
    <nameField>
        <displayFormat>SS2{000000}</displayFormat>
        <label>Service Sheet No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Engineer_Checklist__c/fields/Engineer__c.field-meta.xml
<CustomField>
    <fullName>Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Service Sheets Completed by this Engineer</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Engineer_Checklist__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <formula>IF( Site_Contract__r.Price_Book__r.Name &lt;&gt; &apos;&apos; , Site_Contract__r.Price_Book__r.Name , Site__r.Price_Book__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Book</label>
    <type>Text</type>
</CustomField>

objects/Engineer_Checklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Engineer_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Engineer_Checklist__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the relationship to the Site and Contract - this also relates to Alarm Master Historic Data</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <inlineHelpText>If changing to Dormant, please setup a view to mass cancel the open visits. Use this field to stop Visits if on hold - a red warning appears on the visit booking status.</inlineHelpText>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts (Customer)</relationshipLabel>
    <relationshipName>Site_Contract</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SiteContracts__c/fields/Due__c.field-meta.xml
<CustomField>
    <fullName>Due__c</fullName>
    <inlineHelpText>This is the first month on which a visit/service was/is due on this site. This is used by the salesforce trigger to populate a visit onto the site contract, when the Visit Reschedule is set to On Schedule. On Schedule takes its schedule from this field.</inlineHelpText>
    <label>Month Due</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JAN</fullName>
            </value>
            <value>
                <fullName>FEB</fullName>
            </value>
            <value>
                <fullName>MAR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>MAY</fullName>
            </value>
            <value>
                <fullName>JUN</fullName>
            </value>
            <value>
                <fullName>JUL</fullName>
            </value>
            <value>
                <fullName>AUG</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
            <value>
                <fullName>OCT</fullName>
            </value>
            <value>
                <fullName>NOV</fullName>
            </value>
            <value>
                <fullName>DEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Number_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Services__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Number of Visits per year, the Visits auto reschedule, based on this field.</inlineHelpText>
    <label>Number of Services</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Visit_Rescheduling__c.field-meta.xml
<CustomField>
    <fullName>Visit_Rescheduling__c</fullName>
    <inlineHelpText>On Schedule = When visit completes, new visit is planned based on Month Due field.
On Visit = When visit completes, new visit is planned based on visit date.
Pre-Scheduled = User has scheduled all visits so no revisit is booked. Service Maintains these.</inlineHelpText>
    <label>Visit Rescheduling</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Schedule</fullName>
            </value>
            <value>
                <fullName>On Visit</fullName>
            </value>
            <value>
                <fullName>Pre-Scheduled</fullName>
                <default>true</default>
                <label>Pre-Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notContain</operation>
            <value>Left the company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visits (Customer Contact)</relationshipLabel>
    <relationshipName>Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/Job_DiaryController_Test.cls
@isTest(seeAlldata=true)
/*=========================================================================================================
    *Class Name     : Job_DiaryControllerTest
    *Description    : Test class for SchedulateHandler
    *Company        : Merfantz
    *Date           : 11 Nov 2018  
 ============================================================================================================== */    

    
/*=========================================================================================================
    *Class Name     : Job_DiaryControllerTest
    *Description    : Test class for SchedulateHandler
    *Company        : Merfantz
    *Date           : 11 Nov 2018  
 ============================================================================================================== */    

private class Job_DiaryController_Test {        
   
    
/*================================================================
Method Name: inserScheduleTestRecord
Parameters : Null
Description: 
Date       : 11 Nov 2018  
================================================================*/
    
    public static testMethod void inserJob_DiaryController(){
    
//user
    User u = new User();
             u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User'].Id;
             u.LastName = 'test';
             u.Email = 'test@test.com';
             u.Username = 'test@test.com' + System.currentTimeMillis();
             u.CompanyName = 'TEST';
             u.Title = 'title';
             u.Alias = 'alias';
             u.TimeZoneSidKey = 'America/Los_Angeles';
             u.EmailEncodingKey = 'UTF-8';
             u.LanguageLocaleKey = 'en_US';
             u.LocaleSidKey = 'en_US';
			insert u;

    
    
       //RecordType 
    Id siteId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
    Id siteId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
    Id psp = Schema.SObjectType.Engineer_Checklist__c.getRecordTypeInfosByName().get('Air Compressor Service and Test Report').getRecordTypeId();
    Id opId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Invoice (To Invoice)').getRecordTypeId();




//Account customer
    Account acc=new Account();
    acc.Name='test account';
    acc.Account_Status__c='Live';
    acc.recordtypeid=siteId1 ;
    acc.Customer_type__c='MOD/Barracks' ;   
    insert acc;

//Account Site
    Account ac=new Account();
    ac.Name='test account';
    ac.Account_Status__c='Live';
    ac.recordtypeid=siteId ;
    ac.Customer_type__c='MOD/Barracks' ;  
    insert ac;

//Contact
    Contact cn=new Contact();
    cn.LastName='test';
    cn.AccountID=ac.id; 
    insert cn;  
    
//SiteContracts 
    SiteContracts__c si=new SiteContracts__c();
    si.Site__c=ac.id;
    si.Customer__c=acc.id;
    si.Visit_Rescheduling__c='On Schedule';
    si.Number_of_Services__c=2;
    si.AM_Status__c='Live';
    si.Price_Book__c=Test.getStandardPricebookId();
    si.Due__c='march';    
    insert si;

//Technician
    Engineer__c technician=new Engineer__c();
    technician.Name='test';
    technician.Engineer_ID__c='1234';
    technician.Active_User__c='Yes';
    technician.Street__c='test address';
    technician.City__c='test city';
    technician.Salesforce_User__c=u.id;
    technician.Country__c='test country';
    technician.Postal_Code__c='1245';
    technician.State_Province__c='test state';
    insert technician;
	 
//Visit
    Visits__c vi=new Visits__c();
    vi.Site__c=ac.id;
    vi.Customer_Contact__c=cn.id;
    vi.Customer_Contact__c=cn.id;
    //system.assertEquals(vi.Site__c,vi.Customer_Contact__c.AccountId);    
    vi.Site_Contract__c=si.id;
    vi.Visit_Completed__c=System.now();
    vi.Visit_Complete__c=true;
    vi.Visit_Type__c='Service';
    vi.Actual_Service_Date__c=system.today();
    vi.Engineer2__c=technician.id;
    insert vi;

	Job_DiaryController ec1=new Job_DiaryController();
    ec1.loadVisits();
    }
    
 }