objects/Account/fields/Account_Notes__c.field-meta.xml
<CustomField>
    <fullName>Account_Notes__c</fullName>
    <inlineHelpText>This fields holds notes for accounts to consider on this parent and all sites.</inlineHelpText>
    <label>Account Notes</label>
    <type>TextArea</type>
</CustomField>

objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>If this is changed to Dormant, please setup a view and mass cancel all the open visits. If is it placed on hold, all of the visits will be placed on hold. This filters down from the parent to the site to the site contract and on to visits.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Account Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/All_Site_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>All_Site_Total_Amount__c</fullName>
    <label>Total customer spend last 12 months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Account/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <label>AM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DORMANT</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>LIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Check_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_Status__c</fullName>
    <description>Check Status</description>
    <label>Check Status</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Company_mail__c.field-meta.xml
<CustomField>
    <fullName>Company_mail__c</fullName>
    <label>Company Email</label>
    <type>Email</type>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Date_Account_Status_Changed__c.field-meta.xml
<CustomField>
    <fullName>Date_Account_Status_Changed__c</fullName>
    <inlineHelpText>This is the date the account status changes. It is tracked at the bottom of the account. This is set by Workflow, so you cannot change it.</inlineHelpText>
    <label>Date Account Status Changed</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Price_List_Correct__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Correct__c</fullName>
    <inlineHelpText>This is the date on which the pricing level for this customer was last checked.</inlineHelpText>
    <label>Price List Correct</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Purchase_Order_Required__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Required__c</fullName>
    <inlineHelpText>If you select this on the parent, it over-rides every Site and Every Contract. If you select it for a site, it over-rides the contracts. Contracts can be set specifically.</inlineHelpText>
    <label>Purchase Order Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Reason_Dormant_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Reason_Dormant_On_Hold__c</fullName>
    <label>Account Status Reason</label>
    <type>TextArea</type>
</CustomField>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

objects/Opportunity/fields/Check_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_Status__c</fullName>
    <formula>&quot;PriceList: &quot;&amp;IF(TEXT(Account.Price_List_Correct__c) &lt;&gt; &quot;&quot; , &quot;Yes&quot;, &quot;No &quot; ) &amp;&quot; SageCode: &quot;&amp;IF ( Account.Accounts_Checked_Sage_Code__c  , &quot;Yes&quot; , &quot;No &quot; )&amp;
 &quot;  AccAddOK : &quot; &amp;IF(Account.Accounts_Checked_Address__c , &quot;Yes&quot;, &quot;No &quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check Status</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Opportunities created when converting lead</description>
    <label>Sales</label>
</RecordType>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <inlineHelpText>If changing to Dormant, please setup a view to mass cancel the open visits. Use this field to stop Visits if on hold - a red warning appears on the visit booking status.</inlineHelpText>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts (Customer)</relationshipLabel>
    <relationshipName>Site_Contract</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SiteContracts__c/fields/Due__c.field-meta.xml
<CustomField>
    <fullName>Due__c</fullName>
    <inlineHelpText>This is the first month on which a visit/service was/is due on this site. This is used by the salesforce trigger to populate a visit onto the site contract, when the Visit Reschedule is set to On Schedule. On Schedule takes its schedule from this field.</inlineHelpText>
    <label>Month Due</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JAN</fullName>
            </value>
            <value>
                <fullName>FEB</fullName>
            </value>
            <value>
                <fullName>MAR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>MAY</fullName>
            </value>
            <value>
                <fullName>JUN</fullName>
            </value>
            <value>
                <fullName>JUL</fullName>
            </value>
            <value>
                <fullName>AUG</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
            <value>
                <fullName>OCT</fullName>
            </value>
            <value>
                <fullName>NOV</fullName>
            </value>
            <value>
                <fullName>DEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Number_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Services__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Number of Visits per year, the Visits auto reschedule, based on this field.</inlineHelpText>
    <label>Number of Services</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Purchase_Order_Required__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Required__c</fullName>
    <inlineHelpText>Please select whether a purchase order is required for this Site Contract</inlineHelpText>
    <label>Purchase Order Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Reason_Dormant_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Reason_Dormant_On_Hold__c</fullName>
    <inlineHelpText>Please enter the reason for the change.</inlineHelpText>
    <label>Reason Dormant / On Hold</label>
    <type>TextArea</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Visit_Rescheduling__c.field-meta.xml
<CustomField>
    <fullName>Visit_Rescheduling__c</fullName>
    <inlineHelpText>On Schedule = When visit completes, new visit is planned based on Month Due field.
On Visit = When visit completes, new visit is planned based on visit date.
Pre-Scheduled = User has scheduled all visits so no revisit is booked. Service Maintains these.</inlineHelpText>
    <label>Visit Rescheduling</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Schedule</fullName>
            </value>
            <value>
                <fullName>On Visit</fullName>
            </value>
            <value>
                <fullName>Pre-Scheduled</fullName>
                <default>true</default>
                <label>Pre-Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TriggerActive__c/TriggerActive__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>AccountTrigger</description>
    <label>TriggerActive</label>
</CustomObject>

classes/AccountTriggers_Test.cls
@isTest(seeAlldata=true)
public class AccountTriggers_Test{
 
 @IsTest
 public static void AccountTriggers_Test(){       
     //Getting the     RecordType Id
        Id parentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id childRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        Id opportunityrecordtype = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        
     TriggerActive__c acct = New TriggerActive__c(Name='Test',IsActive__c=false); 
       insert acct;
     
     //Create Parent Record
        Account newParentAccount = new Account();
        newParentAccount.RecordTypeid = parentRecordTypeId;
        newParentAccount.Name = 'TestParentAccount';
        newParentAccount.Customer_type__c='Private Healthcare';
        Insert newParentAccount;
        
        //Create Child Record
        Account newChildAccount = new Account();
        newChildAccount.RecordTypeid = childRecordTypeId;
        newChildAccount.Name = 'TestChildAccount';
        newChildAccount.Customer_type__c='Supplier'; 
        newChildAccount.Parentid= newParentAccount.id;
        //  newChildAccount.Price_List_Correct__c = 29/02/2022;
        newChildAccount.Account_Notes__c='test';
        
        insert newChildAccount;
        
        //Update the PriceList
        newParentAccount.Price_List_Correct__c = system.today();
        newParentAccount.All_Site_Total_Amount__c=100;
         update newParentAccount;
        
        //Create Account 
        Account newAccount = new Account();
        newAccount.RecordTypeid = parentRecordTypeId;
        newAccount.Customer_type__c='Supplier';
        newAccount.Name = 'TestParentAccount';
       
        Insert newAccount;
        
        //Create the Opportunity
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = opportunityrecordtype;
        opp.Name ='Testopp';
        opp.AccountId = newAccount.id;
        datetime t2 = System.now();
        date clsDate = Date.newInstance(t2.year(),t2.month(),t2.day());
        opp.CloseDate= clsDate;
        //  opp.CreatedDate= crtDate;
        opp.StageName = 'Negotiation/Review';
        insert opp;
        
        newAccount.Company_mail__c = 'rak@gmail.com';    
        newAccount.Check_Status__c  ='PriceList: No SageCode: No AccAddOK : No';
        newAccount.Account_Status__c='Dormant';
        newAccount.Reason_Dormant_On_Hold__c='Testing';
        newAccount.Date_Account_Status_Changed__c=system.today();
         
        update newAccount;     
             
     
     //Check Dormant Trigger
    SiteContracts__c t_siteContract= new SiteContracts__c();
     t_siteContract.site__c=newParentAccount.id;  
        t_siteContract.AM_Status__c='Dormant';
        t_siteContract.Visit_Rescheduling__c='On Schedule';
        t_siteContract.Due__c='one';         
        t_siteContract.Number_of_Services__c=1;
        t_siteContract.Purchase_Order_Required__c='No';
        t_siteContract.Customer__c= newAccount.Id; 
        
        insert t_siteContract;
        t_siteContract.site__c=newAccount.id;
        update t_siteContract;
        Account acc=New Account();
        acc=[SELECT id,Account_Status__c,Customer_type__c from Account where id=:newParentAccount.id];
        acc.Account_Status__c='Dormant';
        acc.Customer_type__c='Prison'; 
        acc.Reason_Dormant_On_Hold__c='Testing Records';
        Update acc;
 
    acc=[SELECT id,Account_Status__c from Account where id=:newAccount.id];
    acc.Account_Status__c='Dormant';
    acc.Reason_Dormant_On_Hold__c='Testing Parent Records';
    Update acc;
    
    
    }
}