objects/Account/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <label>AM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DORMANT</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>LIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/SAGE_Code__c.field-meta.xml
<CustomField>
    <fullName>SAGE_Code__c</fullName>
    <label>Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

objects/Auto_Product_Config__c/Auto_Product_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Auto Product Config</label>
</CustomObject>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;Australia&quot;</defaultValue>
    <label>Country</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

objects/Engineer__c/fields/Disciplines__c.field-meta.xml
<CustomField>
    <fullName>Disciplines__c</fullName>
    <label>Disciplines</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Engineer__c/fields/Engineer_ID__c.field-meta.xml
<CustomField>
    <fullName>Engineer_ID__c</fullName>
    <label>Technician ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Engineer__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State / Province</label>
    <type>TextArea</type>
</CustomField>

objects/Engineer__c/fields/Technician_Group__c.field-meta.xml
<CustomField>
    <fullName>Technician_Group__c</fullName>
    <inlineHelpText>Please enter the name of the scheduler for this Technician.</inlineHelpText>
    <label>Technician Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angie Davey</fullName>
            </value>
            <value>
                <fullName>Joel Bidmead</fullName>
            </value>
            <value>
                <fullName>Jo Fyffe</fullName>
            </value>
            <value>
                <fullName>Mel Jones</fullName>
            </value>
            <value>
                <fullName>Nigel Welch</fullName>
            </value>
            <value>
                <fullName>Samantha Cavinder</fullName>
            </value>
            <value>
                <fullName>Sharon Standen</fullName>
            </value>
            <value>
                <fullName>Tim Mann</fullName>
            </value>
            <value>
                <fullName>Tracey Coles</fullName>
            </value>
            <value>
                <fullName>Viv Stuchbery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/fields/Technician_Super_Group__c.field-meta.xml
<CustomField>
    <fullName>Technician_Super_Group__c</fullName>
    <inlineHelpText>Enter either North or South. This field will help creating Views of Technicians in their Service Groups.</inlineHelpText>
    <label>Technician Super Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

objects/Opportunity/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site Contract Number</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>Travel_Time__c</fullName>
    <label>Service Sheet Travel Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/SFDC_Purchase_Order__c/SFDC_Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>Track the lifestyle of a Purchase Order, as it starts as a purchase request and becomes a fully-approved PO. Associate this with a specific cost center and Invoices.</description>
    <label>Supplier Purchase Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Purchase_Order__c/fields/Supplier1__c.field-meta.xml
<CustomField>
    <fullName>Supplier1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Search and select the relevant Supplier, if you cannot find the one you need, use the Supplier Pending Creation Supplier, and enter the name of the Supplier in the Branch field, then ask Accounts to setup the new Supplier, and assign this P/O to it.</inlineHelpText>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipName>Purchase_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SFDC_Purchase_Order__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Visit this P/O relates to, if applicable.</inlineHelpText>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <inlineHelpText>If changing to Dormant, please setup a view to mass cancel the open visits. Use this field to stop Visits if on hold - a red warning appears on the visit booking status.</inlineHelpText>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/EMAIL_ADDRESS__c.field-meta.xml
<CustomField>
    <fullName>EMAIL_ADDRESS__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

objects/SiteContracts__c/fields/Job_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_Time__c</fullName>
    <description>Assign the job time</description>
    <inlineHelpText>Job Time</inlineHelpText>
    <label>Job Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>Travel_Time__c</fullName>
    <description>Assign the travelling time</description>
    <inlineHelpText>Travel Time</inlineHelpText>
    <label>Travel Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Suppliers__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Suppliers__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <defaultValue>&quot;UK&quot;</defaultValue>
    <label>Billing Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Suppliers__c/fields/Billing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Billing_State_Province__c</fullName>
    <label>Billing State/Province</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Suppliers__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Billing Zip/Postal Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Suppliers__c/fields/Sage_Code__c.field-meta.xml
<CustomField>
    <fullName>Sage_Code__c</fullName>
    <label>Sage Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Job_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_Time__c</fullName>
    <description>It pull through the site contract Job Time field.</description>
    <label>Job Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/Technician_Group__c.field-meta.xml
<CustomField>
    <fullName>Technician_Group__c</fullName>
    <formula>TEXT ( Engineer2__r.Technician_Group__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Technician Group</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Technician_Super_Group__c.field-meta.xml
<CustomField>
    <fullName>Technician_Super_Group__c</fullName>
    <formula>TEXT(Engineer2__r.Technician_Super_Group__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Technician Super Group</label>
    <type>Text</type>
</CustomField>

classes/TestDataHandler.cls
/*======================================
    Name           : TestDataHandler
    Author         : 
    Date           : 20th June 2014
    Description    : This controller provide test data
========================================*/

public class TestDataHandler{
    // create Auto Product Config
    public static Auto_Product_Config__c createTestAutoProductConfig(){
        Auto_Product_Config__c autoCon = new Auto_Product_Config__c();
        autoCon.Name = 'Service Sheet';
        return autoCon;
    }

    // create supplier
    public static Suppliers__c createTestSupplier(){
        Suppliers__c supp = new Suppliers__c();
        supp.Name = 'Test supplier';
        supp.Billing_Street__c = 'test street';
        supp.Billing_City__c = 'test city';
        supp.Billing_Country__c = 'UK';
        supp.Billing_State_Province__c = 'test province';
        supp.Billing_Zip_Postal_Code__c = '25489';
        supp.Sage_Code__c = 'st002';
        return supp;
    }
    
    // create site
    Public Static Account createTestSite(){
        Account newSite = new Account(Name='Test Site');
                
        return newSite;
    }
    
    //Create SiteContracts Record
    Public static SiteContracts__c createTestSiteContract(Id siteId){
        SiteContracts__c siteContract=new SiteContracts__c(); 
        siteContract.AM_Status__c='Hold';
        siteContract.Travel_Time__c=2;
        siteContract.Job_Time__c=2;
        siteContract.Site__c = siteId;
        
        return siteContract;
    }
    
    // create Test Technician
    public static Engineer__c createTestEngineer(){
        Engineer__c eng = new Engineer__c();
        eng.Name = 'test tech';
        eng.Disciplines__c = 'Disciplines';
        eng.Email_Address__c = 'test@test.com';
        eng.Engineer_ID__c = 'Tech001';
        eng.Target__c = 78;
        eng.Technician_Super_Group__c = 'North';
        eng.Technician_Group__c = 'Jo Fyffe';
        eng.Street__c = 'test';
        eng.City__c = 'test';
        eng.State_Province__c = 'test';
        eng.Postal_Code__c = '21584';
        eng.Country__c = 'UK';
        return eng;
    }
    
    //Create Visit Record
    Public static Visits__c createTestVisit(Id siteContractId, Id siteId,Id engId){
        Visits__c visit=new Visits__c(); 
        visit.Site__c=siteId;
        visit.Site_Contract__c = siteContractId;
        visit.Engineer2__c = engId;
        return visit;
    }
    
    //Create Opportunity Record
    Public static Opportunity createTestOpportunity(Id accId){
        RecordType oppRT;
        try{
            oppRT = [Select Id, Name, DeveloperName From RecordType Where DeveloperName = 'Order_Form'];
        } catch(Exception ex){}
        Date closeDate = Date.today()+2;
        Opportunity opp = new Opportunity(Name='test opp',AccountId = accId, CloseDate = closeDate, StageName='Proposal/Price Quote' ,Type='Catalogue Order');
        return opp;
    } 
    
    // create purchase order
    public static SFDC_Purchase_Order__c createTestPurchaseOrder(Id suppId,Id visitId){
        SFDC_Purchase_Order__c purchaseOrd = new SFDC_Purchase_Order__c(Supplier1__c=suppId,Visit__c=visitId);
        return purchaseOrd;
    }
}