objects/Account/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <label>AM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DORMANT</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>LIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Account/fields/SAGE_Code__c.field-meta.xml
<CustomField>
    <fullName>SAGE_Code__c</fullName>
    <label>Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Site_Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Invoice_Name__c</fullName>
    <inlineHelpText>This is the name of the site as it will be shown on the invoice, replacing record name in the Site Invoice address.</inlineHelpText>
    <label>Site Invoice Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <formula>IF(Service_Sheet__c &lt;&gt; &quot;&quot;, Service_Sheet__r.Service_Sheet_Type__c, Reactive_Sheet__r.Sheets_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Type</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/recordTypes/To_Invoice.recordType-meta.xml
<RecordType>
    <fullName>To_Invoice</fullName>
    <active>true</active>
    <businessProcess>Order Form</businessProcess>
    <description>Opportunities layout to create an invoice</description>
    <label>Invoice (To Invoice)</label>
</RecordType>

objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c/fields/Long_Project_Order__c.field-meta.xml
<CustomField>
    <fullName>Long_Project_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Long Project Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Long_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer disinfector</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Quote/fields/Vat_Total__c.field-meta.xml
<CustomField>
    <fullName>Vat_Total__c</fullName>
    <formula>(TotalPrice * VAT_Rate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vat Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <formula>Total_Price__c  +  Vat_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/SalesOrder__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer disinfector</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Service Type</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SalesOrder__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>SalesOrderLineItems__c.Total_Price__c</summarizedField>
    <summaryForeignKey>SalesOrderLineItems__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/SalesOrder__c/fields/Vat_Total__c.field-meta.xml
<CustomField>
    <fullName>Vat_Total__c</fullName>
    <formula>( Total_Price__c  *   VAT_Rate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vat Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/SalesOrder__c/recordTypes/Long_Project_Order_Confirmation.recordType-meta.xml
<RecordType>
    <fullName>Long_Project_Order_Confirmation</fullName>
    <active>true</active>
    <label>Long Project Order Confirmation</label>
</RecordType>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <inlineHelpText>If changing to Dormant, please setup a view to mass cancel the open visits. Use this field to stop Visits if on hold - a red warning appears on the visit booking status.</inlineHelpText>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts (Customer)</relationshipLabel>
    <relationshipName>Site_Contract</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SiteContracts__c/fields/Due__c.field-meta.xml
<CustomField>
    <fullName>Due__c</fullName>
    <inlineHelpText>This is the first month on which a visit/service was/is due on this site. This is used by the salesforce trigger to populate a visit onto the site contract, when the Visit Reschedule is set to On Schedule. On Schedule takes its schedule from this field.</inlineHelpText>
    <label>Month Due</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JAN</fullName>
            </value>
            <value>
                <fullName>FEB</fullName>
            </value>
            <value>
                <fullName>MAR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>MAY</fullName>
            </value>
            <value>
                <fullName>JUN</fullName>
            </value>
            <value>
                <fullName>JUL</fullName>
            </value>
            <value>
                <fullName>AUG</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
            <value>
                <fullName>OCT</fullName>
            </value>
            <value>
                <fullName>NOV</fullName>
            </value>
            <value>
                <fullName>DEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Number_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Services__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Number of Visits per year, the Visits auto reschedule, based on this field.</inlineHelpText>
    <label>Number of Services</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Visit_Rescheduling__c.field-meta.xml
<CustomField>
    <fullName>Visit_Rescheduling__c</fullName>
    <inlineHelpText>On Schedule = When visit completes, new visit is planned based on Month Due field.
On Visit = When visit completes, new visit is planned based on visit date.
Pre-Scheduled = User has scheduled all visits so no revisit is booked. Service Maintains these.</inlineHelpText>
    <label>Visit Rescheduling</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Schedule</fullName>
            </value>
            <value>
                <fullName>On Visit</fullName>
            </value>
            <value>
                <fullName>Pre-Scheduled</fullName>
                <default>true</default>
                <label>Pre-Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/LongProjectOrderControllerTest.cls
@isTest(SeeAllData=true)
public class LongProjectOrderControllerTest{
  static testMethod void myTest(){
  Test.startTest();
  Account a=new Account();
  a.Name='Test';
  a.Customer_type__c='Dental Laboratory';
 /* a.Billing Street='Billing Street';
  a.Billing City='Billing City';
 // a.Billing State/Province='Billing State';
 // a.Billing Zip/Postal Code='Billing Zip';
  a.Billing Country='Billing Country';
  a.Shipping Street='Shipping Street'; 
  a.Shipping City='Shipping City';
  a.Shipping State/Province='Shipping State';
  a.Shipping Zip/Postal Code='Shipping Zip';
  a.Shipping Country='Shipping Country'; */
  a.SAGE_Code__c='1234';
  a.Site_Invoice_Name__c='test';
  insert a;
  
  SiteContracts__c sc=new SiteContracts__c();
  sc.Site__c=a.id;
      sc.Customer__c = a.id;
  sc.AM_Status__c='Live';
  sc.Visit_Rescheduling__c='On Schedule';
  sc.Number_of_Services__c=2;
  sc.Due__c='MAR';
  insert sc;
  
 /* RecordType oppRT;
        try{
            oppRT = [Select Id, Name, DeveloperName From RecordType Where DeveloperName = 'To_Invoice'];
        } catch(Exception ex){}
        
         Opportunity opp = new Opportunity(Name='Test Opp',RecordTypeId = oppRT.Id, AccountId = a.Id, CloseDate = closeDate, StageName='Proposal/Price Quote' ,Type='Catalogue Order');
  */
 //  Id PSPBId = Schema.SObjectType.SalesOrder__c.getRecordTypeInfosByName().get('Long_Project_Order_Confirmation').getRecordTypeId();
  SalesOrder__c so=new SalesOrder__c();
 //so.RecordTypeId = PSPBId ;
  so.Account__c=a.id;
  so.Service_Type__c='Air Compressor';
  so.Due_Date__c=system.today();
  so.Account__c=a.id;
  so.Phone__c='944567898';
  so.Email__c='test@gmail.com';
  /* so.Total_Price__c=70;
  so.Vat_Total__c=10;
  so.Order_Total__c  =80; */
  
  insert so;
  
  ApexPages.currentPage().getParameters().put('id',so.id);
  
  
  Project__c p=new Project__c();
  p.Name='Test project';
  p.Long_Project_Order__c=so.id;
  insert p;
  LongProjectOrderController lp=new LongProjectOrderController ();
  lp.getMasterRecordId ();
  lp.setMasterRecordId (so.id);
  Test.stopTest();
  
  
  }
  
  }