objects/Account/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <label>AM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DORMANT</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>LIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Technician__c.field-meta.xml
<CustomField>
    <fullName>Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Engineer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Date__c/Date__c.object-meta.xml
<CustomObject>
    <label>Date</label>
    <nameField>
        <label>Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mechanical_Service_Sheet__c/Mechanical_Service_Sheet__c.object-meta.xml
<CustomObject>
    <description>This object contains two Inspection Certificates:-

Suppression System Mechanical Inspection Certificate
Riser &amp; Hydrant Inspection Certificate</description>
    <label>Mechanical Service Sheet</label>
    <nameField>
        <displayFormat>SSM{00000}</displayFormat>
        <label>Mechanical Service Sheets</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mechanical Service Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mechanical_Service_Sheet__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Email_Confirmation_to__c.field-meta.xml
<CustomField>
    <fullName>Email_Confirmation_to__c</fullName>
    <description>Use this email address to send confirmation of service</description>
    <inlineHelpText>This is the Site Email which will receive a copy of the service sheet</inlineHelpText>
    <label>Email Confirmation to</label>
    <type>Email</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Email_for_HQ_Notification__c.field-meta.xml
<CustomField>
    <fullName>Email_for_HQ_Notification__c</fullName>
    <inlineHelpText>Sends an email to the HQ contact for this company notifying them of this service.</inlineHelpText>
    <label>Email for HQ Notification</label>
    <type>Email</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Engineer__c.field-meta.xml
<CustomField>
    <fullName>Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Mechanical Service Sheets (Technician)</relationshipLabel>
    <relationshipName>Mechanical_Service_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Engineer_s_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Engineer_s_Email_Address__c</fullName>
    <inlineHelpText>Please note this will be populated once the Service Sheet is saved.</inlineHelpText>
    <label>Technician&apos;s Email Address</label>
    <type>Email</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Inspection</fullName>
            </value>
            <value>
                <fullName>Visual Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inspection_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Relates to the contract which will cover this service sheet</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipName>Inspection_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Start_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_and_Time__c</fullName>
    <inlineHelpText>If you populate Start and End Date and Times, and you leave job time empty, Salesforce will calculate it for you. Note this does not work for jobs taking more than one day. For that, you will need to manage the process and work out the overall time.</inlineHelpText>
    <label>Start Date and Time</label>
    <type>DateTime</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/System_Type__c.field-meta.xml
<CustomField>
    <fullName>System_Type__c</fullName>
    <label>System Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dry Riser</fullName>
            </value>
            <value>
                <fullName>Fire Suppression</fullName>
            </value>
            <value>
                <fullName>Hydrant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Sprinkler</fullName>
            </value>
            <value>
                <fullName>Wet Riser</fullName>
            </value>
            <value>
                <fullName>Dry Riser, Wet Riser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Technician__c.field-meta.xml
<CustomField>
    <fullName>Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipName>Inspection_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Mechanical_Service_Sheet__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipName>Inspection_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/AM_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Status__c</fullName>
    <inlineHelpText>If changing to Dormant, please setup a view to mass cancel the open visits. Use this field to stop Visits if on hold - a red warning appears on the visit booking status.</inlineHelpText>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Technician__c.field-meta.xml
<CustomField>
    <fullName>Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If a specific technician services this customer, please enter them here.</inlineHelpText>
    <label>Lead Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Site Contracts worked by this Technician</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Date MUST be in this format : DD/MM/YYYY. PLEASE do not create new planned service dates. If this is not working, contact cascloud for support or simply move straight to actual service date, and ignore the planned service date.</inlineHelpText>
    <label>Planned Visit Date</label>
    <referenceTo>Date__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Engineer_s_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Engineer_s_Email_Address__c</fullName>
    <label>Technician&apos;s Email Address</label>
    <type>Email</type>
</CustomField>

objects/Visits__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Part</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Visit_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>General Equipment</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
                <label>Autoclave</label>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>X-Ray</fullName>
            </value>
            <value>
                <fullName>Annual Mechanical Service &amp; Certificate to Pan Oral X-ray</fullName>
            </value>
            <value>
                <fullName>OPG</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Image Plate Scanner</fullName>
            </value>
            <value>
                <fullName>Sewer pump</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/Technician__c.field-meta.xml
<CustomField>
    <fullName>Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits (Technician)</relationshipLabel>
    <relationshipName>Visits2</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/EmailTriggerWithAttachmentsTest.cls
@isTest(SeeAllData=true)
private class EmailTriggerWithAttachmentsTest {
    
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        RecordType rec=[SELECT id FROM RecordType WHERE SobjectType=:'Mechanical_Service_Sheet__c' AND Name=:'Sprinkler Service Sheet'];
        
        Engineer__c newEngineer=new Engineer__c();
        newEngineer.Name='Test Engineer';
        insert newEngineer;
        
        Account newAccount=new Account();
        newAccount.Name='Test Account';
        insert newAccount;
        
        SiteContracts__c newSiteContract=new SiteContracts__c();
        newSiteContract.AM_Status__c='Live';
        insert newSiteContract;
        
        Visits__c newVisit=new Visits__c();
        newVisit.Site__c=newAccount.id;
        newVisit.Service_Type__c='Test Type';
        newVisit.Engineer2__c=newEngineer.id;
        newVisit.Site_Contract__c=newSiteContract.id;
        insert newVisit;
        
        Mechanical_Service_Sheet__c newMechanicalServiceSheet=new Mechanical_Service_Sheet__c();
        newMechanicalServiceSheet.Date__c=system.today();
        newMechanicalServiceSheet.Start_Date_and_Time__c=Datetime.now();
        newMechanicalServiceSheet.Technician__c=newEngineer.id;
        newMechanicalServiceSheet.Visit__c=newVisit.id;
        newMechanicalServiceSheet.System_Type__c=newVisit.Service_Type__c;
        newMechanicalServiceSheet.Site__c=newAccount.id; 
        newMechanicalServiceSheet.Email_Confirmation_to__c = 'test@test.com';
        newMechanicalServiceSheet.Email_for_HQ_Notification__c = 'test@test.com';
        newMechanicalServiceSheet.Engineer_s_Email_Address__c = 'test@test.com';
        // insert newMechanicalServiceSheet;
        List<Mechanical_Service_Sheet__c> newListMechanicalServiceSheetList=new List<Mechanical_Service_Sheet__c>();
        newListMechanicalServiceSheetList.add(newMechanicalServiceSheet);
        insert newListMechanicalServiceSheetList;
        
        Attachment attach=new Attachment();     
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=newListMechanicalServiceSheetList[0].id;
        insert attach;
        
        Test.startTest();
        EmailTriggerWithAttachmentsController toTestAttachmentsController=new EmailTriggerWithAttachmentsController();
        toTestAttachmentsController.emailAttachmentsMethod(newListMechanicalServiceSheetList);
        EmailTriggerWithAttachmentsController.getRecordTypeId('Sprinkler Service Sheet');
        List<Attachment> attachments=[select id, name from Attachment where parent.id=:newListMechanicalServiceSheetList[0].id];
        toTestAttachmentsController.fetchAttachments(newListMechanicalServiceSheetList[0].id);
        Test.stopTest(); 
    }
}