objects/Account/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The technician is either on holiday, sick, or training.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Engineer__c/fields/Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Technicians</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>Asset.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Booking_Notes__c.field-meta.xml
<CustomField>
    <fullName>Booking_Notes__c</fullName>
    <inlineHelpText>Additional notes taken whilst booking the customer.</inlineHelpText>
    <label>Notes/additional work</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Visits__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>If this is a multi-day service, please enter the end date here..</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Message_to_Technician__c.field-meta.xml
<CustomField>
    <fullName>Message_to_Technician__c</fullName>
    <inlineHelpText>If you put a message here it will appear in the Message field in the Engineer&apos;s view, highlighted with ****  ****</inlineHelpText>
    <label>Assets to service/install</label>
    <type>TextArea</type>
</CustomField>

objects/Visits__c/fields/Requested_Attendance_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Attendance_Time__c</fullName>
    <inlineHelpText>Enter the time the technician should attend this Visit in the format - HH:MM</inlineHelpText>
    <label>Required On Site</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00:00</fullName>
            </value>
            <value>
                <fullName>00:30</fullName>
            </value>
            <value>
                <fullName>01:00</fullName>
            </value>
            <value>
                <fullName>01:30</fullName>
            </value>
            <value>
                <fullName>02:00</fullName>
            </value>
            <value>
                <fullName>02:30</fullName>
            </value>
            <value>
                <fullName>03:00</fullName>
            </value>
            <value>
                <fullName>03:30</fullName>
            </value>
            <value>
                <fullName>04:00</fullName>
            </value>
            <value>
                <fullName>04:30</fullName>
            </value>
            <value>
                <fullName>05:00</fullName>
            </value>
            <value>
                <fullName>05:30</fullName>
            </value>
            <value>
                <fullName>06:00</fullName>
            </value>
            <value>
                <fullName>06:30</fullName>
            </value>
            <value>
                <fullName>07:00</fullName>
            </value>
            <value>
                <fullName>07:30</fullName>
            </value>
            <value>
                <fullName>08:00</fullName>
            </value>
            <value>
                <fullName>08:30</fullName>
            </value>
            <value>
                <fullName>09:00</fullName>
            </value>
            <value>
                <fullName>09:30</fullName>
            </value>
            <value>
                <fullName>10:00</fullName>
            </value>
            <value>
                <fullName>10:30</fullName>
            </value>
            <value>
                <fullName>11:00</fullName>
            </value>
            <value>
                <fullName>11:30</fullName>
            </value>
            <value>
                <fullName>12:00</fullName>
            </value>
            <value>
                <fullName>12:30</fullName>
            </value>
            <value>
                <fullName>13:00</fullName>
            </value>
            <value>
                <fullName>13:30</fullName>
            </value>
            <value>
                <fullName>14:00</fullName>
            </value>
            <value>
                <fullName>14:30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Unscheduled</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Visit_Complete__c.field-meta.xml
<CustomField>
    <fullName>Visit_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Complete</label>
    <type>Checkbox</type>
</CustomField>

objects/Visits__c/fields/Visit_Completed__c.field-meta.xml
<CustomField>
    <fullName>Visit_Completed__c</fullName>
    <description>Keep the visit completed date</description>
    <label>Visit Completed Date/Time</label>
    <type>DateTime</type>
</CustomField>

objects/Visits__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Workshop Repair</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/X2nd_Technician__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits (2nd Technician)</relationshipLabel>
    <relationshipName>Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/Job_DiaryController.cls
/*=========================================================================================================
    *Class Name     : Job_DiaryController
    *Description    : MyDiaryTAb page controller class
    *Company        : Merfantz
    *Date           : 22 Nov 2018  
 ============================================================================================================== */   
public with sharing class Job_DiaryController {
    public string userId;
    public List<SchedulerTechDetails> vstList{get;set;}
    public Map<id,SchedulerTechDetails> VisitMap {get; set;}
    public string LoggedUserId;
    public string flgs{get;set;}
    public Job_DiaryController() {
        flgs='';
        LoggedUserId=UserInfo.getUserId();
        system.debug('LoggedUserId'+LoggedUserId);
        vstList=new List<SchedulerTechDetails>();
        VisitMap   = new Map<id,SchedulerTechDetails>();
        loadVisits();
    }

/*================================================================
Method Name: loadVisits
Parameters : Null
Description: 
Date       : 22 Nov 2018  
================================================================*/
    public void loadVisits(){
    
        List<Engineer__c> Se=new List<Engineer__c>();
        if( Schema.sObjectType.Engineer__c.fields.id.isAccessible() ){
            Se=[select id from Engineer__c where Salesforce_User__c=:LoggedUserId limit 1];
            system.debug('Engineer'+se);
       
            if(Test.IsRunningTest()){
             Se=[select id from Engineer__c limit 1];
            }
         
            userId=se[0].id;    
            system.debug('userID'+userId);
        if( Schema.sObjectType.Visits__c.fields.Engineer2__c.isAccessible() && Schema.sObjectType.Visits__c.fields.Name.isAccessible() && Schema.sObjectType.Visits__c.fields.Status__c.isAccessible()
            && Schema.sObjectType.Visits__c.fields.Actual_Service_Date__c.isAccessible() 
            && Schema.sObjectType.Visits__c.fields.Visit_Type__c.isAccessible() 
            &&  Schema.sObjectType.Config__c.isAccessible()
            && Schema.sObjectType.Config__c.fields.Id.isAccessible() && Schema.sObjectType.Visits__c.fields.Id.isAccessible()  
            && Schema.sObjectType.Visits__c.isAccessible() ){

            TimeZone tz = UserInfo.getTimeZone();
            system.debug('tz'+tz);
            SchedulerTechDetails engs;
            
            
        
        for(visits__c vst:[Select id,Engineer2__c,Status__c,Asset_Name__c,Site__r.name,Actual_Service_Date__c,Message_to_Technician__c,Visit_Completed__c,End_Date__c,Requested_Attendance_Time__c,X2nd_Technician__c,job_Status__c,Visit_Complete__c, Name,Visit_Type__c,Asset__c,Asset__r.name,Booking_Notes__c                                                  From Visits__c 
                                                  where Engineer2__c=:userId or X2nd_Technician__c=:userId
                                                  ]){
           engs=new SchedulerTechDetails();
           DateTime Reqdontime ;
           system.debug('Reqdontime'+Reqdontime);  
           Datetime ActSerDate = vst.Actual_Service_Date__c;
           DateTime ActserDates=vst.Actual_Service_Date__c;
           if(vst.Requested_Attendance_Time__c != null){
               String[] reqAttTimeStr = vst.Requested_Attendance_Time__c.split('\\:');
               ActSerDate = ActSerDate.addHours(Integer.valueOf(reqAttTimeStr[0]));
               ActSerDate = ActSerDate.addMinutes(Integer.valueOf(reqAttTimeStr[1]));
           }
           Reqdontime = ActSerDate;
           system.debug('Reqdontime='+Reqdontime); 
           system.debug('ActSerDate= '+ActSerDate);
           system.debug('ActSerDates='+ActSerDate);
           DateTime vstComDate = vst.End_Date__c;
           if(vstComDate != null){
               vstComDate = vstComDate.addHours(23);
           }
           system.debug('vstComDate'+vstComDate );
           engs.SchedulerTitle=vst.Name;
           system.debug('engs.SchedulerTitle'+engs.SchedulerTitle);
           engs.MsgToTech=vst.Message_to_Technician__c;
           engs.SchedulerNotes=vst.Booking_Notes__c;
           system.debug('engs.SchedulerNotes'+engs.SchedulerNotes);
           engs.SchedulerAsset=vst.Asset_Name__c;
           system.debug('engs.SchedulerAsset'+engs.SchedulerAsset);
           engs.SchedulerSitesName =vst.Site__r.name;
           
           if(vst.End_Date__c != null && vst.Actual_Service_Date__c!=null && vst.Requested_Attendance_Time__c!=null){
           engs.SchedulerStart =Reqdontime.format('MM/dd/yyyy HH:mm:ss',string.valueof(tz));
           engs.SchedulerEnd =vstComDate.format('MM/dd/yyyy HH:mm:ss',string.valueof(tz));
           
           }
           system.debug('engs.SchedulerStart'+engs.SchedulerStart);
           system.debug('engs.SchedulerEnd'+engs.SchedulerEnd);
           if(vst.End_Date__c== null && vst.Actual_Service_Date__c!=null && vst.Requested_Attendance_Time__c!=null){
            
                engs.SchedulerStart =Reqdontime.format('MM/dd/yyyy HH:mm:ss',string.valueof(tz));
                engs.SchedulerEnd =Reqdontime.format('MM/dd/yyyy HH:mm:ss',string.valueof(tz));
              }
            system.debug('engs.SchedulerStart1'+engs.SchedulerStart);
            system.debug('engs.SchedulerEnd1'+engs.SchedulerEnd);
           if(vst.End_Date__c != null && vst.Actual_Service_Date__c!=null && vst.Requested_Attendance_Time__c==null){
           engs.SchedulerStart =ActserDates.format('MM/dd/yyyy HH:mm:ss',string.valueof(tz));
           engs.SchedulerEnd =vstComDate.format('MM/dd/yyyy HH:mm:ss',string.valueof(tz));
           
           }
            system.debug('engs.SchedulerStart2'+engs.SchedulerStart);
            system.debug('engs.SchedulerEnd2'+engs.SchedulerEnd);
            if(vst.End_Date__c== null && vst.Actual_Service_Date__c!=null && vst.Requested_Attendance_Time__c==null){
            
                engs.SchedulerStart =ActserDates.format('MM/dd/yyyy HH:mm:ss',string.valueof(tz));
                engs.SchedulerEnd =ActserDates.format('MM/dd/yyyy HH:mm:ss',string.valueof(tz));
              }
            system.debug('engs.SchedulerStart3'+engs.SchedulerStart);
            system.debug('engs.SchedulerEnd3'+engs.SchedulerEnd);
            engs.SchedulerURL = '/' + vst.Id ;
            system.debug('engs.SchedulerURL'+engs.SchedulerURL);
             if(vst.Visit_Complete__c )
                engs.SchedulerName ='#32CD32';
             else
                engs.SchedulerName ='Red';
                system.debug(engs.SchedulerName);
            VisitMap.put(vst.id,engs);   
        }  
        }
        }
    }
 /*=========================================================================================================
    *Class Name     : SchedulerTechDetails
    *Description    : Inner class(wrapper class)
    *Company        : Merfantz
    *Date           : 22 Nov 2018  
 ============================================================================================================== */      
    public class SchedulerTechDetails{       
        Public String SchedulerStart {get;set;}
        Public String SchedulerEnd {get;set;}
        Public String SchedulerURL {get;set;}
        Public String SchedulerName {get;set;}
        public String SchedulerTitle {get;set;}
        public String MsgToTech{get;set;}
        public String SchedulerAsset{get;set;}
        public String SchedulerNotes{get;set;}
        public String SchedulerSitesName {get;set;}     
        
    }

}