objects/Account/fields/Complaint_Details__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Details__c</fullName>
    <label>Complaint Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Complaints__c/Complaints__c.object-meta.xml
<CustomObject>
    <description>Used to record customer complaints.</description>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Compliant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Complaints__c/fields/Complaint_Details__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Details__c</fullName>
    <label>Complaint Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Complaints__c/fields/Customer_Site__c.field-meta.xml
<CustomField>
    <fullName>Customer_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Complaints</relationshipLabel>
    <relationshipName>Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Complaints__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Complaints__c/fields/Passed_To__c.field-meta.xml
<CustomField>
    <fullName>Passed_To__c</fullName>
    <inlineHelpText>Enter the name of the person you passed this onto to complete.</inlineHelpText>
    <label>Passed To</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adrian Warne</fullName>
            </value>
            <value>
                <fullName>Alison Read</fullName>
            </value>
            <value>
                <fullName>Anne Bassinder</fullName>
            </value>
            <value>
                <fullName>Beverley Harris</fullName>
            </value>
            <value>
                <fullName>Chester Bidmead</fullName>
            </value>
            <value>
                <fullName>Darren Crompton</fullName>
            </value>
            <value>
                <fullName>Diana Pascoe</fullName>
            </value>
            <value>
                <fullName>Gwen Bradby</fullName>
            </value>
            <value>
                <fullName>Harvey Melvin</fullName>
            </value>
            <value>
                <fullName>Joanna Fyffe</fullName>
            </value>
            <value>
                <fullName>Joel Bidmead</fullName>
            </value>
            <value>
                <fullName>Laura Borthwick</fullName>
            </value>
            <value>
                <fullName>Michelle Bassinder</fullName>
            </value>
            <value>
                <fullName>Natasha Blake</fullName>
            </value>
            <value>
                <fullName>Nicki Pratten</fullName>
            </value>
            <value>
                <fullName>Nigel Welch</fullName>
            </value>
            <value>
                <fullName>Paul Faraway</fullName>
            </value>
            <value>
                <fullName>Phil Bassinder</fullName>
            </value>
            <value>
                <fullName>Rachel Dowrick</fullName>
            </value>
            <value>
                <fullName>Rachel Yelland</fullName>
            </value>
            <value>
                <fullName>Samantha Cavinder</fullName>
            </value>
            <value>
                <fullName>Samantha Spencer</fullName>
            </value>
            <value>
                <fullName>Sarah Bayley</fullName>
            </value>
            <value>
                <fullName>Sharon Standen</fullName>
            </value>
            <value>
                <fullName>Tracey Coles</fullName>
            </value>
            <value>
                <fullName>Viv Stuchberry</fullName>
            </value>
            <value>
                <fullName>Warren Bidmead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Complaints__c/fields/Passed_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Passed_To_Email__c</fullName>
    <label>Passed To Email</label>
    <type>Email</type>
</CustomField>

objects/Complaints__c/fields/Recorded_By__c.field-meta.xml
<CustomField>
    <fullName>Recorded_By__c</fullName>
    <label>Recorded By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adrian Warne</fullName>
            </value>
            <value>
                <fullName>Alison Read</fullName>
            </value>
            <value>
                <fullName>Anne Bassinder</fullName>
            </value>
            <value>
                <fullName>Beverley Harris</fullName>
            </value>
            <value>
                <fullName>Chester Bidmead</fullName>
            </value>
            <value>
                <fullName>Darren Crompton</fullName>
            </value>
            <value>
                <fullName>Diana Pascoe</fullName>
            </value>
            <value>
                <fullName>Gwen Bradby</fullName>
            </value>
            <value>
                <fullName>Harvey Melvin</fullName>
            </value>
            <value>
                <fullName>Joanna Fyffe</fullName>
            </value>
            <value>
                <fullName>Joel Bidmead</fullName>
            </value>
            <value>
                <fullName>Laura Borthwick</fullName>
            </value>
            <value>
                <fullName>Michelle Bassinder</fullName>
            </value>
            <value>
                <fullName>Natasha Blake</fullName>
            </value>
            <value>
                <fullName>Nicki Pratten</fullName>
            </value>
            <value>
                <fullName>Nigel Welch</fullName>
            </value>
            <value>
                <fullName>Paul Faraway</fullName>
            </value>
            <value>
                <fullName>Phil Bassinder</fullName>
            </value>
            <value>
                <fullName>Rachel Dowrick</fullName>
            </value>
            <value>
                <fullName>Rachel Yelland</fullName>
            </value>
            <value>
                <fullName>Samantha Cavinder</fullName>
            </value>
            <value>
                <fullName>Samantha Spencer</fullName>
            </value>
            <value>
                <fullName>Sarah Bayley</fullName>
            </value>
            <value>
                <fullName>Sharon Standen</fullName>
            </value>
            <value>
                <fullName>Tracey Coles</fullName>
            </value>
            <value>
                <fullName>Viv Stuchberry</fullName>
            </value>
            <value>
                <fullName>Warren Bidmead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Complaints__c/fields/Reported_to_Manager__c.field-meta.xml
<CustomField>
    <fullName>Reported_to_Manager__c</fullName>
    <label>Reported to Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/ComplaintTriggerHandlerTest.cls
@isTest(SeeAllData=true)
public class ComplaintTriggerHandlerTest{
    @isTest public static void passComplaintsTest(){
        Test.StartTest();
        Account newAccount=new Account(Name='Test Account');
        insert newAccount;  
        list<Complaints__c> compList =new list<Complaints__c>();
        Complaints__c comp=new Complaints__c(Customer_Site__c=newAccount.id);
        insert comp;
        list<Complaints__c> complaintList=[SELECT Id,Customer_Site__c,Department__c,Recorded_By__c,Complaint_Details__c,
                                            Reported_to_Manager__c,Passed_To_Email__c,Passed_To__c 
                                             FROM Complaints__c WHERE Customer_Site__c!=NULL  Limit 1];
        Complaints__c newComp;
        for(Complaints__c oldComp:complaintList){
          newComp=oldComp.clone();
          newComp.Customer_Site__c=newAccount.id;
          newComp.Passed_To_Email__c='testing@puthuvannam.com';
          newComp.Department__c='Service';
          newComp.Complaint_Details__c='Test Service';
          newComp.Recorded_By__c='Tester';
          newComp.Reported_to_Manager__c='No';
          compList.add(newComp);
        }
        insert compList;
         for(Complaints__c newComplaint:compList){
            newComplaint.Passed_To_Email__c='test@puthuvannam.com';
        }
        update compList;
        Test.StopTest(); 
   
    }
    }