objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Price_List_Correct__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Correct__c</fullName>
    <inlineHelpText>This is the date on which the pricing level for this customer was last checked.</inlineHelpText>
    <label>Price List Correct</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Pricebook_Name__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Name__c</fullName>
    <formula>Price_Book__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricebook Name</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <formula>IF(Service_Sheet__c &lt;&gt; &quot;&quot;, Service_Sheet__r.Service_Sheet_Type__c, Reactive_Sheet__r.Sheets_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Type</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Opportunities created when converting lead</description>
    <label>Sales</label>
</RecordType>

objects/OpportunityLineItem/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/OpportunityLineItem/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product2/fields/Product_Name_Check__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Check__c</fullName>
    <inlineHelpText>Enter the product name again in here, and it will check to see if there is another product already created with this name, when you save. This is to avoid duplicates.</inlineHelpText>
    <label>Product Name Check</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Product2/fields/UniqueSageCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueSageCode__c</fullName>
    <inlineHelpText>This is the unique Sage Code, being a combination of the Sage Code and the Nominal Code. It is a required field on the product, and also is the unique external link to Sage.</inlineHelpText>
    <label>Eclipse Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer disinfector</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Service Type</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SalesOrder__c/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/SalesOrderLineItems__c/SalesOrderLineItems__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sales_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesOrderTriggerHandlertest.cls
@isTest(seeAllData=true)
public class SalesOrderTriggerHandlertest {
          
static testMethod void Test1()
{
   			Id SalesRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();

    		Product2 p = new Product2(Name='test other', ProductCode = OpportunityLineItemHandler.OTHER_CODE,UniqueSageCode__c='test2',Product_Name_Check__c='10 Person First Aid Kit Product 2_test2',Isactive=true);
            insert p;
            
            Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
            
            PricebookEntry pbe = new PricebookEntry(UnitPrice=50, Pricebook2Id=standardPB.Id, Product2Id=p.Id, IsActive=true);
            insert pbe;
            
            Account acc=new Account();
            acc.name='test';
            acc.Price_Book__c=standardPB.id;
            acc.Customer_type__c='Private Healthcare';
            acc.Price_List_Correct__c=system.today();
            insert acc;
    	
    		Warehouse__c WH=new Warehouse__c();
            WH.Name='Test';
            insert WH;
    
    		Opportunity opp = new Opportunity(Name='Test opp',recordTypeID=SalesRecTypeId, StageName='New', CloseDate=Date.today(),AccountId=[select id from Account where Price_Book__c!=null and Pricebook_Name__c='Standard Price Book' limit 1].id);
            insert opp;    
            
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1,Warehouse__c=WH.id,Product2id=p.id, PricebookEntryId=pbe.Id, TotalPrice=50);
            insert oli;
    
    		SalesOrder__c Sales=new SalesOrder__c();
            Sales.Account__c=acc.Id;
            Sales.Service_Type__c='Air Compressor';
    		sales.Opportunity__c = opp.id;
    		sales.Show_Description__c = false;
            insert Sales;
    
            SalesOrderLineItems__c Soli=new SalesOrderLineItems__c();
            Soli.Product__c=p.Id;
    		
            Soli.Quantity__c=1;
            Soli.Sales_Order__c=Sales.id;
            Soli.Price__c=12;
            insert Soli;
            
            SalesOrderLineItems__c Soli1=new SalesOrderLineItems__c();
            Soli1.Product__c=p.Id;
            Soli1.Quantity__c=1;
            Soli1.Sales_Order__c=Sales.id;
            Soli1.Price__c=12;
            insert Soli1;
    
    		

    
    Map<Id,SalesOrder__c>son = new Map<Id,SalesOrder__c>();
    son.put(sales.id,sales);
    
    Map<Id,SalesOrder__c>soo = new Map<Id,SalesOrder__c>();
    soo.put(sales.id,sales);
    test.starttest();
    
    SalesOrderTriggerHandler SA= new SalesOrderTriggerHandler();
    SA.InsertOLIPrds(son,soo);
    SA.UpdateStage(son,soo);
    
    sales.Show_Description__c = true;
    update sales;
    
    SA.showdesc(son,soo);
    
    test.stoptest();

}
}