objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Opportunity/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Opportunity/fields/AmountCredited__c.field-meta.xml
<CustomField>
    <fullName>AmountCredited__c</fullName>
    <label>AmountCredited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Opportunity/fields/ExpectedPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedPaymentDate__c</fullName>
    <label>ExpectedPaymentDate</label>
    <type>Date</type>
</CustomField>

objects/Opportunity/fields/FullyPaidOnDate__c.field-meta.xml
<CustomField>
    <fullName>FullyPaidOnDate__c</fullName>
    <label>FullyPaidOnDate</label>
    <type>Date</type>
</CustomField>

objects/Opportunity/fields/PlannedPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>PlannedPaymentDate__c</fullName>
    <label>PlannedPaymentDate</label>
    <type>Date</type>
</CustomField>

objects/Opportunity/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Xero Invoice No.</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/XeroOppId__c.field-meta.xml
<CustomField>
    <fullName>XeroOppId__c</fullName>
    <label>Xero Invoice Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/XeroInvoiceBatchScheduleTest.cls
@isTest
/*============================================================================================================
*Class Name     : XeroInvoiceBatchScheduleTest 
*Description    : All the implementations are related to test XeroInvoiceBatchSchedule.
*Company        : Merfantz Technologies Pvt Ltd
*Date           : 23rd Sept, 2020
*Version        : 1.0
*Change History : Initial class
*Methods        : static testmethod void schedulerTest()                 
*============================================================================================================*/
private class XeroInvoiceBatchScheduleTest{
   
/*====================================================
*Method Name     : schedulerTest
*Description     : This method tests XeroInvoiceBatchSchedule.
*Arguments       : No arguments
*Ticket No       : 46671
====================================================*/
    static testmethod void schedulerTest(){ 
    
        String CRON_EXP = '0 0 0 15 3 ? *';
        
        // Create your test data
        Account a = new Account(Name = 'Test Account',Customer_type__c='Dental Practice');
            insert a;
            
            Warehouse__c wh=new Warehouse__c();
            wh.name='Test';
            wh.default__c=true;
            insert wh;
        
        
            Opportunity o = new Opportunity();
            o.AccountId = a.Id;
            o.Name = 'Test';
            o.StageName = 'Prospecting';
            o.CloseDate = date.today();   
            o.Type = 'New Business';
            o.Invoice_Date__c=system.today()-6;
            o.Due_Date__c=system.today()-1;
            o.XeroOppId__c='123456INV';
            o.Reference__c=null;
            o.ExpectedPaymentDate__c=null;
            o.PlannedPaymentDate__c=null;
            o.FullyPaidOnDate__c=null;
            o.Amount_Paid__c=0;
            o.AmountCredited__c=0;
            o.Amount_Due__c=0;
            insert o;
        
        Test.startTest();

            String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new XeroInvoiceBatchSchedule());
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(CRON_EXP, ct.CronExpression);
            System.assertEquals(0, ct.TimesTriggered);

        Test.stopTest();
        
    }
}