objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Maximum_stock_level__c.field-meta.xml
<CustomField>
    <fullName>Maximum_stock_level__c</fullName>
    <label>Maximum stock level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product2/fields/Min_Stock__c.field-meta.xml
<CustomField>
    <fullName>Min_Stock__c</fullName>
    <label>Re-order stock level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product2/fields/Supplier_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product_Code__c</fullName>
    <label>Supplier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Create_Date__c</fullName>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

objects/PurchaseOrder__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <label>Created By</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tim Boyt</fullName>
            </value>
            <value>
                <fullName>Merfantz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PurchaseOrder__c/fields/Document_Creator__c.field-meta.xml
<CustomField>
    <fullName>Document_Creator__c</fullName>
    <label>Document Creator</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

objects/PurchaseOrder__c/fields/Shipping_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>Purchase Order List No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Supplier_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product_Code__c</fullName>
    <label>Supplier Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Total_Received_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Received_Quantity__c</fullName>
    <label>Total Received Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Purchase_Order__r.Shipping_Warehouse__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QRCodeControllerTest.cls
@isTest(seeAllData=true)
public class QRCodeControllerTest {
    public static @isTest void m1(){
        
        Account Acc=new Account();
        Acc.Name='Test';
        Acc.Customer_type__c='Others';
        insert Acc;
        
        Warehouse__c WH=new Warehouse__c();
        WH.Name='Test';
        insert WH;
     
        PurchaseOrder__c PO=new PurchaseOrder__c();
        PO.Shipping_Warehouse__c=WH.id;
        PO.Create_Date__c=system.today();
        po.created_by__c='test';
        po.Document_Creator__c='test@gmail.com'; 

        insert PO;
        
        product2 prd=new product2();
        prd.Name='Test Product';
        prd.IsActive=true;
        prd.ProductCode='TES124';
        prd.Cost__c=12;
        prd.Supplier_Product_Code__c='Test1';
        prd.Min_Stock__c=2;
        prd.Maximum_stock_level__c=3;
        insert prd;
        Test.startTest();
        PurchaseOrderLineItem__c POLine=new PurchaseOrderLineItem__c();
        POLine.Purchase_Order__c=PO.id;
        POLine.Product__c=prd.id;
        POLine.Quantity__c=1;
        POLine.Total_Received_Quantity__c=1;
        POLine.Price__c=1;
        insert POLine;
        
        Pagereference pageref=Page.GenerateProductLabels;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',po.id);
        QRCodeController controller=new QRCodeController();
        controller.saveToPdf();
        controller.renderingAsHtml();
        controller.renderedFileName='TestPDF';
       }
}