objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Price_List_Correct__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Correct__c</fullName>
    <inlineHelpText>This is the date on which the pricing level for this customer was last checked.</inlineHelpText>
    <label>Price List Correct</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BN Zone D</fullName>
            </value>
            <value>
                <fullName>BR Zone B</fullName>
            </value>
            <value>
                <fullName>Central London (E,EC,WC,W)</fullName>
            </value>
            <value>
                <fullName>CM Zone C</fullName>
            </value>
            <value>
                <fullName>CR Zone C</fullName>
            </value>
            <value>
                <fullName>CT Zone C</fullName>
            </value>
            <value>
                <fullName>CN Zone D</fullName>
            </value>
            <value>
                <fullName>DA Zone A</fullName>
            </value>
            <value>
                <fullName>E Zone C</fullName>
            </value>
            <value>
                <fullName>GU Zone D</fullName>
            </value>
            <value>
                <fullName>HA Zone D</fullName>
            </value>
            <value>
                <fullName>HP Zone D</fullName>
            </value>
            <value>
                <fullName>IG Zone C</fullName>
            </value>
            <value>
                <fullName>KT Zone C</fullName>
            </value>
            <value>
                <fullName>ME Zone B</fullName>
            </value>
            <value>
                <fullName>MK Zone D</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PO Zone E</fullName>
            </value>
            <value>
                <fullName>RG Zone D</fullName>
            </value>
            <value>
                <fullName>RH Zone C</fullName>
            </value>
            <value>
                <fullName>RM Zone B</fullName>
            </value>
            <value>
                <fullName>SE Zone C</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>SL Zone D</fullName>
            </value>
            <value>
                <fullName>SM Zone C</fullName>
            </value>
            <value>
                <fullName>SO Zone D</fullName>
            </value>
            <value>
                <fullName>S- Scotland</fullName>
            </value>
            <value>
                <fullName>SS Zone C</fullName>
            </value>
            <value>
                <fullName>SW Zone C&amp;D</fullName>
            </value>
            <value>
                <fullName>TW Zone D</fullName>
            </value>
            <value>
                <fullName>UB Zone D</fullName>
            </value>
            <value>
                <fullName>WF (NHS)</fullName>
            </value>
            <value>
                <fullName>AL Zone D</fullName>
            </value>
            <value>
                <fullName>CO Zone D</fullName>
            </value>
            <value>
                <fullName>IP Zone D</fullName>
            </value>
            <value>
                <fullName>LU Zone D</fullName>
            </value>
            <value>
                <fullName>WD Zone D</fullName>
            </value>
            <value>
                <fullName>EN Zone C</fullName>
            </value>
            <value>
                <fullName>OX Zone D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TriggerActive__c/TriggerActive__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>AccountTrigger</description>
    <label>TriggerActive</label>
</CustomObject>

classes/AccountTriggerHandlerTest.cls
/*
*Oraganization: Puthuvannam Technology Solutions
*/

@isTest(seeAlldata=true)
Public Class AccountTriggerHandlerTest{
    @isTest Public static void UpdatePriceListDateTest() {  
        
        TriggerActive__c customsetting = new TriggerActive__c();
        customsetting.IsActive__c =true;
        customsetting.Name ='test';
        Insert customsetting;
        
        Account acc=new Account();
        acc.name='test';
        acc.Price_List_Correct__c=system.today();
        acc.Customer_type__c='Prison';
        insert acc;
        acc.Customer_type__c='Prison';
        Update acc;

        //
 
        acc.Region__c='BN Zone D';
        update acc;
        
        acc.Region__c='BR Zone B';
        update acc;
        
        acc.Region__c='Central London (E,EC,WC,W)';
        update acc;
        
        acc.Region__c='BN Zone D';
        update acc;
        
        acc.Region__c='CM Zone C';
        update acc;
        
        acc.Region__c='HA Zone D';
        update acc;
        
        acc.Region__c='HP Zone D';
        update acc;
        
        acc.Region__c='CR Zone C';
        update acc;
        
        acc.Region__c='CT Zone C';
        update acc;
        
        acc.Region__c='CN Zone D';
        update acc;

        
        acc.Region__c='GU Zone D';
        update acc;
        
        acc.Region__c='DA Zone A';
        update acc;
        
        acc.Region__c='IG Zone C';
        update acc;
        
        acc.Region__c='KT Zone C';
        update acc;
        
        acc.Region__c='MK Zone D';
        update acc;
        
        acc.Region__c='ME Zone B';
        update acc;
        
        acc.Region__c='NL';
        update acc;
        
        acc.Region__c='North London (NW,N,EN)';
        update acc;
        
        acc.Region__c='Other';
        update acc;
        
        
        acc.Region__c='PO Zone E';
        update acc;
        
        
        acc.Region__c='RG Zone D';
        update acc;
        
        
        acc.Region__c='RM Zone B';
        update acc;
        
        
        acc.Region__c='RH Zone C';
        update acc;
        
        
        acc.Region__c='SE Zone C';
        update acc;
        
        
        acc.Region__c='SL Zone D';
        update acc;
        
        
        acc.Region__c='SG';
        update acc;
        
        
        acc.Region__c='SM Zone C';
        update acc;
        
        acc.Region__c='SO Zone D';
        update acc;
        
        acc.Region__c='S- Scotland';
        update acc;
        
        acc.Region__c='SS Zone C';
        update acc;
        
        acc.Region__c='SW Zone C&D';
        update acc;
        
        acc.Region__c='TW Zone D';
        update acc;
        
        acc.Region__c='UB Zone D';
        update acc;
        
        acc.Region__c='WF (NHS)';
        update acc;
        
        acc.Region__c='TN Zone B & C';
        update acc;

        acc.Region__c='E Zone C';
        update acc;
       
        acc.Region__c='AL Zone D';
        update acc;

        acc.Region__c='IP Zone D';
        update acc;
       
        acc.Region__c='CO Zone D';
        update acc;

        acc.Region__c='EN Zone C';
        update acc;

        acc.Region__c='WD Zone D';
        update acc;

        acc.Region__c='LU Zone D';
        update acc;

        acc.Region__c='OX Zone D';
        update acc;
  
        
        
        Account exAccount=[Select id,Price_List_Correct__c from Account LIMIT 1];
        //Update the 'Price_List_Correct__c' Field
        exAccount.Price_List_Correct__c=system.today();
        update exAccount;
        
        list<Account> ChildRecords = [Select id,Parentid,Price_List_Correct__c from account where parentid = :exAccount.id limit 1];
        
        /*   for (Account childrecord : ChildRecords) {            
system.assertEquals(childrecord.Price_List_Correct__c,system.today(),'Price List Correct is not Updated');
}  */
    }
}