objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Price_List_Correct__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Correct__c</fullName>
    <inlineHelpText>This is the date on which the pricing level for this customer was last checked.</inlineHelpText>
    <label>Price List Correct</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Pricebook_Name__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Name__c</fullName>
    <formula>Price_Book__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricebook Name</label>
    <type>Text</type>
</CustomField>

objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <description>Inventory Transaction</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory_Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Inventory__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>In Vehicle</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Inventory_Transaction__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Inventory__r.Warehouse__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Other_Product_Qty__c.field-meta.xml
<CustomField>
    <fullName>Other_Product_Qty__c</fullName>
    <label>Other Product Qty</label>
    <summaryFilterItems>
        <field>OpportunityLineItem.Is_Other_Product__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Opportunity/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <formula>IF(Service_Sheet__c &lt;&gt; &quot;&quot;, Service_Sheet__r.Service_Sheet_Type__c, Reactive_Sheet__r.Sheets_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Type</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Opportunities created when converting lead</description>
    <label>Sales</label>
</RecordType>

objects/OpportunityLineItem/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/OpportunityLineItem/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product2/fields/Product_Name_Check__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Check__c</fullName>
    <inlineHelpText>Enter the product name again in here, and it will check to see if there is another product already created with this name, when you save. This is to avoid duplicates.</inlineHelpText>
    <label>Product Name Check</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Product2/fields/UniqueSageCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueSageCode__c</fullName>
    <inlineHelpText>This is the unique Sage Code, being a combination of the Sage Code and the Nominal Code. It is a required field on the product, and also is the unique external link to Sage.</inlineHelpText>
    <label>Eclipse Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer disinfector</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Service Type</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SalesOrder__c/fields/Show_Description__c.field-meta.xml
<CustomField>
    <fullName>Show_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Description</label>
    <type>Checkbox</type>
</CustomField>

objects/SalesOrderLineItems__c/SalesOrderLineItems__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sales_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/OpportunityTriggerHandlerTest.cls
@isTest (seeAllData=true)
/*============================================================================================================
*Class Name     : OpportunityTriggerHandlerTest
*Description    : All the implementations related to test OpportunityTriggerHandler.
*Company        : Merfantz Technologies Pvt Ltd
*Date           : 25th Jun, 2020
*Version        : 1.0
*Change History : Initial class
*Methods        : public static testMethod void oliInsertNoOther() {
                  
*============================================================================================================*/
private class OpportunityTriggerHandlerTest {

/*====================================================
*Method Name     : oliInsertNoOther
*Description     : This method test OpportunityTriggerHandler class.
*Arguments       : No Arguments
*Ticket No       : 40744
====================================================*/
    public static testMethod void oliInsertNoOther() {
            Id SalesRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
            Product2 p = new Product2(Name='test other', ProductCode = OpportunityLineItemHandler.OTHER_CODE,UniqueSageCode__c='test2',Product_Name_Check__c='10 Person First Aid Kit Product 2_test2',Isactive=true);
            insert p;
            
            Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
            
            PricebookEntry pbe = new PricebookEntry(UnitPrice=50, Pricebook2Id=standardPB.Id, Product2Id=p.Id, IsActive=true);
            insert pbe;
            
            Account acc=new Account();
            acc.name='test';
            acc.Price_Book__c=standardPB.id;
            acc.Customer_type__c='Private Healthcare';
            acc.Price_List_Correct__c=system.today();
            insert acc;
            
            SalesOrder__c Sales=new SalesOrder__c();
            Sales.Account__c=acc.Id;
            Sales.Service_Type__c='Air Compressor';
            insert Sales;
            
            SalesOrderLineItems__c Soli=new SalesOrderLineItems__c();
            Soli.Product__c=p.Id;
            Soli.Quantity__c=1;
            Soli.Sales_Order__c=Sales.id;
            Soli.Price__c=12;
            insert Soli;
            
            SalesOrderLineItems__c Soli1=new SalesOrderLineItems__c();
            Soli1.Product__c=p.Id;
            Soli1.Quantity__c=1;
            Soli1.Sales_Order__c=Sales.id;
            Soli1.Price__c=12;
            insert Soli1;
            
            Warehouse__c WH=new Warehouse__c();
            WH.Name='Test';
            insert WH;
            
            Inventory__c inv=new Inventory__c();
            inv.Warehouse__c=WH.id;
            inv.Product__c=p.id;
            insert inv;
            System.assertEquals(inv.Warehouse__c, WH.id);
            Inventory_Transaction__c invtr=new Inventory_Transaction__c();
            invtr.name=inv.name;
            invtr.qty__c=3;
            invtr.Inventory__c=inv.id;
            invtr.Transaction_Type__c='Received';
            
            insert invtr;          
            
            Opportunity opp = new Opportunity(Name='Test opp',recordTypeID=SalesRecTypeId, StageName='New', CloseDate=Date.today(),Sales_Order__c=Sales.id,AccountId=[select id from Account where Price_Book__c!=null and Pricebook_Name__c='Standard Price Book' limit 1].id);
                        insert opp;    
            Id opId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Invoice (To Invoice)').getRecordTypeId();
            opp.recordTypeID=opId;
            opp.StageName='sent';
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1,Warehouse__c=WH.id,Product2id=p.id, PricebookEntryId=pbe.Id, TotalPrice=50);
            
            insert oli;
            System.assertEquals(oli.Warehouse__c, WH.id);

            opp.Show_Description__c=true;
            update opp;
            opp = [SELECT Other_Product_Qty__c FROM Opportunity WHERE Id = :opp.Id];
            
            system.assertEquals(0, opp.Other_Product_Qty__c);
        
    }
    }