objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Nominal_Code__c.field-meta.xml
<CustomField>
    <fullName>Nominal_Code__c</fullName>
    <label>Nominal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <description>Inventory Transaction</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory_Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Inventory_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Items__c.field-meta.xml
<CustomField>
    <fullName>Items__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Moving Status</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Inventory__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>In Vehicle</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Inventory_Transaction__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Inventory__r.Warehouse__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <formula>IF(Service_Sheet__c &lt;&gt; &quot;&quot;, Service_Sheet__r.Service_Sheet_Type__c, Reactive_Sheet__r.Sheets_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Type</label>
    <type>Text</type>
</CustomField>

objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Opportunities created when converting lead</description>
    <label>Sales</label>
</RecordType>

objects/OpportunityLineItem/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product2/fields/Nominal_Code__c.field-meta.xml
<CustomField>
    <fullName>Nominal_Code__c</fullName>
    <label>Nominal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Non_Stock__c.field-meta.xml
<CustomField>
    <fullName>Non_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non Stock</label>
    <type>Checkbox</type>
</CustomField>

objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesOrder__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>Getinge Autoclave</fullName>
            </value>
            <value>
                <fullName>Getinge Washer Disinfector</fullName>
            </value>
            <value>
                <fullName>Mechanical X-Ray</fullName>
            </value>
            <value>
                <fullName>Medisafe Washer disinfector</fullName>
            </value>
            <value>
                <fullName>Report of Examination</fullName>
            </value>
            <value>
                <fullName>Service Type</fullName>
            </value>
            <value>
                <fullName>Suction Pump</fullName>
            </value>
            <value>
                <fullName>Treatment Centre</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SalesOrderLineItems__c/SalesOrderLineItems__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesOrderLineItems__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Sales_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Remaining_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Quantity__c</fullName>
    <formula>Quantity__c- Total_Number_of_Product_Delivered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Serialized__c.field-meta.xml
<CustomField>
    <fullName>Serialized__c</fullName>
    <formula>Product__r.Serialized__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serialized</label>
    <type>Checkbox</type>
</CustomField>

objects/SalesOrderLineItems__c/fields/Total_Number_of_Product_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Product_Delivered__c</fullName>
    <label>Total Number of Product Delivered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/SitePartsUpdateTest.cls
@isTest(SeeAllData=true)
public class SitePartsUpdateTest{
    static testMethod void SitePartsUpdateMethod(){
        Test.startTest();
        List<PricebookEntry> NewEntry=new List<PricebookEntry>();
        PricebookEntry priceBookEntryNew;
        List<Product2> PrdList=new List<Product2>();
        
        Product2 product;        
        Id pb2= Test.getStandardPricebookId();
        
        product = new Product2();
        product.name = 'Test';
        product.ProductCode='Test';
        product.Nominal_Code__c='Test';
        product.isactive=true;
        PrdList.add(product);
        
        product = new Product2();
        product.name = 'Test Nonstock';
        product.ProductCode='Test Non';
        product.Nominal_Code__c='Test Non';
        product.Non_Stock__c=true;
        product.isactive=true;
        PrdList.add(product);
        
        product = new Product2();
        product.name = 'Test Serial';
        product.ProductCode='Test Ser';
        product.Nominal_Code__c='Test Ser';
        product.Serialized__c=true;
        product.isactive=true;
        PrdList.add(product);
        
        insert PrdList;
        
        for(Product2 Prd:PrdList){
            priceBookEntryNew = new PricebookEntry();
            priceBookEntryNew.Product2Id = Prd.Id;
            priceBookEntryNew.PriceBook2Id = pb2;
            priceBookEntryNew.UnitPrice = 20.00;
            priceBookEntryNew.isactive = true;
            NewEntry.add(priceBookEntryNew);
        }
        
        insert NewEntry;
        
        Account a = new Account(Name = 'Test Account');
        a.Customer_type__c='Others';
        insert a;
        
        Opportunity o = new Opportunity();        
        o.AccountId = a.Id;
        o.Name = 'Test';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
        o.Pricebook2Id=pb2;
        o.Type = 'New Business';
        insert o;
        
        List<OpportunityLineItem> Listol = new List<OpportunityLineItem>();               
        for(PricebookEntry Pe:NewEntry){
        OpportunityLineItem oli = new OpportunityLineItem
            (
                OpportunityId =o.Id,
                PricebookEntryId = Pe.Id,
                Quantity = 2,
                UnitPrice = Pe.UnitPrice, 
                ServiceDate = System.today()
            );
            Listol.add(oli);
        }
      insert Listol;
    
    SalesOrder__c Sales=new SalesOrder__c();
    Sales.Account__c=a.Id;
    Sales.Opportunity__c=o.Id;
    Sales.Service_Type__c='Air Compressor';
    insert Sales;
    
    Warehouse__c wa=new Warehouse__c();
    wa.Name='Ware';
    insert wa;
    
    List<Inventory__c> NewINvList=new List<Inventory__c>();
    Inventory__c inv;
    for(Product2 Prd:PrdList){
        inv=new Inventory__c();
        inv.Product__c=Prd.Id;
        inv.Warehouse__c=wa.id;
        NewINvList.add(inv);
    }    
    insert NewINvList;
    

        
    List<Inventory_Transaction__c> InvList=new List<Inventory_Transaction__c>();
    Inventory_Transaction__c IT;
    for(Inventory__c InvLoop:NewINvList){
        IT=new Inventory_Transaction__c();
        IT.Name=InvLoop.Id;
        IT.Qty__c=1;
        IT.Inventory__c=InvLoop.id;
        IT.Items__c=Invloop.Product__c;
        IT.Transaction_Type__c='Received';
        InvList.add(IT);    
    }
    
    insert InvList;
    
    Test.setCurrentPageReference(new PageReference('Page.UpdateSiteParts'));    
    System.currentPageReference().getParameters().put('id',String.valueof(Sales.Id));
    System.currentPageReference().getParameters().put('oid',String.valueof(o.Id));
    System.currentPageReference().getParameters().put('AccId',String.valueof(a.Id));
        
    ApexPages.StandardController sc = new ApexPages.StandardController(Sales);
    SitePartsUpdate Spu=new SitePartsUpdate(sc);    
     
    for(SalesOrderLineItems__c Nonstock:[select Id,Product__c,Price__c,Product__r.Name,Quantity__c,Remaining_Quantity__c,Total_Number_of_Product_Delivered__c from SalesOrderLineItems__c where Non_Stock__c=true and Sales_Order__c=:Sales.id and Remaining_Quantity__c>0]){
       SitePartsUpdate.NotStockWrap Wrapvar = new SitePartsUpdate.NotStockWrap(Nonstock.Id,Nonstock.Product__c,Nonstock.Quantity__c,Nonstock.Product__r.Name,1,Nonstock.Total_Number_of_Product_Delivered__c!=null?Nonstock.Total_Number_of_Product_Delivered__c:0,Nonstock.Remaining_Quantity__c,true,Nonstock.Price__c,'','');
       Spu.NewStock.add(Wrapvar);
   }   
    
   for(SalesOrderLineItems__c NonSerial:[select Id,Product__c,Price__c,Product__r.Name,Quantity__c,Remaining_Quantity__c,Total_Number_of_Product_Delivered__c from SalesOrderLineItems__c where Serialized__c=false and Non_Stock__c=false and Sales_Order__c=:Sales.id and Remaining_Quantity__c>0]){
       SitePartsUpdate.NonSerializeWrap Wrapvar1=new SitePartsUpdate.NonSerializeWrap(NonSerial.Id,NonSerial.Product__c,NonSerial.Quantity__c,NonSerial.Product__r.Name,1,NonSerial.Total_Number_of_Product_Delivered__c!=null?NonSerial.Total_Number_of_Product_Delivered__c:0,NonSerial.Remaining_Quantity__c,true,NonSerial.Price__c,'','');
       Spu.NewNonSerial.add(Wrapvar1);
   }
            
   for(SalesOrderLineItems__c Serial:[select Id,Product__c,Price__c,Product__r.Name,Quantity__c,Remaining_Quantity__c,Total_Number_of_Product_Delivered__c from SalesOrderLineItems__c where Serialized__c=true and Sales_Order__c=:Sales.id and Remaining_Quantity__c>0]){
       SitePartsUpdate.SerializeWrap Wrapvar2=new SitePartsUpdate.SerializeWrap(Serial.Id,Serial.Product__c,'',Serial.Quantity__c,Serial.Product__r.Name,1,Serial.Total_Number_of_Product_Delivered__c!=null?Serial.Total_Number_of_Product_Delivered__c:0,Serial.Remaining_Quantity__c,true,Serial.Price__c,'','');
       Spu.NewSerial.add(Wrapvar2);
   } 
                      
    Spu.NonStockQtyCheck();
    Spu.SaveAction();     
    Test.stopTest();
    }
    


}