objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
                <label>Group (over 5 practices)</label>
            </value>
            <value>
                <fullName>Medical (inc. Hospital w/o dental)</fullName>
            </value>
            <value>
                <fullName>MOD/Barracks</fullName>
            </value>
            <value>
                <fullName>NHS Trust Including Community Dental</fullName>
                <label>NHS Trust Including Community Dental &amp; Hospitals</label>
            </value>
            <value>
                <fullName>Podiatry</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Private Healthcare Group</fullName>
                <label>Private Healthcare</label>
            </value>
            <value>
                <fullName>Non-Sale</fullName>
            </value>
            <value>
                <fullName>Veterinary Surgeon</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Dental School</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Dental Laboratory</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Modx User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Nominal_Code__c.field-meta.xml
<CustomField>
    <fullName>Nominal_Code__c</fullName>
    <label>Nominal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Delivery_Note__c/Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Delivery Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Delivery_Note__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Delivery_Note__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/Active_User__c.field-meta.xml
<CustomField>
    <fullName>Active_User__c</fullName>
    <inlineHelpText>If this is Yes, the technician is still employed. If No, the technician has left.</inlineHelpText>
    <label>Active User</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;Australia&quot;</defaultValue>
    <label>Country</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

objects/Engineer__c/fields/Engineer_ID__c.field-meta.xml
<CustomField>
    <fullName>Engineer_ID__c</fullName>
    <label>Technician ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Engineer__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State / Province</label>
    <type>TextArea</type>
</CustomField>

objects/Engineer_Checklist__c/Engineer_Checklist__c.object-meta.xml
<CustomObject>
    <description>Onsite checklist</description>
    <label>Service Sheet</label>
    <nameField>
        <displayFormat>SS2{000000}</displayFormat>
        <label>Service Sheet No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Engineer_Checklist__c/fields/Engineer__c.field-meta.xml
<CustomField>
    <fullName>Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Service Sheets Completed by this Engineer</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Engineer_Checklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Engineer_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Engineer_Checklist__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the relationship to the Site and Contract - this also relates to Alarm Master Historic Data</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Engineer_Checklist__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <inlineHelpText>This is the visit record that generated this service sheet. when the service sheet is created from the visit, this is automatically filled in. When it is created from the offline excel sheet, this is not automated and needs to be manually connected.</inlineHelpText>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Engineer_Checklist__c/recordTypes/Others.recordType-meta.xml
<RecordType>
    <fullName>Others</fullName>
    <active>true</active>
    <label>Others</label>
</RecordType>

objects/Opportunity/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>Delivery_Note__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Service_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Service_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Sheet</label>
    <referenceTo>Engineer_Checklist__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Service_Sheet</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site Contract Number</inlineHelpText>
    <label>Site Contract</label>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Service Sheets</relationshipLabel>
    <relationshipName>Service_Sheets1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Opportunities created when converting lead</description>
    <label>Sales</label>
</RecordType>

objects/OpportunityLineItem/fields/Service_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Service_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Sheet</label>
    <referenceTo>Engineer_Checklist__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product2/fields/Nominal_Code__c.field-meta.xml
<CustomField>
    <fullName>Nominal_Code__c</fullName>
    <label>Nominal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts (Customer)</relationshipLabel>
    <relationshipName>Site_Contract</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Date MUST be in this format : DD/MM/YYYY. PLEASE do not create new planned service dates. If this is not working, contact cascloud for support or simply move straight to actual service date, and ignore the planned service date.</inlineHelpText>
    <label>Planned Visit Date</label>
    <referenceTo>Date__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/UpdateDeliveryNoteNumberTest.cls
@isTest(seeAlldata=true)
Public Class UpdateDeliveryNoteNumberTest{
     @isTest Public static void UpdateDelNoteNumberMethod() {  
    
        PricebookEntry priceBookEntryNew = new PricebookEntry();
        Product2 product = new Product2(); 
        
       
        Id pb2 = Test.getStandardPricebookId();
        
        product.name = 'Test';
        product.ProductCode='Test';
        product.Nominal_Code__c='Test';
        product.IsActive=true;
        insert product;
        
        priceBookEntryNew.Product2Id = product.Id;
        priceBookEntryNew.PriceBook2Id = pb2;
        priceBookEntryNew.UnitPrice = 20.00;
        priceBookEntryNew.isactive = true;
        insert priceBookEntryNew;
             
    Account a = new Account(Name = 'Test Account',Customer_type__c='Others');
    a.recordtypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
    PricebookEntry pbID = [select Id, name from PricebookEntry where isActive = True limit 1];
    Opportunity o = new Opportunity();
    OpportunityLineItem ol = new OpportunityLineItem();
        
    insert a;

    o.AccountId = a.Id;
    o.Name = 'Test';
    o.StageName = 'Prospecting';
    o.CloseDate = date.today();
    o.Pricebook2Id=pb2;
    o.Type = 'New Business';
    insert o;
    
    SiteContracts__c sc=new SiteContracts__c();
    sc.Site__c=a.id;
    sc.Customer__c=a.id;
    insert sc;
    
    Engineer__c tech = new Engineer__c(
    Name='tech',
    Engineer_ID__c='123',
    Active_User__c='Yes',
    Street__c='test',
    City__c='test',
    State_Province__c='test',
    Postal_Code__c='test',
    Country__c='test'
    
    );
    
    insert tech;
    
    Visits__c v=new Visits__c();
    v.Site__c=a.id;
    v.Site_Contract__c=sc.id;
    v.Actual_Service_Date__c=system.today();
    v.Engineer2__c=tech.id;
    insert v;
    
    Engineer_Checklist__c eng=new Engineer_Checklist__c();
    eng.Site__c=a.id;
    eng.Site_Contract__c=sc.id;
    eng.Visit__c=v.id;
    eng.Engineer__c=tech.id;
    insert eng;
                 
        OpportunityLineItem oli = new OpportunityLineItem
            (
                OpportunityId = o.Id,
                PricebookEntryId = priceBookEntryNew.Id,
                Quantity = 1,
                UnitPrice = priceBookEntryNew.UnitPrice, 
                Service_Sheet__c=eng.id,
                ServiceDate = System.today()
            );
      insert oli;
      
      OpportunityLineItem olii = new OpportunityLineItem
            (
                OpportunityId = o.Id,
                PricebookEntryId = priceBookEntryNew.Id,
                Quantity = 1,
                UnitPrice = priceBookEntryNew.UnitPrice, 
                ServiceDate = System.today()
            );
      insert olii;
      
      Delivery_Note__c DN=new Delivery_Note__c();
      DN.Opportunity__c=o.id;
      DN.Site__c=a.id;
      DN.Date__c=system.today();
      insert DN;
      Test.Starttest();
      SalesOrder__c Sales=new SalesOrder__c();
      Sales.Account__c=a.Id;
      Sales.Opportunity__c=o.Id;
      Sales.Service_Type__c='Air Compressor';
      insert Sales;
      
      UpdateDeliveryNoteNumber DelNo=new UpdateDeliveryNoteNumber();
      DelNo.getDelnoteid();
      DelNo.setDelnoteid(o.Id);
      DelNo.UpdateOppDelNoteNumber();
      Test.StopTest();
     }
     
     
}