objects/Account/fields/Due_Days__c.field-meta.xml
<CustomField>
    <fullName>Due_Days__c</fullName>
    <label>Due Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Price_List_Correct__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Correct__c</fullName>
    <inlineHelpText>This is the date on which the pricing level for this customer was last checked.</inlineHelpText>
    <label>Price List Correct</label>
    <type>Date</type>
</CustomField>

objects/Opportunity/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Product_Name_Check__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Check__c</fullName>
    <inlineHelpText>Enter the product name again in here, and it will check to see if there is another product already created with this name, when you save. This is to avoid duplicates.</inlineHelpText>
    <label>Product Name Check</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Product2/fields/UniqueSageCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueSageCode__c</fullName>
    <inlineHelpText>This is the unique Sage Code, being a combination of the Sage Code and the Nominal Code. It is a required field on the product, and also is the unique external link to Sage.</inlineHelpText>
    <label>Eclipse Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

classes/InvoiceDueTest.cls
@isTest (seeAllData=true)
private class InvoiceDueTest{

    public static testMethod void method1() {
            Product2 p = new Product2(Name='test other', IsActive=true,ProductCode = OpportunityLineItemHandler.OTHER_CODE,UniqueSageCode__c='test2',Product_Name_Check__c='10 Person First Aid Kit Product 2_test2');
            insert p;
            
          //  Pricebook2 standardPB = [select id from Pricebook2 where isStandard=false limit 1];
           Id standardPB = Test.getStandardPricebookId();
           
            
          //  PricebookEntry pbe = [select id,Pricebook2Id,Product2Id from PricebookEntry where Product2Id=:p.id limit 1];
               PricebookEntry pbe = new PricebookEntry(UnitPrice=50, Pricebook2Id=standardPB, Product2Id=p.Id, IsActive=true);
            insert pbe;
            
            Account acc=new Account();
            acc.name='test';
            acc.Price_Book__c=standardPB;
            acc.Price_List_Correct__c=system.today();
            acc.Due_Days__c=10;
            insert acc;
            
         
                       
            Opportunity opp = new Opportunity(Name='Test opp',Amount_Due__c=20,Due_Date__c=system.today()-1, StageName='New', CloseDate=Date.today(),AccountId=acc.id);
            insert opp;
            
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, PricebookEntryId=pbe.Id, TotalPrice=50);
            
            insert oli;
            
            Opportunity opp1 = new Opportunity(Name='Test opp',Amount_Due__c=20,Due_Date__c=system.today()-32, StageName='New', CloseDate=Date.today(),AccountId=acc.id);
            insert opp1;
            
              PageReference pageRef = Page.InvoiceDue ;
                Test.setCurrentPage(pageRef);
                pageRef.getParameters().put('Id', String.valueOf(acc.Id));
                ApexPages.StandardController sc = new ApexPages.StandardController(acc);
                InvoiceDue inv =new InvoiceDue(sc);

     
            
           
            
            
        
    }
    }