objects/Account/fields/Nominal_Code__c.field-meta.xml
<CustomField>
    <fullName>Nominal_Code__c</fullName>
    <label>Nominal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Nominal_Code__c.field-meta.xml
<CustomField>
    <fullName>Nominal_Code__c</fullName>
    <label>Nominal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Supplier_Cost_Price__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Cost_Price__c</fullName>
    <label>Supplier Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Suppliers__c.field-meta.xml
<CustomField>
    <fullName>Suppliers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suppliers</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products (Suppliers)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SupplierProduct__c/SupplierProduct__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <displayFormat>SPN-{000000}</displayFormat>
        <label>Supplier Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SupplierProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Available Suppliers</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SupplierProduct__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateSupplierCostTest.cls
@isTest(seeAlldata=true)
Public Class UpdateSupplierCostTest{
     @isTest Public static void UpdateSupplierCostMethod() {  
        
         Id SuppId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();
        
         Account Pacc = new Account();
         Pacc.Name='Test Customer';
         Pacc.RecordTypeId=SuppId;
         insert Pacc;
         
         Account a=new Account();
         a.Name='Test site';
         a.RecordTypeId=SuppId;
         insert a;
         
        Product2 product = new Product2(); 
        
        Id pb2= Test.getStandardPricebookId();
        
        product.name = 'Test';
        product.ProductCode='Test';
        product.Nominal_Code__c='Test';
        insert product;
        
        product.Suppliers__c=null;
        product.Supplier_Cost_Price__c=null;
        update product;
        
        SupplierProduct__c Spoli=new SupplierProduct__c();
        Spoli.Product__c=product.Id;
        Spoli.Supplier__c=Pacc.Id;
        Spoli.Cost__c=12;
        insert Spoli;
        
        
        product.Suppliers__c=Pacc.Id;
        update product;
     }
}