objects/Account/fields/Purchase_Order_Required__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Required__c</fullName>
    <inlineHelpText>If you select this on the parent, it over-rides every Site and Every Contract. If you select it for a site, it over-rides the contracts. Contracts can be set specifically.</inlineHelpText>
    <label>Purchase Order Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The technician is either on holiday, sick, or training.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Engineer__c/fields/Service_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_End_Date__c</fullName>
    <inlineHelpText>Enter the End date of the technician on call. This will then display a message on the Visits that are scheduled during this time period to alert the schedulers that the technician is on call.</inlineHelpText>
    <label>Call End Date</label>
    <type>Date</type>
</CustomField>

objects/Engineer__c/fields/Service_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Start_Date__c</fullName>
    <inlineHelpText>Enter the Start date of the technician on call. This will then display a message on the Visits that are scheduled during this time period to alert the schedulers that the technician is on call.</inlineHelpText>
    <label>Call Start Date</label>
    <type>Date</type>
</CustomField>

objects/Engineer__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>The technician is either on holiday, sick, or training.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Purchase_Order_Required__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Required__c</fullName>
    <inlineHelpText>Please select whether a purchase order is required for this Site Contract</inlineHelpText>
    <label>Purchase Order Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Booked_with_Customers__c.field-meta.xml
<CustomField>
    <fullName>Booked_with_Customers__c</fullName>
    <inlineHelpText>1. Yes first time, sends Booking confirmation email
2. Yes to any other, sends Rescheduling notification email
3. Yes again, sends Rescheduled confirmation email.</inlineHelpText>
    <label>Booked with Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Waiting P/O</fullName>
            </value>
            <value>
                <fullName>Waiting Permit</fullName>
            </value>
            <value>
                <fullName>Waiting Confirmation</fullName>
            </value>
            <value>
                <fullName>Booked Via Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>If this is a multi-day service, please enter the end date here..</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/VisitAlertPageController.cls
/*============================================================================================================
*Class Name     : VisitAlertPageController
*Description    : To handle the technician call
*Company        : Puthuvannam Technology Solutions Pvt Ltd.
*Date           : 28th May, 2014
*Version        : 1.1
*Methods        : public VisitAlertPageController(ApexPages.StandardController controller)

*============================================================================================================*/

public class VisitAlertPageController {
    public String visitId{get; set;}
    Public Visits__c currentVisit{get; set;}
    
    public VisitAlertPageController(ApexPages.StandardController controller) {
        //Variable Initialization
        visitId =  ApexPages.CurrentPage().getParameters().get('id');
        //get the current engineer details based on the current page id.
       
        currentVisit  =[SELECT id,Name,Engineer2__c,Actual_Service_Date__c,End_Date__c,Site__c,Site_Contract__c,Booked_with_Customers__c 
                                  FROM Visits__c  
                                  WHERE id = :visitId ];
        //currentVisit=(Visits__c)controller.getRecord();
        CheckTechnicianOnCallAvailability();
        CheckTechnicianUnavailableAvailability();
        CheckTechnicianVisitAvailability();
        CheckPurchaseOrderRequiredyes();
        CheckBookedviaSchedule(); // If BookedWithCustomer is 'Booked Via Schedule' show a warning alert
               
    }
    
    
    public void CheckTechnicianOnCallAvailability(){
    
        
        //Check the Engineer's Availability
        if(currentVisit.Engineer2__c !=Null){
            //Fetch the start date and end date of the engineer's call
            Engineer__c currentTechnician = [SELECT id,Service_End_Date__c,Service_Start_Date__c 
                                             FROM Engineer__c 
                                             WHERE id = :currentVisit.Engineer2__c];

            if((currentTechnician.Service_Start_Date__c <= currentVisit.Actual_Service_Date__c && 
                currentTechnician.Service_End_Date__c >= currentVisit.Actual_Service_Date__c) || 
               (currentTechnician.Service_Start_Date__c <= currentVisit.End_Date__c && 
                currentTechnician.Service_End_Date__c <= currentVisit.End_Date__c) ){
                    //Show the warning message 
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'Technician is on Call from  [ '+currentTechnician.Service_Start_Date__c.format()+'  ]  to  [ '+currentTechnician.Service_End_Date__c.format()+' ]'));
            }
            //For testing purospe while running in the production after the deploy.
            system.debug('============'+currentTechnician +'========='+currentVisit.Actual_Service_Date__c );
    
        }    
    }
    
    // Technician CheckTechnicianUnavailableAvailability
    
     public void CheckTechnicianUnavailableAvailability(){
    
        
        //Check the Engineer's Availability
        if(currentVisit.Engineer2__c !=Null){
            //Fetch the start date and end date of the engineer's Unavailable
            Engineer__c currentTechnician = [SELECT id,Start_Date__c,End_Date__c
                                             FROM Engineer__c 
                                             WHERE id = :currentVisit.Engineer2__c];

            if((currentTechnician.Start_Date__c <= currentVisit.Actual_Service_Date__c && 
                currentTechnician.End_Date__c >= currentVisit.Actual_Service_Date__c) || 
               (currentTechnician.Start_Date__c <= currentVisit.End_Date__c && 
                currentTechnician.End_Date__c <= currentVisit.End_Date__c) ){
                    //Show the warning message 
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'Technician is on Unavailable from  [ '+currentTechnician.Start_Date__c.format()+'  ]  to  [ '+currentTechnician.End_Date__c.format()+' ]'));
            }
            //For testing purospe while running in the production after the deploy.
            system.debug('============'+currentTechnician +'========='+currentVisit.Actual_Service_Date__c );
    
        }    
    }
    
     /*Method Name   : CheckTechnicianCall
    //Description    : Check the availability of the technician call 
    //Arguments      : newVList- Receiving all the Visit records which triggers this trigger.
    */
    Private void CheckTechnicianVisitAvailability(){
      if( currentVisit.Engineer2__c  != null){
      List<Visits__c> VisitRecords = [SELECT id,Name,Engineer2__c,Actual_Service_Date__c,End_Date__c 
                                  FROM Visits__c  
                                  WHERE Engineer2__c = :currentVisit.Engineer2__c AND id!=:visitId];
                                  
      if(VisitRecords != null){
       for(Visits__c v:VisitRecords){
         
            if((currentVisit.Actual_Service_Date__c >= v.Actual_Service_Date__c && 
                currentVisit.Actual_Service_Date__c < = v.End_Date__c) || 
               (currentVisit.End_Date__c >= v.Actual_Service_Date__c && 
                currentVisit.End_Date__c <= v.End_Date__c) ){
                    //Show the warning message 
                     ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'Technician is on another Visit [ '+v.Name+'  ] from  [ '+v.Actual_Service_Date__c.format()+'  ]  to  [ '+v.End_Date__c.format()+' ]'));
                }
                
             }
       }                            
      }
      
    }
    
    /*Method Name   :  CheckPurchaseOrderRequiredYes
    //Description    : Check the Purchase Order Required is Yes in Customer/Site and SiteContact
    //Arguments      : newVList- Receiving all the Visit records which triggers this trigger.
    */
     
   Private void CheckPurchaseOrderRequiredyes(){
           //Check the Purchase Order Required is Yes
        if(((currentVisit.Site__c!=Null) || (currentVisit.Site_Contract__c !=Null)) || ((currentVisit.Site__c!=Null) && (currentVisit.Site_Contract__c !=Null) )){
            //Fetch the Purchase Order Required in Customer Site And Site Contracts
            Account currentCustomerSite = [SELECT id,Purchase_Order_Required__c 
                                             FROM Account
                                             WHERE id = :currentVisit.Site__c];
         
           SiteContracts__c currentSiteContracts = [SELECT id,Purchase_Order_Required__c 
                                             FROM SiteContracts__c
                                             WHERE id = :currentVisit.Site_Contract__c ];
         
           if(((currentCustomerSite.Purchase_Order_Required__c =='Yes')||(currentSiteContracts.Purchase_Order_Required__c =='Yes' )) ||((currentCustomerSite.Purchase_Order_Required__c =='Yes')&&(currentSiteContracts.Purchase_Order_Required__c =='Yes' ))) {
               ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'This Visit requires a Purchase Order before it is booked in / attended'));
               }
           }
   }
    /*Method Name   :  CheckBookedviaSchedule
    //Description    : Check the Purchase Order Required is Yes in Customer/Site and SiteContact
    //Arguments      : newVList- Receiving all the Visit records which triggers this trigger.
    */
    
    Private void CheckBookedviaSchedule(){
       if( currentVisit.Booked_with_Customers__c != null && currentVisit.Booked_with_Customers__c=='Booked Via Schedule'){
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'This Visit still requires booking, do not move the date as it has forms part of a schedule already sent to the customer'));    
       }
       
    }
}