objects/Account/fields/Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Left the company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Site Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Contact_Site_Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contact_Site_Contracts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/SiteContractTriggerHandler.cls
public class SiteContractTriggerHandler{

    public SiteContractTriggerHandler(){}
    public void OnBeforeInsert(List<SiteContracts__c> newSC){
        ContactUpdate(newSC);
    }
    
    public void ContactUpdate(List<SiteContracts__c> newSC){        
        List<Id> accid=new List<Id>();
        for(SiteContracts__c sc:newSC){
            if(sc.Site__c!=null){
                accid.add(sc.Site__c);                
            }
        }
        
        if(accid.size()>0){
            Map<Id,Account> accMap=new Map<Id,Account>([select id,Site_Contact__c from Account where id IN :accid]);
            System.debug('accMap===='+accMap);
            for(SiteContracts__c sc:newSC){
                if(accMap.containskey(sc.Site__c)){
                System.debug('contact===='+accMap.get(sc.Site__c).Site_Contact__c);
                    sc.Contact_Site_Contracts__c=accMap.get(sc.Site__c).Site_Contact__c;
                }
            }    
        }
    }
}