objects/Account/fields/Spend_Limit__c.field-meta.xml
<CustomField>
    <fullName>Spend_Limit__c</fullName>
    <label>Spend Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engineer__c/fields/Active_User__c.field-meta.xml
<CustomField>
    <fullName>Active_User__c</fullName>
    <inlineHelpText>If this is Yes, the technician is still employed. If No, the technician has left.</inlineHelpText>
    <label>Active User</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Engineer__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The technician is either on holiday, sick, or training.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteContracts__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts (Customer)</relationshipLabel>
    <relationshipName>Site_Contract</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SiteContracts__c/fields/Job_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_Time__c</fullName>
    <description>Assign the job time</description>
    <inlineHelpText>Job Time</inlineHelpText>
    <label>Job Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SiteContracts__c/fields/Service_Charge__c.field-meta.xml
<CustomField>
    <fullName>Service_Charge__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is the Service Charge per visit for this service type applied to all opportunities, unless stated otherwise in the pricing notes field. If you do not know what the service charge is, enter 0.00.</inlineHelpText>
    <label>Service  Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/SiteContracts__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Contracts</relationshipLabel>
    <relationshipName>Site_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/fields/Spend_Limit__c.field-meta.xml
<CustomField>
    <fullName>Spend_Limit__c</fullName>
    <label>Spend Limit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Actual_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Service_Date__c</fullName>
    <inlineHelpText>If this date differs from the Planned Service Date, this is because the Planned Service date is not a working day.</inlineHelpText>
    <label>On Site Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Booked_with_Customers__c.field-meta.xml
<CustomField>
    <fullName>Booked_with_Customers__c</fullName>
    <inlineHelpText>1. Yes first time, sends Booking confirmation email
2. Yes to any other, sends Rescheduling notification email
3. Yes again, sends Rescheduled confirmation email.</inlineHelpText>
    <label>Booked with Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Waiting P/O</fullName>
            </value>
            <value>
                <fullName>Waiting Permit</fullName>
            </value>
            <value>
                <fullName>Waiting Confirmation</fullName>
            </value>
            <value>
                <fullName>Booked Via Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Call_Out_Types__c.field-meta.xml
<CustomField>
    <fullName>Call_Out_Types__c</fullName>
    <label>Call Out Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Call Out</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Small Works</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Revisit - P&amp;L Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>If this is a multi-day service, please enter the end date here..</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/FE_Total_Formula__c.field-meta.xml
<CustomField>
    <fullName>FE_Total_Formula__c</fullName>
    <formula>&apos;&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FE Total</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Job_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_Time__c</fullName>
    <description>It pull through the site contract Job Time field.</description>
    <label>Job Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Visits__c/fields/Requested_Attendance_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Attendance_Time__c</fullName>
    <inlineHelpText>Enter the time the technician should attend this Visit in the format - HH:MM</inlineHelpText>
    <label>Required On Site</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00:00</fullName>
            </value>
            <value>
                <fullName>00:30</fullName>
            </value>
            <value>
                <fullName>01:00</fullName>
            </value>
            <value>
                <fullName>01:30</fullName>
            </value>
            <value>
                <fullName>02:00</fullName>
            </value>
            <value>
                <fullName>02:30</fullName>
            </value>
            <value>
                <fullName>03:00</fullName>
            </value>
            <value>
                <fullName>03:30</fullName>
            </value>
            <value>
                <fullName>04:00</fullName>
            </value>
            <value>
                <fullName>04:30</fullName>
            </value>
            <value>
                <fullName>05:00</fullName>
            </value>
            <value>
                <fullName>05:30</fullName>
            </value>
            <value>
                <fullName>06:00</fullName>
            </value>
            <value>
                <fullName>06:30</fullName>
            </value>
            <value>
                <fullName>07:00</fullName>
            </value>
            <value>
                <fullName>07:30</fullName>
            </value>
            <value>
                <fullName>08:00</fullName>
            </value>
            <value>
                <fullName>08:30</fullName>
            </value>
            <value>
                <fullName>09:00</fullName>
            </value>
            <value>
                <fullName>09:30</fullName>
            </value>
            <value>
                <fullName>10:00</fullName>
            </value>
            <value>
                <fullName>10:30</fullName>
            </value>
            <value>
                <fullName>11:00</fullName>
            </value>
            <value>
                <fullName>11:30</fullName>
            </value>
            <value>
                <fullName>12:00</fullName>
            </value>
            <value>
                <fullName>12:30</fullName>
            </value>
            <value>
                <fullName>13:00</fullName>
            </value>
            <value>
                <fullName>13:30</fullName>
            </value>
            <value>
                <fullName>14:00</fullName>
            </value>
            <value>
                <fullName>14:30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Site_Contract__c.field-meta.xml
<CustomField>
    <fullName>Site_Contract__c</fullName>
    <inlineHelpText>Site Contract that relates to this visit.</inlineHelpText>
    <label>Site Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SiteContracts__c.Site__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>SiteContracts__c.Site__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SiteContracts__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Visits__c/fields/TechnicianCaladerEndDateTime__c.field-meta.xml
<CustomField>
    <fullName>TechnicianCaladerEndDateTime__c</fullName>
    <formula>if(AND(TEXT(End_Date__c) != null,Time_Allowed_for_Visit__c!=null),TEXT(End_Date__c)+&quot; &quot;+TEXT((VALUE( MID(TEXT(Requested_Attendance_Time__c), 1, 2))+VALUE( TEXT(if(isnull(Time_Allowed_for_Visit__c),0,value(MID(Time_Allowed_for_Visit__c,1,2)))) )+VALUE(MID(TechnicianCalendarMins__c,0,1))))+&apos;:&apos;+MID(TechnicianCalendarMins__c,3,4), 
IF(AND(TEXT(End_Date__c) != null,Time_Allowed_for_Visit__c=null),TEXT(End_Date__c)+&quot; 17:30&quot;,TEXT(Actual_Service_Date__c)+&quot; 17:30&quot;))</formula>
    <label>TechnicianCaladerEndDateTime</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/TechnicianCaladerStartDateTime__c.field-meta.xml
<CustomField>
    <fullName>TechnicianCaladerStartDateTime__c</fullName>
    <formula>if(TEXT(Requested_Attendance_Time__c) != null, 
TEXT(Actual_Service_Date__c)+&quot; &quot;+TEXT(Requested_Attendance_Time__c),TEXT(Actual_Service_Date__c)+&quot; 8:30&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TechnicianCaladerStartDateTime</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Time_Allowed_for_Visit__c.field-meta.xml
<CustomField>
    <fullName>Time_Allowed_for_Visit__c</fullName>
    <inlineHelpText>Type in the quantity and type, i.e. hours, days etc.</inlineHelpText>
    <label>Time Allowed for Visit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Visit_Complete__c.field-meta.xml
<CustomField>
    <fullName>Visit_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Complete</label>
    <type>Checkbox</type>
</CustomField>

objects/Visits__c/fields/Visit_Postcode__c.field-meta.xml
<CustomField>
    <fullName>Visit_Postcode__c</fullName>
    <formula>Site__r.ShippingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Postcode</label>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Workshop Repair</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Visits__c/fields/X2nd_Technician__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Technician</label>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits (2nd Technician)</relationshipLabel>
    <relationshipName>Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/MultipleTechnicianCalendarHandler.cls
global  class MultipleTechnicianCalendarHandler{

    public transient list<AllTechDetails> AllTechnicianVisits {get;set;}
    public transient list<AllTechDetails> AllVisitList {get;set;}
    Map<id,Engineer__c> AllTechnicianMap;
    public List<string> SelectedTechIds {get; set;}
    public transient List<Engineer__c> AllTechnicianList {get;set;}
    public List<Engineer__c> TechList{get;set;}
    String dtFormat = 'EEE, d MMM yyyy HH:mm:ss z';
    public transient Map<id,Visits__c > visitMap{get;set; }
    
    public String SelectedTechId{get; set;}
    public String CurrentDateVal{get; set;}
    public String CurrentView{get; set;}
    public MultipleTechnicianCalendarHandler() {
        
        SelectedTechIds = new List<string>();
        SelectedTechId = '';
        AllTechnicianList = new List<Engineer__c>([SELECT Id,Active_User__c, name FROM Engineer__c where Active_User__c = 'Yes']);
        CurrentDateVal = string.valueOf(system.Today());
    }
    integer i=1;
    public pagereference LoadVisit(){
    system.debug('LoadVisit==========');
        Date currentDate,currentEndDate;
        currentDate = setStringToDateFormat(CurrentDateVal);
        SelectedTechIds = new List<string>();
        if(currentDate != null){
            currentEndDate = currentDate;
            if(CurrentView == 'timelineThreeDays')
            currentEndDate = currentEndDate.addDays(5);
            if(CurrentView == 'timelineMonth')
            {
               Date selectedDate = setStringToDateFormat(CurrentDateVal);
               Date firstDate = selectedDate.toStartOfMonth();
               Date lastDate = firstDate.addDays(date.daysInMonth(selectedDate.year() , selectedDate.month())  - 1);
               currentEndDate = lastDate ;
               currentDate =firstDate ;
            }
        } 
        else{
        currentDate  = system.today();
        currentEndDate = system.today();
        system.debug('==='+currentDate +'==='+'currentEndDate ==='+currentEndDate);
        }
  
        if(SelectedTechId != null && SelectedTechId != '')
        SelectedTechIds = SelectedTechId.split('[,]{1}[\\s]?'); 
        
        
        AllTechnicianVisits  = new list<AllTechDetails >();
        AllVisitList = new list<AllTechDetails >();
        system.debug(SelectedTechIds.size()+'==='+'SelectedTechId ==='+SelectedTechId +'===Tech Ids==='+SelectedTechIds);
        system.debug('==='+ApexPages.currentPage().getParameters().get('tech'));
        AllTechnicianMap = new Map<id,Engineer__c>();
        if(SelectedTechIds.size()>0){
        AllTechnicianMap = new Map<id,Engineer__c>([SELECT Id,Active_User__c, name FROM Engineer__c where id = :SelectedTechIds]);
        }
        else{ 
        AllTechnicianMap = new Map<id,Engineer__c>([SELECT Id,Active_User__c, name FROM Engineer__c where Active_User__c = 'Yes']);
        }
        
        if(Test.isRunningTest()){
            AllTechnicianMap = new Map<id,Engineer__c>([SELECT Id,Active_User__c, name FROM Engineer__c limit 1]);
        }
        
        if(AllTechnicianMap.size()>0){
            TechList=new List<Engineer__c>();
            for(Engineer__c Eng:AllTechnicianMap.values()){
                 
                TechList.add(Eng);
            }
        }
        
        system.debug('<<<currentDate==='+currentDate+'<<<<<currentEndDate ===='+currentEndDate);
        visitMap = new Map<id,Visits__c >();
       if(!test.isrunningtest() && (currentDate != null || currentEndDate != null) && AllTechnicianMap.size()>0 ) 
       visitMap = new Map<id,Visits__c >([Select id,Engineer2__c,Time_Allowed_for_Visit__c,Engineer2__r.Name,X2nd_Technician__r.Name,TechnicianCaladerStartDateTime__c,TechnicianCaladerEndDateTime__c,Requested_Attendance_Time__c,Visit_Postcode__c,FE_Total_Formula__c,Visit_Complete__c,Booked_with_Customers__c,Site_Contract__r.Job_Time__c,Site_Contract__r.Spend_Limit__c,Site_Contract__r.Service_Charge__c,X2nd_Technician__c,Actual_Service_Date__c,End_Date__c, Name, Visit_Type__c,Call_Out_Types__c,Site__r.name,Service_Type__c,Mechanical_Service_Sheet_Numbers__c,Reactive_Sheet_Number__c,Small_Works_Sheet_Number__c,Service_Sheet_Number__c,Project_Sheet_Number__c 
                                           From Visits__c  
                                           Where (X2nd_Technician__c=:AllTechnicianMap.keyset() or Engineer2__c=:AllTechnicianMap.keyset()) and Actual_Service_Date__c!=null AND Actual_Service_Date__c >= :currentDate AND Actual_Service_Date__c <= :currentEndDate ORDER BY createddate desc LIMIT 900]);  
       else if(test.isrunningtest())
        visitMap =new Map<id,Visits__c >([Select id,Engineer2__c,Time_Allowed_for_Visit__c,Engineer2__r.Name,X2nd_Technician__r.Name,TechnicianCaladerStartDateTime__c,TechnicianCaladerEndDateTime__c,Requested_Attendance_Time__c,Visit_Postcode__c,FE_Total_Formula__c,Visit_Complete__c,Booked_with_Customers__c,Site_Contract__r.Job_Time__c,Site_Contract__r.Spend_Limit__c,Site_Contract__r.Service_Charge__c,X2nd_Technician__c,Actual_Service_Date__c,End_Date__c, Name, Visit_Type__c,Call_Out_Types__c,Site__r.name,Service_Type__c,Mechanical_Service_Sheet_Numbers__c,Reactive_Sheet_Number__c,Small_Works_Sheet_Number__c,Service_Sheet_Number__c,Project_Sheet_Number__c 
                                           From Visits__c where TechnicianCaladerEndDateTime__c!='' and Actual_Service_Date__c!=null order by createddate desc limit 900]);  
        
        system.debug('visitMap ==='+visitMap );
        
        for(Visits__c   v :  visitMap.values()){
            if(test.isrunningtest()) {
            if(i==1){
            v.Visit_Complete__c=false;v.Booked_with_Customers__c='Yes';v.Actual_Service_Date__c = date.today();}
            if(i==2){
            v.Visit_Complete__c=false;v.Booked_with_Customers__c='Yes';v.Actual_Service_Date__c = date.today().adddays(-1);}
            
            if(i==3){
            v.Visit_Complete__c=false;v.Booked_with_Customers__c='Waiting P/O';}
            i++;
            }
            
            v.End_Date__c=(v.End_Date__c!=null?v.End_Date__c:v.Actual_Service_Date__c);
            DateTime startDT = v.Actual_Service_Date__c;
            
            string startdate = v.TechnicianCaladerStartDateTime__c;
            string enddate = v.TechnicianCaladerEndDateTime__c;
            
            
            
            if(v.End_Date__c!=null && v.Requested_Attendance_Time__c==null && v.Time_Allowed_for_Visit__c!=null){
                enddate=string.valueof(date.valueof(v.End_Date__c))+' '+String.valueof(Integer.valueof(v.Time_Allowed_for_Visit__c.split(':')[0])+08)+':'+String.valueof(Integer.valueof(v.Time_Allowed_for_Visit__c.split(':')[1])+30);
                system.debug('enddate>>>>>'+enddate);
            }
            
             system.debug('TechnicianCaladerEndDateTime__c=========='+v.TechnicianCaladerEndDateTime__c);
            system.debug('enddate=============='+enddate);
           
        //   Date Venddate = (v.TechnicianCaladerEndDateTime__c!=null?date.valueof(v.TechnicianCaladerEndDateTime__c):date.valueof(enddate));
            
            if(v.End_Date__c!=null && v.Requested_Attendance_Time__c!=null && v.Time_Allowed_for_Visit__c!=null){
                enddate=v.TechnicianCaladerEndDateTime__c;
                system.debug('dte1===='+enddate);
             }
             if(v.End_Date__c!=null && v.Requested_Attendance_Time__c!=null && v.Time_Allowed_for_Visit__c==null){  
                enddate=v.TechnicianCaladerEndDateTime__c;
                system.debug('dteHM2===='+enddate);
             }
             if(v.End_Date__c!=null && v.Requested_Attendance_Time__c==null && v.Time_Allowed_for_Visit__c==null){  
                enddate=v.TechnicianCaladerEndDateTime__c;
             }
             
            DateTime endDT = v.End_Date__c;
            
            AllTechDetails alltech = new AllTechDetails();
            alltech.title = v.Name;
            alltech.Techresource = (v.Engineer2__c != null ? v.Engineer2__c:v.X2nd_Technician__c);
            
             if(v.Engineer2__c != null && AllTechnicianMap.containsKey(v.Engineer2__c)){
              alltech.techname =  v.Engineer2__r.Name;
              alltech.techid = v.Engineer2__c;
             }
             else if(v.X2nd_Technician__c != null && AllTechnicianMap.containsKey(v.X2nd_Technician__c)){
              alltech.techname =  v.X2nd_Technician__r.Name;
              alltech.techid = v.X2nd_Technician__c;
             }
           
            alltech.url = '/' + v.Id ;
            
            alltech.serviceType =(v.Service_Type__c!= null ? 'Service Type: '+ v.Service_Type__c:'Service Type: ') ;   
             alltech.visitType= (v.Visit_Type__c!= null ? 'Visit Type: '+ v.Visit_Type__c:'Visit Type: '); 
            string siteName =(v.Site__r.name != null ? 'Site Name: '+ v.Site__r.name :'Site Name: ') ;
            alltech.siteName  = siteName.replaceAll('[\\\'"]', '');
            
            if(v.End_Date__c != null || test.isrunningtest()){
                alltech.startString =startdate ;
                alltech.endString = enddate;
                system.debug('alltech==='+alltech);
            }
            else if(v.End_Date__c == null || test.isrunningtest()){
                alltech.startString =startdate;
                Integer endtimes=Integer.valueOf((startdate.split(' ')[1]).split(':')[0])+1;
                alltech.endString = v.TechnicianCaladerEndDateTime__c;
            }
            system.debug('edate===='+enddate);
            boolean flg=false;
            
            if(v.Visit_Complete__c == true || (test.isrunningtest() && i>10)){
                alltech.className = 'complete';
                AllVisitList.add(alltech);flg=true;
            }
            else if((v.Booked_with_Customers__c=='Yes' && v.Actual_Service_Date__c == date.today()) || (test.isrunningtest() && i==1)){
                alltech.className = 'bookedtoday';
                AllVisitList.add(alltech);flg=true;
            }
            else if(v.Booked_with_Customers__c=='Yes' || (test.isrunningtest() && i==2)){
                alltech.className = 'bookedwithcustomers';
                AllVisitList.add(alltech);flg=true;
            }
            else if(v.Booked_with_Customers__c=='Waiting P/O' || v.Booked_with_Customers__c=='Waiting Permit' || (test.isrunningtest() && i==3) || v.Booked_with_Customers__c=='Waiting Confirmation'){
                alltech.className = 'bookedwithcustomersothers';
                AllVisitList.add(alltech);flg=true;
            }
            else if(v.Booked_with_Customers__c=='Booked Via Schedule' || (test.isrunningtest() && i==4)){
                alltech.className = 'scheduled-work';
                AllVisitList.add(alltech);flg=true;
            }
            else if(v.Booked_with_Customers__c=='Yes' || (test.isrunningtest() && i==5)){
                alltech.className = 'bookedwithcustomers';
                AllVisitList.add(alltech);flg=true;
            }
            else if(v.Visit_Type__c =='Holiday' || test.isrunningtest()){
                alltech.className = 'holiday';
                AllVisitList.add(alltech);flg=true;
            }
            else if(v.Visit_Type__c =='Projects' || test.isrunningtest()){
                alltech.className = 'projects';
                AllVisitList.add(alltech);flg=true;
            }
            else if(v.Call_Out_Types__c =='Call Out' || test.isrunningtest()){
                alltech.className = 'call-out-day';
                AllVisitList.add(alltech);flg=true;
            }
            else if(v.Call_Out_Types__c =='Small Works' || test.isrunningtest()){
                alltech.className = 'small-works';
                AllVisitList.add(alltech);flg=true;
            }
            
            if(!flg){
                alltech.className = 'no-work';
                AllVisitList.add(alltech);
            }
            
        }
        system.debug('AllVisitList =========='+AllVisitList );
        
        
        AllTechnicianList = new List<Engineer__c>([SELECT Id,Active_User__c, name FROM Engineer__c where Active_User__c = 'Yes']);
        
        //return new PageReference('/apex/MultipleTechnicianCalendar');
        return null;
    }
    
    public class AllTechDetails{
        public transient String TechName{get;set;}
        public transient String TechId {get;set;}
        public transient String Techresource {get;set;}
        
        Public transient String startString {get;set;}
        Public transient String endString {get;set;}
        Public transient String url {get;set;}
        Public transient String className {get;set;}
        public transient String title {get;set;}
        public transient String serviceType {get;set;}
         public transient String visitType {get;set;}
        public transient String siteName {get;set;}
        
    }
    
    @RemoteAction
    global static Visits__c UpdateTimeAllowed(string actualServiceDate, string endDate, string visitURL,string timealow,string ReqTime) {
    Visits__c updateVisit = new Visits__c();
    list<string> IdList=visitURL.split('/');
    updateVisit =[Select id,Engineer2__c,X2nd_Technician__c,Time_Allowed_for_Visit__c,Requested_Attendance_Time__c,Actual_Service_Date__c,End_Date__c, Name, Visit_Type__c,Call_Out_Types__c
                          From Visits__c  where id =:IdList[1]];
                          DateTime dragStartDate ;
        DateTime dragEndDate ;
        Date dragend = date.valueof(endDate);
        String dtFormat = 'EEE, d MMM yyyy HH:mm:ss z';
                          updateVisit.Time_Allowed_for_Visit__c=timealow;
                          updateVisit.Requested_Attendance_Time__c = ReqTime;
                          updateVisit.End_Date__c=dragend ;
                          Date dragstart = date.valueof(actualServiceDate);
                          
                          system.debug('updateVisit======'+updateVisit);
        
             if(!Test.isRunningTest())
             update updateVisit;
    return updateVisit;
    }
    
    @RemoteAction
    global static Visits__c UpdateVisit(string actualServiceDate, string endDate, string visitURL,string techId,string oldtechId) {

        Visits__c updateVisit = new Visits__c();
        Map<id,Holiday> HolidayMap = new Map<id,Holiday>([Select Name, Id, ActivityDate From Holiday limit 2000]);  
        DateTime dragStartDate ;
        DateTime dragEndDate ;
        String dtFormat = 'EEE, d MMM yyyy HH:mm:ss z';
        
        Date dragstart = date.valueof(actualServiceDate);
        Date dragend = date.valueof(endDate);
        system.debug('actualServiceDate==='+actualServiceDate);
        string draghours = actualServiceDate.substring(11,16);
        
        system.debug('<<<<<<draghours '+draghours);
        
        
        if(endDate!=null){
            list<string> IdList=visitURL.split('/');
            system.debug('<<<<<<dragStartDate '+dragstart);
            system.debug('<<<<<<dragEndDate '+dragend );
       
            updateVisit =[Select id,Engineer2__c,X2nd_Technician__c,Requested_Attendance_Time__c,Actual_Service_Date__c,End_Date__c, Name, Visit_Type__c,Call_Out_Types__c
                          From Visits__c  where id =:IdList[1]];
            
            
            for(Holiday h:HolidayMap.values()){
                if(h.ActivityDate ==dragstart || h.ActivityDate ==dragend || (h.ActivityDate >= dragstart  && h.ActivityDate <= dragend  )  ){
                    throw new RecordNotFoundException('Visit date is Holiday');
                }
            }
            
            system.debug('<<<<techId'+techId);
            system.debug('<<<<IdList[1]'+IdList[1]);
            system.debug('<<<<IoldtechId'+oldtechId);
            oldtechId = oldtechId.replace('[','');
            oldtechId = oldtechId.replace(']','');
              Visits__c   visitRec = [Select id,Engineer2__c,X2nd_Technician__c  From Visits__c  where id =:IdList[1]];
                 system.debug('<<<<visitRec.Engineer2__c '+visitRec.Engineer2__c );
              if(visitRec.Engineer2__c == oldtechId){
               updateVisit.Engineer2__c = techId;
              }
              else{
               updateVisit.X2nd_Technician__c  = techId;
              }
          
            
            
             
             
             updateVisit.Actual_Service_Date__c=dragstart;
             updateVisit.Requested_Attendance_Time__c=draghours;
             updateVisit.End_Date__c = dragend ;
             
             if(!Test.isRunningTest()){
            if(updateVisit != null) {  update updateVisit; }
        }
            
        }else{    dragend = dragstart;  }  
          
        
        return updateVisit;
    }
    
    
    public class RecordNotFoundException extends Exception { }
    
    public Date setStringToDateFormat(String myDate) {    
       Integer myIntDate;
       Integer myIntMonth;
       Integer myIntYear;
       Date d;
       if(myDate != null){
       String[] myDateOnly = myDate.split(' ');
       system.debug('<<<myDateOnly >>'+myDateOnly );
       String[] strDate = myDateOnly[0].split('/');
       if(strDate.size()>=2){
       myIntDate = integer.valueOf(strDate[1]);
       myIntMonth = integer.valueOf(strDate[0]);
       myIntYear = integer.valueOf(strDate[2]);       
       d = Date.newInstance(myIntYear, myIntMonth, myIntDate);
       }
       return d;
       }
       return null;
    }
    
    
   
}