objects/Account/fields/Survey_Count_HS__c.field-meta.xml
<CustomField>
    <fullName>Survey_Count_HS__c</fullName>
    <label>Survey Count HS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Account/fields/Survey_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Date__c</fullName>
    <label>Survey Mail Sent On</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Survey_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Survey_Engineer__c</fullName>
    <label>Survey Engineer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Visit_Confirmation_Email_to__c.field-meta.xml
<CustomField>
    <fullName>Visit_Confirmation_Email_to__c</fullName>
    <label>Certification Email To</label>
    <type>Email</type>
</CustomField>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>Survey Force object</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SurveyTaker__c/SurveyTaker__c.object-meta.xml
<CustomObject>
    <description>Survey Force object</description>
    <label>Survey Taken</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Survey Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SurveyTaker__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surveys Taken</relationshipLabel>
    <relationshipName>Surveys_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SurveyTaker__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipLabel>Surveys Taken</relationshipLabel>
    <relationshipName>Surveys_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attending Engineer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The user-entered value must match filter criteria.</errorMessage>
        <filterItems>
            <field>Engineer__c.Active_User__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Mail_Count__c.field-meta.xml
<CustomField>
    <fullName>Mail_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Mail Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Visits__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Site to which this Visit refers.</description>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits to This Site ( Open Site Contracts to Schedule )</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Visits__c/fields/Survey_Sent__c.field-meta.xml
<CustomField>
    <fullName>Survey_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When the survey sent button is clicked , this checkbox will be clicked</description>
    <label>Survey Sent</label>
    <type>Checkbox</type>
</CustomField>

objects/Visits__c/fields/Visit_Confirmation_Email_to__c.field-meta.xml
<CustomField>
    <fullName>Visit_Confirmation_Email_to__c</fullName>
    <inlineHelpText>Update field on Visit confirmation Email to values</inlineHelpText>
    <label>Visit Confirmation Email to</label>
    <type>Email</type>
</CustomField>

classes/SurveySubmitController.cls
/*============================================================================================================
*Class Name     : SurveySubmitController
*Description    : When the survey submit button is clicked
*Company        : Merfantz Technology Pvt Ltd.
*Date           : 13th April, 2014
*Version        : 1.1
*Methods        : public SurveySubmitController(ApexPages.StandardController controller)

*============================================================================================================*/
public class SurveySubmitController {
    public visits__c THisVisit {get;set;}
    //public List<Visits__C> VisitList {get;set;}
    public List<Visits__c> VisitToSend = new list<Visits__c>();
    public list<SurveyTaker__c> Surveys {get;set;}
    public id currentRecordId;
    public boolean popUP {get;set;}
    public boolean Error {get;set;}
    public set<id> selectedVisits {get;set;}
    public integer ThisVisitSurvey{get;set;}
    public account acc {get;set;}
    
    public SurveySubmitController(ApexPages.StandardController controller) {
        ThisVisitSurvey=0;
        popUP=false;
        Error=false;
        selectedVisits=new set<id>();
        acc = new account();
        //currentRecordId  = ApexPages.CurrentPage().getparameters().get('id')!=null?ApexPages.CurrentPage().getparameters().get('id'):'a0Q7Z000008st1C';
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        System.debug(currentRecordId);
        THisVisit = [SELECT id,Name,Engineer2__c,Survey_Sent__c,Mail_Count__c,Site__r.name,Engineer2__r.name,Site__c,Visit_Confirmation_Email_to__c  FROM Visits__c WHERE id =: currentRecordId ];
        Surveys=[SELECT Id, Visit__c, Site__c, Survey__c,Visit__r.name, Site__r.name, Survey__r.name, Name FROM SurveyTaker__c where Site__c = :THisVisit.Site__c  and (createddate=this_month or createddate=LAST_N_MONTHS:2)];
    	ThisVisitSurvey=[SELECT Id, Visit__c, Site__c, Survey__c,Visit__r.name, Site__r.name, Survey__r.name, Name FROM SurveyTaker__c where Site__c = :THisVisit.Site__c  and (createddate=this_month or createddate=LAST_N_MONTHS:2) and Visit__c=:THisVisit.id].size();
        acc=[select id,name,Survey_Date__c,Survey_Count_HS__c from account where id=:THisVisit.Site__c];

        system.debug(ThisVisitSurvey);
    }
    
    public void sendSurvey()
    {
        System.debug('e');
        try{
        THisVisit.Survey_Sent__c=THisVisit.Survey_Sent__c==true?false:true;
        acc.Survey_Date__c=System.today();
            if(acc.Survey_Count_HS__c>0){
             acc.Survey_Count_HS__c = acc.Survey_Count_HS__c + 1;
            }
            else{
                 acc.Survey_Count_HS__c =1;
            }
            
        acc.Survey_Engineer__c = THisVisit.Engineer2__r.name;
        update THisVisit;
        update acc;
        popUP=true;
        Error=false;
        system.debug('fun line');
        }catch(Exception e)
        {
            Error=true;
            if(e.getMessage().contains('Survey can send only'))
            apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'Survey can send only when Visit is completed'));
            else
            apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,e.getMessage()));
            System.debug(e);
        }
        System.debug('e');
        
    }

    public PageReference doRedirect(){
        PageReference pg = new PageReference('/'+currentRecordId);
        pg.setRedirect(true);
        return pg;  
    }
    
    
    
}