objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Technician_Compliance__c/Technician_Compliance__c.object-meta.xml
<CustomObject>
    <label>Customer Gift</label>
    <nameField>
        <displayFormat>CG{000000}</displayFormat>
        <label>Technician Compliance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Technician_Compliance__c/fields/Customer_Site__c.field-meta.xml
<CustomField>
    <fullName>Customer_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer / Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Technician Compliance</relationshipLabel>
    <relationshipName>Technician_Compliance</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Technician_Compliance__c/fields/Firstname__c.field-meta.xml
<CustomField>
    <fullName>Firstname__c</fullName>
    <label>Firstname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Technician_Compliance__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <label>Gift</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Biscuits</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Flowers</fullName>
            </value>
            <value>
                <fullName>Fudge</fullName>
            </value>
            <value>
                <fullName>Graze Box</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Technician_Compliance__c/fields/Lastname__c.field-meta.xml
<CustomField>
    <fullName>Lastname__c</fullName>
    <label>Lastname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/CustomerdeliveryNoteController.cls
/*============================================================================================================
*Class Name     : CustomerdeliveryNoteController
*Description    : To handle the Customer Note
*Company        : Puthuvannam Technology Solutions Pvt Ltd.
*Date           : 23rd June, 2014
*Version        : 30.0
*Methods        : public CustomerdeliveryNoteController(ApexPages.StandardController controller)

*============================================================================================================*/

public class CustomerdeliveryNoteController {

public String CurrentId{get; set;}
public String Accid{get; set;}
public String listAccount{get; set;}
public String ShipStreet{get; set;}
public String ShipCity{get; set;}
public String ShipState{get; set;}
public String ShipZip{get; set;}
public String ShipCountry{get; set;}
public String FirstName{get; set;}
public String LastName{get; set;}
public String Name{get; set;}
public String Gift{get; set;}
public String Customer{get; set;}

    public CustomerdeliveryNoteController(ApexPages.StandardController controller) {

      CurrentId=ApexPages.currentPage().getParameters().get('id');
      system.debug('-----------'+CurrentId);
      Technician_Compliance__c Accid=[select id,Customer_Site__r.name,Firstname__c,Lastname__c,Gift__c from Technician_Compliance__c where id=:CurrentId];
      system.debug('-----------'+Accid);
      
      Account listAccount=[select name, ShippingStreet,ShippingCity,ShippingState,ShippingPostalCode,ShippingCountry from Account where id=:Accid.Customer_Site__c];
       system.debug('-----------'+listAccount);
      ShipStreet= listAccount.ShippingStreet;
      ShipCity = listAccount.ShippingCity;
      ShipState= listAccount.ShippingState;
      ShipZip= listAccount.ShippingPostalCode;
      ShipCountry= listAccount.ShippingCountry ;
      FirstName=Accid.Firstname__c;
      LastName=Accid.Lastname__c ;
      Name=FirstName+'  '+LastName;
      Gift=Accid.Gift__c; 
      Customer=Accid.Customer_Site__r.name; 
    }
   
    

}