objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Auto_Product_Config__c/Auto_Product_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Auto Product Config</label>
</CustomObject>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visits__c/fields/April__c.field-meta.xml
<CustomField>
    <fullName>April__c</fullName>
    <label>April</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/August__c.field-meta.xml
<CustomField>
    <fullName>August__c</fullName>
    <label>August</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/December__c.field-meta.xml
<CustomField>
    <fullName>December__c</fullName>
    <label>December</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <label>February</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <label>January</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/July__c.field-meta.xml
<CustomField>
    <fullName>July__c</fullName>
    <label>July</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/June__c.field-meta.xml
<CustomField>
    <fullName>June__c</fullName>
    <label>June</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <label>March</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <label>May</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/November__c.field-meta.xml
<CustomField>
    <fullName>November__c</fullName>
    <label>November</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/October__c.field-meta.xml
<CustomField>
    <fullName>October__c</fullName>
    <label>October</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Visits__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <inlineHelpText>If there is a specific purchase order number for this visit,please put it here.If this is blank,as soon as the visit is edited, the PO(if there is one) from the Site or the Customer will be used.
If mandatory, yet a P/O is not required, enter a dot (.).</inlineHelpText>
    <label>Purchase Order</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Visits__c/fields/September__c.field-meta.xml
<CustomField>
    <fullName>September__c</fullName>
    <label>September</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

classes/TestMonthlyTargetTrigger.cls
/*
        Name           : TestMonthlyTargetTrigger
        Author         : 
        Date           : 23rd June 2014
        Description    : Test class of MonthlyTargetTrigger
*/

@isTest(SeeAllData=true)
public class TestMonthlyTargetTrigger{
    // test method
    @isTest
    private static void test(){
        // create test auto product config
        Auto_Product_Config__c auto = TestDataHandler.createTestAutoProductConfig();
        insert auto;
        
        // create test account
        Account site = TestDataHandler.createTestSite();
        insert site;
        
        // create test site contract
        SiteContracts__c siteContact = TestDataHandler.createTestSiteContract(site.Id);
        insert siteContact;
        
        // create test engineer
        Engineer__c eng = TestDataHandler.createTestEngineer();
        insert eng;
        
        // create test visit
        List<Visits__c> listVisit = new List<Visits__c>();
        for(Integer counter = 1 ; counter <= 12 ; counter++){
            Visits__c visit = TestDataHandler.createTestVisit(siteContact.Id,site.Id,eng.Id);
            visit.Order_Value__c = 500;
            visit.Purchase_Order__c = 'Test';
            listVisit.add(visit);
        }
        insert listVisit;
        
        Map<Integer,String> mapMonths = new Map<Integer,String>{1=>'January__c',2=>'February__c',3=>'March__c',4=>'April__c',5=>'May__c',6=>'June__c',7=>'July__c',8=>'August__c',9=>'September__c',10=>'October__c',11=>'November__c',12=>'December__c'};
        Integer currentMonth = system.today().month();
        for(Integer counter=1 ; counter <= 12 ; counter++){
            if(currentMonth > 12){
                currentMonth = 1;
            }
            listVisit[0].put(mapMonths.get(currentMonth),0);
            update listVisit[0];
            currentMonth++;
        }
        for(Visits__c visit : listVisit){
            visit.Order_Value__c = null;
        }
        update listVisit;
    }
}