objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

objects/Auto_Product_Config__c/Auto_Product_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Auto Product Config</label>
</CustomObject>

objects/Engineer__c/Engineer__c.object-meta.xml
<CustomObject>
    <description>This Object contains all the information regarding personnel who are in the role of Engineer.</description>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Purchase_Order__c/SFDC_Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>Track the lifestyle of a Purchase Order, as it starts as a purchase request and becomes a fully-approved PO. Associate this with a specific cost center and Invoices.</description>
    <label>Supplier Purchase Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Purchase_Order__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>Enter the department you are raising the P/O for.</inlineHelpText>
    <label>Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>IT &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service - North</fullName>
            </value>
            <value>
                <fullName>Service - North Reactive</fullName>
            </value>
            <value>
                <fullName>Service - North Small Works</fullName>
            </value>
            <value>
                <fullName>Service - South</fullName>
            </value>
            <value>
                <fullName>Service - South Reactive</fullName>
            </value>
            <value>
                <fullName>Service - South Small Works</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SFDC_Purchase_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supplier Purchase Orders</relationshipLabel>
    <relationshipName>Supplier_Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SFDC_Purchase_Order__c/fields/Supplier1__c.field-meta.xml
<CustomField>
    <fullName>Supplier1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Search and select the relevant Supplier, if you cannot find the one you need, use the Supplier Pending Creation Supplier, and enter the name of the Supplier in the Branch field, then ask Accounts to setup the new Supplier, and assign this P/O to it.</inlineHelpText>
    <label>Supplier</label>
    <referenceTo>Suppliers__c</referenceTo>
    <relationshipName>Purchase_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SFDC_Purchase_Order__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Visit this P/O relates to, if applicable.</inlineHelpText>
    <label>Visit</label>
    <referenceTo>Visits__c</referenceTo>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteContracts__c/SiteContracts__c.object-meta.xml
<CustomObject>
    <description>Links Sites to Contracts and holds all Alarm Master Data</description>
    <label>Site Contract</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>ContractId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object contains information relating to the timing of Services for each Customer site, by Engineer.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PurchaseOrderTriggerTest.cls
/*======================================================================================
        Name            : PurchaseOrderTriggerTest
        Author          : 
        Date            : 20th June 2014
        Description     : This controller is test class of PurchaseOrderTrigger
==========================================================================================
*/

// @isTest
public class PurchaseOrderTriggerTest{
    // Test metod
  /*  @isTest
    private static void test(){
        Auto_Product_Config__c auto = TestDataHandler.createTestAutoProductConfig();
        insert auto;
    
        Account site = TestDataHandler.createTestSite();
        insert site;
        
        SiteContracts__c siteContact = TestDataHandler.createTestSiteContract(site.Id);
        insert siteContact;
        
        //Opportunity opp = TestDataHandler.createTestOpportunity(site.id);
        //insert opp;
        
        Engineer__c eng = TestDataHandler.createTestEngineer();
        insert eng;
        
        Visits__c visit = TestDataHandler.createTestVisit(siteContact.Id,site.Id,eng.Id);
        //visit.Opportunity__c = opp.Id;
        insert visit;
        
        Suppliers__c supp = TestDataHandler.createTestSupplier();
        insert supp;
        
        SFDC_Purchase_Order__c purchase=new SFDC_Purchase_Order__c ();
        purchase.Supplier1__c=supp.id;
        purchase.Visit__c=visit.id;
        purchase.Department__c='test';
        insert purchase;
        
        SFDC_Purchase_Order__c purchaseOrd = TestDataHandler.createTestPurchaseOrder(supp.Id,visit.Id);
        
        insert purchaseOrd;
    }*/
}