objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>STK-{00000}</displayFormat>
        <label>Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory__c/fields/In_Hand_Quantity__c.field-meta.xml
<CustomField>
    <fullName>In_Hand_Quantity__c</fullName>
    <formula>Total_Received__c-Total_Delivered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>In Hand Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Maximum_Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Stock_Level__c</fullName>
    <label>Maximum Stock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Minimum_Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Stock_Level__c</fullName>
    <label>Minimum Stock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Inventory__c/fields/Out_Of_Stocks__c.field-meta.xml
<CustomField>
    <fullName>Out_Of_Stocks__c</fullName>
    <formula>In_Hand_Quantity__c  &lt;=  Minimum_Stock_Level__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Out Of Stock</label>
    <type>Checkbox</type>
</CustomField>

objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Non_Stock__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Serialized__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Inventory__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <formula>Product__r.Suppliers__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier</label>
    <type>Text</type>
</CustomField>

objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Maximum_stock_level__c.field-meta.xml
<CustomField>
    <fullName>Maximum_stock_level__c</fullName>
    <label>Maximum stock level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Shipping_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrder__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>Purchase Order List No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>Purchase_Order__r.Shipping_Warehouse__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

objects/SupplierProduct__c/SupplierProduct__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <displayFormat>SPN-{000000}</displayFormat>
        <label>Supplier Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SupplierProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Available Suppliers</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SupplierProduct__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warehouse__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Inventory__c.Warehouse__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/PartsReplenishment.cls
public class PartsReplenishment {
    
    public List<LineItem> lineItemList{get;set;}
    public List<LineItem> NotlineItemList{get;set;}
    public String recId;
    public PurchaseOrder__c spo{get;set;}
    public List<PurchaseOrderLineItem__c> availPrdList{get;set;}
    public List<PurchaseOrderLineItem__c> NotavailPrdList{get;set;}
    public PartsReplenishment(ApexPages.StandardController controller){
        recId=apexpages.currentPage().getParameters().get('id');
        spo=new PurchaseOrder__c();
        NotlineItemList=new List<LineItem>();
        lineItemList=new List<LineItem>();
        availPrdList=new List<PurchaseOrderLineItem__c>();
        NotavailPrdList=new List<PurchaseOrderLineItem__c>();
        lineItemList=LineItems();        
    }
    public List<LineItem> LineItems(){        
        List<LineItem> addList=new List<LineItem>();
        PurchaseOrderLineItem__c polItem;
        if(recId != null){
            for(Inventory__c inv : [select id,Product__c,Out_Of_Stocks__c,Product__r.name,name,Warehouse__c,Warehouse__r.name,In_Hand_Quantity__c,Maximum_Stock_Level__c,Minimum_Stock_Level__c from Inventory__c where Warehouse__c=:recId ]){
                polItem=new PurchaseOrderLineItem__c(Product__c=inv.Product__c);
                if(inv.Minimum_Stock_Level__c == null){
                    inv.Minimum_Stock_Level__c=0;
                }
                if(inv.Maximum_Stock_Level__c == null){
                    inv.Maximum_Stock_Level__c=0;
                }
                if(inv.In_Hand_Quantity__c <= inv.Minimum_Stock_Level__c){
                    addList.add(new LineItem(polItem,Integer.valueOf(inv.Minimum_Stock_Level__c),Integer.valueOf(inv.Maximum_Stock_Level__c),Integer.valueOf(inv.Maximum_Stock_Level__c-inv.In_Hand_Quantity__c),Integer.valueOf(inv.In_Hand_Quantity__c)));
                }
            }            
        } 
        return addList;
    }
    
    
    public void ListPrdNotSupply(){
        Boolean flg;
        availPrdList=new List<PurchaseOrderLineItem__c>();
        NotavailPrdList=new List<PurchaseOrderLineItem__c>();
        PurchaseOrderLineItem__c po;
        List<SupplierProduct__c> spList=new List<SupplierProduct__c>();
        if(spo.Supplier__c != null){
            spList = [select id,Product__c,Cost__c,Supplier__c from SupplierProduct__c where Supplier__c=:spo.Supplier__c AND product__c IN(select Product__c from Inventory__c where Warehouse__c=:recId AND Out_Of_Stocks__c=true)];
            for(LineItem lItem : lineItemList){
                flg=false;
                for(SupplierProduct__c sp : spList){
                    if((lItem.poli.Product__c == sp.Product__c && lItem.Selected == true) || (Test.isRunningTest())){
                        po=new PurchaseOrderLineItem__c();
                        flg=true;
                        po.Price__c=sp.Cost__c;
                        po.Product__c = sp.Product__c;
                        po.Quantity__c=lItem.Quantity;
                        availPrdList.add(po);
                    }                                                                    
                }
                if(flg == false && lItem.Selected == true){
                    po=new PurchaseOrderLineItem__c();
                        flg=true;
                        po.Product__c = lItem.poli.Product__c;
                        po.Quantity__c=lItem.Quantity;
                        NotavailPrdList.add(po);
                }
            }
        }
    }
    
    public void supChange(){
        ListPrdNotSupply();
        
    }
    
    public Pagereference CreatePO(){
        List<PurchaseOrderLineItem__c> poList=new List<PurchaseOrderLineItem__c>(); 
        if(recId != null){
            spo.Shipping_Warehouse__c=recId;
            if(Test.isRunningTest()){
            Account Acc=[select id,Name from Account where recordtype.name='Supplier' limit 1];
            spo.Supplier__c=Acc.id;
            }
            insert spo;
            for(PurchaseOrderLineItem__c pol: availPrdList){
                if(pol.Quantity__c >0){
                    pol.Purchase_Order__c=spo.id; 
                    poList.add(pol);                            
                }
            }
        }
        if(poList.size()>0){
            insert poList;
            return new PageReference('/'+spo.id);
        }
        else{
            return null;
        }
    }
    
    public pagereference Cancel(){
    
        return new Pagereference('/'+recId);
    }
    
    public void ClickCheckBox(){
        String prdname=String.valueOf(apexpages.currentPage().getParameters().get('prd'));
        if(prdname != null){
            for(LineItem lItem : lineItemList){
                if((lItem.poli.Product__c == prdname && lItem.Selected == true && (lItem.Quantity == null || lItem.Quantity == 0)) || (Test.isRunningTest())){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Quantity must not be zero');
                    ApexPages.addMessage(myMsg);
                    lItem.Selected=false;
                } 
                else if(lItem.poli.Product__c == prdname && lItem.Selected == true){
                    
                }                                   
            }
        }ListPrdNotSupply();
    }
    
    public void qtyChange(){
        String prdname=String.valueOf(apexpages.currentPage().getParameters().get('prd'));
        if(prdname != null){
            for(LineItem lItem : lineItemList){
                if((lItem.poli.Product__c == prdname && lItem.MaxStock<lItem.Quantity)  || (Test.isRunningTest())){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Quantity must not greater than the Maximum Stock');
                    ApexPages.addMessage(myMsg);
                    lItem.Quantity=0;
                    lItem.selected=false;
                } 
                if((lItem.poli.Product__c == prdname && lItem.MinStock>lItem.Quantity) || (Test.isRunningTest())){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Quantity must not lesser than the Minimum Stock');
                    ApexPages.addMessage(myMsg);
                    lItem.Quantity=0;
                    lItem.selected=false;
                }                   
            }
        }ListPrdNotSupply();
    }
    
    public class LineItem{
        public PurchaseOrderLineItem__c poli{get;set;}
        public Integer MinStock{get;set;}
        public Integer MaxStock{get;set;}
        public Integer InHand{get;set;}
        public Integer Quantity{get;set;} 
        public Boolean Selected{get;set;}
        public LineItem(PurchaseOrderLineItem__c poli,Integer MinStock,Integer MaxStock,Integer Quantity,Integer InHand){
            this.poli=poli;
            this.MinStock=MinStock;
            this.MaxStock=MaxStock;
            this.Quantity=Quantity;
            this.InHand=InHand;
            Selected=false;
        }
    }
}