objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Supplier_Cost_Price__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Cost_Price__c</fullName>
    <label>Supplier Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Supplier_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product_Code__c</fullName>
    <label>Supplier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Suppliers__c.field-meta.xml
<CustomField>
    <fullName>Suppliers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suppliers</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products (Suppliers)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SupplierProduct__c/SupplierProduct__c.object-meta.xml
<CustomObject>
    <label>Supplier Product</label>
    <nameField>
        <displayFormat>SPN-{000000}</displayFormat>
        <label>Supplier Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SupplierProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Available Suppliers</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SupplierProduct__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Products</relationshipLabel>
    <relationshipName>Supplier_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SupplierProduct__c/fields/Supplier_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Product_Code__c</fullName>
    <label>Supplier Product Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

objects/Suppliers__c/Suppliers__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SupplierProductHanndler.cls
Public class SupplierProductHanndler{
      
      public void OnAfterInsert(Map<id,SupplierProduct__c> Newmap){
       CurrenyType(Newmap);
       InsertSupplierCost(Newmap);
      // InsertSupplierCode(Newmap);
      
      }
      
      Public void OnAfterUpdate(Map<Id,SupplierProduct__c> Newmap,Map<Id,SupplierProduct__c> OldMap){
        
       UpdateSupplierCost(Newmap,OldMap);
       // UpdateSupplierCode(Newmap,OldMap);
      
      }
      
 /*====================================================

*Method Name     : CurrenyType
*Description     : Update the currency type based on supplier
*Arguments       : newmap 
====================================================*/

 
      Public void CurrenyType(Map<id,SupplierProduct__c> Newmap ){
        List<SupplierProduct__c> sprod=new List<SupplierProduct__c>();
        
        for(SupplierProduct__c sp:[Select id,CurrencyIsoCode,Supplier__c,Supplier__r.CurrencyIsoCode from SupplierProduct__c where 
                                     id In:Trigger.newMap.keySet()]){
            sp.CurrencyIsoCode=sp.Supplier__r.CurrencyIsoCode;
            sprod.add(sp);                       
        
        }
        if(sprod.size()>0){
          
            update sprod;  
        }
       
      }
      
      /*====================================================

*Method Name     : InsertSupplierCost
*Description     : Update Supplier cost on product
*Arguments       : newmap 
====================================================*/
      
    Public void InsertSupplierCost(Map<id,SupplierProduct__c> Newmap){
       List<Id> supid =new List <Id>();
       List<product2> prdcost=new List<product2>();
       String SupCost;
        Map<String,Decimal> SupplierCostMap=new Map<String,Decimal>();
       
       for(SupplierProduct__c sp:Newmap.values()){
         if(sp.Supplier__c!=null && sp.Product__c!=null && sp.Cost__c!=null){
             supid.add(sp.Supplier__c);
             SupCost=String.valueof(sp.Supplier__c )+String.valueof(sp.Product__c);
             if(!SupplierCostMap.containskey(SupCost)){
                    SupplierCostMap.put(SupCost,sp.Cost__c);
              }
         }
       }
       
       if(supid.size()>0){
          for(Product2 prdlist: [select id,Supplier_Cost_Price__c,Suppliers__c from Product2 where Suppliers__c IN:supid]){
               SupCost=String.valueof(prdlist.Suppliers__c)+String.valueof(prdlist.Id);
               if(SupplierCostMap.ContainsKey(SupCost)){
                  prdlist.Supplier_Cost_Price__c=SupplierCostMap.get(SupCost);
                  prdcost.add(prdlist);
               }
             
          }
          
          if(prdcost.size()>0){
                update prdcost;
             }  
         
       }
    }
    /*-----------------------------------------------------
    For default checkbox
    --------------------------------------
     Public void InsertSupplierCode(Map<id,SupplierProduct__c> Newmap){
       List<Id> supid =new List <Id>();
       List<product2> prdcost=new List<product2>();
       String SupCost;
        Map<String,String> SupplierCostMap=new Map<String,String>();
       
       for(SupplierProduct__c sp:Newmap.values()){
         if(sp.Supplier__c!=null && sp.Product__c!=null && sp.Supplier_Product_Code__c!=null){
             supid.add(sp.Supplier__c);
             SupCost=String.valueof(sp.Supplier__c )+String.valueof(sp.Product__c);
             if(!SupplierCostMap.containskey(SupCost)){
                    SupplierCostMap.put(SupCost,sp.Supplier_Product_Code__c);
              }
         }
       }
       
       if(supid.size()>0){
          for(Product2 prdlist: [select id,Supplier_Cost_Price__c,Suppliers__c,Supplier_Product_Code__c from Product2 where Suppliers__c IN:supid]){
               SupCost=String.valueof(prdlist.Suppliers__c)+String.valueof(prdlist.Id);
               if(SupplierCostMap.ContainsKey(SupCost)){
                  prdlist.Supplier_Product_Code__c=SupplierCostMap.get(SupCost);
                  prdcost.add(prdlist);
               }
             
          }
          
          if(prdcost.size()>0){
                update prdcost;
             }  
         
       }
    }*/
   /*====================================================
        
        *Method Name     : UpdateSupplierCost
        *Description     : Update Supplier cost on product
        *Arguments       : newmap 
        ====================================================*/
      
       Public void UpdateSupplierCost(Map<Id,SupplierProduct__c> Newmap,Map<Id,SupplierProduct__c> OldMap){
            
         List<Id> supid =new List <Id>();
         List<product2> prdcost=new List<product2>();
         String SupCost;
         Map<String,Decimal> SupplierCostMap=new Map<String,Decimal>();
       
         for(SupplierProduct__c sp:Newmap.values()){
             if(sp.Supplier__c!=null && sp.Product__c!=null && sp.Cost__c!=null && OldMap.get(sp.id).Cost__c!=sp.Cost__c){
                supid.add(sp.Supplier__c);
                SupCost=String.valueof(sp.Supplier__c )+String.valueof(sp.Product__c);
               if(!SupplierCostMap.containskey(SupCost)){
                    SupplierCostMap.put(SupCost,sp.Cost__c);
               }
             }
          }
          
          
          if(supid.size()>0){
            for(Product2 prdlist: [select id,Supplier_Cost_Price__c,Suppliers__c from Product2 where Suppliers__c IN:supid]){
               SupCost=String.valueof(prdlist.Suppliers__c)+String.valueof(prdlist.Id);
               if(SupplierCostMap.ContainsKey(SupCost)){
                  prdlist.Supplier_Cost_Price__c=SupplierCostMap.get(SupCost);
                  prdcost.add(prdlist);
               }
             
            }
          
            if(prdcost.size()>0){
                update prdcost;
            }  
         
         }
         
       }
 
 }