objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>Purchase Order List No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Order_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/RaisePO.cls
public class RaisePO {

    public RaisePO(ApexPages.StandardController controller) {
        OrdId=ApexPages.currentpage().getParameters().get('id');        
        addSPO= new PurchaseOrder__c();  
    }
    public String OrdId{get;set;}
    public PurchaseOrder__c addSPO{get; set;}
    public List<PurchaseOrderLineItem__c> addLI{get;set;}
    public List<String> prds{get;set;}
        
    public void CreatePO(){
        prds=new List<String>();   
        addLI=new List<PurchaseOrderLineItem__c>();
        PurchaseOrderLineItem__c poli;
        for(OrderItem oli: [select Id,PricebookEntry.Product2Id,Quantity, OrderId from OrderItem where OrderId=:OrdId]){
           prds.add(oli.PricebookEntry.Product2Id);
        }
             
        for(OrderItem oppLI: [select Id,PricebookEntry.Product2Id,Quantity,UnitPrice,OrderId from OrderItem where OrderId=:OrdId]){
            if(oppLI.Quantity >0){
                poli=new PurchaseOrderLineItem__c(Product__c=oppLI.PricebookEntry.Product2Id,Quantity__c=oppLI.Quantity,Price__c=oppLI.UnitPrice);
                addLI.add(poli);
            }
        }          
      }        
    
    public pageReference AddPOLI(){
        addSPO.Sales_Order__c=OrdId;
        insert addSPO;   
        if(addLI.size()>0){
            for(PurchaseOrderLineItem__c pol:addLI){
                pol.Purchase_Order__c=addSPO.id;
                insert pol;
            }
        }
        return new PageReference('javascript:window.top.close();window.opener.location.reload();');
    }
    
}