objects/Account_Product_Price__c/Account_Product_Price__c.object-meta.xml
<CustomObject>
    <label>Special Product Pricing</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account to Product Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Product Pricings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Product_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Product Pricings</relationshipLabel>
    <relationshipName>Account_to_Product_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Account_Product_Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Account_Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Account_to_Product_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/OpportunityLineItem/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <formula>Opportunity.Account.Parent.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Id</label>
    <type>Text</type>
</CustomField>

objects/OpportunityLineItem/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/OpportunityLineItem/fields/SalesDescription__c.field-meta.xml
<CustomField>
    <fullName>SalesDescription__c</fullName>
    <label>SalesDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/OpportunityLineItem/fields/Site_Id__c.field-meta.xml
<CustomField>
    <fullName>Site_Id__c</fullName>
    <formula>Opportunity.Account.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Id</label>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Extended_Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Extended_Sales_Description__c</fullName>
    <label>Extended Sales Description</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

objects/Product2/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <label>Sales Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

classes/OpportunityProductHandler.cls
Public class OpportunityProductHandler{

 public void BeforeInsert(List<OpportunityLineItem > newList){
    system.debug('newlist==========='+newList);
        
        InsertExtendedSales(newList);
        
    }
    public void BeforeUpdate(Map<Id,OpportunityLineItem> newMap){
    
        UpddateExtendedSales(newMap);
     
    }
 
 /* =================================================================
    Method Name:UpddateExtendedSales
    Description: Update Extended sales description
    Created Date: 13.7.17
    =====================================================================  */
    
  public void UpddateExtendedSales(Map<Id,OpportunityLineItem> newMap){
        system.debug('update newMap=========='+newMap.values());
        List<Id> ProductId=new List<Id>();
        Map<Id,Product2> PrdsList=new Map<Id,Product2>();
        
        for(OpportunityLineItem NewId:newMap.values()){
            ProductId.add(NewId.Product2Id);
            
            }
       
        for(Product2 prd:[select id,Extended_Sales_Description__c,Sales_Description__c from product2 where id IN:ProductId]){
            PrdsList.put(prd.id,prd);
        }  
       
        for(OpportunityLineItem NewId:newMap.values()){
           
           if(PrdsList.containskey(NewId.Product2Id)){
              if(NewId.Extended_Sales_Description__c==null){
                 NewId.Extended_Sales_Description__c=PrdsList.get(NewId.Product2Id).Extended_Sales_Description__c;
               }
               if(NewId.SalesDescription__c==null){
                  NewId.SalesDescription__c=PrdsList.get(NewId.Product2Id).Sales_Description__c;
               }
           }
       }
    } 
    
    /* =================================================================
    Method Name:InsertExtendedSales and Update sales price based on customer
    Description: InsertExtendedSales description
    Created Date: 13.7.17
    =====================================================================  */
    
     public void InsertExtendedSales(List<OpportunityLineItem> newMap){
   
        List<Id> ProductId=new List<Id>();
        Set<Id> Accid=new Set<Id>();
        Map<Id,Product2> PrdsList=new Map<Id,Product2>();
        Map<Id,Account_Product_Price__c > SProd=new Map<Id,Account_Product_Price__c >();
       
        for(OpportunityLineItem NewId:newMap)
        {
            ProductId.add(NewId.Product2Id);
            Accid.add(NewId.Site_Id__c);
            Accid.add(NewId.Customer_Id__c);
            
        }
        system.debug('ProductId=========='+ProductId);
        system.debug('Accid============'+Accid);
        
          for(Account_Product_Price__c ap:[Select id,Account__c,Price__c,Product__c from Account_Product_Price__c where Product__c IN:ProductId AND Account__c IN:Accid]){
            SProd.put(ap.Product__c,ap); 
      }
        for(Product2 prd:[select id,Extended_Sales_Description__c,Sales_Description__c from product2 where id IN:ProductId]){
               PrdsList.put(prd.id,prd);
               
         } 
       
         for(OpportunityLineItem NewId:newMap){
           
           if(PrdsList.containskey(NewId.Product2Id)){
             if(NewId.Extended_Sales_Description__c==null){        
                NewId.Extended_Sales_Description__c=PrdsList.get(NewId.Product2Id).Extended_Sales_Description__c;
              }
              if(NewId.SalesDescription__c==null){
                 NewId.SalesDescription__c=PrdsList.get(NewId.Product2Id).Sales_Description__c;
               }
              
               
           }
           
          if(SProd.containskey(NewId.Product2Id)){
               NewId.UnitPrice=SProd.get(NewId.Product2Id).Price__c;
          }
       }
    }
}