objects/Account_Product_Price__c/Account_Product_Price__c.object-meta.xml
<CustomObject>
    <label>Special Product Pricing</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account to Product Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Product Pricings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Product_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Product Pricings</relationshipLabel>
    <relationshipName>Account_to_Product_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Account_Product_Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Account_Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Account_to_Product_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product2/fields/Product_Name_Check__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Check__c</fullName>
    <inlineHelpText>Enter the product name again in here, and it will check to see if there is another product already created with this name, when you save. This is to avoid duplicates.</inlineHelpText>
    <label>Product Name Check</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Product2/fields/UniqueSageCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueSageCode__c</fullName>
    <inlineHelpText>This is the unique Sage Code, being a combination of the Sage Code and the Nominal Code. It is a required field on the product, and also is the unique external link to Sage.</inlineHelpText>
    <label>Eclipse Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

classes/SpecialAccountProductPricePageTest.cls
/*Class Name : SpecialAccountProductPricePageTest
Purpose      : SpecialAccountProductPricePageController Test Class.
Author       : Sachin Chincholi
Created On   : 03/02/2014
Last Modified On : 06/02/2014
Reason for Modification : Added Functionality */


@isTest(seeAllData = true)
public class SpecialAccountProductPricePageTest{
    
    static testMethod void specialAccountProductTest() {
        test.startTest();
        List<Account_Product_Price__c> appList =  new List<Account_Product_Price__c>();
        ApexPages.StandardController controller;  
        
        //Create Test Data
        Account acc = new Account();
        acc.name = 'Test Account';
        insert acc;
        
        //Create Test Data for Product
        Pricebook2 pb2 = [select Id,name,isActive from Pricebook2 where isStandard=true];
        
        Product2 p2 = new Product2(Name='Test Product',isActive=true,UniqueSageCode__c='H8486_4888',Product_Name_Check__c='10 Person First Aid Kit Product');
        insert p2;
        
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pb2.id, Product2Id=p2.Id, UnitPrice=99, isActive=true);
        insert pbe;
        
        Account_Product_Price__c app = new Account_Product_Price__c(); 
        app.Account__c = acc.id;
        app.Product__c = p2.id;
        app.Price__c = 0.00;
        appList.add(app);
        insert appList;
        ApexPages.CurrentPage().getparameters().put('id', appList[0].id);
        SpecialAccountProductPricePageController  instance = new SpecialAccountProductPricePageController(controller);
        instance.addRow();
        instance.addRowAcc();
        instance.SaveData();
        system.assertEquals(app.Price__c,0.00);
        system.assertEquals(appList.size(),1);
        instance.SaveandExit();
        test.stopTest();
    }
}