objects/SurveyTaker__c/SurveyTaker__c.object-meta.xml
<CustomObject>
    <description>Survey Force object</description>
    <label>Survey Taken</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Survey Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SurveyTaker__c/fields/No_of_Question__c.field-meta.xml
<CustomField>
    <fullName>No_of_Question__c</fullName>
    <label>No of Question</label>
    <summaryForeignKey>SurveyQuestionResponse__c.SurveyTaker__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

classes/SurveyTakerHandler.cls
public class SurveyTakerHandler {
    public static void sendEmailTemplate(List<SurveyTaker__c> surveyTakers, Map<id,SurveyTaker__c> oldmap) {
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        
        String[] toAddresses = new String[]{'salesforcetestwork@gmail.com'};
        
        Id emailTemplateId = '00X4E000001e5AQUAY';
        
        for (SurveyTaker__c st : surveyTakers) {
        if(st.No_of_Question__c>0 && oldmap.get(st.id).No_of_Question__c!=st.No_of_Question__c){
        
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            EmailTemplate emailTemplate = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where name ='Survey Submit Notification' limit 1];
            email.setToAddresses(toAddresses);
             email.setSubject(Messaging.renderStoredEmailTemplate(emailTemplate.Id,UserInfo.getUserId(), st.Id).getSubject());
            email.setHtmlBody(Messaging.renderStoredEmailTemplate(emailTemplate.Id,UserInfo.getUserId(), st.Id).getHtmlBody()); 
            emailList.add(email);
        
        if(emailList.size()>0){
            Messaging.sendEmail(emailList);
        }
      }
    }
}
}